/* Small Phone delivery runner. Fixed 60 Hz simulation; server replays the same rules. */
(function(root){
 'use strict';
 const MAX=9000,STEP=1000/60,CAMERA=14000,VIEW=70000;
 function maxTicks(version){return version>=6?9000:version>=5?10800:6000;}
 function speed(t,version=2){if(version>=5)t=Math.min(t,6000);return (version>=3?400:160)+(version===1?Math.min(240,Math.floor(t/12)):Math.floor(t/12));}
 function distanceAt(t,version=2){if(version>=5&&t>6000)return distanceAt(6000,4)+(t-6000)*900;const n=version===1?Math.min(t,2880):t,q=Math.floor(n/12),r=n%12;return (version>=3?400:160)*t+6*q*(q-1)+q*(r+1)+(version===1?Math.max(0,t-2880)*240:0);}
 function project(gap){return CAMERA/(CAMERA+gap);}
 function track(seed,version=2){let n=seed,at=version>=4?36000:version===3?45000:18000,rows=[],safe=1;for(let i=0;at<=distanceAt(maxTicks(version),version)+VIEW;i++){n=n*48271%2147483647;let kind=i<3?-1:n%(version>=4?8:6),objects=[],action='';if(i<3){let lane=(seed+i)%3;if(lane===safe)safe=version>=4?(safe+1+Math.floor(n/6)%2)%3:safe===1?(Math.floor(n/6)%2)*2:1;objects=[{lane,type:2}];}else if(kind===2||kind===3){action=kind===2?'u':'d';objects=[0,1,2].map(lane=>({lane,type:kind===2?0:1}));}else{safe=version>=4?(safe+1+Math.floor(n/6)%2)%3:safe===1?(Math.floor(n/6)%2)*2:1;objects=[0,1,2].filter(lane=>lane!==safe).map(lane=>({lane,type:2}));if(kind===5||version>=4&&(kind===6||kind===7)){objects.push({lane:safe,type:kind===7?1:0});action=kind===7?'d':'u';}}n=n*48271%2147483647;rows.push({distance:at,safeLane:safe,action,objects,index:i});at+=(version>=4?(i<3?24000:32000+Math.min(8000,i*200)):(version===3?26000:0)+(i<3?22000:19000+(version===1?0:Math.min(12000,i*350))))+n%(i<3?3001:4001);}return rows;}
 function create(seed,version=2){return {physicsVersion:version,tick:0,distance:0,lane:1,x:1000,prevX:1000,hearts:3,jump:0,slide:0,shield:0,lastInput:-6,inputs:[],rows:track(seed,version),row:0,done:false,orders:0};}
 function input(g,a){if(g.done||!['l','r','u','d'].includes(a)||g.tick-g.lastInput<6)return false;g.lastInput=g.tick;g.inputs.push({t:g.tick,a});if(a==='l')g.lane=Math.max(0,g.lane-1);if(a==='r')g.lane=Math.min(2,g.lane+1);if(a==='u'&&g.tick>=g.jump&&g.tick>=g.slide)g.jump=g.tick+42;if(a==='d'&&g.tick>=g.jump&&g.tick>=g.slide)g.slide=g.tick+42;return true;}
 function step(g){if(g.done)return;g.tick++;g.prevX=g.x;g.x+=Math.max(-160,Math.min(160,g.lane*1000-g.x));g.distance+=speed(g.tick,g.physicsVersion);while(g.rows[g.row]&&g.rows[g.row].distance<=g.distance){const row=g.rows[g.row++];for(const o of row.objects){const jump=g.jump-g.tick,slide=g.slide-g.tick,clear=o.type===0&&jump>=11&&jump<=31||o.type===1&&slide>=4&&slide<=38;if(Math.abs(o.lane*1000-g.x)<430&&!clear&&g.tick>=g.shield){g.hearts--;g.shield=g.tick+50;}}}g.orders=Math.min(g.physicsVersion>=6?25:g.physicsVersion>=5?18:10,Math.floor(g.tick/(g.physicsVersion>=6?360:600)));g.done=g.hearts===0||g.tick>=maxTicks(g.physicsVersion);}
 const engine={track,create,input,step,speed,distanceAt,project,MAX,maxTicks};if(typeof module!=='undefined'&&module.exports){module.exports=engine;return;}root.NorthRunnerEngine=engine;
 let view=null,raf=0;
 const css=`.nr-root{position:fixed;inset:0;max-width:430px;left:50%;right:auto;width:100%;transform:translateX(-50%);z-index:9000;background:#f7f5ed;color:#292c31;display:flex;flex-direction:column;font-family:inherit;padding:env(safe-area-inset-top,0px) 0 env(safe-area-inset-bottom,0px)}.nr-root *{box-sizing:border-box}.nr-top{height:56px;flex-shrink:0;display:flex;align-items:center;gap:12px;padding:10px 16px;background:#ffe43a}.nr-top b{flex:1}.nr-root button{font:inherit;color:#292c31;border:0;border-radius:18px;padding:11px 16px;background:#ffe43a;font-weight:700;cursor:pointer}.nr-root button:disabled{opacity:.5;cursor:default}.nr-top button{background:#fff8b1;padding:7px 12px}.nr-stage{position:relative;flex:1;min-height:0;overflow:hidden;touch-action:none}.nr-stage canvas{width:100%;height:100%;display:block}.nr-hud{position:absolute;left:12px;right:12px;top:12px;display:flex;justify-content:space-between;pointer-events:none;gap:8px}.nr-hud>span{background:#fffef0e8;border-radius:18px;padding:8px 12px;font-size:14px;font-weight:700}.nr-hud .nr-hearts{display:flex;gap:10px;color:#ef4b4f;font-size:22px;padding:6px 12px;align-items:center}.nr-hearts b{font-size:22px;line-height:1;font-weight:400}.nr-hearts .empty{color:#c9c6c0}.nr-overlay{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:20px;background:#30596633}.nr-panel{background:#fff;border-radius:25px;padding:25px 22px;max-width:360px;width:100%;text-align:center;box-shadow:0 12px 35px #38534c26}.nr-panel h2{margin:0 0 12px;font-size:25px}.nr-panel p{font-size:14px;line-height:1.8;color:#70736f}.nr-panel strong{display:block;color:#e77b32;font-size:36px;margin:14px 0}.nr-panel button{display:block;width:100%;margin-top:10px}.nr-help{position:absolute;bottom:16px;left:0;right:0;text-align:center;color:#fff;font-size:12px;pointer-events:none;text-shadow:0 1px 3px #46576d}.nr-root .nr-alt{background:#fff5bc}.nr-caption{font-size:12px!important;color:#999!important}.nr-tip{position:absolute;top:66px;width:100%;text-align:center;color:#a4521d;font-weight:bold;pointer-events:none}`;
 function music(v,kind,restart=false){if(!v.audio)return;v.audioEpoch=(v.audioEpoch||0)+1;const a=v.audio;a.pause();if(!kind)return;const src='assets/north-runner-'+kind+'.mp3';if(v.musicKind!==kind){a.src=src;v.musicKind=kind;restart=true;}a.loop=kind==='game';a.muted=false;if(restart)a.currentTime=0;if(document.hidden)return;const promise=a.play();if(promise&&promise.catch)promise.catch(()=>{});}
 function primeMusic(v){if(!v.audio)v.audio=new Audio();const a=v.audio,epoch=v.audioEpoch=(v.audioEpoch||0)+1;a.pause();a.src='assets/north-runner-game.mp3';v.musicKind='game';a.loop=true;a.muted=true;a.preload='auto';a.setAttribute('playsinline','');const promise=a.play();if(promise&&promise.then)promise.then(()=>{if(v.audioEpoch===epoch){a.pause();a.currentTime=0;}}).catch(()=>{});}
 function valid(v){if(view!==v||S!==v.state||root.actId()!==v.account)return false;const p=root.phoneFriendState();return p.id===v.phone&&p.secret===v.secret;}
 function text(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 function panel(html){if(!view)return;view.overlay.innerHTML='<section class="nr-panel">'+html+'</section>';view.overlay.hidden=false;view.overlay.style.display='flex';}
 function message(err){return /runner-expired/.test(err.message)?'这一局已超过6分钟，请重新开局。':/runner-invalid/.test(err.message)?'这一局校验未通过，没有发放奖励。':/runner-too-fast/.test(err.message)?'游戏时间尚未完成校验，请稍后重试领取。':'暂时无法连接奖励服务。可以重试，不会重复领钱。';}
 function daily(d){return '今日已领 '+(d.used/100)+' / '+(Number.isFinite(d.limit)?d.limit/100:100)+' 虚拟币 · 北京时间00:00重置';}
 function intro(v){if(!valid(v))return;let preview=v.daily&&v.daily.preview,remaining=v.daily?Math.max(0,(Number.isFinite(v.daily.limit)?v.daily.limit/100:100)-v.daily.used/100):null;panel('<h2>小袋鼠送餐跑酷</h2><p>三条街道，准时送餐。<br>左右换道 · 上滑跳跃 · 下滑俯身<br>每局三颗心，撞到障碍扣一颗。</p><p>'+(preview?'本地试玩 · 不连接正式钱包':v.daily?daily(v.daily):'正在读取今日奖励…')+'</p>'+(preview?'':'<button data-nr="start" '+(!v.daily?'disabled':'')+'>'+(remaining===0?'继续挑战 · 今日已领满':'开始送餐')+'</button>')+'<button class="nr-alt" data-nr="practice">'+(preview?'开始试玩':'练习模式 · 不发奖励')+'</button><p class="nr-caption">每局最长150秒，每6秒完成1单，最多25单。<br>正式奖励为每单1、每天最多100；试玩不发币。</p>');}
 async function load(v){try{const d=await root.northRunnerRPC('status',{});if(!valid(v))return;v.daily=d;intro(v);}catch(e){if(!valid(v))return;panel('<h2>小袋鼠送餐跑酷</h2><p>'+text(message(e))+'</p><button data-nr="retry">重新连接</button><button class="nr-alt" data-nr="practice">先练习 · 不发奖励</button>');}}
 async function start(practice){let v=view;if(!v||v.busy||!valid(v))return;v.busy=true;v.practice=practice;primeMusic(v);try{panel('<h2>准备送餐</h2><p>正在准备街景和送餐车…</p>');await Promise.all([v.sprite.decode(),v.street.decode(),v.van.decode()]);if(!valid(v))return;if(practice)v.run={seed:Math.floor(Math.random()*2147483646)+1,physicsVersion:6};else {v.client=v.client||crypto.randomUUID();panel('<h2>准备送餐</h2><p>正在创建这一局，请稍等…</p>');v.run=await root.northRunnerRPC('start',{p_client:v.client,p_physics:6});if(!valid(v))return;}v.g=create(v.run.seed,v.run.physicsVersion||1);v.mode='running';v.busy=false;v.last=0;v.acc=0;v.x=1;v.lastHearts=3;v.overlay.hidden=true;v.overlay.style.display='none';v.tip.textContent=practice?'练习模式 · 无云端奖励':'';v.canvas.focus();music(v,'game',true);}catch(e){music(v,null);if(/runner-expired/.test(e.message))v.client=null;if(valid(v))panel('<h2>未能开局</h2><p>'+text(message(e))+'</p><button data-nr="start">重试原开局</button><button class="nr-alt" data-nr="practice">练习模式</button>');}finally{v.busy=false;}}
 function pause(){let v=view;if(!v||v.mode!=='running')return;v.mode='paused';music(v,null);panel('<h2>已暂停</h2><p>回来后继续，不会突然向前跳。<br>奖励局从开局起6分钟内有效。</p><button data-nr="resume">继续送餐</button><button class="nr-alt" data-nr="exit">退出本局</button>');}
 function finish(v){music(v,'result',true);v.mode='finished';v.paint=true;v.tip.textContent='';if(!v.practice){const data=S.food.north||(S.food.north={});data.runnerPending={account:v.account,phone:v.phone,id:v.run.id,seed:v.run.seed,physicsVersion:v.g.physicsVersion,ticks:v.g.tick,distance:v.g.distance,inputs:v.g.inputs,orders:v.g.orders};root.save();}result(v);}
 function result(v,notice){let left=v.daily?Math.max(0,(Number.isFinite(v.daily.limit)?v.daily.limit/100:100)-v.daily.used/100):0,amount=Math.min(v.g.orders,left);panel('<h2>'+(v.g.hearts?'送餐挑战完成！':'休息一下再出发')+'</h2><strong>'+v.g.orders+' 单</strong><p>本局完成送餐 · '+Math.floor(v.g.tick/60)+'秒</p><p>'+(notice|| (v.practice?'练习局不发放云端奖励':'预计可领取 '+amount+' 虚拟币，以云端结算为准'))+'</p>'+(!v.practice&&!v.claimed?'<button data-nr="claim">领取奖励</button><button class="nr-alt" data-nr="discard">放弃本局奖励</button>':'')+'<button class="nr-alt" data-nr="again">再跑一局</button><button class="nr-alt" data-nr="exit">返回外卖</button>');}
 async function claim(){const v=view;if(!v||v.busy||v.practice||v.claimed||!valid(v))return;v.busy=true;try{const d=await root.northRunnerRPC('claim',{p_id:v.run.id,p_ticks:v.g.tick,p_inputs:v.g.inputs});if(!valid(v))return;v.claimed=true;v.daily=d;const data=S.food.north;if(data.runnerPending&&data.runnerPending.id===v.run.id)delete data.runnerPending;root.save();result(v,'已到账 '+d.reward/100+' 虚拟币 · '+daily(d));}catch(e){if(valid(v))result(v,text(message(e)));}finally{v.busy=false;}}
 function exit(force){let v=view;if(!v)return false;if(!force&&v.mode==='running'){pause();return true;}if(!force&&v.mode==='paused'){panel('<h2>退出这局？</h2><p>未完成的这局不会领取奖励。</p><button data-nr="leave">确认退出</button><button class="nr-alt" data-nr="resume">继续跑</button>');return true;}music(v,null);if(v.audio){v.audio.removeAttribute('src');v.audio.load();}cancelAnimationFrame(raf);v.abort.abort();v.resize.disconnect();v.root.remove();view=null;return true;}
 function command(a){const v=view;if(!v||v.mode!=='running'||!valid(v))return;input(v.g,a);}
 function shape(c,color,pts){c.fillStyle=color;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fill();}
 function rounded(c,x,y,w,h,r,color){c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
 function ground(v,gap,lane){const p=project(gap);return {p,x:v.w/2+(lane-1)*v.w*.26*p,y:v.h*.28+(v.h*.85-v.h*.28)*p,size:v.w*.26*p*.74};}
 function paintRoad(v,g){const c=v.ctx,w=v.w,h=v.h,horizon=h*.28,foot=h*.85;if(v.street.complete&&v.street.naturalWidth)c.drawImage(v.street,0,0,w,h);else{c.fillStyle='#bce6ec';c.fillRect(0,0,w,h);}if(!v.asphalt&&v.street.naturalWidth){v.asphalt=document.createElement('canvas');v.asphalt.width=v.asphalt.height=256;v.asphalt.getContext('2d').drawImage(v.street,v.street.naturalWidth*.36,v.street.naturalHeight*.7,v.street.naturalWidth*.28,v.street.naturalHeight*.25,0,0,256,256);const texture=v.asphalt.getContext('2d'),fade=texture.createLinearGradient(0,0,256,0);fade.addColorStop(0,'rgba(255,255,255,0)');fade.addColorStop(.18,'#fff');fade.addColorStop(.82,'#fff');fade.addColorStop(1,'rgba(255,255,255,0)');texture.globalCompositeOperation='destination-in';texture.fillStyle=fade;texture.fillRect(0,0,256,256);}
  if(v.asphalt){c.save();c.beginPath();c.moveTo(w/2,horizon);c.lineTo(w*1.12,h);c.lineTo(-w*.12,h);c.closePath();c.clip();c.globalAlpha=.5;for(let i=0;i<48;i++){const y=horizon+8+(h-horizon-8)*i/48,dy=(h-horizon-8)/48+.5,p=(y+dy/2-horizon)/(foot-horizon),z=CAMERA/p-CAMERA,sy=((g.distance+z)*.012%240+240)%240;const half=w*.49*p;c.drawImage(v.asphalt,0,sy,256,12,w/2-half,y,half*2,dy);}c.restore();}
  const first=Math.floor((g.distance-2500)/6000);for(let i=first;i<first+15;i++){const gap=i*6000-g.distance;if(gap<=-CAMERA+500||gap>VIEW)continue;const a=ground(v,gap,1),b=ground(v,gap+1800,1);if(a.y>h+5&&b.y>h+5)continue;c.strokeStyle='#fff6d6';c.lineWidth=Math.max(.6,a.p*3);c.globalAlpha=Math.min(1,a.p*1.7);for(const sign of [-1,1]){c.beginPath();c.moveTo(a.x+sign*w*.13*a.p,a.y);c.lineTo(b.x+sign*w*.13*b.p,b.y);c.stroke();}c.globalAlpha=1;}
  for(let i=Math.floor(g.distance/23000);i<Math.floor(g.distance/23000)+4;i++){const gap=i*23000-g.distance;if(gap<0||gap>VIEW)continue;const at=ground(v,gap,1),size=55*at.p;for(const side of [-1,1]){const x=at.x+side*w*.59*at.p;c.fillStyle='#41342330';c.beginPath();c.ellipse(x,at.y,size*.3,size*.07,0,0,Math.PI*2);c.fill();rounded(c,x-size*.03,at.y-size*1.3,size*.06,size*1.3,size*.025,'#68695a');rounded(c,x-size*.16,at.y-size*1.45,size*.32,size*.27,size*.055,'#e5b95a');rounded(c,x-size*.1,at.y-size*1.41,size*.2,size*.18,size*.03,'#fff2b7');}}
 }
 function paintObstacle(v,o,gap){const c=v.ctx,a=ground(v,gap,o.lane),x=a.x,y=a.y,size=a.size;c.fillStyle='#34261644';c.beginPath();c.ellipse(x+size*.04,y+1,size*.48,size*.1,0,0,Math.PI*2);c.fill();if(o.type===0){shape(c,'#cf8e49',[[x-size/2,y-size*.64],[x+size*.34,y-size*.64],[x+size*.34,y],[x-size/2,y]]);shape(c,'#b17335',[[x+size*.34,y-size*.64],[x+size*.52,y-size*.78],[x+size*.52,y-size*.14],[x+size*.34,y]]);shape(c,'#f4c78a',[[x-size/2,y-size*.64],[x-size*.32,y-size*.78],[x+size*.52,y-size*.78],[x+size*.34,y-size*.64]]);c.fillStyle='#ffe7ba';c.fillRect(x-size*.04,y-size*.64,size*.12,size*.64);rounded(c,x-size*.32,y-size*.43,size*.22,size*.17,2*a.p,'#fff3d9');}
  else if(o.type===1){rounded(c,x-size*.46,y-size*1.8,size*.08,size*1.8,2*a.p,'#a1a392');rounded(c,x+size*.38,y-size*1.8,size*.08,size*1.8,2*a.p,'#828776');rounded(c,x-size*.5,y-size*1.8,size,size*.24,3*a.p,'#f3bd32');c.save();c.beginPath();c.rect(x-size*.5,y-size*1.8,size,size*.24);c.clip();for(let j=0;j<6;j++)shape(c,'#f6eee0',[[x-size*.55+j*size*.21,y-size*1.8],[x-size*.45+j*size*.21,y-size*1.8],[x-size*.58+j*size*.21,y-size*1.56],[x-size*.68+j*size*.21,y-size*1.56]]);c.restore();}
  else if(v.van.complete&&v.van.naturalWidth)c.drawImage(v.van,x-size*.62,y-size*1.24,size*1.24,size*1.24);
 }
 function paintRider(v,g){const c=v.ctx,w=v.w,foot=v.h*.85,t=g.tick,size=w*.28,fraction=Math.min(1,v.acc/STEP),qx=Number.isFinite(g.x)?(g.prevX+(g.x-g.prevX)*fraction):g.lane*1000,x=w/2+(qx/1000-1)*w*.26,jump=t<g.jump?Math.sin((42-(g.jump-t))/42*Math.PI)*size*.75:0,remaining=g.slide-t,duck=remaining>0?Math.min(1,(42-remaining)/6,remaining/6):0,y=foot-jump;c.fillStyle='#41342844';c.beginPath();c.ellipse(x,foot+3,size*.48*(1-jump/(size*2)),size*.09,0,0,Math.PI*2);c.fill();c.save();if(t<g.shield&&Math.floor(t/5)%2===0)c.globalAlpha=.4;c.translate(x,y);c.rotate((g.lane-qx/1000)*.14);c.scale(1,1-duck*.32);if(v.sprite.complete&&v.sprite.naturalWidth)c.drawImage(v.sprite,-size*.64,-size*1.28,size*1.28,size*1.28);c.restore();}
 function draw(v,dt){const g=v.g||v.decor,t=g.tick;paintRoad(v,g);let rider=false;
  const nextDrop=(Math.floor(t/600)+1)*600,dropGap=distanceAt(nextDrop)-g.distance;if(dropGap<VIEW&&nextDrop<=MAX){const a=ground(v,dropGap,1),c=v.ctx,wide=v.w*.4*a.p;c.strokeStyle='#ffe473';c.lineWidth=2+4*a.p;c.beginPath();c.moveTo(a.x-wide,a.y);c.lineTo(a.x+wide,a.y);c.stroke();}
  for(let i=Math.min(g.rows.length-1,g.row+5);i>=Math.max(0,g.row-2);i--){const row=g.rows[i],gap=row.distance-g.distance;if(gap<=-CAMERA+500||gap>VIEW)continue;const projected=ground(v,gap,1),highest=Math.max(...row.objects.map(o=>o.type===0?.78:o.type===1?1.8:1.24))*projected.size;if(projected.y-highest>v.h+5)continue;if(gap<0&&!rider){paintRider(v,g);rider=true;}for(const o of row.objects)paintObstacle(v,o,gap);}if(!rider)paintRider(v,g);
  if(v.mode!=='running'||t%6===0){v.hearts.innerHTML=Array.from({length:3},(_,i)=>'<b class="'+(i<g.hearts?'':'empty')+'">'+(i<g.hearts?'♥':'♡')+'</b>').join('');v.score.textContent=g.orders+' 单 · 速度 '+(speed(t,g.physicsVersion)/160).toFixed(1)+'×';if(g.hearts<v.lastHearts){v.tip.textContent='碰到障碍 · 小心！';v.hitUntil=t+70;v.lastHearts=g.hearts;}if(v.hitUntil&&t>v.hitUntil){v.tip.textContent=v.practice?'练习模式 · 无云端奖励':'';v.hitUntil=0;}}
 }
 function frame(now){const v=view;if(!v)return;if(!valid(v)){exit(true);return;}let dt=v.last?Math.min(100,now-v.last):0;v.last=now;if(v.mode==='running'){v.acc+=dt;let count=0;while(v.acc>=STEP&&count++<6){step(v.g);v.acc-=STEP;if(v.g.done){finish(v);break;}}}else v.acc=0;if(v.mode==='running'||v.paint){draw(v,dt);v.paint=false;}raf=requestAnimationFrame(frame);}
 function open(){if(view){return;}if(!root.isMain()){root.toast('请在本人主账号打开跑腿');return;}if(!document.getElementById('nr-css')){let s=document.createElement('style');s.id='nr-css';s.textContent=css;document.head.appendChild(s);}const p=root.phoneFriendState(),v={state:S,account:root.actId(),phone:p.id,secret:p.secret,abort:new AbortController(),mode:'intro',x:1,paint:true,decor:create(1)};view=v;let node=document.createElement('section');node.className='nr-root';node.innerHTML='<header class="nr-top"><button data-nr="exit">‹ 返回</button><b>小袋鼠跑腿</b><button data-nr="pause">暂停</button></header><div class="nr-stage"><canvas tabindex="0" aria-label="小袋鼠送餐跑酷：方向键或滑动控制"></canvas><div class="nr-hud"><span class="nr-score">0 单</span><span class="nr-hearts"><b>♥</b><b>♥</b><b>♥</b></span></div><div class="nr-tip"></div><div class="nr-help">箱子 ↑ 跳跃　横杆 ↓ 俯身　汽车 ← → 避开</div><div class="nr-overlay"></div></div>';document.body.appendChild(node);Object.assign(v,{root:node,canvas:node.querySelector('canvas'),overlay:node.querySelector('.nr-overlay'),hearts:node.querySelector('.nr-hearts'),score:node.querySelector('.nr-score'),tip:node.querySelector('.nr-tip')});v.ctx=v.canvas.getContext('2d',{alpha:false});v.sprite=new Image();v.sprite.src='assets/north-runner-rider.png';v.street=new Image();v.street.src='assets/north-runner-street.png';v.van=new Image();v.van.src='assets/north-runner-van.png';[v.sprite,v.street,v.van].forEach(image=>image.onload=()=>{v.paint=true;});const signal=v.abort.signal;
  node.addEventListener('click',e=>{let b=e.target.closest('[data-nr]');if(!b)return;const a=b.dataset.nr;if(a==='start')start(false);if(a==='practice')start(true);if(a==='pause')pause();if(a==='resume'){music(v,'game');v.mode='running';v.last=0;v.overlay.style.display='none';}if(a==='retry')load(v);if(a==='claim')claim();if(a==='exit')exit();if(a==='leave')exit(true);if(a==='discard')panel('<h2>放弃这一局？</h2><p>尚未到账的本局奖励将不再申请。</p><button data-nr="discard-confirm">确认放弃，重新开始</button><button class="nr-alt" data-nr="claim">返回领取</button>');if(a==='discard-confirm'){const d=S.food.north;if(d.runnerPending&&d.runnerPending.id===v.run.id)delete d.runnerPending;root.save();v.client=null;v.claimed=false;v.mode='intro';load(v);}if(a==='again'){music(v,null);if(!v.practice&&!v.claimed){panel('<h2>还有未领取的奖励</h2><p>先领取这一局，或返回外卖后再领取。</p><button data-nr="claim">领取奖励</button><button class="nr-alt" data-nr="exit">返回外卖</button>');return;}v.client=null;v.claimed=false;v.mode='intro';load(v);}},{signal});
  document.addEventListener('keydown',e=>{let a={ArrowLeft:'l',ArrowRight:'r',ArrowUp:'u',ArrowDown:'d'}[e.key];if(a){e.preventDefault();command(a);}if(e.key==='Escape')pause();},{signal});let touch=null;v.canvas.addEventListener('pointerdown',e=>{touch={id:e.pointerId,x:e.clientX,y:e.clientY};v.canvas.setPointerCapture(e.pointerId);},{signal});v.canvas.addEventListener('pointermove',e=>{if(!touch||touch.id!==e.pointerId)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;command(Math.abs(dx)>Math.abs(dy)?dx>0?'r':'l':dy>0?'d':'u');touch=null;},{signal});['pointerup','pointercancel','lostpointercapture'].forEach(type=>v.canvas.addEventListener(type,()=>touch=null,{signal}));document.addEventListener('visibilitychange',()=>{if(document.hidden){music(v,null);pause();}},{signal});window.addEventListener('blur',()=>{music(v,null);pause();},{signal});
  v.resize=new ResizeObserver(()=>{const r=v.canvas.getBoundingClientRect(),d=Math.min(1.5,devicePixelRatio||1);v.paint=true;v.w=r.width;v.h=r.height;v.canvas.width=Math.round(r.width*d);v.canvas.height=Math.round(r.height*d);v.ctx.setTransform(d,0,0,d,0,0);});v.resize.observe(v.canvas);const pending=S.food.north&&S.food.north.runnerPending;if(pending&&pending.account===v.account&&pending.phone===v.phone){v.run={id:pending.id,seed:pending.seed};v.g={tick:pending.ticks,distance:distanceAt(pending.ticks,pending.physicsVersion||1),orders:pending.orders,inputs:pending.inputs,hearts:0,rows:[],row:0,lane:1};v.mode='finished';root.northRunnerRPC('status',{}).then(d=>{if(valid(v)){v.daily=d;result(v);}}).catch(()=>{if(valid(v))result(v,'连接失败，可重试领取原局奖励。');});}else {intro(v);load(v);}raf=requestAnimationFrame(frame);
 }
 root.NorthRunner={open,back:()=>exit(),close:()=>exit(true),pause};
})(typeof window==='undefined'?globalThis:window);
