/* 电子宠物：独立养成模块。所有持久状态仅挂在 S.me.ePet 下。 */
const PET_DAY=86400000;
const PET_HOUR=3600000;
const PET_STAGE_NAMES=['奶团期','幼崽期','少年期','成长期','成年期'];
const PET_STAGE_MONTHS=[0,2,5,10,18];
const PET_FOODS=[
  {id:'kibble',name:'营养粮',icon:'◇',price:18,fill:24,note:'日常主食'},
  {id:'chicken',name:'鸡肉小碗',icon:'◒',price:32,fill:38,note:'香喷喷的正餐'},
  {id:'fish',name:'鲜鱼餐',icon:'≈',price:38,fill:42,note:'猫狗都喜欢'},
  {id:'snack',name:'星星零食',icon:'☆',price:14,fill:12,note:'开心加倍'}
];
const PET_WEAR=[
  {id:'bow',type:'head',name:'莓果蝴蝶结',price:68},
  {id:'clip',type:'head',name:'星光发卡',price:58},
  {id:'flower-clip',type:'head',name:'雏菊小花夹',price:72},
  {id:'beret',type:'head',name:'软呢小贝雷帽',price:96},
  {id:'crown',type:'head',name:'奶油小皇冠',price:108},
  {id:'collar',type:'neck',name:'软绒项圈',price:76},
  {id:'bell-collar',type:'neck',name:'格纹铃铛项圈',price:88},
  {id:'pearl-collar',type:'neck',name:'珍珠花边项圈',price:98},
  {id:'scarf',type:'neck',name:'野餐小领巾',price:92},
  {id:'flower-collar',type:'neck',name:'春日花环项圈',price:106},
  {id:'moon-collar',type:'neck',name:'月光吊坠项圈',price:102},
  {id:'dress',type:'body',name:'奶油小裙子',price:128},
  {id:'sweater',type:'body',name:'云朵针织衫',price:118},
  {id:'raincoat',type:'body',name:'雨后小斗篷',price:136},
  {id:'overalls',type:'body',name:'莓果背带裤',price:142},
  {id:'cape',type:'body',name:'星夜短披风',price:148}
];
const PET_BREEDS={
  cat:[
    {id:'orange',name:'奶油橘猫',note:'暖橘虎斑，亲人又爱撒娇',fur:'#e7aa68',second:'#fff0d7',eye:'#6f9a68'},
    {id:'ragdoll',name:'布偶猫',note:'蓝眼长毛，安静又黏人',fur:'#eee5d8',second:'#80665f',eye:'#67a9d3'},
    {id:'silver',name:'银渐层',note:'银灰绒毛，圆脸小公主',fur:'#d6d7d4',second:'#737775',eye:'#91b06f'},
    {id:'siamese',name:'暹罗猫',note:'重点色脸蛋，活泼话很多',fur:'#e6d1aa',second:'#594945',eye:'#73acd3'}
  ],
  dog:[
    {id:'shiba',name:'柴犬',note:'卷尾小狐狸，精神又忠诚',fur:'#da9556',second:'#fff0d5',eye:'#795b4a'},
    {id:'corgi',name:'柯基',note:'短腿大耳朵，走路一扭一扭',fur:'#d99654',second:'#fff4dc',eye:'#78594a'},
    {id:'bichon',name:'比熊',note:'蓬松白棉花，开心爱转圈',fur:'#f0efea',second:'#d8d2ca',eye:'#765d55'},
    {id:'golden',name:'金毛',note:'软耳暖金色，温柔又热情',fur:'#d8a45f',second:'#edc47f',eye:'#755747'}
  ]
};
let _petPaintDraft=null;
let _petAudioCtx=null;
let _petIgnoreTapUntil=0;
let _petSvgNonce=0;
let _petThrowBall='';
let _petBallState=null;
let _petToyTimers=[];

function petClamp(v,a,b){return Math.max(a,Math.min(b,+v||0));}
function petUid(){return typeof uid==='function'?uid():'pet_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function petRoot(){
  S.me=S.me||{};
  if(!S.me.ePet||typeof S.me.ePet!=='object'||Array.isArray(S.me.ePet))S.me.ePet={coins:320,pets:[],activeId:'',inventory:{kibble:3,chicken:1,fish:1,snack:2},ownedWear:[],sharedRoleId:'',logs:[],version:1};
  const x=S.me.ePet;
  x.pets=Array.isArray(x.pets)?x.pets:[];
  x.inventory=x.inventory&&typeof x.inventory==='object'?x.inventory:{kibble:3,chicken:1,fish:1,snack:2};
  x.ownedWear=Array.isArray(x.ownedWear)?x.ownedWear:[];
  x.logs=Array.isArray(x.logs)?x.logs:[];
  x.coins=Math.max(0,Math.floor(+x.coins||0));
  if(!x.activeId&&x.pets[0])x.activeId=x.pets[0].id;
  x.pets.forEach(petNormalize);
  if(x.pets.length===2){const a=x.pets[0],b=x.pets[1],distance=Math.hypot(a.roomX-b.roomX,a.roomY-b.roomY);if(distance<18){b.roomX=a.roomX<52?petClamp(a.roomX+30,18,84):petClamp(a.roomX-30,18,84);b.roomY=petClamp(a.roomY+4,34,84);}}
  petUpdateAll(x);
  return x;
}
function petNormalize(p){
  if(!p||typeof p!=='object')return;
  p.id=p.id||petUid();p.species=p.species==='dog'?'dog':'cat';p.name=String(p.name||'小团子').slice(0,12);
  p.bornAt=+p.bornAt||Date.now();p.lastUpdate=+p.lastUpdate||Date.now();p.lastPoopAt=+p.lastPoopAt||p.bornAt;
  ['hunger','clean','joy','energy','health','affection'].forEach(k=>p[k]=petClamp(p[k]==null?86:p[k],0,100));
  p.poop=petClamp(p.poop,0,6);p.careScore=petClamp(p.careScore==null?65:p.careScore,0,100);p.careActions=Math.max(0,+p.careActions||0);
  p.meals=p.meals&&typeof p.meals==='object'?p.meals:{};p.accessories=p.accessories&&typeof p.accessories==='object'?p.accessories:{head:'',neck:'',body:''};
  p.colors=p.colors&&typeof p.colors==='object'?p.colors:{fur:p.species==='cat'?'#f4cba7':'#d7b08a',accent:'#ef8faa',cloth:'#db8ba8'};
  const breeds=PET_BREEDS[p.species],fallback=p.species==='dog'?'shiba':'orange';
  if(!breeds.some(b=>b.id===p.breed))p.breed=fallback;
  const roomMinX=p.species==='cat'?15:14,roomMaxX=p.species==='cat'?84:86;
  p.roomX=petClamp(p.roomX==null?50:p.roomX,roomMinX,roomMaxX);p.roomY=petClamp(p.roomY==null?72:p.roomY,22,86);
  p.plumpness=petClamp(p.plumpness==null?0:p.plumpness,0,100);
  p.sleepPose=Math.max(0,Math.min(2,Math.floor(+p.sleepPose||0)));
  p.strokes=Array.isArray(p.strokes)?p.strokes:[];p.looks=Array.isArray(p.looks)?p.looks:[];p.revealed=!!p.revealed;
}
function petBreed(species,id){const list=PET_BREEDS[species==='dog'?'dog':'cat'];return list.find(b=>b.id===id)||list[0];}
function petDefault(species,name,breed){
  const now=Date.now();
  species=species==='dog'?'dog':'cat';const b=petBreed(species,breed);
  return {id:petUid(),species,breed:b.id,name:String(name||'小团子').slice(0,12),bornAt:now,lastUpdate:now,lastPoopAt:now,hunger:88,clean:92,joy:86,energy:88,health:100,affection:50,poop:0,careScore:68,careActions:0,meals:{},accessories:{head:'',neck:'',body:''},colors:{fur:b.fur,accent:'#ef8faa',cloth:'#db8ba8'},roomX:50,roomY:72,sleepPose:Math.floor(Math.random()*3),strokes:[],looks:[],revealed:false,mateId:'',speech:''};
}
function petActive(){const x=petRoot();return x.pets.find(p=>p.id===x.activeId)||x.pets[0]||null;}
function petLocalDay(ts){const d=new Date(ts||Date.now());return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function petMealSlot(now){const h=new Date(now||Date.now()).getHours();return h>=5&&h<11?'breakfast':h>=11&&h<17?'lunch':h>=17?'dinner':'late';}
function petMealName(slot){return {breakfast:'早餐',lunch:'午餐',dinner:'晚餐',late:'夜宵'}[slot]||'加餐';}
function petIsNight(){const h=new Date().getHours();return h>=22||h<6;}
function petUpdateAll(x){
  const now=Date.now();let changed=false;
  (x.pets||[]).forEach(p=>{
    const elapsed=Math.min(96,Math.max(0,(now-(+p.lastUpdate||now))/PET_HOUR));
    if(elapsed>.02){
      p.hunger=petClamp(p.hunger-elapsed*3.15,0,100);
      p.clean=petClamp(p.clean-elapsed*(.75+p.poop*.24),0,100);
      p.joy=petClamp(p.joy-elapsed*(p.hunger<30?2.2:1.05),0,100);
      p.energy=petClamp(p.energy+(petIsNight()?elapsed*4.2:-elapsed*.65),0,100);
      if(p.hunger<20)p.plumpness=petClamp(p.plumpness-elapsed*.18,0,100);
      if(p.hunger<18||p.clean<16||p.joy<15)p.health=petClamp(p.health-elapsed*1.15,0,100);else if(p.hunger>55&&p.clean>55)p.health=petClamp(p.health+elapsed*.35,0,100);
      p.lastUpdate=now;changed=true;
    }
    const newPoop=Math.min(6,Math.floor((now-(+p.lastPoopAt||now))/(7*PET_HOUR)));
    if(newPoop>0){p.poop=petClamp(p.poop+newPoop,0,6);p.lastPoopAt+=(newPoop*7*PET_HOUR);changed=true;}
    const low=petMoodValue(p)<25;
    if(low&&!p.lowMoodSince){p.lowMoodSince=now;changed=true;}else if(!low&&p.lowMoodSince){p.lowMoodSince=0;changed=true;}
    p.depressed=!!(p.lowMoodSince&&now-p.lowMoodSince>8*PET_HOUR);
  });
  if(changed&&typeof save==='function')save();
}
function petAgeInfo(p){
  const days=Math.max(0,(Date.now()-p.bornAt)/PET_DAY),boost=1+Math.min(.18,(p.careScore/100)*.18),months=Math.max(0,Math.floor(days/15*12*boost));
  let stage=0;for(let i=PET_STAGE_MONTHS.length-1;i>=0;i--)if(months>=PET_STAGE_MONTHS[i]){stage=i;break;}
  const age=months<12?Math.max(1,months+1)+'个月':Math.floor(months/12)+'岁'+(months%12?months%12+'个月':'');
  return {days,months,stage,age,boost};
}
function petMoodValue(p){return Math.round(p.joy*.42+p.health*.26+p.hunger*.18+p.clean*.14);}
function petMoodLabel(p){const v=petMoodValue(p);if(p.depressed)return'闷闷不乐';if(v<25)return'快要蔫了';if(v<45)return'有点委屈';if(v<68)return'安安静静';if(v<86)return'很开心';return'兴奋得转圈';}
function petLog(text,coin){const x=petRoot();x.logs.unshift({time:Date.now(),text:String(text||'').slice(0,100)});if(x.logs.length>200)x.logs.length=200;if(coin)x.coins=Math.max(0,x.coins+coin);save();}
function petRole(){const x=petRoot();return x.sharedRoleId&&typeof getC==='function'?getC(x.sharedRoleId):null;}
function petRoleName(){const c=petRole();return c?(c.remark||c.name):'';}
function petTogether(action){const n=petRoleName();return n?('你和'+n+'一起'+action):('你'+action);}

function petStrokePaths(p){return (p.strokes||[]).map(s=>{const pts=(s.points||[]).map((q,i)=>(i?'L':'M')+petClamp(q[0],0,320).toFixed(1)+' '+petClamp(q[1],0,320).toFixed(1)).join(' ');return pts?`<path d="${pts}" fill="none" stroke="${esc(s.color||'#c46f8b')}" stroke-width="${petClamp(s.width||6,2,24)}" stroke-linecap="round" stroke-linejoin="round"/>`:'';}).join('');}
function petIsSleeping(p){return !!(p&&((p.forcedSleepUntil||0)>Date.now()||(petIsNight()&&!((p.awakeUntil||0)>Date.now()))));}
function petBreedName(p){return petBreed(p&&p.species,p&&p.breed).name;}
function petBodyWearSvg(id,cloth){
  if(id==='dress')return `<path d="M103 201q57-29 114 0l20 71q-77 27-154 0Z" fill="${cloth}" stroke="#fff" stroke-width="5" opacity=".94"/><path d="M105 213q54 18 110 0" fill="none" stroke="#fff" stroke-width="6" opacity=".7"/>`;
  if(id==='sweater')return `<path d="M101 201q59-25 118 0l6 62q-65 22-130 0Z" fill="${cloth}" stroke="#fff" stroke-width="5" opacity=".94"/><path d="M159 190v78" stroke="#fff" stroke-width="4" opacity=".55"/>`;
  if(id==='raincoat')return `<path d="M99 201q61-29 122 0l13 68q-74 24-148 0Z" fill="#f4c95d" stroke="#fff" stroke-width="5" opacity=".96"/><path d="M111 205q49 19 98 0M160 198v72" fill="none" stroke="#fff" stroke-width="4" opacity=".72"/><circle cx="160" cy="222" r="4" fill="#fff"/><circle cx="160" cy="241" r="4" fill="#fff"/>`;
  if(id==='overalls')return `<path d="M104 217q56-18 112 0l8 55q-64 20-128 0Z" fill="#799bc4" stroke="#fff" stroke-width="5" opacity=".96"/><path d="M126 190v48m68-48v48M127 221h66v43" fill="none" stroke="#fff" stroke-width="6"/><circle cx="128" cy="219" r="5" fill="#f7d76e"/><circle cx="192" cy="219" r="5" fill="#f7d76e"/>`;
  if(id==='cape')return `<path d="M110 191q50 25 100 0l28 77q-78 32-156 0Z" fill="#596184" stroke="#fff" stroke-width="5" opacity=".95"/><path d="M112 197q48 20 96 0" fill="none" stroke="#f7d76e" stroke-width="6"/><path d="m199 229 5 10 11 2-8 8 2 11-10-5-10 5 2-11-8-8 11-2Z" fill="#f7d76e" stroke="none"/>`;
  return '';
}
function petNeckWearSvg(id,accent){
  if(id==='collar')return `<path d="M111 180q49 20 98 0" fill="none" stroke="${accent}" stroke-width="13"/><circle cx="160" cy="195" r="10" fill="#f8c858" stroke="#fff" stroke-width="3"/>`;
  if(id==='bell-collar')return `<path d="M111 180q49 20 98 0" fill="none" stroke="#d16f71" stroke-width="14"/><path d="M115 177q45 18 90 0" fill="none" stroke="#fff" stroke-width="4" stroke-dasharray="10 8"/><circle cx="160" cy="198" r="11" fill="#f4c754" stroke="#fff" stroke-width="3"/><path d="M153 199h14m-7 0v7" stroke="#9f7832" stroke-width="2"/>`;
  if(id==='pearl-collar')return `<path d="M113 179q47 28 94 0" fill="none" stroke="#fff8ee" stroke-width="5"/>${[118,132,146,160,174,188,202].map((x,i)=>`<circle cx="${x}" cy="${184+Math.abs(3-i)*3}" r="7" fill="#fff8ee" stroke="#d8b8ae" stroke-width="2"/>`).join('')}<circle cx="160" cy="204" r="8" fill="${accent}" stroke="#fff" stroke-width="3"/>`;
  if(id==='scarf')return `<path d="M110 178q50 24 100 0" fill="none" stroke="${accent}" stroke-width="16"/><path d="M170 192l35 53-30-8-18 25-4-65Z" fill="${accent}" stroke="#fff" stroke-width="4"/><path d="M183 213l11 17" stroke="#fff" stroke-width="3" opacity=".72"/>`;
  if(id==='flower-collar')return `<path d="M111 181q49 22 98 0" fill="none" stroke="#78a77a" stroke-width="7"/>${[124,142,160,178,196].map((x,i)=>`<g transform="translate(${x} ${187+Math.abs(2-i)*3})"><circle r="8" fill="#fff" stroke="#e8c4cf" stroke-width="2"/><circle r="3.5" fill="#f5c85e" stroke="none"/></g>`).join('')}`;
  if(id==='moon-collar')return `<path d="M111 180q49 20 98 0" fill="none" stroke="#596184" stroke-width="12"/><path d="M166 190a12 12 0 1 1-10 19 10 10 0 1 0 10-19Z" fill="#f6d878" stroke="#fff" stroke-width="2"/><circle cx="141" cy="193" r="2.5" fill="#fff" stroke="none"/><circle cx="181" cy="192" r="2.5" fill="#fff" stroke="none"/>`;
  return '';
}
function petHeadWearSvg(id,accent){
  if(id==='bow')return `<g transform="translate(204 73) rotate(10)"><path d="M0 16Q-31-4-34 20T0 25Q31-4 34 20T0 25Z" fill="${accent}" stroke="#fff" stroke-width="4"/><circle cx="0" cy="21" r="9" fill="#f7b0c2"/></g>`;
  if(id==='clip')return `<g transform="translate(205 78) rotate(18)"><path d="m0-14 5 10 12 2-9 8 3 12-11-6-11 6 3-12-9-8 12-2Z" fill="#ffd86d" stroke="#fff" stroke-width="3"/></g>`;
  if(id==='flower-clip')return `<g transform="translate(205 77) rotate(13)">${[0,60,120,180,240,300].map(a=>`<ellipse cx="0" cy="-11" rx="7" ry="12" transform="rotate(${a})" fill="#fff" stroke="#e6b7c4" stroke-width="2"/>`).join('')}<circle r="7" fill="#f5c85e" stroke="#fff" stroke-width="2"/></g>`;
  if(id==='beret')return `<g transform="translate(160 66) rotate(-7)"><ellipse cx="0" cy="1" rx="48" ry="19" fill="${accent}" stroke="#fff" stroke-width="4"/><path d="M-35 4q35-42 70 0" fill="${accent}" stroke="#fff" stroke-width="4"/><path d="M0-31q6-10 13-2" fill="none" stroke="${accent}" stroke-width="7"/></g>`;
  if(id==='crown')return `<g transform="translate(160 62)"><path d="m-36 18 5-40 20 22L0-30 12 0l22-22 3 40Z" fill="#f6d56b" stroke="#fff" stroke-width="4"/><circle cx="-11" cy="0" r="4" fill="${accent}" stroke="none"/><circle cx="12" cy="0" r="4" fill="#79a5ca" stroke="none"/></g>`;
  return '';
}
function petSvg(p,opt){
  opt=opt||{};const a=petAgeInfo(p),s=opt.stage==null?a.stage:Math.max(0,Math.min(4,Math.floor(opt.stage))),id='pet'+String(p.id).replace(/[^a-z0-9]/gi,'').slice(-8)+'r'+(++_petSvgNonce),breed=petBreed(p.species,p.breed),fur=p.colors.fur||breed.fur,second=breed.second,accent=p.colors.accent||'#ef8faa',cloth=p.colors.cloth||'#db8ba8';
  const sleeping=opt.awake?false:(opt.sleeping==null?petIsSleeping(p):!!opt.sleeping),sad=petMoodValue(p)<40,voice=p.reaction==='voice',lick=p.reaction==='lick',happyEyes=lick||['eat','bath','clean','together'].includes(p.reaction),round=1+(petClamp(p.plumpness||0,0,100)/100)*.18;
  const scale=[.66,.78,.9,1,1.08][s],bodyW=[94,108,121,132,142][s]*(p.breed==='corgi'?1.13:1)*round,bodyH=[78,88,98,108,116][s]*(p.breed==='corgi'?.84:1)*(1+(round-1)*.55),headR=[61,60,58,56,55][s]*(p.breed==='bichon'?1.08:1),cy=[204,203,201,199,197][s];
  const eyeColor=breed.eye||'#76594f',eyes=happyEyes?'<path d="M119 138q11 11 22 0M179 138q11 11 22 0"/>':sad?'<path d="M120 139q10-8 20 0M180 139q10-8 20 0"/>':`<ellipse cx="130" cy="136" rx="5" ry="8" fill="${eyeColor}"/><ellipse cx="190" cy="136" rx="5" ry="8" fill="${eyeColor}"/><circle cx="132" cy="133" r="1.6" fill="#fff" stroke="none"/><circle cx="192" cy="133" r="1.6" fill="#fff" stroke="none"/>`;
  const upright=p.species==='cat'||p.breed==='shiba'||p.breed==='corgi';
  const ears=p.breed==='corgi'?`<path d="M108 111Q70 81 82 35q43 12 62 53M212 111q38-30 26-76-43 12-62 53" fill="${fur}"/><path d="M104 88Q87 69 91 49q25 12 36 36m89 3q17-19 13-39-25 12-36 36" fill="${second}" opacity=".82"/>`:upright?`<path d="M104 103 111 43l43 42M216 103l-7-60-43 42" fill="${fur}"/><path d="m116 82 3-25 18 22m67 3-3-25-18 22" fill="${second}" opacity=".72"/>`:`<path d="M105 88Q62 72 72 137q20 12 42-8M215 88q43-16 33 49-20 12-42-8" fill="${fur}"/>`;
  const tail=p.species==='cat'?`<g class="pet-tail"><path d="M210 232c38 22 76 10 91-15 12-20 7-39-7-46-12-6-25 0-27 11-2 10 8 17 18 12-7 19-26 28-46 22-13-4-21-12-26-19Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/></g>`:p.breed==='golden'?`<g class="pet-tail"><path d="M216 226q42 0 73-29-5 32-28 48 19-2 34-13-20 31-77 26Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/><path d="M237 239q27-8 43-25m-37 33q25-4 38-14" fill="none" stroke="${second}" stroke-width="3" opacity=".5"/></g>`:p.breed==='corgi'?`<g class="pet-tail"><path d="M218 229q35-23 31-49 22 24 3 50-13 16-35 18Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/><path d="M231 230q13-13 11-29" fill="none" stroke="${second}" stroke-width="4" opacity=".52"/></g>`:p.breed==='bichon'?`<g class="pet-tail"><path d="M216 231q23-11 25-28-5-17 12-22 12-17 27-5 19 2 17 20 8 17-9 25-10 18-31 9-17 13-39 19Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/><path d="M246 211q13 8 25 0m-20-19q9 8 18 1m6 21q9 4 15-3" fill="none" stroke="${second}" stroke-width="3" opacity=".5"/></g>`:`<g class="pet-tail"><path d="M218 231q35-12 40-37 3-18-12-19-13-1-13 12 0 10 10 11-18 10-28-3 1-30 30-35 32-4 39 28 7 34-46 60Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/><path d="M238 225q29-11 33-34 2-13-7-19" fill="none" stroke="${second}" stroke-width="4" opacity=".48"/></g>`;
  const body=p.species==='cat'?`<path d="M160 ${cy-bodyH}C${160-bodyW*.56} ${cy-bodyH*.9} ${160-bodyW*.88} ${cy-bodyH*.3} ${160-bodyW*.92} ${cy+bodyH*.2}C${160-bodyW} ${cy+bodyH*.72} ${160-bodyW*.52} ${cy+bodyH} 160 ${cy+bodyH}S${160+bodyW} ${cy+bodyH*.72} ${160+bodyW*.92} ${cy+bodyH*.2}C${160+bodyW*.88} ${cy-bodyH*.3} ${160+bodyW*.56} ${cy-bodyH*.9} 160 ${cy-bodyH}Z" fill="url(#${id}fur)"/>`:`<ellipse cx="160" cy="${cy}" rx="${bodyW}" ry="${bodyH}" fill="url(#${id}fur)"/>`;
  const muzzle=p.species==='dog'?`<ellipse cx="160" cy="157" rx="36" ry="25" fill="${second}" opacity=".9"/>`:'';
  let markings='';
  if(p.breed==='orange')markings='<path d="M142 91q18 15 36 0M147 80l8 27m18-27-8 27" fill="none" opacity=".3"/>';
  else if(p.breed==='ragdoll'||p.breed==='siamese')markings=`<path d="M118 91q42-35 84 0l-13 57q-29 21-58 0Z" fill="${second}" opacity=".9"/>`;
  else if(p.breed==='silver')markings=`<path d="M128 79q32 25 64 0M134 89q26 20 52 0" fill="none" stroke="${second}" opacity=".48"/>`;
  else if(p.breed==='shiba')markings=`<path d="M124 97q36 20 72 0l-8 61q-28 22-56 0Z" fill="${second}" opacity=".9"/><path d="M112 141q14 17 31 12m65-12q-14 17-31 12" fill="none" stroke="${second}" stroke-width="9" opacity=".85"/>`;
  else if(p.breed==='corgi')markings=`<path d="M145 70q15 10 30 0l15 88q-30 25-60 0Z" fill="${second}" opacity=".95"/><path d="M107 202q53 36 106 0l8 54q-61 24-122 0Z" fill="${second}" opacity=".88"/>`;
  else if(p.breed==='bichon')markings=`<path d="M105 105Q82 83 102 65q13-25 36-14 20-25 43-5 29-9 37 19 22 18-3 43" fill="${fur}" stroke="#805e52" stroke-width="5"/><path d="M105 105Q82 83 102 65q13-25 36-14 20-25 43-5 29-9 37 19 22 18-3 43" fill="none" stroke="rgba(255,255,255,.34)" stroke-width="2"/>`;
  else if(p.breed==='golden')markings=`<path d="M112 93q-14 48 9 70m87-70q14 48-9 70" fill="none" stroke="${second}" stroke-width="13" opacity=".66"/>`;
  const bodyWear=petBodyWearSvg(p.accessories.body,cloth);
  const neck=petNeckWearSvg(p.accessories.neck,accent);
  const head=petHeadWearSvg(p.accessories.head,accent);
  const defs=`<defs><linearGradient id="${id}fur" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#fff" stop-opacity=".42"/><stop offset=".42" stop-color="${fur}"/><stop offset="1" stop-color="${fur}" stop-opacity=".84"/></linearGradient><filter id="${id}soft"><feDropShadow dx="0" dy="7" stdDeviation="7" flood-opacity=".14"/></filter></defs>`;
  if(sleeping){
    const pose=Math.max(0,Math.min(2,p.sleepPose||0)),poses=[{bx:172,by:211,rx:101,ry:56,rot:-4,hx:103,hy:201,hr:-7},{bx:154,by:215,rx:108,ry:52,rot:7,hx:226,hy:202,hr:10},{bx:167,by:213,rx:96,ry:62,rot:0,hx:116,hy:185,hr:-3}],z=poses[pose];
    const sleepEars=p.breed==='corgi'?`<path d="M-35-24Q-72-45-58-78q38 10 51 45M35-24q72-45 58-78-38 10-51 45" fill="${fur}"/><path d="M-38-34q-20-18-14-31 19 8 29 27m61 4q20-18 14-31-19 8-29 27" fill="${second}" opacity=".78"/>`:p.species==='cat'||p.breed==='shiba'?`<path d="M-38-25-32-70-5-40M38-25 32-70 5-40" fill="${fur}"/><path d="M-29-42-25-60-13-41m42-1 25-60 13-41" fill="${second}" opacity=".72"/>`:p.breed==='bichon'?`<path d="M-35-30Q-72-42-66 13q17 17 37-7M35-30q72-42 66 13-17 17-37-7" fill="${fur}"/><path d="M-43-33q-20-28 1-38 13-25 34-10 22-21 42 0 24-12 36 12 20 13 2 36" fill="${fur}" stroke="#805e52" stroke-width="5"/>`:`<path d="M-35-30Q-75-38-66 16q18 14 38-8M35-30q75-38 66 16-18 14-38-8" fill="${fur}"/>`;
    const sleepMark=p.breed==='ragdoll'||p.breed==='siamese'?`<path d="M-39-24q39-30 78 0L28 20Q0 39-28 20Z" fill="${second}" opacity=".9"/>`:p.breed==='orange'?`<path d="M-15-43 0-25 15-43M-44-7l24 5M44-7 20-2" fill="none" opacity=".3"/>`:p.breed==='silver'?`<path d="M-20-43Q0-24 20-43M-40-8l23 7M40-8 17-1" fill="none" stroke="${second}" opacity=".52"/>`:p.breed==='corgi'?`<path d="M-11-46Q0-35 11-46L24 21Q0 38-24 21Z" fill="${second}" opacity=".94"/>`:p.breed==='shiba'?`<path d="M-31-25Q0-4 31-25L24 22Q0 39-24 22Z" fill="${second}" opacity=".9"/>`:'';
    const sleepTail=p.species==='cat'?`<path d="M225 235q50 5 54 28 2 21-27 24-33 3-64-17 35 9 56 0 18-8 2-18-12-8-29-7Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/>`:p.breed==='bichon'?`<path d="M224 236q25-3 30 14 17-8 27 6 13 15-2 27-14 15-32 3-18 4-31-10Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/>`:p.breed==='golden'?`<path d="M220 238q52 1 76 31-26-9-42 5 17 4 29 14-39 2-72-22Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/>`:`<path d="M221 239q41-8 55 13 12 20-10 35-19 13-42-2 24 1 31-12 6-12-10-17Z" fill="url(#${id}fur)" stroke="#805e52" stroke-width="5"/>`;
    return `<svg class="pet-svg pet-stage-${s} is-asleep sleep-pose-${pose}" viewBox="0 0 320 320" role="img" aria-label="${esc(p.name)}，${esc(breed.name)}，正在睡觉">${defs}<ellipse cx="160" cy="270" rx="112" ry="18" fill="#6f4f3d" opacity=".11"/><g transform="translate(160 170) scale(${scale}) translate(-160 -170)" filter="url(#${id}soft)" stroke="#805e52" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">${sleepTail}<ellipse cx="${z.bx}" cy="${z.by}" rx="${z.rx}" ry="${z.ry}" transform="rotate(${z.rot} ${z.bx} ${z.by})" fill="url(#${id}fur)"/><path d="M112 240q25 15 52 1M176 246q23 11 44-2" fill="none" opacity=".75"/><g transform="translate(${z.hx} ${z.hy}) rotate(${z.hr})"><circle r="54" fill="url(#${id}fur)"/>${sleepEars}${sleepMark}<path d="M-34 5q9 8 18 0M16 5q9 8 18 0" fill="none"/><path d="M-5 20q5 5 10 0" fill="${accent}"/><path d="M0 25q-8 7-15 1M0 25q8 7 15 1" fill="none"/>${p.species==='cat'?'<path d="M-28 24-58 18M-29 31-59 34M28 24 58 18M29 31 59 34" fill="none" stroke-width="3" opacity=".62"/>':''}</g></g></svg>`;
  }
  const mouth=lick?`<path d="M145 159q15 15 30 0" fill="#70413f"/><path d="M151 165q9 24 18 0" fill="#f18ba1" stroke="#fff" stroke-width="2" class="pet-tongue"/>`:p.reaction==='eat'?`<ellipse cx="160" cy="165" rx="12" ry="8" fill="#70413f"/><path d="M152 167q8 7 16 0" fill="#f2a1ad" stroke="none" class="pet-chew"/>`:voice?`<ellipse cx="160" cy="166" rx="14" ry="11" fill="#70413f"/><path d="M152 169q8 7 16 0" fill="#f18ba1" stroke="none"/>`:happyEyes?`<path d="M145 158q15 17 30 0" fill="none"/>`:`<path d="M160 155q-7 10-15 4M160 155q7 10 15 4" fill="none"/>`;
  const livingDetails=p.species==='cat'?`<path d="M119 160 84 148M118 168 78 168M119 176 85 187M201 160l35-12M202 168l40 0M201 176l34 11" fill="none" stroke-width="3" opacity=".62"/><path d="M122 78l10 15m66-15-10 15" fill="none" stroke-width="3" opacity=".34"/><path d="M142 185q18 11 36 0l-6 12 9 8-21 14-21-14 9-8Z" fill="${second}" opacity=".27"/><path d="M133 244q27 18 54 0M118 263q12-8 24 0m36 0q12-8 24 0M128 266v7m64-7v7" fill="none" opacity=".5"/><path d="M111 145l-10 8 13 2m95-10 10 8-13 2" fill="none" stroke-width="3" opacity=".5"/>`:`<path d="M137 239q23 13 46 0" fill="none" opacity=".42"/><ellipse cx="126" cy="276" rx="18" ry="9" fill="${second}" opacity=".72"/><ellipse cx="194" cy="276" rx="18" ry="9" fill="${second}" opacity=".72"/>`;
  const nose=p.species==='cat'?`<path d="M154 150q6-5 12 0-6 8-12 0Z" fill="${accent}"/>`:`<path d="M155 150q5 5 10 0" fill="${accent}"/>`;
  return `<svg class="pet-svg pet-stage-${s} ${sad?'is-sad':''} ${lick?'is-licking':''}" viewBox="0 0 320 320" role="img" aria-label="${esc(p.name)}，${esc(breed.name)}，${PET_STAGE_NAMES[s]}">${defs}<ellipse cx="160" cy="284" rx="93" ry="18" fill="#6f4f3d" opacity=".11"/><g transform="translate(160 170) scale(${scale}) translate(-160 -170)" filter="url(#${id}soft)" stroke="#805e52" stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round">${tail}${body}<path d="M112 241q-13 45 13 47M208 241q13 45-13 47" fill="none"/><circle cx="160" cy="126" r="${headR}" fill="url(#${id}fur)"/>${ears}${markings}${muzzle}<g fill="none">${eyes}</g>${nose}${mouth}<circle cx="111" cy="157" r="9" fill="${accent}" opacity=".22" stroke="none"/><circle cx="209" cy="157" r="9" fill="${accent}" opacity=".22" stroke="none"/>${livingDetails}${bodyWear}${neck}${head}</g><g class="pet-custom-strokes">${petStrokePaths(p)}</g></svg>`;
}

function openPetGame(){closeModal();go('pet');}
function petChooseSpecies(species){
  const x=petRoot();if(x.pets.length>=2){toast('小家里已经住着两只宠物啦');return;}
  const list=PET_BREEDS[species==='dog'?'dog':'cat'];openModal(`<div class="pet-breed-modal"><small>CHOOSE A BREED</small><h3>想遇见哪一种${species==='dog'?'小狗':'猫猫'}？</h3><p>品种决定耳朵、脸型、花纹和体态，毛色以后仍然可以自由调整。</p><div class="pet-breed-grid">${list.map(b=>{const q=petDefault(species,b.name,b.id);return `<button onclick="petChooseBreed('${species}','${b.id}')">${petSvg(q,{awake:true})}<b>${b.name}</b><small>${b.note}</small></button>`;}).join('')}</div><button class="btn g" onclick="closeModal()">再想想</button></div>`);
}
function petChooseBreed(species,breed){
  const b=petBreed(species,breed),p=petDefault(species,'新朋友',breed);openModal(`<div class="pet-adopt-modal"><small>NEW FAMILY · ${esc(b.name)}</small><h3>给它取个名字</h3><div class="pet-adopt-peek">${petSvg(p,{awake:true})}</div><div class="field"><input id="pet_adopt_name" maxlength="12" placeholder="2—12个字，例如：奶糖"></div><button class="btn p" onclick="petConfirmAdoption('${species}','${breed}')">把它带回家</button><button class="btn g" onclick="petChooseSpecies('${species}')">换一个品种</button></div>`);
  setTimeout(()=>{const e=$('#pet_adopt_name');if(e)e.focus();},80);
}
function petConfirmAdoption(species,breed){
  const e=$('#pet_adopt_name'),name=String(e&&e.value||'').trim();if(name.length<1){toast('先给它取一个名字');return;}
  const x=petRoot(),p=petDefault(species,name,breed);if(x.pets.length){const first=x.pets[0];p.roomX=first.roomX<52?74:27;p.roomY=petClamp(first.roomY+3,54,80);}x.pets.push(p);x.activeId=p.id;closeModal();save();render();
}
function petReveal(){const p=petActive();if(!p)return;p.revealed=true;p.speech='我出来啦！以后请多多照顾我。';p.reaction='first';p.affection=58;petLog('你打开小箱子，'+p.name+'跳进了新家。',36);render();setTimeout(()=>{if(p){p.reaction='';save();}},1200);}
function petSwitch(id){const x=petRoot();if(!x.pets.some(p=>p.id===id))return;x.activeId=id;save();render();}
function petAddSecond(){const x=petRoot();if(x.pets.length>=2){toast('已经养了两只宠物');return;}openModal(`<h3>再领养一位小伙伴</h3><div class="hint">第二只宠物拥有独立年龄、饱腹、清洁和心情，也可以和第一只结伴。</div><div class="pet-species-grid"><button onclick="petChooseSpecies('cat')">${petSvg(petDefault('cat','小猫','orange'),{awake:true})}<b>领养猫猫</b></button><button onclick="petChooseSpecies('dog')">${petSvg(petDefault('dog','小狗','shiba'),{awake:true})}<b>领养狗狗</b></button></div><button class="btn g" onclick="closeModal()">取消</button>`);}
function petPair(){const x=petRoot();if(x.pets.length<2){toast('需要先养两只宠物');return;}const a=x.pets[0],b=x.pets[1];if(petAgeInfo(a).stage<3||petAgeInfo(b).stage<3){toast('等两只宠物都进入成长期再结伴');return;}a.mateId=b.id;b.mateId=a.id;petLog(a.name+'和'+b.name+'成为了彼此最亲密的伙伴。',88);toast('它们已经结伴啦');render();}
function petSetSpeech(p,text){p.speech=String(text||'').slice(0,70);p.speechAt=Date.now();}
function petAnimalVoice(species){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;_petAudioCtx=_petAudioCtx||new C();const c=_petAudioCtx;c.resume&&c.resume();const t=c.currentTime,g=c.createGain();g.connect(c.destination);g.gain.setValueAtTime(.0001,t);if(species==='cat'){const o=c.createOscillator(),o2=c.createOscillator();o.type='triangle';o2.type='sine';o.frequency.setValueAtTime(720,t);o.frequency.exponentialRampToValueAtTime(430,t+.16);o.frequency.exponentialRampToValueAtTime(610,t+.34);o2.frequency.setValueAtTime(1090,t);o2.frequency.exponentialRampToValueAtTime(690,t+.32);o.connect(g);o2.connect(g);g.gain.exponentialRampToValueAtTime(.055,t+.035);g.gain.exponentialRampToValueAtTime(.0001,t+.44);o.start(t);o2.start(t);o.stop(t+.46);o2.stop(t+.46);}else{const len=Math.floor(c.sampleRate*.34),buf=c.createBuffer(1,len,c.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/len,1.7);const src=c.createBufferSource(),filter=c.createBiquadFilter(),o=c.createOscillator();src.buffer=buf;filter.type='bandpass';filter.frequency.value=520;filter.Q.value=.8;o.type='sawtooth';o.frequency.setValueAtTime(155,t);o.frequency.exponentialRampToValueAtTime(92,t+.23);src.connect(filter);filter.connect(g);o.connect(g);g.gain.exponentialRampToValueAtTime(.07,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.3);src.start(t);o.start(t);o.stop(t+.32);}setTimeout(()=>{if(_petAudioCtx&&_petAudioCtx.state==='running'&&typeof _petAudioCtx.suspend==='function')_petAudioCtx.suspend().catch(()=>{});},1200);}catch(_){}}
function petReaction(p,kind,bubble,duration){p.reaction=kind;p.reactionBubble=bubble||'';p.awakeUntil=Date.now()+5*60000;p.forcedSleepUntil=0;save();render();setTimeout(()=>{if(p.reaction===kind){p.reaction='';p.reactionBubble='';save();if(typeof cur==='function'&&cur().p==='pet')render();}},duration||950);}
function petTap(e){if(e&&e.stopPropagation)e.stopPropagation();if(Date.now()<_petIgnoreTapUntil)return;const p=petActive();if(!p||!p.revealed)return;if(petIsSleeping(p)){p.sleepPose=(p.sleepPose+1)%3;petReaction(p,'stretch','♡',1100);return;}const mood=petMoodValue(p),pool=mood<35?['voice','nuzzle','hop']:mood>78?['spin','jump','lick','voice','hop']:['voice','hop','nuzzle','lick'],kind=pool[Math.floor(Math.random()*pool.length)];if(kind==='voice')petAnimalVoice(p.species);const bubble=kind==='voice'?(p.species==='cat'?'喵～':'汪！'):kind==='lick'?'♥':kind==='spin'?'♪':kind==='nuzzle'?'♡':'✦';p.joy=petClamp(p.joy+(mood<35?2:4),0,100);p.affection=petClamp(p.affection+1,0,100);petReaction(p,kind,bubble,kind==='lick'?1450:kind==='spin'?1200:900);}
function petSleepOne(p){if(!p)return;const x=petRoot(),index=Math.max(0,x.pets.findIndex(q=>q.id===p.id));p.roomX=x.pets.length>1?(index?30:18):23;p.roomY=x.pets.length>1?(index?46:42):43;p.sleepPose=(p.sleepPose+1+Math.floor(Math.random()*2))%3;p.forcedSleepUntil=Date.now()+45*60000;p.reaction='';p.reactionBubble='';save();render();}
function petGoSleep(e){if(e&&e.stopPropagation)e.stopPropagation();petSleepOne(petActive());}
function petBowl(e){if(e&&e.stopPropagation)e.stopPropagation();const p=petActive();if(!p)return;p.roomX=77;p.roomY=53;p.awakeUntil=Date.now()+5*60000;p.forcedSleepUntil=0;save();render();setTimeout(petFeed,40);}
function petToy(e){if(e&&e.stopPropagation)e.stopPropagation();const p=petActive();if(!p)return;openModal(`<div class="pet-toybox"><small>TOY BASKET</small><h3>选一个球陪${esc(p.name)}玩</h3><p>选好后点房间里的位置把球扔出去，它会跑过去捡回来。</p><div><button onclick="petChooseBall('yarn')"><i class="yarn">⌁</i><b>软毛线球</b><small>猫猫最爱扑</small></button><button onclick="petChooseBall('tennis')"><i class="tennis"></i><b>薄荷网球</b><small>弹起来很轻快</small></button><button onclick="petChooseBall('star')"><i class="star">★</i><b>星星软球</b><small>不会磕到小嘴</small></button></div><button class="btn g" onclick="closeModal()">先不玩</button></div>`);}
function petClearToyTimers(){_petToyTimers.forEach(clearTimeout);_petToyTimers=[];}
function petChooseBall(id){if(!['yarn','tennis','star'].includes(id))return;petClearToyTimers();_petThrowBall=id;_petBallState=null;closeModal();render();toast('点一下地毯，把球扔出去');}
function petThrowAt(e){if(!_petThrowBall)return;const room=document.querySelector('.pet-world'),p=petActive(),pets=petRoot().pets;if(!room||!p)return;if(e&&e.stopPropagation)e.stopPropagation();const r=room.getBoundingClientRect(),x=petClamp((e.clientX-r.left)/r.width*100,24,80),y=petClamp((e.clientY-r.top)/r.height*100,47,76),ball=_petThrowBall;_petThrowBall='';petClearToyTimers();pets.forEach(q=>{q.awakeUntil=Date.now()+5*60000;q.forcedSleepUntil=0;q.reactionBubble='';});_petBallState={id:ball,phase:'flying',x,y,fromX:18,fromY:82};render();_petToyTimers.push(setTimeout(()=>{pets.forEach((q,i)=>{const tx=petClamp(x+(pets.length>1?(i?8:-8):0),16,84),el=document.querySelector(`.pet-character[data-pet-id="${q.id}"]`);if(el){el.classList.add('react-fetch');el.style.setProperty('--pet-x',tx+'%');el.style.setProperty('--pet-y',y+'%');}q.roomX=tx;q.roomY=y;q.reaction='fetch';});save();},430));_petToyTimers.push(setTimeout(()=>{_petBallState={id:ball,phase:'caught',x,y};pets.forEach((q,i)=>{q.reaction=i?'together':'fetch';q.reactionBubble=i?'一起追到啦！':'捡到啦！';});render();requestAnimationFrame(()=>{const ballEl=document.querySelector('.pet-thrown-ball.caught');pets.forEach((q,i)=>{const tx=pets.length>1?(i?59:43):50,el=document.querySelector(`.pet-character[data-pet-id="${q.id}"]`);q.roomX=tx;q.roomY=73;if(el){el.style.setProperty('--pet-x',tx+'%');el.style.setProperty('--pet-y','73%');}});if(ballEl){ballEl.style.setProperty('--ball-x','50%');ballEl.style.setProperty('--ball-y','69%');}});save();},1250));_petToyTimers.push(setTimeout(()=>{_petBallState=null;pets.forEach((q,i)=>{q.reaction=i?'together':'jump';q.reactionBubble=i?'下次还要一起追！':'还要再来吗？';q.joy=petClamp(q.joy+22,0,100);q.energy=petClamp(q.energy-10,0,100);q.affection=petClamp(q.affection+4,0,100);});petLog(petTogether(pets.length>1?'给两只宠物扔球，它们一起追着捡了回来。':'给'+p.name+'扔球，它开心地捡了回来。'),7);save();render();},2300));_petToyTimers.push(setTimeout(()=>{pets.forEach(q=>{q.reaction='';q.reactionBubble='';});save();render();},3500));}
function petPlayTogether(){const x=petRoot();if(x.pets.length<2){toast('再领养一只宠物，就能让它们一起互动');return;}const spots=[{x:42,y:70},{x:60,y:70}];x.pets.forEach((p,i)=>{p.roomX=spots[i].x;p.roomY=spots[i].y;p.awakeUntil=Date.now()+5*60000;p.forcedSleepUntil=0;p.reaction='together';p.reactionBubble=i?'你追我呀！':'一起玩吧！';p.joy=petClamp(p.joy+16,0,100);p.energy=petClamp(p.energy-7,0,100);p.affection=petClamp(p.affection+3,0,100);});petLog(x.pets.map(p=>p.name).join('和')+'在房间里一起追逐玩耍。',8);save();render();setTimeout(()=>{x.pets.forEach(p=>{if(p.reaction==='together'){p.reaction='';p.reactionBubble='';}});save();if(typeof cur==='function'&&cur().p==='pet')render();},1800);}
function petDropTarget(px,py){const hit=(cx,cy,rx,ry)=>Math.pow((px-cx)/rx,2)+Math.pow((py-cy)/ry,2)<=1;if(hit(20,49,10,9))return'bed';if(hit(80,49,9,8))return'bowl';if(hit(19,80,9,7))return'toy';return'';}
function petDragMount(){const room=document.querySelector('.pet-world');if(!room)return;document.querySelectorAll('.pet-character[data-pet-id]').forEach(el=>{if(el._petDragBound)return;el._petDragBound=true;let active=false,moved=false,sx=0,sy=0,startX=0,startY=0,p=null;const place=(x,y)=>{el.style.setProperty('--pet-x',x+'%');el.style.setProperty('--pet-y',y+'%');};el.addEventListener('pointerdown',ev=>{if(ev.button!=null&&ev.button!==0)return;const x=petRoot();p=x.pets.find(q=>q.id===el.dataset.petId);if(!p)return;x.activeId=p.id;active=true;moved=false;sx=ev.clientX;sy=ev.clientY;const cs=getComputedStyle(el);startX=parseFloat(cs.getPropertyValue('--pet-x'))||p.roomX;startY=parseFloat(cs.getPropertyValue('--pet-y'))||p.roomY;el.classList.add('is-dragging');try{el.setPointerCapture(ev.pointerId);}catch(_){}ev.preventDefault();});el.addEventListener('pointermove',ev=>{if(!active||!p)return;const r=room.getBoundingClientRect(),dx=(ev.clientX-sx)/r.width*100,dy=(ev.clientY-sy)/r.height*100;if(Math.abs(ev.clientX-sx)+Math.abs(ev.clientY-sy)>7)moved=true;const minX=p.species==='cat'?15:14,maxX=p.species==='cat'?84:86;p.roomX=petClamp(startX+dx,minX,maxX);p.roomY=petClamp(startY+dy,22,86);place(p.roomX,p.roomY);ev.preventDefault();});const done=ev=>{if(!active||!p)return;active=false;el.classList.remove('is-dragging');const x=petRoot();x.activeId=p.id;if(moved){_petIgnoreTapUntil=Date.now()+450;p.awakeUntil=Date.now()+5*60000;p.forcedSleepUntil=0;save();const target=petDropTarget(p.roomX,p.roomY);if(target==='bed')setTimeout(()=>petSleepOne(p),20);else if(target==='bowl')setTimeout(()=>{render();petBowl();},20);else if(target==='toy')setTimeout(()=>{render();petToy();},20);else setTimeout(render,20);}else{save();setTimeout(render,20);}try{el.releasePointerCapture(ev.pointerId);}catch(_){}if(ev)ev.preventDefault();};el.addEventListener('pointerup',done);el.addEventListener('pointercancel',done);});}
function petFeed(){const x=petRoot(),p=petActive();if(!p)return;openModal(`<h3>今天吃什么？</h3><div class="hint">当前是${petMealName(petMealSlot())}时间。早、中、晚按时吃饭会提高成长照顾分。</div><div class="pet-food-list">${PET_FOODS.map(f=>`<button onclick="petFeedItem('${f.id}')"><i>${f.icon}</i><span><b>${f.name}</b><small>${f.note} · 饱腹 +${f.fill}</small></span><em>× ${x.inventory[f.id]||0}</em></button>`).join('')}</div><button class="pet-shop-link" onclick="closeModal();petOpenShop('food')">粮食不够？去宠物商城</button><button class="btn g" onclick="closeModal()">取消</button>`);}
function petFeedItem(id){const x=petRoot(),p=petActive(),f=PET_FOODS.find(v=>v.id===id);if(!p||!f)return;if(!(x.inventory[id]>0)){toast('这份食物没有库存了');return;}const slot=petMealSlot(),day=petLocalDay();p.meals[day]=p.meals[day]||{};const firstMeal=slot!=='late'&&!p.meals[day][slot];x.inventory[id]--;p.hunger=petClamp(p.hunger+f.fill,0,100);p.health=petClamp(p.health+4,0,100);p.joy=petClamp(p.joy+(id==='snack'?10:4),0,100);p.affection=petClamp(p.affection+2,0,100);p.plumpness=petClamp(p.plumpness+(firstMeal?4:id==='snack'?1:2),0,100);if(firstMeal){p.meals[day][slot]=Date.now();p.careScore=petClamp(p.careScore+2.4,0,100);}p.careActions++;const speech=id==='fish'?'好鲜！我把小碗舔得干干净净。':id==='snack'?'是星星零食！今天最喜欢你。':'吃饱啦，肚子暖暖的。';petSetSpeech(p,speech);petLog(petTogether('给'+p.name+'喂了'+f.name+'。'),6);closeModal();petReaction(p,'eat',speech,2400);}
function petBath(){const p=petActive();if(!p)return;if(petIsSleeping(p)){toast('它正睡得香，轻轻拖出小窝再洗澡吧');return;}p.clean=100;p.joy=petClamp(p.joy+5,0,100);p.health=petClamp(p.health+3,0,100);p.careScore=petClamp(p.careScore+1.6,0,100);p.careActions++;petSetSpeech(p,'香香的！');petLog(petTogether('给'+p.name+'洗了个香香澡。'),8);petReaction(p,'bath','洗得香喷喷啦！',2500);}
function petPlay(){const p=petActive();if(!p)return;if(petIsSleeping(p)){toast('它正趴在小窝里睡觉');return;}if(p.energy<14){petSetSpeech(p,'有点累啦…');render();return;}p.joy=petClamp(p.joy+26,0,100);p.energy=petClamp(p.energy-12,0,100);p.hunger=petClamp(p.hunger-5,0,100);p.affection=petClamp(p.affection+4,0,100);p.careScore=petClamp(p.careScore+1.2,0,100);p.careActions++;petSetSpeech(p,p.species==='dog'?'再来一次！':'抓到毛球啦！');p.reaction='play';p.reactionBubble='♪';petLog(petTogether('陪'+p.name+'玩了一会儿。'),7);render();setTimeout(()=>{p.reaction='';p.reactionBubble='';save();if(typeof cur==='function'&&cur().p==='pet')render();},900);}
function petCleanPoop(){const p=petActive();if(!p)return;if(!p.poop){toast('小窝现在干干净净');return;}const n=p.poop;p.poop=0;p.clean=petClamp(p.clean+22,0,100);p.joy=petClamp(p.joy+7,0,100);p.careScore=petClamp(p.careScore+2,0,100);petSetSpeech(p,'小窝清爽了，我可以放心打滚啦。');petLog('你清理了'+p.name+'的小窝（'+n+'处）。',5*n);petReaction(p,'clean','亮晶晶，真舒服！',2100);}
function petRoleCare(){const p=petActive(),c=petRole();if(!p){return;}if(!c){petInviteRole();return;}const acts=['feed','play','clean'],act=acts[Math.floor(Math.random()*acts.length)],n=c.remark||c.name;let reaction='together',bubble='有人陪我真开心！';if(act==='feed'){const id=PET_FOODS.find(f=>petRoot().inventory[f.id]>0);if(id){petRoot().inventory[id.id]--;p.hunger=petClamp(p.hunger+id.fill,0,100);p.plumpness=petClamp(p.plumpness+2,0,100);bubble=n+'添的饭也好香！';petSetSpeech(p,bubble);petLog(n+'过来给'+p.name+'添了'+id.name+'。',4);reaction='eat';}else{bubble=n+'摸摸我，说晚点带好吃的来。';petSetSpeech(p,bubble);}}else if(act==='play'){p.joy=petClamp(p.joy+20,0,100);p.affection=petClamp(p.affection+3,0,100);bubble=n+'陪我玩了好久！';petSetSpeech(p,bubble);petLog(n+'陪'+p.name+'玩了玩具。',5);}else{p.clean=petClamp(p.clean+15,0,100);p.poop=0;bubble=n+'把我的小窝收拾好啦。';petSetSpeech(p,bubble);petLog(n+'帮忙整理了'+p.name+'的小窝。',5);reaction='clean';}p.careScore=petClamp(p.careScore+1.5,0,100);petReaction(p,reaction,bubble,1600);}

function petInviteRole(){const cs=(S.contacts||[]).filter(c=>!c.deleted);if(!cs.length){toast('先创建一个角色');return;}const current=petRole();openModal(`<h3>邀请共同照顾</h3><div class="hint">受邀角色会知道宠物的名字、状态和你们一起照顾过的事。可以随时更换。</div>${cs.map(c=>`<div class="section"><div class="it" onclick="petSetRole('${c.id}')"><span>${esc(c.remark||c.name)}</span><span class="v">${current&&current.id===c.id?'共同照顾中':'邀请'}</span></div></div>`).join('')}${current?'<button class="btn d" onclick="petSetRole(\'\')">取消共同照顾</button>':''}<button class="btn g" onclick="closeModal()">关闭</button>`);}
function petSetRole(id){const x=petRoot();x.sharedRoleId=id||'';const c=id&&getC(id);if(c){c.gamesPlayed=c.gamesPlayed||[];if(!c.gamesPlayed.includes('电子宠物'))c.gamesPlayed.push('电子宠物');petLog('你邀请'+(c.remark||c.name)+'成为宠物的共同照顾人。',0);}save();closeModal();render();toast(c?'邀请成功':'已取消共同照顾');}
function petRolePrompt(c){const x=S.me&&S.me.ePet;if(!x||!c||!Array.isArray(x.pets)||!x.pets.length)return'';const rows=x.pets.map(p=>{petNormalize(p);const a=petAgeInfo(p);return p.name+'（'+petBreedName(p)+'，'+a.age+'，'+PET_STAGE_NAMES[a.stage]+'，'+petMoodLabel(p)+'）';}),names=x.pets.map(p=>p.name).join('、'),shared=x.sharedRoleId===c.id;if(!shared)return '\n\n# 用户的电子宠物\n'+S.me.name+'在游戏大厅养了电子宠物：'+rows.join('；')+'。你知道它们的名字是'+names+'，可以在话题相关时自然提及，但你不是共同照顾人，不要声称自己刚刚喂养或清理过。';const needs=[];x.pets.forEach(p=>{if(p.hunger<35)needs.push(p.name+'饿了');if(p.clean<35)needs.push(p.name+'需要清洁');if(petMoodValue(p)<35)needs.push(p.name+'心情低落');if(p.energy<20)needs.push(p.name+'有些疲惫');});const recent=(x.logs||[]).slice(0,5).map(l=>'• '+l.text).join('\n');return '\n\n# 你们共同照顾的电子宠物\n你和'+S.me.name+'正在游戏大厅共同养育：'+rows.join('；')+'。这是持续存在的游戏状态，你明确知道它们的名字。\n'+(recent?'最近照顾记录：\n'+recent+'\n':'')+(needs.length?'当前需要留意：'+needs.join('、')+'。请用你自己的口吻自然提醒用户照顾，不要像系统通知。\n':'目前没有急需提醒的异常状态，不要为了提宠物而每轮重复。\n')+'记录中以你的名字发生的照顾行为就是你刚刚做过的事，不要否认或表现得不知情。你可以自然关心吃饭、洗澡、心情和成长，但不要假装现实世界里真的养了它。';}

function petOpenShop(tab){tab=tab||'food';const x=petRoot();openModal(`<div class="pet-shop"><header><small>PET MARKET</small><h3>宠物商城</h3><b>叶子币 ${x.coins}</b></header><nav><button class="${tab==='food'?'on':''}" onclick="petOpenShop('food')">食物</button><button class="${tab==='wear'?'on':''}" onclick="petOpenShop('wear')">装扮</button></nav>${tab==='food'?`<div class="pet-shop-grid">${PET_FOODS.map(f=>`<button onclick="petBuyFood('${f.id}')"><i>${f.icon}</i><b>${f.name}</b><small>${f.note}</small><em>${f.price} 币</em></button>`).join('')}</div>`:`<div class="pet-shop-grid wear">${PET_WEAR.map(w=>`<button onclick="petBuyWear('${w.id}')"><i>${w.type==='head'?'⌁':w.type==='neck'?'○':'♢'}</i><b>${w.name}</b><small>${x.ownedWear.includes(w.id)?'已经拥有':'永久装扮'}</small><em>${x.ownedWear.includes(w.id)?'已拥有':w.price+' 币'}</em></button>`).join('')}</div>`}<p>照顾、清理和陪玩都能获得叶子币，不需要充值。</p><button class="btn g" onclick="closeModal()">关闭商城</button></div>`);}
function petBuyFood(id){const x=petRoot(),f=PET_FOODS.find(v=>v.id===id);if(!f)return;if(x.coins<f.price){toast('叶子币不够，先陪宠物玩一会儿');return;}x.coins-=f.price;x.inventory[id]=(x.inventory[id]||0)+1;save();petOpenShop('food');toast('买到了 '+f.name);}
function petBuyWear(id){const x=petRoot(),w=PET_WEAR.find(v=>v.id===id);if(!w)return;if(x.ownedWear.includes(id)){toast('这件已经在衣柜里');return;}if(x.coins<w.price){toast('叶子币不够');return;}x.coins-=w.price;x.ownedWear.push(id);save();petOpenShop('wear');toast('新装扮已放进衣柜');}

function petOpenStyle(){const p=petActive(),x=petRoot();if(!p)return;const breeds=PET_BREEDS[p.species].map(b=>`<button class="pet-breed-choice ${p.breed===b.id?'on':''}" onclick="petChangeBreed('${b.id}')"><i style="background:${b.fur}"></i><span>${b.name}</span><small>${b.note}</small></button>`).join(''),groups=['head','neck','body'].map(type=>{const none=`<button class="${!p.accessories[type]?'on':''}" onclick="petWear('${type}','')"><span>不佩戴</span><small>保持原样</small></button>`,items=PET_WEAR.filter(w=>w.type===type).map(w=>{const owned=x.ownedWear.includes(w.id);return `<button class="${p.accessories[type]===w.id?'on':''} ${owned?'':'locked'}" onclick="${owned?`petWear('${type}','${w.id}')`:`petBuyWearFromStyle('${w.id}')`}"><span>${w.name}</span><small>${owned?'已经拥有':w.price+' 叶子币 · 点击购买'}</small></button>`;}).join('');return `<section><b>${type==='head'?'头饰':type==='neck'?'项圈':'衣服'} <em>未拥有的也可直接购买</em></b><div>${none+items}</div></section>`;}).join('');openModal(`<div class="pet-style"><header><small>DRESS ROOM</small><h3>${esc(p.name)}的衣帽间</h3></header><div class="pet-style-preview"><small>实时全身预览</small>${petSvg(p,{awake:true})}</div><section class="pet-breed-section"><b>选择${p.species==='cat'?'猫猫':'狗狗'}品种</b><div>${breeds}</div></section><div class="pet-color-row"><label>毛色 <input type="color" value="${p.colors.fur}" oninput="petSetColor('fur',this.value)"></label><label>装扮色 <input type="color" value="${p.colors.cloth}" oninput="petSetColor('cloth',this.value)"></label></div>${groups}<div class="pet-style-actions"><button onclick="petOpenPainter()">画笔自定义</button><button onclick="petSaveLook()">保存为新形象</button></div>${p.looks.length?`<section><b>保存的形象</b><div>${p.looks.map((l,i)=>`<button onclick="petApplyLook(${i})"><span>造型 ${i+1}</span></button>`).join('')}</div></section>`:''}<button class="btn g" onclick="closeModal();render()">完成</button></div>`);}
function petChangeBreed(id){const p=petActive(),b=p&&PET_BREEDS[p.species].find(v=>v.id===id);if(!p||!b)return;p.breed=b.id;p.colors.fur=b.fur;save();petOpenStyle();}
function petBuyWearFromStyle(id){const x=petRoot(),p=petActive(),w=PET_WEAR.find(v=>v.id===id);if(!p||!w)return;if(x.ownedWear.includes(id)){petWear(w.type,id);return;}if(x.coins<w.price){toast('叶子币不够，陪宠物互动可以获得');return;}x.coins-=w.price;x.ownedWear.push(id);p.accessories[w.type]=id;save();petOpenStyle();toast('已经买下并穿好了');}
function petWear(type,id){const p=petActive();if(!p||!['head','neck','body'].includes(type))return;p.accessories[type]=id||'';save();petOpenStyle();}
function petSetColor(key,value){const p=petActive();if(!p||!/^#[0-9a-f]{6}$/i.test(value))return;p.colors[key]=value;save();const v=document.querySelector('.pet-style-preview');if(v)v.innerHTML='<small>实时全身预览</small>'+petSvg(p,{awake:true});}
function petSaveLook(){const p=petActive();if(!p)return;p.looks.push({accessories:Object.assign({},p.accessories),colors:Object.assign({},p.colors),strokes:JSON.parse(JSON.stringify(p.strokes||[])),time:Date.now()});p.looks=p.looks.slice(-8);save();petOpenStyle();toast('已经保存为一个新形象');}
function petApplyLook(i){const p=petActive(),l=p&&p.looks[i];if(!l)return;p.accessories=Object.assign({head:'',neck:'',body:''},l.accessories||{});p.colors=Object.assign({},p.colors,l.colors||{});p.strokes=JSON.parse(JSON.stringify(l.strokes||[]));save();petOpenStyle();toast('已经换上这套形象');}
function petOpenPainter(){const p=petActive();if(!p)return;_petPaintDraft=JSON.parse(JSON.stringify(p.strokes||[]));openModal(`<div class="pet-painter"><header><small>CUSTOM ATELIER</small><h3>在${esc(p.name)}身上自由画</h3><p>画笔会作为独立图层保存，不会破坏宠物和装扮。</p></header><div class="pet-paint-stage">${petSvg(Object.assign({},p,{strokes:[]}),{awake:true})}<canvas id="petPaintCanvas" width="320" height="320"></canvas></div><div class="pet-paint-tools"><input id="petPaintColor" type="color" value="${p.colors.accent||'#ef8faa'}"><input id="petPaintWidth" type="range" min="2" max="22" value="7"><button onclick="petPaintUndo()">撤回</button><button onclick="petPaintClear()">清空</button></div><div class="btns"><button class="btn g" onclick="petOpenStyle()">取消</button><button class="btn p" onclick="petPaintSave()">保存新形象</button></div></div>`);setTimeout(petPainterMount,30);}
function petPainterDraw(){const cv=$('#petPaintCanvas');if(!cv)return;const ctx=cv.getContext('2d');ctx.clearRect(0,0,320,320);(_petPaintDraft||[]).forEach(s=>{if(!s.points||!s.points.length)return;ctx.beginPath();ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.moveTo(s.points[0][0],s.points[0][1]);s.points.slice(1).forEach(q=>ctx.lineTo(q[0],q[1]));ctx.stroke();});}
function petPainterMount(){const cv=$('#petPaintCanvas');if(!cv)return;petPainterDraw();let cur=null;const point=e=>{const r=cv.getBoundingClientRect();return [petClamp((e.clientX-r.left)/r.width*320,0,320),petClamp((e.clientY-r.top)/r.height*320,0,320)];};cv.onpointerdown=e=>{e.preventDefault();const col=($('#petPaintColor')||{}).value||'#ef8faa',w=+((($('#petPaintWidth')||{}).value)||7);cur={color:col,width:w,points:[point(e)]};try{cv.setPointerCapture(e.pointerId);}catch(_){}};cv.onpointermove=e=>{if(!cur)return;e.preventDefault();const q=point(e),last=cur.points[cur.points.length-1];if(Math.hypot(q[0]-last[0],q[1]-last[1])<2)return;cur.points.push(q);petPainterDraw();const ctx=cv.getContext('2d');ctx.beginPath();ctx.strokeStyle=cur.color;ctx.lineWidth=cur.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.moveTo(cur.points[0][0],cur.points[0][1]);cur.points.slice(1).forEach(v=>ctx.lineTo(v[0],v[1]));ctx.stroke();};const done=()=>{if(!cur)return;if(cur.points.length===1)cur.points.push([cur.points[0][0]+.5,cur.points[0][1]+.5]);_petPaintDraft.push(cur);cur=null;petPainterDraw();};cv.onpointerup=done;cv.onpointercancel=done;}
function petPaintUndo(){if(_petPaintDraft&&_petPaintDraft.length)_petPaintDraft.pop();petPainterDraw();}
function petPaintClear(){_petPaintDraft=[];petPainterDraw();}
function petPaintSave(){const p=petActive();if(!p)return;p.strokes=JSON.parse(JSON.stringify(_petPaintDraft||[]));save();petSaveLook();}

function petStat(label,value,kind){return `<div class="pet-stat ${kind||''}"><span><b>${label}</b><em>${Math.round(value)}</em></span><i><u style="width:${petClamp(value,0,100)}%"></u></i></div>`;}
function petMealStrip(p){const d=p.meals[petLocalDay()]||{};return ['breakfast','lunch','dinner'].map(k=>`<span class="${d[k]?'done':''}"><i>${d[k]?'✓':'·'}</i>${petMealName(k)}</span>`).join('');}
function petStageBook(p){const a=petAgeInfo(p),preview=Object.assign({},p,{reaction:'',reactionBubble:'',strokes:[]});return PET_STAGE_NAMES.map((n,i)=>`<span class="${i<=a.stage?'seen':''} ${i===a.stage?'now':''}">${petSvg(preview,{awake:true,stage:i})}<b>${n}</b><small>${i===0?'刚到家':i===1?'会跑跳':i===2?'身形舒展':i===3?'接近成年':'完整体态'}</small></span>`).join('');}
function petDeleteLog(time){const x=petRoot();if(!confirm('删除这条照顾日记吗？'))return;x.logs=x.logs.filter(l=>+l.time!==+time);save();petOpenCareBook();}
function petClearLogs(){const x=petRoot();if(!x.logs.length)return;if(!confirm('清空全部照顾日记吗？此操作不能撤回。'))return;x.logs=[];save();petOpenCareBook();}
function petOpenCareBook(){const p=petActive(),x=petRoot(),a=p&&petAgeInfo(p),role=petRole();if(!p)return;openModal(`<div class="pet-care-book"><header><small>${esc(petBreedName(p))} · CARE BOOK</small><h3>${esc(p.name)}的成长手册</h3></header><section class="pet-vitals"><div><small>MOOD</small><b>${petMoodLabel(p)}</b></div>${petStat('心情',petMoodValue(p),'mood')}${petStat('饱腹',p.hunger,'food')}${petStat('洁净',p.clean,'clean')}${petStat('活力',p.energy,'energy')}</section><section class="pet-care-card"><header><div><small>TODAY'S CARE</small><b>今天的三餐</b></div><button onclick="petRoleCare()">${role?'让TA照顾':'邀请角色'}</button></header><div class="pet-meals">${petMealStrip(p)}</div></section><section class="pet-grow-card"><header><div><small>GROWING BOOK</small><b>${a.age} · ${PET_STAGE_NAMES[a.stage]}</b></div><em>照顾加速 ${(a.boost*100-100).toFixed(0)}%</em></header><div class="pet-stage-book">${petStageBook(p)}</div><p>现实每 15 天约长一岁；按时喂饭会逐渐长得更圆润，照顾稳定时成长最多加快约 18%。</p></section><section class="pet-family-card"><button onclick="petInviteRole()"><i>♡</i><span><b>共同照顾人</b><small>${role?esc(role.remark||role.name):'还没有邀请角色'}</small></span><em>›</em></button><button onclick="petPair()"><i>∞</i><span><b>配偶 / 结伴</b><small>${p.mateId?'已经找到最亲密的伙伴':x.pets.length<2?'需要养两只宠物':'成长后可以结伴'}</small></span><em>›</em></button></section>${x.logs.length?`<section class="pet-log"><header><div><small>CARE DIARY</small><b>照顾日记</b></div><button onclick="petClearLogs()">清空</button></header>${x.logs.map(l=>`<p><time>${new Date(l.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time><span>${esc(l.text)}</span><button onclick="petDeleteLog(${+l.time})" aria-label="删除这条照顾日记">⌫</button></p>`).join('')}</section>`:''}<button class="btn g" onclick="closeModal()">回到房间</button></div>`);}
function petRenderAdopt(){return `<div class="pet-page pet-onboard"><div class="pet-nav"><button onclick="openGames()">‹</button><span><b>电子宠物</b><small>POCKET FAMILY</small></span><button onclick="petOpenShop('food')">商城</button></div><div class="pet-onboard-scroll"><section class="pet-onboard-hero"><small>A TINY NEW LIFE</small><h1>领养你的<br>第一位小家人</h1><p>从小箱子里相遇，陪它吃饭、长大、换装，也可以邀请角色共同照顾。</p><div class="pet-box-mini"><i></i><b>?</b></div></section><h3>想先遇见谁？</h3><div class="pet-species-grid main"><button onclick="petChooseSpecies('cat')">${petSvg(petDefault('cat','小猫','orange'),{awake:true})}<b>软乎乎的猫猫</b><small>橘猫、布偶、银渐层、暹罗</small></button><button onclick="petChooseSpecies('dog')">${petSvg(petDefault('dog','小狗','shiba'),{awake:true})}<b>摇尾巴的狗狗</b><small>柴犬、柯基、比熊、金毛</small></button></div><div class="pet-feature-notes"><span>八种品种</span><span>五段成长</span><span>自由换装</span><span>画笔改造</span></div></div></div>`;}
function petRenderBox(p){return `<div class="pet-page pet-box-page"><div class="pet-nav"><button onclick="openGames()">‹</button><span><b>神秘小箱子</b><small>轻轻点开它</small></span><button onclick="petOpenShop('food')">商城</button></div><div class="pet-box-room"><div class="pet-box-copy"><small>WELCOME HOME</small><h2>${esc(p.name)}已经到家</h2><p>箱子里偶尔传来细小的动静。准备好以后，亲手打开它。</p></div><button class="pet-crate" onclick="petReveal()" aria-label="打开小箱子"><i class="lid"></i><i class="crate-face"><u></u><u></u></i><span>轻触打开</span></button><div class="pet-box-hint">第一次相遇会记录为它的领养日</div></div></div>`;}
function petRoomPosition(q,index,total){if(!petIsSleeping(q)||!((q.forcedSleepUntil||0)>Date.now()))return{x:q.roomX,y:q.roomY};if(total>1)return{x:index?30:18,y:index?46:42};return{x:23,y:43};}
function petRenderRoomPet(q,index,total,activeId){const active=q.id===activeId,sleeping=petIsSleeping(q),pos=petRoomPosition(q,index,total),recent=q.speechAt&&Date.now()-q.speechAt<9000?q.speech:'',bubble=q.reactionBubble||recent,effects={bath:'◌ · ◦ · ○',eat:'· ᵕ ·',clean:'✦ · ✧',together:'♡ · ♡'},effect=effects[q.reaction]||'';return `${q.hunger<35?`<div class="pet-need-bubble live" style="--pet-x:${pos.x}%;--pet-y:${pos.y}%"><i>◒</i></div>`:''}${sleeping?`<div class="pet-zzz" style="--pet-x:${pos.x}%;--pet-y:${pos.y}%"><i>z</i><i>Z</i><i>z</i></div>`:''}${bubble?`<div class="pet-live-bubble" style="--pet-x:${pos.x}%;--pet-y:${pos.y}%">${esc(bubble)}</div>`:''}${effect?`<div class="pet-action-effect ${q.reaction}" style="--pet-x:${pos.x}%;--pet-y:${pos.y}%">${effect}</div>`:''}<div class="pet-character ${active?'drag-enabled active':'roommate'} ${sleeping?'is-sleeping':''} ${q.reaction?'react-'+q.reaction:''}" data-pet-id="${esc(q.id)}" style="--pet-x:${pos.x}%;--pet-y:${pos.y}%" onclick="${active?'petTap(event)':`petSwitch('${q.id}')`}">${petSvg(q,{sleeping})}<span class="pet-room-name">${esc(q.name)}${active?' · 当前':''}</span></div>`;}
function petRenderHome(p){const x=petRoot(),a=petAgeInfo(p),role=petRole(),flies=p.poop>=3||p.clean<24,allSleeping=x.pets.every(petIsSleeping),ordered=x.pets.map((q,i)=>({q,i})).sort((a,b)=>(a.q.id===p.id?1:0)-(b.q.id===p.id?1:0)),pets=ordered.map(v=>petRenderRoomPet(v.q,v.i,x.pets.length,p.id)).join(''),ball=_petBallState?`<div class="pet-thrown-ball ${_petBallState.phase} ${_petBallState.id}" style="--ball-x:${_petBallState.x}%;--ball-y:${_petBallState.y}%;--ball-from-x:${_petBallState.fromX||_petBallState.x}%;--ball-from-y:${_petBallState.fromY||_petBallState.y}%"><i>${_petBallState.id==='star'?'★':_petBallState.id==='yarn'?'⌁':''}</i></div>`:'',throwLayer=_petThrowBall?`<button class="pet-throw-layer" onclick="petThrowAt(event)" aria-label="点击地毯把球扔出去"><span>点一下地毯，把${_petThrowBall==='yarn'?'毛线球':_petThrowBall==='tennis'?'网球':'星星球'}扔出去</span></button>`:'';return `<div class="pet-page pet-home-world ${allSleeping?'is-sleeping':''}"><section class="pet-world"><div class="pet-room-bg"></div><header class="pet-world-top"><button onclick="openGames()">‹</button><div><b>${esc(p.name)}</b><small>${esc(petBreedName(p))} · ${a.age} · ${PET_STAGE_NAMES[a.stage]}</small></div><button onclick="petOpenShop('food')">商城 ${x.coins}</button></header><div class="pet-world-switch">${x.pets.map(q=>`<button class="${q.id===p.id?'on':''}" onclick="petSwitch('${q.id}')">${q.species==='dog'?'◡':'⌁'} ${esc(q.name)}</button>`).join('')}${x.pets.length<2?'<button onclick="petAddSecond()">＋</button>':''}</div><div class="pet-mini-vitals"><span title="心情"><i>♡</i><u><b style="width:${petMoodValue(p)}%"></b></u></span><span title="饱腹"><i>◒</i><u><b style="width:${p.hunger}%"></b></u></span><span title="洁净"><i>♨</i><u><b style="width:${p.clean}%"></b></u></span></div>${role?`<button class="pet-role-chip" onclick="petInviteRole()"><span>${esc((role.remark||role.name).slice(0,2))}</span><b>${esc(role.remark||role.name)}</b></button>`:''}${x.pets.length>1?'<button class="pet-together-play" onclick="petPlayTogether()">♡ 一起玩</button>':''}<button class="pet-scene-hotspot bed" onclick="petGoSleep(event)" aria-label="去小窝睡觉"></button><button class="pet-scene-hotspot bowl" onclick="petBowl(event)" aria-label="点击食盆喂饭或购买食物"></button><button class="pet-scene-hotspot toy" onclick="petToy(event)" aria-label="打开玩具篮选择小球"></button>${pets}${ball}${throwLayer}${p.poop?`<button class="pet-poops immersive" onclick="petCleanPoop()" aria-label="清理粑粑">${Array.from({length:Math.min(4,p.poop)},(_,i)=>`<i style="--i:${i}">●</i>`).join('')}</button>`:''}${flies?'<div class="pet-flies immersive"><i>⌁</i><i>⌁</i><i>⌁</i></div>':''}<footer class="pet-world-dock"><button onclick="petBath()"><i>♨</i><span>洗澡</span></button><button onclick="petCleanPoop()"><i>◇</i><span>清理</span></button><button onclick="petOpenStyle()"><i>✦</i><span>装扮</span></button><button onclick="petOpenCareBook()"><i>☰</i><span>手册</span></button></footer></section></div>`;}
function renderPetGame(){const x=petRoot(),p=petActive();setTimeout(petAfterRender,0);if(!p)return petRenderAdopt();if(!p.revealed)return petRenderBox(p);return petRenderHome(p);}
function petAfterRender(){const p=petActive();if(!p)return;petDragMount();if(p.speechAt&&Date.now()-p.speechAt>25000){p.speech='';p.speechAt=0;save();}}
if(typeof window!=='undefined')window.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&S&&S.me&&S.me.ePet){petRoot();if(typeof cur==='function'&&cur().p==='pet')render();}});
