/* Local ride simulation. GPS stays on-device; no dispatch, map service or real fare request. */
(function(root){'use strict';
const account=()=>String(actId()||'main'),money=n=>'¥'+Number(n).toFixed(2),safe=v=>esc(v).replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const types=[{id:'express',name:'滴滴快车',base:10,km:2.2,eta:3,note:'经济实用 · 4座'},{id:'taxi',name:'出租车',base:14,km:2.5,eta:2,note:'巡游出租 · 4座'},{id:'special',name:'专车',base:23,km:3.8,eta:5,note:'舒适专车 · 4座'},{id:'luxury',name:'滴滴豪华车',base:45,km:6.8,eta:6,note:'豪华车型 · 4座'}];
const places=[['上海虹桥站',31.194,121.327],['上海迪士尼',31.144,121.667],['东方明珠',31.240,121.499],['上海浦东机场',31.145,121.805],['北京南站',39.866,116.378],['北京首都机场',40.079,116.603],['苏州站',31.325,120.608],['杭州东站',30.291,120.213],['广州南站',22.989,113.269]];
let active=false,view='cover',detailId='',origin=null,locating=false,locationToken=0,limit=12,signature='',running=null;
function state(){const t=tvInit();t.taxiForms=t.taxiForms||{};return t.taxiForms[account()]||(t.taxiForms[account()]={from:'',to:'',coords:null,locationAt:0,mode:'solo',roleIds:[],helperId:'',distance:8,query:null});}
function raw(){const t=tvInit();return t.taxiOrders||(t.taxiOrders=[]);}
function owned(o){return !!o&&o.taxiV2&&o.accountId===account();}
function visible(o,now=Date.now()){return owned(o)&&(!['completed','cancelled'].includes(o.status)||now<Number(o.closedAt)+86400000);}
function rows(){return raw().filter(o=>visible(o));}
function current(x){return raw().find(o=>owned(o)&&o.id===(typeof x==='string'?x:x&&x.id));}
function riders(q){if(q.mode==='solo')return [{id:'me',name:S.me.name||'我'}];const people=q.roleIds.map(k=>{const c=getC(k);return {id:'role:'+k,name:c&&(c.remark||c.name)||'角色'};});return q.mode==='together'?[{id:'me',name:S.me.name||'我'},...people]:people;}
function validate(q){if(!q||q.accountId!==account()||!['solo','together','give'].includes(q.mode))return '出行账户或方式已变化，请重新查询';if(![q.from,q.to].every(x=>typeof x==='string'&&x.trim()&&x.length<=150&&!/[<>\[\]\r\n]/.test(x))||q.from.trim()===q.to.trim())return '请填写不同的上车地点和目的地';if(!Array.isArray(q.roleIds)||new Set(q.roleIds).size!==q.roleIds.length||q.mode==='solo'&&q.roleIds.length||q.mode==='give'&&q.roleIds.length!==1||q.mode==='together'&&(q.roleIds.length<1||q.roleIds.length>3))return '请重新选择乘车角色，每车最多4人';if(q.helperId&&(!getC(q.helperId)||getC(q.helperId).deleted||getC(q.helperId).blocked||getC(q.helperId).isPhoneFriend))return '共享角色不可用';if(q.roleIds.some(k=>{const c=getC(k);return !c||c.deleted||c.blocked||c.isPhoneFriend;}))return '乘车角色不可用，请重新选择';if(!Number.isFinite(q.distance)||q.distance<.5||q.distance>200)return '模拟距离须为0.5至200公里';if(q.coords&&(!Number.isFinite(q.coords.latitude)||!Number.isFinite(q.coords.longitude)||Math.abs(q.coords.latitude)>90||Math.abs(q.coords.longitude)>180))return '定位坐标无效';if(q.coords&&(!Number.isFinite(q.locationAt)||Date.now()-q.locationAt>300000||q.locationAt-Date.now()>5000))return '定位已超过5分钟，请刷新当前位置';return '';}
function distance(a,b){const rad=n=>n*Math.PI/180,x=rad(b[1]-a.latitude),y=rad(b[2]-a.longitude),h=Math.sin(x/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b[1]))*Math.sin(y/2)**2;return 6371*2*Math.asin(Math.sqrt(Math.min(1,h)));}
function quotes(q){if(validate(q))return [];return types.map(t=>({...t,cents:Math.round((t.base+t.km*q.distance)*100),duration:Math.max(8,Math.round(q.distance/25*60+5))}));}
function paint(){const e=document.querySelector('.ctt-scroll'),top=e&&e.scrollTop||0;root.render();const n=document.querySelector('.ctt-scroll');if(n)n.scrollTop=top;}
function change(key,value){const s=state();s[key]=value;s.query=null;if(key==='from'){s.coords=null;s.locationAt=Date.now();}save();}
function mode(value){const s=state();if(!['solo','together','give'].includes(value)||s.mode===value)return;s.mode=value;s.roleIds=[];s.helperId='';s.query=null;if(value==='give'||s._giveMode){s.from='';s.coords=null;s.locationAt=0;}s._giveMode=value==='give';save();paint();}
function modal(html){NorthTravelFlight.modal('<div class="ctt-dialog">'+html+'</div>');}
function people(){const s=state(),contacts=(S.contacts||[]).filter(c=>!c.deleted&&!c.blocked&&!c.isPhoneFriend);modal('<h3>'+(s.mode==='solo'?'共享出行给角色':s.mode==='give'?'给谁叫车':'同行角色')+'</h3><p>每辆车最多4位乘客，车费按一单计算。</p>'+contacts.map(c=>'<label class="ctt-person"><input type="'+(s.mode!=='together'?'radio':'checkbox')+'" name="taxiRoles" value="'+safe(c.id)+'" '+((s.roleIds.includes(c.id)||s.helperId===c.id)?'checked':'')+'>'+esc(c.remark||c.name)+'</label>').join('')+'<button onclick="NorthTravelTaxi.savePeople()">确认乘车人员</button>');}
function destination(){modal('<h3>选择目的地</h3><input id="cttDestinationSearch" class="ctt-destination-search" value="'+safe(state().to)+'" placeholder="输入或搜索目的地" maxlength="150" oninput="NorthTravelTaxi.destinationFilter(this.value)"><div id="cttDestinationChoices">'+destinationChoices(state().to)+'</div><button onclick="NorthTravelTaxi.setDestination(document.getElementById(\'cttDestinationSearch\').value)">使用这个目的地</button>');}
function destinationChoices(v){const found=places.filter(p=>!v||p[0].toLowerCase().includes(String(v).trim().toLowerCase()));return found.map(p=>'<button class="ctt-destination-choice" data-place="'+safe(p[0])+'" onclick="NorthTravelTaxi.setDestination(this.dataset.place)">'+esc(p[0])+'<span>›</span></button>').join('')||'<p>可以直接填写目的地，再点下方确认。</p>';}
function destinationFilter(v){document.getElementById('cttDestinationChoices').innerHTML=destinationChoices(v);}
function setDestination(v){v=String(v||'').trim();if(!v||v.length>150||/[<>\[\]\r\n]/.test(v))return toast('请输入有效目的地');change('to',v);closeModal();paint();}
function canCancel(o){return !!(o&&visible(o)&&o.payer==='me'&&o.mode!=='give'&&o.people.some(p=>p.id==='me')&&['waiting','arrived'].includes(o.status));}
function cancelButton(o){return canCancel(o)?'<button class="ctt-cancel" onclick="event.stopPropagation();NorthTravelTaxi.cancel(\''+safe(o.id)+'\')">取消打车 · 原路退款</button>':'';}
function savePeople(){const s=state(),ids=[...document.querySelectorAll('input[name="taxiRoles"]:checked')].map(e=>e.value);if(s.mode!=='together'?ids.length!==1:ids.length<1||ids.length>3)return toast('请选择乘车角色，每车最多4人');if(s.mode==='solo')s.helperId=ids[0];else s.roleIds=ids;s.query=null;save();closeModal();paint();}
async function locate(){const s=state();if(locating||s.mode==='give')return;locating=true;const token=++locationToken,aid=account();paint();try{let v;
 if(root.__SMALL_PHONE_PRIVATE__&&root.SmallPhoneNative&&root.SmallPhoneNative.request){const n=await root.SmallPhoneNative.request('location.current');const x=n&&n.result||n;if(x&&Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)&&Number.isFinite(x.accuracy)&&x.accuracy>=0&&x.timestamp&&Math.abs(Date.now()-x.timestamp)<60000)v=x;}
 if(!v){if(!navigator.geolocation)throw Error('此设备不支持定位，请手动填写上车地点');const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:0,timeout:10000}));v=p.coords;}
 if(!Number.isFinite(v.latitude)||!Number.isFinite(v.longitude)||Math.abs(v.latitude)>90||Math.abs(v.longitude)>180)throw Error('无法取得有效位置，请手动填写');
 if(token!==locationToken||aid!==account()||state().mode==='give')return;s.coords={latitude:v.latitude,longitude:v.longitude,accuracy:v.accuracy};s.locationAt=Date.now();s.from='当前定位点';s.query=null;save();toast('已取得真实设备位置，请确认附近的上车点');
 }catch(e){if(token===locationToken&&aid===account())toast(e.code===1?'定位未授权，可手动输入上车地点':e.code===3?'定位超时，请重试或手动填写':e.message||'定位失败，请手动填写');}finally{if(token===locationToken){locating=false;if(aid===account()&&active)paint();}}}
function query(){const s=state(),q={accountId:account(),from:s.from.trim(),to:s.to.trim(),coords:s.coords&&{...s.coords},locationAt:s.locationAt,mode:s.mode,roleIds:[...s.roleIds],helperId:s.helperId||'',distance:Number(s.distance),ts:Date.now()};const poi=places.find(p=>q.to.includes(p[0]));if(q.coords&&poi){q.distance=Math.round(Math.max(.5,distance(q.coords,poi)*1.3)*10)/10;q.distanceSource='直线距离折算，非真实道路路线';}else q.distanceSource='手动／默认模拟距离，非真实道路路线';const error=validate(q);if(error)return toast(error);q.people=riders(q);s.query=q;view='results';save();paint();}
function userMoney(cents,note){const n=Math.round(Number(S.me.balance)*100);if(!Number.isSafeInteger(n)||n+cents<0)return false;addBill(cents<0?'out':'in',Math.abs(cents)/100,note);return true;}
function roleMoney(c,source,cents,note,o){if(!c||!['roleWallet','roleBank'].includes(source))return false;const d=source==='roleBank'?(S.spy||(S.spy={}))[c.id]:c,key=source==='roleBank'?'balance':'wallet';if(!d)return false;const next=NorthHotelData.moneyNext(d[key],cents);if(next===null)return false;d[key]=next;const bank=(S.spy||(S.spy={}))[c.id]||((S.spy[c.id])={balance:0,wallet:[]});bank.wallet=bank.wallet||[];bank.wallet.unshift({id:uid(),time:Date.now(),ts:Date.now(),type:cents<0?'out':'in',amount:Math.abs(cents)/100,note,taxiOrderId:o.id});bank.wallet=bank.wallet.slice(0,40);return true;}
function known(o){return o.knownRoleIds.filter(k=>{const c=getC(k);return c&&!c.deleted&&!c.blocked&&!c.isPhoneFriend;});}
function notifyCard(o){for(const k of known(o))msgs(k).push({id:uid(),time:Date.now(),role:o.payer==='ta'&&o.cid===k?'assistant':'user',type:'ticket',trip:{id:o.id,taxiV2:true,accountId:o.accountId}});}
function book(q,type,c=null){const error=validate(q);if(error||Date.now()-q.ts>600000){toast(error||'报价已过期，请重新查询');return false;}const f=quotes(q).find(x=>x.id===type);if(!f)return false;const key=JSON.stringify([q.from,q.to,q.coords,q.mode,q.roleIds,type]);const prior=rows().find(o=>!['completed','cancelled'].includes(o.status)&&o.bookingKey===key);if(prior)return true;if(c&&(c.blocked||c.deleted||c.isPhoneFriend))return false;const funds=c?tvHotelRoleMoney(c):null,o={id:uid(),taxiV2:true,accountId:account(),bookingKey:key,from:q.from,to:q.to,coords:q.coords&&{...q.coords},mode:q.mode,people:riders(q),knownRoleIds:[...new Set([...q.roleIds,...(q.helperId?[q.helperId]:[]),...(c?[c.id]:[])])],type,carName:f.name,price:f.cents/100,distance:q.distance,distanceSource:q.distanceSource||'模拟距离',duration:f.duration,eta:f.eta,ts:Date.now(),arriveAt:Date.now()+f.eta*60000,status:'waiting',payer:c?'ta':'me',cid:c&&c.id||'',fundingSource:c?funds&&funds.source:'userWallet',driver:'模拟司机 · '+({express:'陈',taxi:'李',special:'周',luxury:'林'}[type])+'师傅',plate:'模拟车辆 · '+String(raw().length+1).padStart(3,'0'),_hiddenFromChar:!c&&!q.roleIds.length&&!q.helperId};
 if(c?!funds||!roleMoney(c,funds.source,-f.cents,'模拟打车：'+o.to,o):!userMoney(-f.cents,'模拟打车：'+o.to)){toast('付款余额不足，未叫车');return false;}raw().push(o);notifyCard(o);save();stamp();if(typeof cur==='function'&&cur().p==='chat')root.render();return true;}
function choose(type){const q=state().query;if(book(q,type)){view='orders';paint();toast('模拟叫车成功');}}
function summary(x){const o=current(x);if(!o||!visible(o))return '打车行程已结束／已清理';return '模拟打车 '+o.carName+' · '+o.from+' → '+o.to+' · 乘车人：'+o.people.map(p=>p.name).join('、')+' · '+(o.mode==='solo'?'用户独自出行':o.mode==='give'?'给角色叫车':'用户与角色同行')+' · '+statusText(o)+' · '+(o.payer==='ta'?'角色自己的银行付款':'用户钱包付款')+' '+money(o.price)+' · '+o.driver;}
function statusText(o){return {waiting:'等待司机 · 预计'+Math.max(0,Math.ceil((o.arriveAt-Date.now())/60000))+'分钟到达',arrived:'司机已到达 · 等待上车确认',riding:'已确认上车 · 行程中',completed:'行程已完成',cancelled:'已取消并退款'}[o.status]||'未知状态';}
function refundWaiting(o,closedAt){if(!o||!visible(o)||!['waiting','arrived'].includes(o.status))return false;const cents=Math.round(o.price*100),c=getC(o.cid);if(o.payer==='ta'?!roleMoney(c,o.fundingSource,cents,'模拟打车取消退款',o):!userMoney(cents,'模拟打车取消退款'))return false;o.status='cancelled';o.closedAt=closedAt;return true;}
function cancel(k){const o=current(k);if(!canCancel(o)||!refundWaiting(o,Date.now()))return false;save();stamp();paint();toast('已取消，费用原路退回');return true;}
function board(k){tick();const o=current(k);if(!o||o.status!=='arrived')return false;o.status='riding';o.boardedAt=Date.now();o.finishAt=o.boardedAt+o.duration*60000;save();stamp();paint();tick();return true;}
function finish(k){const o=current(k);if(!o||o.status!=='riding')return false;o.status='completed';o.closedAt=Date.now();save();stamp();paint();return true;}
function card(x){const o=current(x);if(!o||!visible(o))return '<div class="cth-chat-hotel cth-chat-unavailable">打车行程已结束／已清理</div>';return '<div class="cth-chat-hotel ctt-card" role="button" tabindex="0" data-order="'+safe(o.id)+'" onclick="event.stopPropagation();NorthTravelTaxi.detail(this.dataset.order)" onkeydown="if(event.key===\'Enter\'||event.key===\' \'){event.preventDefault();NorthTravelTaxi.detail(this.dataset.order)}"><div class="ctt-card-head">'+NorthTravelHome.icon('car')+'<span>小鱼旅行 · 打车<small>'+esc(o.carName)+' · 专属出行卡</small></span></div><div class="cth-chat-body"><div class="cth-chat-status" data-taxi-status="'+safe(o.id)+'">'+esc(statusText(o))+'</div><b class="cth-chat-name">'+esc(o.to)+'</b><p>从 '+esc(o.from)+' 出发</p><p>乘车人：'+esc(o.people.map(p=>p.name).join('、'))+'</p><p>'+esc(o.driver)+' · '+esc(o.plate)+'</p><div class="cth-chat-total"><span>'+(o.payer==='ta'?'角色自己的银行付款':'我的钱包付款')+'</span><strong>'+money(o.price)+'</strong></div></div><div class="cth-chat-footer"><span>一路安心，慢慢抵达</span><b>查看行程 ›</b></div></div>';}
function head(title,action){return '<header class="ctt-head"><button aria-label="返回上一页" onclick="'+action+'"><svg viewBox="0 0 24 24"><path d="m15 4-8 8 8 8" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button><b>'+title+'</b><span>'+NorthTravelHome.icon('car')+'</span></header>';}
function render(){if(view==='cover'){const s=state();return '<div class="ctt-app">'+head('打车','NorthTravelHome.home()')+'<main class="ctt-scroll"><section class="ctt-hero"><small>小鱼旅行 · 城市出行</small><h1>下一站，安心出发</h1><p>自己出发，也可以陪ta一起。</p>'+NorthTravelHome.icon('car')+'</section><section class="ctt-form"><div class="ctt-modes">'+[['solo','我自己'],['together','和角色一起'],['give','给对方叫车']].map(([k,n])=>'<button class="'+(s.mode===k?'selected':'')+'" onclick="NorthTravelTaxi.mode(\''+k+'\')">'+n+'</button>').join('')+'</div><label class="ctt-address"><i class="ctt-start"></i><span>'+(s.mode==='give'?'对方上车地点':'上车地点')+'<input id="cttFrom" value="'+safe(s.from)+'" placeholder="'+(s.mode==='give'?'输入对方的上车地点':'定位或输入上车地点')+'" maxlength="150" onchange="NorthTravelTaxi.change(\'from\',this.value)"></span>'+(s.mode!=='give'?'<button class="ctt-locate" onclick="NorthTravelTaxi.locate()" '+(locating?'disabled':'')+'>'+NorthTravelHome.icon('pin')+(locating?'定位中':'定位')+'</button>':'')+'</label><label class="ctt-address"><i class="ctt-end"></i><span>目的地<input id="cttTo" value="'+safe(s.to)+'" placeholder="你想去哪里？" maxlength="150" onchange="NorthTravelTaxi.change(\'to\',this.value)"></span><button class="ctt-destination-open" aria-label="选择目的地" onclick="NorthTravelTaxi.destination()">⌄</button></label>'+(s.coords?'<p class="ctt-location-note">已获取真实位置'+(Number.isFinite(s.coords.accuracy)?' · 精度约'+Math.round(s.coords.accuracy)+'米':'')+'，可手动填写具体上车点。</p>':'')+(s.mode!=='solo'?'<button class="ctt-party" onclick="NorthTravelTaxi.people()">'+(s.mode==='give'?'乘车角色':'同行角色')+'<b>'+esc(s.roleIds.map(k=>{const c=getC(k);return c&&(c.remark||c.name)||'';}).join('、')||'选择角色')+' ›</b></button>':'<button class="ctt-party" onclick="NorthTravelTaxi.people()">共享出行给角色（可选）<b>'+esc(s.helperId&&getC(s.helperId)&&(getC(s.helperId).remark||getC(s.helperId).name)||'选择角色')+' ›</b></button>')+'<button class="ctt-query" onclick="NorthTravelTaxi.query()">查询车型与价格</button></section><button class="ctt-orders-entry" onclick="NorthTravelTaxi.orders()">我的打车订单 <span>›</span></button><p class="ctt-note">小手机模拟叫车，不向真实平台派车。没有地图路线时按默认8公里估价，可在报价页调整；每车最多4人，完成或取消后24小时隐藏。司机到达后30分钟未确认上车，会自动取消并退款。</p></main></div>';}
 if(view==='results'){const q=state().query;if(!q)return '<div class="ctt-app">'+head('车型报价','NorthTravelTaxi.cover()')+'<p class="ctt-note">请重新查询</p></div>';return '<div class="ctt-app">'+head('选择你的出行','NorthTravelTaxi.cover()')+'<main class="ctt-scroll"><section class="ctt-route"><b>'+esc(q.from)+' → '+esc(q.to)+'</b><p>'+esc(riders(q).map(p=>p.name).join('、'))+' · 每车一单</p><label>模拟距离 <input id="cttDistance" type="number" min="0.5" max="200" step="0.5" value="'+q.distance+'" onchange="NorthTravelTaxi.reprice(this.value)"> 公里</label><small>'+esc(q.distanceSource)+'</small></section>'+quotes(q).map(f=>'<article class="ctt-quote">'+NorthTravelHome.icon('car')+'<div><h2>'+f.name+'</h2><p>'+f.note+'</p><small>预计'+f.eta+'分钟接驾 · 车程约'+f.duration+'分钟</small></div><strong>'+money(f.cents/100)+'</strong><button data-taxi-type="'+f.id+'" onclick="NorthTravelTaxi.choose(this.dataset.taxiType)">打车</button></article>').join('')+'<p class="ctt-note">报价为人民币模拟估价，不是滴滴或出租车平台的实时价格，无真实司机派单。</p></main></div>';}
 if(view==='orders')return '<div class="ctt-app">'+head('我的打车订单','NorthTravelTaxi.cover()')+'<main class="ctt-scroll">'+(rows().length?rows().slice().reverse().slice(0,limit).map(o=>'<section class="ctt-order-row">'+card(o)+cancelButton(o)+'</section>').join('')+(rows().length>limit?'<button class="ctt-query" onclick="NorthTravelTaxi.more()">查看更多行程</button>':''):'<p class="ctt-empty">还没有打车订单</p>')+'<p class="ctt-note">自己付款且自己乘车的未上车行程可在这里取消；角色给你叫车、给角色叫车不可手动取消。行程完成或取消后24小时自动隐藏，账单保留。</p></main></div>';
 const o=current(detailId);if(!o||!visible(o))return '<div class="ctt-app">'+head('打车行程','NorthTravelTaxi.backDetail()')+'<p class="ctt-empty">行程已结束／已清理</p></div>';return '<div class="ctt-app">'+head('专属打车行程','NorthTravelTaxi.backDetail()')+'<main class="ctt-scroll">'+card(o)+'<section class="ctt-driver"><h2>'+esc(statusText(o))+'</h2><p>'+esc(o.driver)+' · '+esc(o.plate)+'</p><p>'+esc(o.from)+' → '+esc(o.to)+'</p><p>模拟距离 '+o.distance+'公里 · 预计车程 '+o.duration+'分钟</p><p>乘车人：'+esc(o.people.map(p=>p.name).join('、'))+'</p><p>付款：'+(o.payer==='ta'?'角色自己的银行余额':'我的钱包')+' · '+money(o.price)+'</p></section>'+(o.status==='arrived'?'<button class="ctt-query" onclick="NorthTravelTaxi.board(\''+safe(o.id)+'\')">已经上车 · 告诉角色</button>':o.status==='riding'?'<button class="ctt-query" onclick="NorthTravelTaxi.finish(\''+safe(o.id)+'\')">已到达 · 结束行程</button>':'')+'<p class="ctt-note">模拟司机到达后可确认上车，30分钟内未确认会取消并退款；给角色叫车时，角色成功报备车到后，30秒后模拟上车并再次报备；也可手动确认对方已经上车。上车后开始计时，预计车程结束自动完成，也可手动确认到达。只有自己付款、自己乘车的行程可在我的打车订单中取消；角色给你叫车、你给角色叫车不可手动取消。已上车的行程不能退车费。</p></main></div>';}
function reprice(v){const q=state().query,n=Number(v);if(!q||!Number.isFinite(n)||n<.5||n>200)return toast('距离须为0.5至200公里');q.distance=n;q.distanceSource='手动模拟距离';q.ts=Date.now();state().distance=n;save();paint();}
function open(){NorthTravelHome.home();active=true;view='cover';origin=null;paint();}
function deactivate(){active=false;locationToken++;locating=false;}
function cover(){active=true;view='cover';origin=null;paint();}
function orders(){active=true;view='orders';limit=12;origin=null;paint();}
function detail(k){const o=current(k);if(!o||!visible(o))return toast('行程已结束／已清理');origin=typeof cur==='function'?{...cur()}:null;if(origin&&origin.p!=='travel')go('travel');NorthTravelHome.home();active=true;view='detail';detailId=k;paint();}
function backDetail(){if(origin&&origin.p==='chat'){active=false;origin=null;back();return;}orders();}
function more(){limit+=12;paint();}
function stamp(){signature=account()+'|'+rows().map(o=>o.id+o.status).join('|');}
const tags=note=>[...String(note||'').matchAll(/\[打车提醒\|([^|\]]+)\|([^|\]]+)\|(arrive|board)\]/g)];
function eligible(o,k,stage){return !!(o&&visible(o)&&known(o).includes(k)&&o.status===(stage==='arrive'?'arrived':'riding')&&(stage!=='arrive'||Date.now()<o.arriveAt+1800000));}
function noteValid(note){return tags(note).every(m=>eligible(current(m[1]),m[2],m[3]));}
function delivered(note,msg,k){if(!msg||!['text','voice'].includes(msg.type)||!String(msg.content||msg.text||'').trim()||!noteValid(note))return;for(const m of tags(note)){const o=current(m[1]);if(o&&m[2]===k){(o.reminded||(o.reminded={}))[k+':'+m[3]]=Date.now();msg._taxiReminderOrderId=o.id;if(o.mode==='give'&&o.people.some(p=>p.id==='role:'+k)&&m[3]==='arrive'&&!o.autoBoardAt)o.autoBoardAt=Date.now()+30000;}}}
function tick(){if(typeof S==='undefined'||typeof actId!=='function'||typeof tvInit!=='function'||!S.travel||!Array.isArray(S.travel.taxiOrders)||!S.travel.taxiOrders.length)return;const now=Date.now();let changed=false;for(const o of rows()){if(o.status==='waiting'&&now>=o.arriveAt){o.status='arrived';changed=true;}if(o.mode==='give'&&o.status==='arrived'&&o.autoBoardAt&&now>=o.autoBoardAt&&now<o.arriveAt+1800000&&o.people.every(p=>p.id.startsWith('role:')&&known(o).includes(p.id.slice(5)))){o.status='riding';o.boardedAt=o.autoBoardAt;o.finishAt=o.boardedAt+o.duration*60000;changed=true;}if(o.status==='arrived'&&now>=o.arriveAt+1800000&&refundWaiting(o,o.arriveAt+1800000))changed=true;if(o.status==='riding'&&now>=o.finishAt){o.status='completed';o.closedAt=o.finishAt;changed=true;}}if(changed)save();const next=account()+'|'+rows().map(o=>o.id+o.status).join('|');if(signature&&signature!==next){if(active)paint();else if(typeof cur==='function'&&cur().p==='chat')root.render();}signature=next;if(typeof document!=='undefined'&&document.querySelectorAll)document.querySelectorAll('[data-taxi-status]').forEach(e=>{const o=current(e.dataset.taxiStatus);if(o&&visible(o))e.textContent=statusText(o);});
 if(typeof scheduleReply!=='function'||typeof document!=='undefined'&&document.hidden)return;if(running&&now-running.at<120000)return;running=null;
 for(const o of rows()){const stage=o.status==='arrived'?'arrive':o.status==='riding'?'board':'';if(!stage)continue;for(const k of known(o)){if(!eligible(o,k,stage))continue;const recipient=o.mode==='give'&&o.people.some(p=>p.id==='role:'+k);const key=k+':'+stage,replyKey=typeof replyStateKey==='function'?replyStateKey(k,o.accountId):'';if(o.reminded&&o.reminded[key]||o.retryAt&&o.retryAt[key]>now||typeof replyGenerationBusy==='function'&&replyGenerationBusy(k,o.accountId)||typeof _replyTimers!=='undefined'&&_replyTimers[replyKey]||typeof _replyFeatureTimers!=='undefined'&&_replyFeatureTimers[replyKey]||typeof roleBusyActive==='function'&&roleBusyActive(getC(k),o.accountId)||typeof _call!=='undefined'&&_call&&_call.state==='active'&&_call.id===k)continue;const token={at:now};running=token;(o.retryAt||(o.retryAt={}))[key]=now+120000;save();scheduleReply(k,'[打车提醒|'+o.id+'|'+k+'|'+stage+']\n[系统：'+(recipient?(stage==='arrive'?'用户为你叫的模拟司机已经到达你的上车点，请主动向用户报备车到了、准备上车，不能说已经上车。':'你已经在模拟流程中上车，请主动向用户报备你已上车，不能说用户上车，也不能说已经到达目的地。'):(stage==='arrive'?'模拟司机已经到达上车点，提醒实际乘车人上车，尚未确认上车。':'用户刚确认实际乘车人已经上车，请自然回应，不能说已经到达目的地。'))+summary(o)+'。按你的角色口语发微信，不复述系统标记。]',()=>{if(running===token)running=null;},o.accountId);return;}}
}
function rolePrompt(c){const mine=rows().filter(o=>o.knownRoleIds.includes(c.id)),q=state().query,shared=q&&Date.now()-q.ts<=600000&&(q.roleIds.includes(c.id)||q.helperId===c.id);
 return '\n\n# 小手机模拟打车\n'+(mine.length?mine.map(summary).join('\n'):'暂无你知情的打车订单。')+'\n真正叫车可输出 [叫车|目的地|快车/出租车/专车/豪华车|给你/我们一起/我自己]，必须基于用户明确共享的最新查询与上车地点；不能猜用户或角色的实时位置。输出 [叫车查询] 可按共享查询叫车。仅用你自己的银行余额，失败不能说已叫好，司机只是模拟。'+(shared?'\n用户共享的打车查询（尚未叫车）：'+JSON.stringify(q):'');}
function roleQuery(c,destination,type,guest){const q=state().query;if(!q||!c||Date.now()-q.ts>600000)return false;const shared=q.roleIds.includes(c.id)||q.helperId===c.id;if(!shared)return false;const copy={...q,roleIds:[...q.roleIds],people:q.people&&q.people.map(p=>({...p}))};if(destination&&destination.trim()!==q.to)return false;if(guest==='给你'){if(q.mode==='give')return false;copy.mode='solo';copy.roleIds=[];}else if(guest==='我们一起'){if(q.mode==='give')return false;copy.mode='together';copy.roleIds=[c.id];}else if(guest==='我自己'){if(q.mode!=='give'||q.roleIds[0]!==c.id)return false;}else if(guest)return false;return book(copy,type||'express',c);}
function consume(content,c,done){let failed=false;const out=String(content||'').replace(/\[打车提醒\|[^\]\n]+\]/g,'').replace(/\[叫车\|([^\]\n]+)\]/g,(_,args)=>{const a=args.split('|').map(x=>x.trim()),type={快车:'express',滴滴快车:'express',出租车:'taxi',专车:'special',豪华车:'luxury',滴滴豪华车:'luxury'}[a[1]],ok=a.length===3&&type&&roleQuery(c,a[0],type,a[2]);failed=failed||!ok;done(!!ok);return '';}).replace(/\[叫车查询\]/g,()=>{const ok=roleQuery(c);failed=failed||!ok;done(ok);return '';});return failed?'':out;}
function inspection(since=0){return rows().filter(o=>o.ts>since).slice(-12).map(o=>'·她的打车订单：'+summary(o)).join('\n')+'\n';}
setInterval(tick,1000);if(typeof document!=='undefined'&&document.addEventListener)document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});if(root.addEventListener){root.addEventListener('pageshow',tick);root.addEventListener('focus',tick);}
root.NorthTravelTaxi={active:()=>active,state,open,deactivate,cover,orders,detail,backDetail,render,change,mode,people,savePeople,destination,destinationFilter,setDestination,locate,query,reprice,quotes,validate,book,choose,rows,current,visible,summary,card,canCancel,cancel,board,finish,tick,noteValid,delivered,rolePrompt,roleQuery,consume,inspection,types};
})(globalThis);
