import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
// The paid internal service was explicitly retired; verify its replacement and external safety.
for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const app=fs.readFileSync(base+'app.js','utf8'),album=fs.readFileSync(base+'photo-album.js','utf8');
 const extract=name=>{const match=app.match(new RegExp('function '+name+'\\([^\\n]+'));assert(match,name);return match[0]};
 test(base+'saved internal flags cannot activate voice, ASR, or the retired backend',()=>{
  const settings={tts:{relay:true,enabled:true},stt:{relay:true},aiCore:{enabled:true,url:'https://retired.example'}};
  const c=vm.createContext({S:{settings},fetch(){throw Error('unexpected network')}});
  for(const name of ['aiCoreOn','aiCoreUrl','ttsRelayOn','sttRelayOn'])vm.runInContext(extract(name),c);
  assert.equal(c.aiCoreOn(),false);assert.equal(c.aiCoreUrl(),'');assert.equal(c.ttsRelayOn(settings.tts),false);assert.equal(c.sttRelayOn(),false);
  assert.equal(settings.tts.relay,true,'do not erase user archives');
  assert.doesNotMatch(app,/await aiRelay\(|await licenseSyncAiIdentity\(/);
 });
 test(base+'album renders the active user avatar, real item count, and only approved categories',()=>{
  const c=vm.createContext({S:{me:{name:'North',avatar:'my-avatar'},photoAlbum:{items:[{name:'Photo',src:'image.jpg'}]}},esc:s=>String(s).replaceAll('<','&lt;'),av:a=>'<img src="'+a+'">',storedImageElementSource:s=>s,render(){},toast(){}});
  vm.runInContext(album,c);let html=c.renderPhotoAlbum();assert.match(html,/my-avatar/);assert.match(html,/人物与宠物/);assert.doesNotMatch(html,/AI账户|媒体类型|1899/);
  c.photoAlbumTab('library');html=c.renderPhotoAlbum();assert.match(html,/1 个项目/);assert.match(html,/image.jpg/);
  c.S.photoAlbum.items=[];assert.match(c.renderPhotoAlbum(),/0 个项目/);assert.match(c.renderPhotoAlbum(),/还没有照片/);
 });
 test(base+'replacement module has no account requests and the old module is absent',()=>{
  assert.equal(fs.existsSync(base+'ai-account.js'),false);assert.doesNotMatch(album,/aiRelay\(|localStorage\.|pickFile\(/);
  const html=fs.readFileSync(base+'小手机.html','utf8');assert.match(html,/photo-album\.js/);assert.doesNotMatch(html,/ai-account\.js/);
 });
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const album=fs.readFileSync(base+'photo-album.js','utf8');
 const make=()=>vm.createContext({S:{me:{},photoAlbum:{items:Array.from({length:1000},(_,i)=>({src:'photo-'+i+'.jpg',takenAt:i?'2026-10-04T13:42:00+08:00':null}))}},esc:String,storedImageElementSource:s=>s,render(){},toast(){},document:{querySelector:()=>null},setTimeout:fn=>fn()});
 test(base+'photo capture date is explicit and missing metadata never becomes upload time',()=>{const c=make();vm.runInContext(album,c);assert.equal(c.photoAlbumTaken({createdAt:'2026-10-05'}).date,'拍摄时间未知');assert.equal(c.photoAlbumTaken({takenAt:'not-a-date'}).date,'拍摄时间未知');assert.equal(c.photoAlbumTaken({takenAt:'2026-10-04'}).date,'拍摄时间未知');assert.equal(c.photoAlbumTaken({takenAt:'2026-10-04T13:42:00+08:00'}).time,'13:42');assert.equal(c.photoAlbumTaken({capturedAt:0}).time.length,5);});
 test(base+'viewer opens any indexed photo, bounds image DOM, and returns to library',()=>{const c=make();vm.runInContext(album,c);c.photoAlbumTab('library');c.photoAlbumOpen(500);let html=c.renderPhotoAlbum();assert.match(html,/501 \/ 1000/);assert.equal((html.match(/class="photo-view-slide"/g)||[]).length,3);assert.equal((html.match(/class="photo-view-thumb /g)||[]).length,41);assert.match(html,/更早的照片/);assert.match(html,/更晚的照片/);assert.match(html,/2026年10月4日/);c.photoAlbumOpen(-1);assert.match(c.renderPhotoAlbum(),/501 \/ 1000/);c.photoAlbumClose();assert.match(c.renderPhotoAlbum(),/data-photo-album="library"/);});
 test(base+'swipe advances one image, rejects vertical/cancel/edge gestures and stale timers',()=>{const c=make();const timers=[];c.setTimeout=fn=>timers.push(fn);vm.runInContext(album,c);c.photoAlbumOpen(0);const track={style:{}},box={clientWidth:390,querySelector:()=>track,setPointerCapture(){}};const event=(x,y)=>({currentTarget:box,clientX:x,clientY:y,pointerId:1,button:0});const selected=[];c.photoAlbumSelect=i=>selected.push(i);c.photoAlbumPointer(event(250,50),'start');c.photoAlbumPointer(event(120,55),'move');assert.match(track.style.transform,/-130px/);c.photoAlbumPointer(event(120,55),'end');timers.shift()();assert.deepEqual(selected,[1]);c.photoAlbumPointer(event(150,50),'start');c.photoAlbumPointer(event(260,55),'end');assert.equal(timers.length,0);c.photoAlbumPointer(event(250,50),'start');c.photoAlbumPointer(event(180,240),'end');assert.equal(timers.length,0);c.photoAlbumPointer(event(250,50),'start');c.photoAlbumPointer(event(120,50),'cancel');assert.equal(timers.length,0);c.photoAlbumPointer(event(250,50),'start');c.photoAlbumPointer(event(120,50),'end');c.photoAlbumClose();timers.shift()();assert.deepEqual(selected,[1]);});
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const source=fs.readFileSync(base+'photo-album.js','utf8');
 test(base+'collections filter accounts, show correct dates, omit dates on square tiles, and preserve return tab',()=>{
 const c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:[{src:'a.jpg',category:'回忆',location:'阿勒泰',takenAt:'2026-01-16T13:42'},{src:'b.jpg',category:'人物与宠物',takenAt:'2026-01-16T13:42'},{src:'hidden.jpg',category:'回忆',accountId:'other'}]}},esc:String,storedImageElementSource:s=>s,render(){},document:{querySelector:()=>null}});vm.runInContext(source,c);c.photoAlbumToggle('回忆');assert.match(c.photoAlbumSection('回忆'),/阿勒泰/);assert.match(c.photoAlbumSection('回忆'),/2026年1月16日/);assert.doesNotMatch(c.photoAlbumSection('回忆'),/hidden.jpg|播放/);c.photoAlbumToggle('人物与宠物');assert.match(c.photoAlbumSection('人物与宠物'),/b.jpg/);assert.doesNotMatch(c.photoAlbumSection('人物与宠物'),/2026年|photo-category-caption/);c.photoAlbumOpen(0);c.photoAlbumClose();assert.match(c.renderPhotoAlbum(),/data-photo-album="collections"/);
 });
 test(base+'categorized upload preserves original bytes and metadata, creates a separate thumbnail, and rolls back on storage failure',async()=>{
 const writes=new Map(),deleted=[],data={me:{active:'main'},photoAlbum:{items:[]}};let count=0;
 const c=vm.createContext({S:data,Blob,Uint8Array,atob,document:{querySelector:()=>null},uid:()=>String(++count),compress:async()=> 'data:image/jpeg;base64,YWJj',imgPut:async(k,v)=>writes.set(k,v),imgDel:async k=>{deleted.push(k);writes.delete(k)},saveNowAsync:async()=>true,render(){},toast(){}});vm.runInContext(source,c);c.photoAlbumUploadOpen('旅程');const original=new Blob(['original-pixels'],{type:'image/jpeg'});original.name='trip.jpg';c.photoAlbumChooseFiles({files:[original]});const button={},status={};const form={elements:{category:{value:'旅程'},title:{value:'旅行'},location:{value:'新疆'},takenAt:{value:'2026-01-16T13:42'}},querySelector:s=>s==='[type="submit"]'?button:status};await c.photoAlbumUploadSave(form);assert.equal(data.photoAlbum.items.length,1);const row=data.photoAlbum.items[0];assert.equal(row.category,'旅程');assert.equal(row.takenAt,'2026-01-16T13:42');assert.equal(row.accountId,'main');assert.equal(writes.get(row.src.slice(6)),original);assert.equal(await writes.get(row.thumbSrc.slice(6)).text(),'abc');assert.doesNotMatch(JSON.stringify(data.photoAlbum),/data:image|original-pixels/);
 c.photoAlbumUploadOpen('旅程');c.photoAlbumChooseFiles({files:[original]});c.saveNowAsync=async()=>false;await c.photoAlbumUploadSave(form);assert.equal(data.photoAlbum.items.length,1);assert.equal(deleted.length,2);assert.match(status.textContent,/存储空间不足/);assert.equal(button.disabled,false);
 });
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(base+'local photo URLs release offscreen images and reload when scrolled back',async()=>{const callbacks=[],tasks=[],revoked=[];let seq=0;const img={dataset:{albumRef:'local-photo'},isConnected:true,src:'',getAttribute(){return this.src||null},removeAttribute(){this.src=''},nextElementSibling:{hidden:true}};const c=vm.createContext({S:{me:{}},esc:String,storedImageElementSource:s=>s,document:{querySelectorAll:()=>[img]},queueMicrotask:f=>tasks.push(f),Blob,imgGet:async()=>new Blob(['pixels']),URL:{createObjectURL:()=> 'blob:local-'+(++seq),revokeObjectURL:x=>revoked.push(x)},IntersectionObserver:class{constructor(cb){callbacks.push(cb)}observe(){}disconnect(){}}});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);c.photoAlbumImageHTML('album:local-photo','photo');tasks.shift()();callbacks[0]([{isIntersecting:true,target:img}]);await new Promise(setImmediate);assert.equal(img.src,'blob:local-1');callbacks[0]([{isIntersecting:false,target:img}]);assert.equal(img.src,'');assert.deepEqual(revoked,['blob:local-1']);callbacks[0]([{isIntersecting:true,target:img}]);await new Promise(setImmediate);assert.equal(img.src,'blob:local-2');});

test('album exit observer waits for body before initialization',()=>{let ready,observed=0;const doc={body:null,addEventListener:(name,fn)=>{assert.equal(name,'DOMContentLoaded');ready=fn}};const c=vm.createContext({document:doc,MutationObserver:class{observe(node){assert(node);observed++}}});vm.runInContext(fs.readFileSync('photo-album.js','utf8'),c);assert.equal(observed,0);doc.body={};ready();assert.equal(observed,1);});
for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 test(base+'library sort preserves selection identity, unknown dates last, account preferences independent',async()=>{
 const a={id:'a',src:'a',uploadedAt:100,takenAt:'2026-10-03T08:00'},b={id:'b',src:'b',uploadedAt:200,takenAt:'2026-10-01T08:00'},u={id:'u',src:'u',uploadedAt:300},other={id:'other',accountId:'other',src:'x',uploadedAt:999};
 const c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:[a,b,u,other]}},document:{querySelector:()=>null},render(){},toast(){},saveNowAsync:async()=>true});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);
 assert.deepEqual(Array.from(c.photoAlbumRows(),x=>x.id),['u','b','a']);c.photoAlbumSelectionToggle();c.photoAlbumPick(2);await c.photoAlbumSetSort('taken');assert.deepEqual(Array.from(c.photoAlbumRows(),x=>x.id),['a','b','u']);assert.equal(vm.runInContext('_photoAlbumSelection.rows.has(photoAlbumRows()[0])',c),true);c.S.me.active='other';assert.equal(c.photoAlbumSortMode(),'added');assert.deepEqual(Array.from(c.photoAlbumRows(),x=>x.id),['other']);c.photoAlbumPick(0);assert.equal(vm.runInContext('_photoAlbumSelection.rows.size',c),1);
 });
 test(base+'multi delete commits before blob cleanup, preserves other accounts/shared files and rolls back failure',async()=>{
 const a={src:'album:__album_photo_a',thumbSrc:'album:__album_photo_a_thumb'},shared={src:'album:__album_photo_shared'},other={accountId:'other',src:shared.src},asset={src:'assets/photo.jpg'};const rows=[a,shared,other,asset],deleted=[];let good=false,saves=0;
 const c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:rows}},document:{querySelector:()=>null},render(){},toast(){},saveNowAsync:async()=>{saves++;return good},imgDel:async key=>{assert(good);deleted.push(key)}});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);
 c.photoAlbumSelectionToggle();c.photoAlbumPick(0);c.photoAlbumPick(1);await c.photoAlbumDeleteSelected();assert.equal(c.S.photoAlbum.items,rows);assert.equal(deleted.length,0);assert.equal(vm.runInContext('_photoAlbumSelection.rows.size',c),2);good=true;await c.photoAlbumDeleteSelected();assert.deepEqual(Array.from(c.S.photoAlbum.items,x=>x.src),[other.src,asset.src]);assert.deepEqual(deleted,[]);assert.equal(c.S.photoAlbum.deletedItems.length,2);assert.equal(vm.runInContext('_photoAlbumSelection',c),null);assert.equal(saves,2);
 });
}
for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 function shareFixture(){let seq=0;const sent=[],replies=[],visions=[],pf={id:'ME',friends:[{phone_id:'F',display_name:'真人'}],groups:[{group_id:'PG',name:'真人群'}],messages:{},groupMessages:{}};const photos=[{src:'album:__album_photo_one',name:'one'},{src:'album:__album_photo_two',name:'two'}];const S={me:{active:'main'},contacts:[{id:'R',name:'角色',avatar:'🙂'},{id:'blocked',name:'blocked',blocked:true},{id:'alt',name:'alt',_added:{alt:true},altOnly:true}],groups:[{id:'G',name:'角色群',msgs:[]}],photoAlbum:{items:photos},messages:{}};
 const c=vm.createContext({S,Blob,console,document:{querySelector:()=>null},render(){},toast(){},uid:()=> 's'+(++seq),addedHere:x=>!x.altOnly,phoneFriendState:()=>pf,groupDisplayName:g=>g.name,pfFriendDisplayName:f=>f.display_name,phoneFriendAvatar:()=> '🙂',pfGroupDisplayName:g=>g.name,getC:id=>S.contacts.find(x=>x.id===id),phoneFriendById:id=>pf.friends.find(x=>x.phone_id===id),pfGroupById:id=>pf.groups.find(x=>x.group_id===id),gmMutedUntil:()=>0,pfGagKey:id=>'pf:'+id,pfgGagKey:id=>'pfg:'+id,imgGet:async()=>new Blob(['original']),compress:async()=> 'data:image/jpeg;base64,small',saveNowAsync:async()=>true,msgsForAccount:(id,owner)=>S.messages[id+'#'+owner]||(S.messages[id+'#'+owner]=[]),pushMsg:(id,m)=>(S.messages[id+'#main']||(S.messages[id+'#main']=[])).push(m),runVisionForMessage:async(id,m)=>{visions.push(m.id);m.desc='景色';m.visionState='success';return true},visionPhotoSource:async()=> 'img',suspicionFulfillRequest(){},scheduleReply:id=>replies.push(id),aiGroupReply:id=>replies.push(id),pfPack:JSON.stringify,pfMsgPayload:m=>JSON.parse(m.text),pfMsgList:(holder,id)=>holder[id]||[],PHONE_FRIEND_BODY_MAX:60000,sendPhoneFriendBody:async(id,body)=>{sent.push('pf:'+id);(pf.messages[id]||(pf.messages[id]=[])).push({id:'server'+(++seq),text:body})},sendPhoneFriendGroupBody:async(id,body)=>{sent.push('pfg:'+id);(pf.groupMessages[id]||(pf.groupMessages[id]=[])).push({id:'server'+(++seq),text:body})},esc:String,av:s=>'<span>'+s+'</span>',storedImageElementSource:s=>s});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);return {c,S,pf,sent,replies,visions,photos};}
 test(base+'album shares multiple photos to roles, real friends, role groups and real groups without duplicate retry',async()=>{const {c,S,pf,sent,replies,visions}=shareFixture();c.photoAlbumSelectionToggle();c.photoAlbumPick(0);c.photoAlbumPick(1);c.photoAlbumShareOpen();const ts=c.photoAlbumShareTargets();assert.deepEqual(Array.from(ts,t=>t.key),['role:R','group:G','pf:F','pfg:PG']);for(let i=0;i<ts.length;i++)c.photoAlbumShareTarget(i);await c.photoAlbumShareSend();await new Promise(setImmediate);assert.equal(S.messages['R#main'].length,2);assert.equal(S.groups[0].msgs.length,2);assert.equal(pf.messages.F.length,2);assert.equal(pf.groupMessages.PG.length,2);assert.equal(sent.length,4);assert.equal(new Set(replies).size,2);assert.equal(visions.length,2,'one vision call per photo across recipients');await c.photoAlbumShareSend();assert.equal(S.messages['R#main'].length,2);assert.equal(sent.length,4);assert.equal(S.photoAlbum.items.length,2);assert.equal(vm.runInContext('_photoAlbumShare',c),null);assert.equal(vm.runInContext('_photoAlbumViewer',c),null);assert.equal(vm.runInContext('_photoAlbumTab',c),'library');});
 test(base+'album cancels without sending, isolates account changes and avoids resending uncertain network results',async()=>{const {c,S,pf,sent}=shareFixture();c.photoAlbumShareOpen();assert.equal(vm.runInContext('_photoAlbumShare',c),null);c.photoAlbumSelectionToggle();c.photoAlbumPick(0);c.photoAlbumShareOpen();c.photoAlbumShareClose();assert.equal(sent.length,0);c.photoAlbumShareOpen();c.photoAlbumShareTarget(2);c.sendPhoneFriendBody=async(id,body)=>{sent.push(id);(pf.messages[id]||(pf.messages[id]=[])).push({id:'local_1',text:body,sendState:'unknown'})};await c.photoAlbumShareSend();assert.match(vm.runInContext('_photoAlbumShare.status',c),/待确认/);await c.photoAlbumShareSend();assert.equal(sent.length,1);S.me.active='alt';await c.photoAlbumShareSend();assert.equal(sent.length,1);});
 test(base+'album send storage failure does not call role hooks or vision and remains retryable',async()=>{const {c,S}=shareFixture();let calls=0;c.pushMsg=()=>calls++;c.runVisionForMessage=async()=>{calls++;return true};c.saveNowAsync=async()=>false;c.photoAlbumSelectionToggle();c.photoAlbumPick(0);c.photoAlbumShareOpen();c.photoAlbumShareTarget(0);await c.photoAlbumShareSend();assert.equal(S.messages['R#main'].length,0);assert.equal(calls,0);assert.match(vm.runInContext('_photoAlbumShare.status',c),/未发送 1/);assert.equal(vm.runInContext('_photoAlbumShare.busy',c),false);});
 test(base+'group photo preview includes factual description and group image display supports original viewer',()=>{const app=fs.readFileSync(base+'app.js','utf8');const f=app.match(/function gmText\(m\)\{[^\n]+/)[0],c=vm.createContext({});vm.runInContext(f,c);assert.equal(c.gmText({type:'image',desc:'城市风景'}),'[图片] 城市风景');assert.equal(c.gmText({type:'text',content:'unchanged'}),'unchanged');assert.match(app,/else if\(m.type==='image'\)inner=`<div class="imagemsg"/);});
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const source=fs.readFileSync(base+'photo-album.js','utf8');
 const searchFixture=()=>{const items=[{id:'jan',name:'一月',src:'jan.jpg',category:'旅程',location:'上海',takenAt:'2026-01-02T11:00'}, {id:'may',name:'五月',src:'may.jpg',category:'旅程',location:'杭州',takenAt:'2026-05-03T23:10-07:00'}, {id:'old',src:'old.jpg',category:'旅程',takenAt:'2025-05-03T11:00'}, {id:'unknown',src:'unknown.jpg',category:'旅程',uploadedAt:Date.parse('2026-05-03')}, {id:'alt',src:'secret.jpg',accountId:'other',takenAt:'2026-05-03T11:00'}];const c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items}},esc:String,storedImageElementSource:s=>s,render(){},toast(){},save(){},saveNowAsync:async()=>true,imgDel:async()=>{},document:{querySelector:()=>null}});vm.runInContext(source,c);return c;};
 test(base+'search combines capture dates and categories without upload-time fallback or account leaks',()=>{const c=searchFixture();c.photoAlbumSearchOpen();for(const [q,ids] of [['五月份',['may','old']],['2026年旅程',['jan','may']],['2026年5月3日',['may']],['2026-05-03',['may']],['2026/05',['may']],['2026年 杭州',['may']],['2026年 春',['may']],['13月份',[]]]){c.photoAlbumSearchSubmit(q);assert.deepEqual(Array.from(c.photoAlbumSearchRows(),r=>r.id),ids,q);}assert.equal(c.photoAlbumSearchMatch({src:'x',location:'夏威夷'},'夏威夷'),true);assert.equal(c.photoAlbumDateParts({takenAt:'2026-02-30T11:00'}),null);});
 test(base+'clearing bounded search history preserves photos, other account history, and viewer returns to search',()=>{const c=searchFixture(),items=c.S.photoAlbum.items;c.photoAlbumSearchOpen();for(let i=0;i<20;i++)c.photoAlbumSearchSubmit('query '+i);assert.equal(c.photoAlbumSearchPrefs().queries.length,12);c.photoAlbumSearchSubmit('五月份');c.photoAlbumSearchView(0);assert.match(c.renderPhotoAlbum(),/1 \/ 2/);c.photoAlbumClose();assert.match(c.renderPhotoAlbum(),/data-photo-album="search"/);c.photoAlbumSearchClearHistory();assert.equal(c.photoAlbumSearchPrefs().queries.length,0);assert.equal(c.S.photoAlbum.items,items);assert.equal(items.length,5);c.S.me.active='other';c.renderPhotoAlbum();assert.equal(c.photoAlbumSearchRows().length,0);assert.equal(c.photoAlbumSearchPrefs().queries.length,0);});
 test(base+'search selection maps filtered rows correctly after sorting and deletion preserves unmatched photos',async()=>{const c=searchFixture();c.photoAlbumSearchOpen();c.photoAlbumSearchSubmit('2026年5月');c.photoAlbumSearchSelectionToggle();c.photoAlbumSearchPick(0);assert.equal(vm.runInContext('Array.from(_photoAlbumSelection.rows)[0].id',c),'may');await c.photoAlbumSetSort('taken');assert.equal(vm.runInContext('Array.from(_photoAlbumSelection.rows)[0].id',c),'may');await c.photoAlbumDeleteSelected();assert.deepEqual(Array.from(c.S.photoAlbum.items,r=>r.id),['jan','old','unknown','alt']);assert.equal(c.photoAlbumSearchRows().length,0);assert.match(c.renderPhotoAlbum(),/没有符合条件/);c.photoAlbumSearchClose(true);assert.match(c.renderPhotoAlbum(),/data-photo-album="collections"/);});
 test(base+'recent projects use actual viewing or sharing and never invent editing history',()=>{const c=searchFixture();c.photoAlbumRecentMark(c.S.photoAlbum.items[1],'viewed');c.photoAlbumSearchOpen();c.photoAlbumSearchRecent('viewed');assert.deepEqual(Array.from(c.photoAlbumSearchRows(),r=>r.id),['may']);c.photoAlbumSearchRecent('edited');assert.equal(c.photoAlbumSearchRows().length,0);c.photoAlbumRecentMark(c.S.photoAlbum.items[0],'shared');c.photoAlbumSearchRecent('shared');assert.deepEqual(Array.from(c.photoAlbumSearchRows(),r=>r.id),['jan']);});
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(base+'collection popup picks the chosen category, cancels without upload, and blocks stale account selection',()=>{const source=fs.readFileSync(base+'photo-album.js','utf8');let clicks=0;const c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:[]}},render(){},esc:String,toast(){},document:{querySelector:()=>null,getElementById:id=>({click:()=>{assert.equal(id,'photo-album-category-file-2');clicks++;}})}});vm.runInContext(source,c);c.photoAlbumMenuToggle();const html=c.photoAlbumMenuHTML();assert.equal((html.match(/role="menuitem"/g)||[]).length,7);assert.match(html,/上传到人物与宠物/);assert.doesNotMatch(html,/全部显示|全部折叠|重新排序/);c.photoAlbumMenuPick(2);assert.equal(clicks,1);c.photoAlbumMenuChosen(2,{files:[]});assert.equal(vm.runInContext('_photoAlbumUpload',c),null);const original={name:'pet.jpg',type:'image/jpeg'};c.photoAlbumMenuChosen(2,{files:[original]});assert.equal(vm.runInContext('_photoAlbumUpload.category',c),'人物与宠物');assert.equal(vm.runInContext('_photoAlbumUpload.files[0]',c),original);c.photoAlbumUploadCancel();c.photoAlbumMenuToggle();c.S.me.active='other';c.photoAlbumMenuChosen(2,{files:[original]});assert.equal(vm.runInContext('_photoAlbumUpload',c),null);assert.equal(c.S.photoAlbum.items.length,0);});

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const source=fs.readFileSync(base+'photo-album.js','utf8'),app=fs.readFileSync(base+'app.js','utf8');
 const setup=()=>{const role={id:'lover',name:'林予',persona:'温柔'},S={me:{active:'main'},couple:{cid:'lover'},settings:{chat:{base:'https://external.example',key:'test'}},photoAlbum:{items:[]}},c=vm.createContext({S,console,Promise,Date,Blob,URL,Set,Map,uid:(()=>{let i=0;return()=>String(++i)})(),getC:id=>id===role.id?role:null,cur:()=>({p:'home'}),save(){},saveNowAsync:async()=>true,render(){},toast(){},coupleAlbumItems:()=>[],roleInterceptDiagnosticAction(){}});vm.runInContext(source,c);return {c,S,role};};
 test(base+'album permission defaults off and remains tied to current couple/account',()=>{const {c,S,role}=setup();assert.equal(c.photoAlbumCoupleAllowed(role),false);c.photoAlbumPermissionToggle();assert.equal(c.photoAlbumCoupleAllowed(role),true);S.couple.cid='other';assert.equal(c.photoAlbumCoupleAllowed(role),false);S.couple.cid='lover';S.me.active='second';assert.equal(c.photoAlbumCoupleAllowed(role),false);S.me.active='main';c.photoAlbumPermissionToggle();assert.equal(c.photoAlbumCoupleAllowed(role),false);});
 test(base+'role classifies a cat photo once, leaves comment and preserves source',async()=>{const {c,S,role}=setup();const photo={id:'photo1',src:'idb:original',desc:'一只猫',visionState:'success'};assert.equal(await c.photoAlbumRoleSave(role,photo,'好可爱'),false);c.photoAlbumPermissionToggle();assert.equal(await c.photoAlbumRoleSave(role,photo,'好可爱'),true);assert.equal(await c.photoAlbumRoleSave(role,photo,'想摸摸它'),true);assert.equal(S.photoAlbum.items.length,1);assert.equal(S.photoAlbum.items[0].src,photo.src);assert.equal(S.photoAlbum.items[0].category,'人物与宠物');assert.equal(S.photoAlbum.items[0].roleComment.text,'想摸摸它');assert.equal(S.photoAlbum.items[0].takenAt,null);c.saveNowAsync=async()=>false;assert.equal(await c.photoAlbumRoleSave(role,{...photo,id:'failed'},'不要假报成功'),false);assert.equal(S.photoAlbum.items.length,1);});
 test(base+'revocation rejects delayed model comment and missing external config sends no requests',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const row={id:'p',accountId:'main',src:'idb:x',desc:'湖面',visionState:'success'};S.photoAlbum.items.push(row);let finish,calls=0;c.chatAPI=()=>{calls++;return new Promise(r=>finish=r)};const pending=c.photoAlbumGenerateComment(row,role);await Promise.resolve();c.photoAlbumPermissionToggle();finish('想和你看湖');await pending;assert.equal(row.roleComment,undefined);c.photoAlbumPermissionToggle();delete S.settings.chat.key;await c.photoAlbumGenerateComment(row,role);assert.equal(calls,1);assert.equal(row.commentState,'failed');});
 test(base+'legacy photos import once with unknown capture time without deleting legacy records',()=>{const {c,S,role}=setup();const old=[{id:'old',source:'album',src:'idb:old',desc:'旧照片',time:42}];c.coupleAlbumItems=()=>old;c.photoAlbumImportLegacy(role);c.photoAlbumImportLegacy(role);assert.equal(S.photoAlbum.items.length,1);assert.equal(old.length,1);assert.equal(S.photoAlbum.items[0].takenAt,null);assert.equal(c.photoAlbumRolePrompt(role),'');S.photoAlbum.items=[];c.photoAlbumImportLegacy(role);assert.equal(S.photoAlbum.items.length,0,'deletion must not resurrect a migrated photo');});
 test(base+'album participates in launch guards and app control without role self-enabling photo access',()=>{assert.match(app,/album:..=>openApp\('album'\)/);assert.match(app,/travel:'小鱼旅行',album:'相册'/);assert.match(app,/if\(!row\|\|key==='albumAuth'\)return null/);assert.match(app,/album:'album',aiaccount:'album'/);assert.match(app,/content=await coupleAlbumConsumeSaveTag\(content,c/);assert.match(source,/function renderPhotoAlbum\(\)\{if\(typeof appLocked/);});
 test(base+'memory cards require authorized existing understood photos',()=>{const {c,S,role}=setup();const msgs=[];c.msgsForAccount=()=>msgs;S.photoAlbum.items.push({id:'p',accountId:'main',src:'idb:x',desc:'湖',visionState:'success'});c.photoAlbumConsumeMemory('[回忆相册|p|想再看这片湖]',role,{});assert.equal(msgs.length,0);c.photoAlbumPermissionToggle();c.photoAlbumTaken=()=>({date:'拍摄时间未知'});c.photoAlbumConsumeMemory('[回忆相册|wrong|无效]',role,{});assert.equal(msgs.length,0);c.photoAlbumConsumeMemory('[回忆相册|p|想再看这片湖]',role,{},'给我分享一张相册回忆');assert.equal(msgs.length,1);assert.equal(msgs[0].type,'albummemory');});
 test(base+'successful vision is persisted once across concurrent comments and later shares',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const row={id:'p',accountId:'main',src:'idb:x'};S.photoAlbum.items.push(row);let calls=0,finish;c.runVisionForMessage=async(id,m)=>{calls++;await new Promise(r=>finish=r);m.desc='小猫在窗边';m.visionState='success';return true};c.photoAlbumShareBlob=async()=>new Blob(['x']);c.visionPhotoSource=async()=> 'image';const one=c.photoAlbumEnsureVision(row,role.id),two=c.photoAlbumEnsureVision(row,role.id);assert.equal(calls,1);finish();assert.equal(await one,true);assert.equal(await two,true);assert.equal(await c.photoAlbumEnsureVision(row,role.id),true);assert.equal(calls,1);S.photoAlbum.items=[];assert.equal(await c.photoAlbumEnsureVision(row,role.id),false);});
 test(base+'album source is distinct from ordinary photos and role saving does not duplicate or invent photographer',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const row={id:'p',accountId:'main',src:'idb:x',uploadedBy:'me',category:'人物与宠物',desc:'猫',visionState:'success'};S.photoAlbum.items.push(row);assert.equal(c.photoAlbumChatSourceText({type:'image'}),'');const m={id:'sent',src:'data:x',role:'user',_albumShare:c.photoAlbumSourceSnapshot(row)};assert.equal(await c.photoAlbumRoleSave(role,m,'想留着'),true);assert.equal(S.photoAlbum.items.length,1);assert.equal(row.uploadedBy,'me');assert.equal(row.savedBy,role.id);const source=c.photoAlbumChatSourceText({_albumShare:c.photoAlbumSourceSnapshot(row)});assert.match(source,/林予曾保存/);assert.match(source,/用户上传/);assert.match(source,/不代表拍摄/);S.photoAlbum.items=[];assert.equal(await c.photoAlbumRoleSave(role,m,'已删除不可悄悄复原'),false);});
 test(base+'a batch sends one event and revoked or switched permission invalidates queued events',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const notes=[];c.featureEventNote=(k,n)=>n;c.scheduleFeatureReply=(id,n)=>notes.push(n);c.chatAPI=async()=> '很可爱';const rows=Array.from({length:4},(_,i)=>({id:'p'+i,accountId:'main',src:'idb:'+i,desc:'小猫',visionState:'success'}));S.photoAlbum.items.push(...rows);await c.photoAlbumQueueComments(rows,true);assert.equal(notes.length,1);assert.match(notes[0],/上传了 4 张/);assert.equal(rows.filter(r=>r.roleComment).length,4);assert.equal(c.photoAlbumEventNoteValid(notes[0],role.id,'main'),true);c.photoAlbumPermissionToggle();assert.equal(c.photoAlbumEventNoteValid(notes[0],role.id,'main'),false);c.photoAlbumNotifyOperation('delete',4,[]);assert.equal(notes.length,1);c.photoAlbumPermissionToggle();assert.equal(c.photoAlbumEventNoteValid(notes[0],role.id,'main'),false);assert.equal(c.photoAlbumEventNoteValid('普通聊天',role.id,'main'),true);});
 test(base+'memory sharing rejects unrelated topics, repeated spontaneous cards, and multiple cards in one response',()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const row={id:'p',accountId:'main',src:'idb:x',desc:'小猫',visionState:'success'};S.photoAlbum.items.push(row);const msgs=[];c.msgsForAccount=()=>msgs;c.photoAlbumTaken=()=>({date:'未知'});const tag='[回忆相册|p|想看这只小猫]';c.photoAlbumConsumeMemory(tag,role,{},'今天吃饭了吗');assert.equal(msgs.length,0);c.photoAlbumConsumeMemory(tag+tag,role,{},'给我分享相册回忆');assert.equal(msgs.length,1);c.photoAlbumConsumeMemory(tag,role,{},'小猫好可爱');assert.equal(msgs.length,1);c.photoAlbumConsumeMemory(tag,role,{},'[功能事件即时反应] 上传了照片');assert.equal(msgs.length,1);});

 test(base+'actual reply gates discard revoked album events without blocking ordinary chat',()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();let note;c.featureEventNote=(k,n)=>n;c.scheduleFeatureReply=(id,n)=>note=n;c.photoAlbumNotifyOperation('delete',3,[]);c._replyFeaturePending={k:[{note},{note:'正常事件'}]};c.replyStateKey=()=> 'k';c.actId=()=> 'main';c.deferAccountReply=()=>{throw Error('must not defer revoked event')};for(const name of ['featureEventQueueEntries','replyAccountChanged'])vm.runInContext(app.match(new RegExp('function '+name+'\\([^\\n]+'))[0],c);assert.equal(c.featureEventQueueEntries(role.id,'main').length,2);c.photoAlbumPermissionToggle();assert.equal(c.featureEventQueueEntries(role.id,'main').length,1);let removed=false;assert.equal(c.replyAccountChanged(role.id,note,null,'main',{isConnected:true,remove(){removed=true}}),true);assert.equal(removed,true);assert.equal(c.replyAccountChanged(role.id,'普通聊天',null,'main'),false);});

 test(base+'role category tags select only existing groups, unknown images are not guessed',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();assert.equal(c.photoAlbumRoleCategory({desc:'热狗配番茄酱',visionState:'success'}),'共享相簿');assert.equal(c.photoAlbumRoleCategory({desc:'一只小猫',visionState:'failed'}),'共享相簿');assert.equal(await c.photoAlbumRoleSave(role,{id:'trip',role:'assistant',src:'idb:t',desc:'海边景色',visionState:'success'},'好想去','旅程'),true);assert.equal(S.photoAlbum.items[0].category,'旅程');assert.equal(S.photoAlbum.items[0].uploadedBy,role.id);assert.equal(await c.photoAlbumRoleSave(role,{id:'trip',src:'idb:t'},'再看一眼','回忆'),true);assert.equal(S.photoAlbum.items[0].category,'旅程','saving again must not relocate an existing photo');assert.equal(c.photoAlbumRoleCategory({desc:'一只小猫',visionState:'success'},'不存在的分组'),'人物与宠物');});
 test(base+'manual move preserves original, vision, comment and provenance; storage failure rolls back and stale account does not move',async()=>{const {c,S}=setup();const row={id:'p',accountId:'main',src:'album:original',thumbSrc:'album:thumb',category:'共享相簿',categories:['共享相簿','回忆'],desc:'小猫',visionState:'success',roleComment:{roleId:'lover',text:'可爱'},savedBy:'lover'};S.photoAlbum.items.push(row);assert.equal(await c.photoAlbumMove(row,'人物与宠物','main'),true);assert.equal(row.category,'人物与宠物');assert.equal(row.categories,undefined);assert.equal(row.categoryBy,'user');assert.equal(row.src,'album:original');assert.equal(row.desc,'小猫');assert.equal(row.roleComment.text,'可爱');assert.equal(row.savedBy,'lover');c.saveNowAsync=async()=>false;assert.equal(await c.photoAlbumMove(row,'旅程','main'),false);assert.equal(row.category,'人物与宠物');assert.equal(await c.photoAlbumMove(row,'不存在','main'),false);S.me.active='other';assert.equal(await c.photoAlbumMove(row,'回忆','main'),false);assert.equal(row.category,'人物与宠物');});
 test(base+'moving a role saved picture is respected on later saves and updates current role knowledge once',async()=>{const {c,S,role}=setup();c.photoAlbumPermissionToggle();const row={id:'p',accountId:'main',src:'idb:x',category:'人物与宠物',desc:'小猫',visionState:'success'};S.photoAlbum.items.push(row);const notes=[];c.featureEventNote=(k,n)=>n;c.scheduleFeatureReply=(id,n)=>notes.push(n);assert.equal(await c.photoAlbumMove(row,'精选照片','main'),true);assert.equal(notes.length,1);assert.match(notes[0],/重新分类到：精选照片/);assert.match(c.photoAlbumRolePrompt(role),/"category":"精选照片"/);assert.equal(await c.photoAlbumRoleSave(role,{id:'forward',role:'user',src:'data:x',_albumShare:c.photoAlbumSourceSnapshot(row)},'留着','人物与宠物'),true);assert.equal(row.category,'精选照片');assert.equal(S.photoAlbum.items.length,1);});
 test(base+'long press cancels before activation when ordinary scrolling starts',()=>{const {c,S}=setup();let timerCleared=0;c.setTimeout=()=> 9;c.clearTimeout=()=>timerCleared++;const row={id:'p',accountId:'main',src:'idb:x'};S.photoAlbum.items.push(row);const tile={dataset:{photoMoveId:'p'}};c.photoAlbumDragStart({target:{closest:()=>tile}},{clientX:50,clientY:50});c.photoAlbumDragMove({preventDefault(){throw Error('ordinary scroll must remain native')},stopPropagation(){}},{clientX:50,clientY:80});assert.equal(timerCleared,1);assert.equal(vm.runInContext('_photoAlbumHold',c),null);});
 test(base+'actual role command parser accepts category+comment and keeps old save tags compatible',async()=>{const {c,role}=setup();const calls=[];c.coupleAlbumSaveRecent=async(r,text,category)=>{calls.push({text,category});return true};vm.runInContext(app.match(/async function coupleAlbumConsumeSaveTag\([^\n]+/)[0],c);assert.equal(await c.coupleAlbumConsumeSaveTag('好看[存共同相册|人物与宠物|好可爱]',role,{}),'好看');assert.equal(calls[0].category,'人物与宠物');assert.equal(calls[0].text,'好可爱');await c.coupleAlbumConsumeSaveTag('[存共同相册|我想留着]',role,{});assert.equal(calls[1].text,'我想留着');assert.equal(calls[1].category,undefined);});

 test(base+'releasing outside a group leaves a clickable picker and stops intercepting normal pointer motion',()=>{const {c,S}=setup();S.photoAlbum.items.push({id:'p',accountId:'main',src:'idb:x'});c.document={elementFromPoint:()=>null};vm.runInContext("_photoAlbumDrag={row:S.photoAlbum.items[0],owner:'main',host:{isConnected:true},active:true,ghost:{style:{}}}",c);c.photoAlbumDragEnd({preventDefault(){},stopPropagation(){}},{clientX:10,clientY:10},false);assert.equal(vm.runInContext('_photoAlbumDrag.active',c),false);c.photoAlbumDragMove({preventDefault(){throw Error('released picker must not steal native motion')},stopPropagation(){}},{clientX:15,clientY:15});});

}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const source=fs.readFileSync(base+'app.js','utf8').replace(/\r\n/g,'\n');
 const extract=name=>{const start=source.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert(start>=0,name);const rest=source.slice(start),next=rest.slice(1).search(/\n(?:async )?function /);return next<0?rest:rest.slice(0,next+1);};
 test(base+'album original and thumbnail survive file/cloud backup without mutating live state; missing assets fail explicitly',async()=>{
  const bytes=Buffer.from([0,255,13,10,129,64]),store=new Map([['__album_photo_a',new Blob([bytes],{type:'image/png'})],['__album_photo_a_thumb',new Blob(['thumb'],{type:'image/jpeg'})]]);
  class Reader{readAsDataURL(blob){blob.arrayBuffer().then(b=>{this.result='data:'+blob.type+';base64,'+Buffer.from(b).toString('base64');this.onload();},()=>this.onerror());}}
  const S={settings:{},me:{},photoAlbum:{items:[{src:'album:__album_photo_a',thumbSrc:'album:__album_photo_a_thumb',desc:'缓存画面',roleComment:{text:'留言'},categoryBy:'user'}]}};
  const c=vm.createContext({S,Blob,FileReader:Reader,Set,WeakSet,TextEncoder,TextDecoder,Date,performance,setTimeout,_bootImagesPromise:null,imgGet:async k=>store.get(k),imageRefKeys:()=>[],imgMany:async()=>({}),_rehydrateWithCache(){}});
  for(const n of ['albumBackupHasRefs','albumBackupImage','albumBackupHydrate','fullBackupState','backupJsonBlob','fullBackupFileBlob','readBackupJson'])vm.runInContext(extract(n),c);
  const snapshot=await c.fullBackupState(),file=await c.fullBackupFileBlob(),restored=await c.readBackupJson(file);
  for(const value of [snapshot,restored]){const row=value.photoAlbum.items[0];assert.deepEqual(Buffer.from(row.src.split(',')[1],'base64'),bytes);assert.equal(Buffer.from(row.thumbSrc.split(',')[1],'base64').toString(),'thumb');assert.equal(row.desc,'缓存画面');assert.equal(row.roleComment.text,'留言');assert.equal(row.categoryBy,'user');assert.doesNotMatch(JSON.stringify(value),/album:__album/);}
  assert.equal(S.photoAlbum.items[0].src,'album:__album_photo_a','backup cannot rewrite live references');
  store.delete('__album_photo_a');await assert.rejects(c.fullBackupState(),/原文件缺失/);await assert.rejects(c.fullBackupFileBlob(),/原文件缺失/);
 });
 test(base+'storage GC retains reserved album assets while existing chat references and importer pins remain protected',()=>{
  assert.match(extract('imgGC'),/key\.indexOf\('__'\)===0/);assert.match(extract('imgUsedKeys'),/_backupImportPins/);assert.match(extract('readJsonFile'),/await imgPut\(key,s\)/);assert.match(extract('applyFullBackupData'),/await prepareImportedStateForSave\(\)/);
 });
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 test(base+'photo metadata editor saves dates and location without touching image/vision/provenance; failed storage rolls back',async()=>{
 const row={id:'p',accountId:'main',src:'album:original',thumbSrc:'album:thumb',category:'人物与宠物',desc:'猫',visionState:'success',roleComment:{text:'喜欢'},savedBy:'role',capturedAt:'2026-10-01T07:00'},S={me:{active:'main'},photoAlbum:{items:[row]}};
 const c=vm.createContext({S,Set,Map,Date,URL,Blob,esc:s=>s,toast(){},render(){},document:{querySelector:()=>null},saveNowAsync:async()=>true});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);vm.runInContext('_photoAlbumViewer={rows:S.photoAlbum.items,index:0}',c);
 const error={textContent:''},done={disabled:false},form={elements:{date:{value:'2026-10-05'},time:{value:'08:31'},location:{value:'家里'},title:{value:'小猫'}},querySelector:s=>s==='.photo-meta-error'?error:done};c.photoAlbumEditOpen();c.photoAlbumSelect=()=>{};await c.photoAlbumEditSave(form);assert.equal(row.takenAt,'2026-10-05T08:31');assert.equal(row.capturedAt,undefined);assert.equal(row.location,'家里');assert.equal(row.title,'小猫');assert.equal(row.src,'album:original');assert.equal(row.desc,'猫');assert.equal(row.savedBy,'role');assert.equal(row.roleComment.text,'喜欢');assert.equal(row.metadataBy,'user');
 c.photoAlbumEditOpen();form.elements.date.value='2026-02-30';await c.photoAlbumEditSave(form);assert.match(error.textContent,/有效/);assert.equal(row.takenAt,'2026-10-05T08:31');form.elements.date.value='2026-11-05';c.saveNowAsync=async()=>false;await c.photoAlbumEditSave(form);assert.equal(row.takenAt,'2026-10-05T08:31');assert.match(error.textContent,/保存失败/);S.me.active='other';await c.photoAlbumEditSave(form);assert.equal(row.takenAt,'2026-10-05T08:31');
 });
 test(base+'album rerender emits the already loaded original URL immediately',()=>{const c=vm.createContext({S:{me:{}},Set,Map,URL,esc:s=>s,document:{}});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);vm.runInContext("_photoAlbumUrls.set('__album_photo_a','blob:cached-original')",c);const html=c.photoAlbumImageHTML('album:__album_photo_a','猫');assert.match(html,/src="blob:cached-original"/);assert.match(html,/data-album-ref="__album_photo_a"/);});
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 const fixture=()=>{const role={id:'r',name:'林予',avatar:'头像'},row={id:'p',accountId:'main',src:'album:original',category:'旅程',desc:'小猫',visionState:'success'},S={me:{active:'main'},couple:{cid:'r',albumAuth:true,albumAuthCid:'r',albumAuthEpoch:1},photoAlbum:{items:[row]}},calls=[],c=vm.createContext({S,Date,URL,Blob,Set,Map,WeakSet,WeakMap,esc:String,getC:()=>role,save(){},saveNowAsync:async()=>true,toast(){},render(){},roleInterceptDiagnosticAction:(o,ok)=>calls.push(ok),msgsForAccount:()=>[],cur:()=>({p:'home'})});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);vm.runInContext('_photoAlbumViewer={rows:S.photoAlbum.items,index:0}',c);return {c,S,row,role,calls};};
 test(base+'favorites are derived from independent user and role likes, preserve original grouping and rollback failed saves',async()=>{const {c,S,row,role}=fixture();assert.equal(c.photoAlbumGroupRows('我的喜欢').length,0);assert.equal(await c.photoAlbumUserLike(),true);assert.equal(row.likedByMe,true);assert.equal(c.photoAlbumGroupRows('我的喜欢').length,1);assert.equal(c.photoAlbumGroupRows('旅程').length,1);assert.equal(await c.photoAlbumRoleLike(row,role),true);assert.equal(await c.photoAlbumUserLike(),true);assert.equal(row.likedByMe,false);assert.equal(c.photoAlbumHasLikes(row),true);assert.equal(c.photoAlbumGroupRows('我的喜欢').length,1);assert.equal(row.category,'旅程');assert.equal(row.src,'album:original');assert.equal(row.desc,'小猫');c.saveNowAsync=async()=>false;assert.equal(await c.photoAlbumUserLike(),false);assert.equal(row.likedByMe,false);S.me.active='other';assert.equal(c.photoAlbumGroupRows('我的喜欢').length,0);assert.equal(await c.photoAlbumUserLike(),false);});
 test(base+'role likes require current permission, cached vision and a real contextual occasion; revoke blocks late saves',async()=>{const {c,S,row,role,calls}=fixture();assert.equal(await c.photoAlbumConsumeLikes('好看[喜欢相册|p]',role,{},'今天吃饭了吗'),'好看');assert.equal(row.roleLikes,undefined);await c.photoAlbumConsumeLikes('[喜欢相册|p]',role,{},'[功能事件即时反应] 相册操作');assert.equal(row.roleLikes,undefined);await c.photoAlbumConsumeLikes('[喜欢相册|p]',role,{},'不要给照片点赞');assert.equal(row.roleLikes,undefined);await c.photoAlbumConsumeLikes('[喜欢相册|p]',role,{},'看看相册里你喜欢哪张照片');assert.equal(row.roleLikes.r.name,'林予');assert.equal(await c.photoAlbumRoleLike(row,role),false,'repeated decisions do not replace records');delete row.roleLikes.r;let complete;c.saveNowAsync=()=>new Promise(r=>complete=r);const pending=c.photoAlbumRoleLike(row,role);S.couple.albumAuth=false;S.couple.albumAuthEpoch++;complete(true);assert.equal(await pending,false);assert.equal(row.roleLikes.r,undefined);row.visionState='failed';assert.equal(await c.photoAlbumRoleLike(row,role),false);});
 test(base+'past album image cannot cause unsolicited likes, user and role saves can overlap, deleted photos stay absent',async()=>{const {c,S,row,role}=fixture();c.msgsForAccount=()=>[{role:'user',type:'image',_albumShare:{photoId:'p'}}];await c.photoAlbumConsumeLikes('[喜欢相册|p]',role,{},'');assert.equal(row.roleLikes,undefined);let release;c.saveNowAsync=()=>new Promise(r=>release=r);const user=c.photoAlbumUserLike();c.saveNowAsync=async()=>true;assert.equal(await c.photoAlbumRoleLike(row,role),true);release(true);assert.equal(await user,true);assert.equal(row.likedByMe,true);assert.equal(row.roleLikes.r.name,'林予');S.photoAlbum.items=[];assert.equal(await c.photoAlbumRoleLike(row,role),false);assert.equal(c.photoAlbumGroupRows('我的喜欢').length,0);await c.photoAlbumConsumeLikes('[喜欢相册|p]',role,{},'看看相册');assert.equal(S.photoAlbum.items.length,0);});
 test(base+'one comment call optionally likes the photo using its existing vision cache',async()=>{const {c,S,row,role}=fixture();S.settings={chat:{base:'external',key:'fixture'}};let requests=0;c.photoAlbumEnsureVision=async()=>true;c.chatAPI=async()=>{requests++;return '这只小猫真可爱。[喜欢照片]'};await c.photoAlbumGenerateComment(row,role);assert.equal(requests,1);assert.equal(row.roleComment.text,'这只小猫真可爱。');assert.equal(row.roleLikes.r.name,'林予');assert.equal(row.desc,'小猫');});
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 test(base+'viewer category picker uses existing move, retains likes and metadata, avoids rerender and supports failed save retry',async()=>{
 const row={id:'p',accountId:'main',src:'album:original',thumbSrc:'album:thumb',category:'回忆',desc:'猫',visionState:'success',likedByMe:true,roleLikes:{r:{time:1,name:'林予'}},roleComment:{text:'好可爱'},takenAt:'2026-10-05T08:31',location:'家里'},S={me:{active:'main'},photoAlbum:{items:[row]}};let renders=0,removed=0;const c=vm.createContext({S,Date,URL,Blob,Set,Map,WeakSet,esc:String,toast(){},save(){},saveNowAsync:async()=>true,render(){renders++},cur:()=>({p:'album'}),document:{querySelector:()=>({insertAdjacentHTML(){},remove(){removed++}})}});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);vm.runInContext('_photoAlbumViewer={rows:S.photoAlbum.items,index:0}',c);
 c.photoAlbumEditOpen('category');assert.match(c.photoAlbumEditHTML(),/当前分类：回忆/);assert.doesNotMatch(c.photoAlbumEditHTML(),/value="我的喜欢"/);const error={textContent:''},button={disabled:false},form={elements:{category:{value:'旅程'}},querySelector:x=>x==='.photo-meta-error'?error:button};await c.photoAlbumCategorySave(form);assert.equal(row.category,'旅程');assert.equal(renders,0);assert.equal(removed,1);assert.equal(row.src,'album:original');assert.equal(row.roleComment.text,'好可爱');assert.equal(row.roleLikes.r.name,'林予');assert.equal(row.likedByMe,true);assert.equal(row.takenAt,'2026-10-05T08:31');assert.equal(row.location,'家里');
 c.photoAlbumEditOpen('category');form.elements.category.value='人物与宠物';c.saveNowAsync=async()=>false;await c.photoAlbumCategorySave(form);assert.equal(row.category,'旅程');assert.match(error.textContent,/未保存/);assert.equal(button.disabled,false);c.saveNowAsync=async()=>true;S.me.active='other';await c.photoAlbumCategorySave(form);assert.equal(row.category,'旅程');S.me.active='main';await c.photoAlbumCategorySave(form);assert.equal(row.category,'人物与宠物');assert.equal(renders,0);
 });
}

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(base+'viewer trash deletes only the current photo, rolls back failed saves and returns after the last photo',async()=>{const a={id:'a',src:'album:__album_photo_a',category:'回忆',likedByMe:true},b={id:'b',src:'b.jpg',category:'回忆'},other={id:'other',src:'other.jpg',accountId:'other'};let good=false,release;const deleted=[],c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:[a,b,other]}},esc:String,storedImageElementSource:s=>s,render(){},toast(){},document:{querySelector:()=>null},saveNowAsync:async()=>good,imgDel:async k=>deleted.push(k)});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);c.photoAlbumOpen(0,'回忆');assert.match(c.renderPhotoAlbum(),/onclick="photoAlbumDeleteCurrent\(\)"/);await c.photoAlbumDeleteCurrent();assert.equal(c.S.photoAlbum.items.length,3);assert.equal(deleted.length,0);assert.equal(vm.runInContext('_photoAlbumViewer.rows[_photoAlbumViewer.index].id',c),'a');good=true;c.saveNowAsync=()=>new Promise(r=>release=r);const pending=c.photoAlbumDeleteCurrent();await c.photoAlbumDeleteCurrent();release(true);await pending;assert.deepEqual(Array.from(c.S.photoAlbum.items,r=>r.id),['b','other']);assert.deepEqual(deleted,[]);assert.equal(c.S.photoAlbum.deletedItems[0].row,a);assert.equal(vm.runInContext('_photoAlbumViewer.rows[_photoAlbumViewer.index].id',c),'b');assert.equal(c.photoAlbumGroupRows('我的喜欢').length,0);c.saveNowAsync=async()=>true;c.S.me.active='other';await c.photoAlbumDeleteCurrent();assert.equal(c.S.photoAlbum.items.length,2);c.S.me.active='main';await c.photoAlbumDeleteCurrent();assert.deepEqual(Array.from(c.S.photoAlbum.items,r=>r.id),['other']);assert.equal(vm.runInContext('_photoAlbumViewer',c),null);assert.match(c.renderPhotoAlbum(),/data-photo-album="library"/);});

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(base+'deleted photo notice snapshots known facts before removal, merges batches and respects permission and storage gates',async()=>{const role={id:'lover'},known={id:'cat',accountId:'main',src:'cat.jpg',title:'猫咪',category:'人物与宠物',takenAt:'2026-10-05T11:00',location:'北京',desc:'一只眯眼的小猫',visionState:'success'},unknown={id:'sea',src:'sea.jpg',title:'海边',category:'旅程',desc:'不能使用的失败识别内容',visionState:'failed'},hidden={id:'hidden',src:'hidden.jpg',coupleRoleId:'old-lover',title:'旧情侣私密标题',desc:'旧情侣私密画面',visionState:'success'},other={id:'alt',src:'alt.jpg',accountId:'other',title:'其他账号私密标题'},notes=[];const S={me:{active:'main'},couple:{cid:'lover',albumAuth:true,albumAuthCid:'lover'},photoAlbum:{items:[known,unknown,hidden,other]}};let good=false,release;const c=vm.createContext({S,esc:String,storedImageElementSource:s=>s,getC:id=>id==='lover'?role:null,uid:()=>String(notes.length),featureEventNote:(k,n)=>n,scheduleFeatureReply:(id,n)=>notes.push(n),render(){},toast(){},document:{querySelector:()=>null},saveNowAsync:async()=>good,imgDel:async()=>{},runVisionForMessage(){throw Error('deletion must not recognize images')}});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);const state={owner:'main',rows:new Set([known,unknown,hidden,other])};await c.photoAlbumDeleteSelected(state);assert.equal(notes.length,0);assert.equal(S.photoAlbum.items.length,4);good=true;c.saveNowAsync=()=>new Promise(r=>release=r);const pending=c.photoAlbumDeleteSelected(state);known.desc='删除过程中变动的描述';release(true);await pending;assert.equal(notes.length,1);assert.match(notes[0],/删除了 3 张/);assert.match(notes[0],/猫咪/);assert.match(notes[0],/一只眯眼的小猫/);assert.match(notes[0],/人物与宠物/);assert.match(notes[0],/2026-10-05T11:00/);assert.match(notes[0],/北京/);assert.match(notes[0],/海边/);assert.doesNotMatch(notes[0],/不能使用的失败识别内容|旧情侣私密|其他账号私密|删除过程中变动|cat.jpg|sea.jpg/);assert.equal(S.photoAlbum.items.length,1);assert.equal(c.photoAlbumRoleRows(role).length,0);const last={id:'last',src:'last.jpg',title:'不应通知'};S.photoAlbum.items.push(last);const revoked=c.photoAlbumDeleteSelected({owner:'main',rows:new Set([last])});S.couple.albumAuth=false;release(true);await revoked;assert.equal(notes.length,1);});

for(const base of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(base+'recently deleted restores intact rows, expires at exactly three days, isolates accounts and rolls back storage failure',async()=>{let now=1000,good=true;const deleted=[],notices=[],row={id:'p',src:'album:__album_photo_original',thumbSrc:'album:__album_photo_thumb',category:'人物与宠物',title:'小猫',desc:'小猫眯眼',visionState:'success',likedByMe:true,roleLikes:{lover:{name:'林予'}},roleComment:{text:'好可爱'}},other={id:'q',accountId:'other',src:'album:__album_photo_other'};const FakeDate=class extends Date{static now(){return now}},c=vm.createContext({S:{me:{active:'main'},photoAlbum:{items:[row,other]}},Date:FakeDate,esc:String,storedImageElementSource:s=>s,document:{querySelector:()=>null},render(){},toast(){},saveNowAsync:async()=>good,imgDel:async k=>deleted.push(k)});vm.runInContext(fs.readFileSync(base+'photo-album.js','utf8'),c);await c.photoAlbumDeleteSelected({owner:'main',rows:new Set([row,other])});assert.equal(c.S.photoAlbum.items.length,1);assert.equal(c.photoAlbumTrashRows().length,1);assert.equal(deleted.length,0);assert.equal(c.S.photoAlbum.deletedItems[0].expiresAt,1000+3*86400000);c.photoAlbumTrashOpen();c.photoAlbumTrashView(0);assert.match(c.renderPhotoAlbum(),/恢复照片/);good=false;await c.photoAlbumTrashRestore();assert.equal(c.S.photoAlbum.items.length,1);assert.equal(c.photoAlbumTrashRows().length,1);good=true;await c.photoAlbumTrashRestore();assert.equal(c.S.photoAlbum.items[1],row);assert.equal(row.roleComment.text,'好可爱');assert.equal(row.likedByMe,true);assert.equal(row.roleLikes.lover.name,'林予');assert.equal(c.photoAlbumTrashRows().length,0);await c.photoAlbumDeleteSelected({owner:'main',rows:new Set([row])});now=1000+3*86400000-1;assert.equal(c.photoAlbumTrashRows().length,1);await c.photoAlbumTrashExpire();assert.equal(deleted.length,0);now++;assert.equal(c.photoAlbumTrashRows().length,0);good=false;await c.photoAlbumTrashExpire();assert.equal(c.S.photoAlbum.deletedItems.length,1);assert.equal(deleted.length,0);good=true;await c.photoAlbumTrashExpire();assert.equal(c.S.photoAlbum.deletedItems.length,0);assert.deepEqual(deleted,['__album_photo_original','__album_photo_thumb']);assert.equal(c.S.photoAlbum.items[0],other);c.S.me.active='other';await c.photoAlbumDeleteSelected({owner:'other',rows:new Set([other])});c.S.me.active='main';now+=3*86400000;await c.photoAlbumTrashExpire();assert.equal(c.S.photoAlbum.deletedItems.length,1);c.S.me.active='other';await c.photoAlbumTrashExpire();assert.equal(c.S.photoAlbum.deletedItems.length,0);assert.equal(deleted.at(-1),'__album_photo_other');});
