import vm from 'node:vm';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const source = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../小手机.html', import.meta.url), 'utf8');

test('calendar follows the local day and supports month navigation and date location', () => {
  assert.match(source, /function calEnsure\(\)[\s\S]*todayStr\(\)/);
  assert.match(source, /function calShift\(step\)/);
  assert.match(source, /function calToday\(\)/);
  assert.match(source, /function calLocate\(\)/);
  assert.match(source, /function calLocateGo\(\)/);
  assert.match(source, /function calMonthRows\(month\)/);
  assert.match(source, /for\(let m=1;m<=12;m\+\+\)/);
});

test('calendar has a real month grid without the old visible system notice', () => {
  const start = source.indexOf('function calMonthSection(');
  const end = source.indexOf('function addCalEvent(', start);
  const renderSource = source.slice(start, end);
  assert.match(renderSource, /cal-week/);
  assert.match(renderSource, /cal-grid/);
  assert.match(renderSource, /cal-agenda/);
  assert.doesNotMatch(renderSource, /你和ta都能加日程/);
  assert.doesNotMatch(renderSource, /节假日ta会发红包祝福/);
  assert.match(html, /\.cal-card\{/);
  assert.match(html, /\.cal-day\.today/);
});

test('browser presents a Baidu-style home and structured result view', () => {
  const start = source.indexOf('function renderBrowser(');
  const end = source.indexOf('async function browserModelSearch', start);
  const renderSource = source.slice(start, end);
  assert.match(renderSource, /br-logo/);
  assert.match(renderSource, /百度热搜/);
  assert.match(renderSource, /br-result/);
  assert.match(renderSource, /百度一下/);
  assert.match(html, /\.br-search\{/);
  assert.match(html, /\.br-result\{/);
});

test('non-drawing games use themed rooms, compact controls and line icons', () => {
  const start = source.indexOf('function renderGS()');
  const end = source.indexOf('function gsExit()', start);
  const renderSource = source.slice(start, end);
  assert.match(renderSource, /gs-theme-/);
  assert.match(renderSource, /gs-score/);
  assert.match(renderSource, /gs-compose/);
  assert.match(renderSource, /_gs\.kind==='tod'/);
  assert.doesNotMatch(renderSource, /🎲|⚡|💑|🎭/);
  assert.match(source, /function renderUC\(\)[\s\S]*uc-room/);
  assert.match(html, /\.gs-room\{/);
  assert.match(html, /\.uc-room\{/);
});

function calendarVM(){const ctx={S:{calendar:[],periods:[],me:{active:'main'}},actId:()=> 'main',Date,Intl,Map,Number,todayStr:()=> '2026-10-08',esc:String,toast(){},render(){},_calSelected:'2026-10-01'};vm.createContext(ctx);for(const name of ['calParticipation','calParticipationLabel','calRoleCanRemind','calRoleParticipationConsume','calCareWindow','calCareValid','calUndatedReminders','calUndatedReminderHTML','calReminderAgendaRow','roleCalDateValid','calOccurrenceStarts','calExpandedEvents','calAttr','calCall','calCollections','calCollection','calPrefs','calEventOwned','calEventVisible','calDateParts','calDateString','calUtcValue','calDayDiff','calAddDays','calMonthName','calMonthRows','calRowHeight','calMonthHeight','calLunarLabel','calEventsByYear','calIcon','calTimeValue','calEventColor','calAgendaHTML','calMonthSection','periodStore','periodNormalize','periodRecords','periodEffectiveEnd']){const line=source.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'('));assert(line,name);vm.runInContext(line,ctx);}vm.runInContext('let _calLunarFormatter=null,_calLunarUnavailable=false;const _calLunarLabels=new Map();',ctx);return ctx;}
test('month page uses Monday alignment, real month lengths and authentic lunar labels',()=>{const c=calendarVM();assert.equal(c.calMonthRows('2026-10'),5);assert.equal(c.calMonthRows('2028-02'),5);for(let m=1;m<=12;m++){const month='2026-'+String(m).padStart(2,'0'),h=c.calMonthSection(month,{},'2026-10-08');assert.equal((h.match(/data-cal-date=/g)||[]).length,new Date(2026,m,0).getDate());assert.doesNotMatch(h,/cal-dot/);}assert.equal(c.calLunarLabel('2026-10-01').text,'廿一');assert.equal(c.calLunarLabel('2026-10-08').text,'廿八');assert.equal(c.calLunarLabel('2026-10-10').text,'九月');assert.equal(c.calLunarLabel('2026-10-10').monthStart,true);});
test('calendar agenda and dots only follow saved real events and period spans',()=>{const c=calendarVM();c.S.calendar=[{id:'event',date:'2026-10-08',title:'目标自省',time:'05:00',endTime:'05:30',location:'家'},{id:'wedding',date:'2026-10-11',title:'婚礼约定',type:'wedding',time:'19:00'}];c.S.periods=[{id:'period',startDate:'2026-10-05',endDate:'2026-10-07'}];const before=JSON.stringify(c.S),byDate=c.calEventsByYear(2026),empty=c.calAgendaHTML('2026-10-01',byDate),day=c.calAgendaHTML('2026-10-08',byDate);assert.match(empty,/无日程/);assert.match(day,/目标自省/);assert.match(day,/05:00/);assert.match(day,/05:30/);assert.match(day,/位置：家/);assert.equal(byDate['2026-10-06'][0]._periodDay,2);assert.equal(byDate['2026-10-11'][0].type,'wedding');assert.equal(JSON.stringify(c.S),before);const h=c.calMonthSection('2026-10',byDate,'2026-10-08');assert.equal((h.match(/class="cal-dot/g)||[]).length,5);});

test('year overview has authentic 12-month grids, lunar-year names, red current/selected years and no data writes',()=>{const c=calendarVM();for(const name of ['calYearName','calYearMonthHTML','calYearSection','calYearPick','calYearOpenMonth','calInputClock','calSelect']){const line=source.split('\n').find(x=>x.startsWith('function '+name+'('));assert(line,name);vm.runInContext(line,c);}vm.runInContext('const CAL_YEAR_MIN=1900,CAL_YEAR_MAX=2100;let _calYearSelected=2026,_calYearCenter=2026,_calYearView=true,_calMonth="2026-10",_calIgnoreClickUntil=0;',c);const before=JSON.stringify(c.S);assert.equal(c.calYearName(2026),'丙午马年');assert.equal(c.calYearName(2027),'丁未羊年');const y=c.calYearSection(2027);assert.equal((y.match(/data-cal-year-month=/g)||[]).length,12);assert.equal((y.match(/data-cal-year-date=/g)||[]).length,365);assert.match(c.calYearSection(2026),/cal-year-title cal-year-red/);assert.doesNotMatch(y,/cal-year-title cal-year-red/);c.calYearPick(2027);assert.match(c.calYearSection(2027),/cal-year-title cal-year-red/);c.calYearOpenMonth(2028,2,{target:{closest:()=>({dataset:{calYearDate:'2028-02-29'}})}});assert.equal(c._calSelected,'2028-02-29');assert.equal(JSON.stringify(c.S),before);assert.equal((c.calYearSection(1900).match(/data-cal-year-date=/g)||[]).length,365);assert.equal((c.calYearSection(2000).match(/data-cal-year-date=/g)||[]).length,366);});


test('calendar collections enforce visibility, alert and character permissions independently',()=>{const c=calendarVM();for(const name of ['calRepeatLabel','calEventFact','calRoleEvents','calRoleSharedText','calEventAlerts','calShareAllowed','calShareText']){vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);}c.S.calendarCollections=[{id:'private',owner:'main',name:'私人',color:'#ff453a',visible:true,alerts:true,sharedWith:[]},{id:'shared',owner:'main',name:'一起出游',color:'#009aff',visible:true,alerts:true,sharedWith:['a']},{id:'other',owner:'other',name:'他账户',sharedWith:['a']}];c.S.calendar=[{id:'old',date:'2026-10-08',title:'旧日程'},{id:'p',calendarId:'private',date:'2026-10-08',title:'秘密',contactId:'a'},{id:'s',calendarId:'shared',date:'2026-10-08',title:'一起看电影',contactId:'a'},{id:'o',calendarId:'other',date:'2026-10-08',title:'另一账户'}];assert.deepEqual(Array.from(c.calRoleEvents('a'),x=>x.id),['old','s']);assert.deepEqual(Array.from(c.calRoleEvents('b'),x=>x.id),['old']);assert.doesNotMatch(c.calRoleSharedText('a'),/秘密|他账户|另一账户/);assert.equal(c.calEventAlerts(c.S.calendar[1]),false);assert.equal(c.calEventAlerts(c.S.calendar[2]),true);c.S.calendarCollections[1].visible=false;assert.equal(c.calEventsByYear(2026)['2026-10-08'].length,2);assert.equal(c.calRoleEvents('a').length,2);c.S.calendarCollections[1].alerts=false;assert.equal(c.calEventAlerts(c.S.calendar[2]),false);const card={calendarId:'shared',calendarOwner:'main',calendarRecipient:'a'};assert.match(c.calShareText(card),/一起看电影/);c.S.calendarCollections[1].sharedWith=[];assert.equal(c.calShareAllowed(card),false);assert.doesNotMatch(c.calShareText(card),/一起看电影/);assert.equal(c.calRoleEvents('a').length,1);c.S.calendar.push({id:'done',date:'2026-10-08',title:'完成的提醒',type:'reminder',completed:true});c.S.calendarPreferences={main:{showCompleted:false}};assert.equal(c.calEventVisible(c.S.calendar.at(-1)),false);});


test('role calendar sharing records only its own entries, deduplicates retries and rolls back failed saves',async()=>{const c=calendarVM(),role={id:'a',name:'A'};Object.assign(c,{getC:id=>id==='a'?role:null,uid:(()=>{let i=0;return()=> 'id'+(++i);})(),actId:()=>c.S.me.active,NORTH_PREVIEW:true,notifyIncoming(){},cur:()=>({p:'home'}),refreshChatMessages(){},calPersist:async()=>true});c.S.messages={};c.msgs=id=>c.S.messages[id]||(c.S.messages[id]=[]);c.accountMessageKey=id=>id;for(const name of ['calRollbackCards','roleCalRows','roleCalDateValid','roleCalCardRows','roleCalShareText'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);vm.runInContext(source.split('\n').find(x=>x.startsWith('async function roleCalConsume(')),c);const before=JSON.stringify(c.S.calendar);assert.equal((await c.roleCalConsume('[分享我的日程|2026-10-08]',role,'empty')).changed,false);assert.equal((await c.roleCalConsume('[我的日程|2026-02-30|14:00|无效日期]',role,'bad')).changed,false);const result=await c.roleCalConsume('[我的日程|2026-10-08|14:00|书店]\n[分享我的日程|2026-10-08]',role,'one');assert.equal(result.sent,1);assert.equal(c.S.roleCalendar.length,1);assert.equal(c.S.messages.a.length,1);assert.equal(JSON.stringify(c.S.calendar),before);await c.roleCalConsume('[分享我的日程|2026-10-08]',role,'one');assert.equal(c.S.messages.a.length,1);await c.roleCalConsume('[分享我的日程|2026-10-08]',role,'two');assert.equal(c.S.messages.a.length,2);assert.match(c.roleCalShareText(c.S.messages.a[0]),/书店/);c.S.me.active='other';assert.equal(c.roleCalRows('a').length,0);assert.doesNotMatch(c.roleCalShareText(c.S.messages.a[0]),/书店/);c.S.me.active='main';const snapshot=JSON.stringify(c.S);c.calPersist=async()=>false;await c.roleCalConsume('[我的日程|2026-10-09|全天|旅行]\n[分享我的日程|2026-10-09]',role,'fail');assert.equal(JSON.stringify(c.S),snapshot);c.calPersist=async()=>{c.msgs('a').push({id:'unrelated',type:'text',content:'并发到达的消息'});return false;};await c.roleCalConsume('[我的日程|2026-10-10|全天|新计划]\n[分享我的日程|2026-10-10]',role,'concurrent-fail');assert.equal(c.S.roleCalendar.length,1);assert.equal(c.S.messages.a.at(-1).content,'并发到达的消息');assert.equal(c.S.messages.a.filter(m=>m.type==='rolecalendarshare').length,2);});


test('custom label colors validate exact hex values and preserve RGB and spectrum conversion',()=>{const c=calendarVM();for(const name of ['calColorValue','calRgb','calRgbHex','calHsvHex','calHexHsv'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);assert.equal(c.calColorValue(' 7C6CF2 '),'#7c6cf2');for(const invalid of ['#123','#ffffff00','red','javascript:alert(1)','#12345g'])assert.equal(c.calColorValue(invalid),'');assert.equal(c.calRgbHex(124,108,242),'#7c6cf2');assert.equal(c.calHsvHex(0,1,1),'#ff0000');assert.equal(c.calHsvHex(120,1,1),'#00ff00');assert.equal(c.calHsvHex(240,1,1),'#0000ff');assert.equal(c.calHsvHex(180,0,1),'#ffffff');assert.equal(c.calHsvHex(260,1,0),'#000000');for(const hex of ['#7c6cf2','#ff9f0a','#b58255','#009aff','#30d158','#000000','#ffffff']){const hsv=c.calHexHsv(hex);assert.equal(c.calHsvHex(hsv.h,hsv.s,hsv.v),hex);}});


test('recurrence uses actual civil dates, skips nonexistent month/leap days and expands multi-day spans',()=>{const c=calendarVM();const event={id:'repeat',date:'2026-01-31',endDate:'2026-01-31',title:'月末',repeat:{unit:'month',interval:1}};assert.deepEqual(Array.from(c.calOccurrenceStarts(event,'2026-01-01','2026-05-31')),['2026-01-31','2026-03-31','2026-05-31']);event.date='2024-02-29';event.repeat={unit:'year',interval:1};assert.deepEqual(Array.from(c.calOccurrenceStarts(event,'2025-01-01','2028-12-31')),['2028-02-29']);event.date='2026-10-05';event.endDate='2026-10-06';event.repeat={unit:'week',interval:2,until:'2026-10-20'};assert.deepEqual(Array.from(c.calOccurrenceStarts(event,'2026-10-01','2026-11-30')),['2026-10-05','2026-10-19']);const rows=c.calExpandedEvents(event,'2026-10-01','2026-10-31');assert.deepEqual(Array.from(rows,e=>e.date),['2026-10-05','2026-10-06','2026-10-19','2026-10-20']);assert.equal(rows[2]._occurrenceDate,'2026-10-19');assert.equal(event.date,'2026-10-05');event.owner='other';assert.equal(c.calExpandedEvents(event,'2026-10-01','2026-10-31').length,0);});


test('new item alerts respect exact lead time, expiry, ownership, muted calendars and successful-save deduplication',async()=>{const c=calendarVM();Object.assign(c,{calPersist:async()=>true,actId:()=>c.S.me.active,toast:t=>c.notifications.push(t),playDing(){},notifications:[]});c.S.calendarCollections=[{id:'one',owner:'main',alerts:true}];for(const name of ['calEventLocalAt','calUserEventAlerts'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);vm.runInContext('let _calAlertBusy=false;',c);vm.runInContext(source.split('\n').find(x=>x.startsWith('async function calFireEventAlerts(')),c);const e={id:'a',owner:'main',editorVersion:1,title:'第一项',type:'event',date:'2099-01-10',endDate:'2099-01-10',time:'12:00',endTime:'13:00',calendarId:'one',alertMinutes:15,repeat:{unit:'none'}};c.S.calendar=[e];await c.calFireEventAlerts(new Date(2099,0,10,11,44,59).getTime());assert.equal(c.notifications.length,0);await c.calFireEventAlerts(new Date(2099,0,10,11,45).getTime());await c.calFireEventAlerts(new Date(2099,0,10,11,46).getTime());assert.equal(c.notifications.length,1);c.S.calendarAlertFired={};c.S.calendarCollections[0].alerts=false;await c.calFireEventAlerts(new Date(2099,0,10,11,45).getTime());assert.equal(c.notifications.length,1);c.S.calendarCollections[0].alerts=true;c.S.me.active='other';await c.calFireEventAlerts(new Date(2099,0,10,11,45).getTime());assert.equal(c.notifications.length,1);c.S.me.active='main';c.calPersist=async()=>false;await c.calFireEventAlerts(new Date(2099,0,10,11,45).getTime());assert.equal(Object.keys(c.S.calendarAlertFired).length,0);assert.equal(c.notifications.length,1);c.calPersist=async()=>true;c.S.calendar.push({...e,id:'b',title:'第二项'});await c.calFireEventAlerts(new Date(2099,0,10,11,45).getTime());assert.equal(c.notifications.length,2);assert.match(c.notifications.at(-1),/第一项.*第二项/);c.S.calendarAlertFired={};await c.calFireEventAlerts(new Date(2099,0,10,13,1).getTime());assert.equal(c.notifications.length,2);});


test('event invitations scope one event and retry only failed role reminders without crossing accounts or expiry',async()=>{const c=calendarVM(),D=Date;let now=new D(2099,0,10,11,44).getTime();c.Date=class extends D{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};const roles=[{id:'a',name:'甲'},{id:'b',name:'乙'},{id:'c',name:'丙'}];Object.assign(c,{actId:()=>c.S.me.active,isMain:()=>true,isBlk:()=>false,getC:id=>roles.find(x=>x.id===id),calPersist:async()=>true,roleOnlineProactiveBlocked:()=>false,queued:[]});c.S.contacts=roles;c.S.me.name='用户';c.scheduleFeatureReply=(id,note,delay,done,aid)=>{c.queued.push({id,note,done,aid});return true;};for(const name of ['calEventLocalAt','calRepeatLabel','calEventFact','calDepartureText','calInviteRoles','calInvitedEvent','featureEventNote','calInviteReminderNote','calInviteNoteValid','calFireInvitedReminders','calRoleEvents'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);vm.runInContext('let _calInvitedBusy={};',c);c.S.calendarCollections=[{id:'private',owner:'main',alerts:true,sharedWith:[]}];const e={id:'invite',owner:'main',editorVersion:1,type:'event',title:'去书店',notes:'逛完喝咖啡',date:'2099-01-10',endDate:'2099-01-10',time:'12:00',endTime:'13:00',calendarId:'private',alertMinutes:15,invitees:['a','b'],repeat:{unit:'none'}};c.S.calendar=[e,{...e,id:'secret',title:'另一个秘密',invitees:[]}];c.calFireInvitedReminders();assert.equal(c.queued.length,0);now=new D(2099,0,10,11,45).getTime();c.calFireInvitedReminders();assert.equal(c.queued.length,2);assert.deepEqual(Array.from(c.calRoleEvents('a'),x=>x.id),['invite']);assert.equal(c.calRoleEvents('c').length,0);assert.match(c.queued[0].note,/去书店.*逛完喝咖啡/);assert.doesNotMatch(c.queued[0].note,/另一个秘密/);assert.equal(c.calInviteNoteValid(c.queued[0].note,'a','main'),true);assert.equal(c.calInviteNoteValid(c.queued[0].note,'b','main'),false);c.calFireInvitedReminders();assert.equal(c.queued.length,2);await c.queued[0].done(false);await c.queued[1].done(true);c.calFireInvitedReminders();assert.equal(c.queued.length,3);assert.equal(Object.keys(c.S.calendarRoleFired).length,1);e.invitees=['b'];assert.equal(c.calInviteNoteValid(c.queued[2].note,'a','main'),false);await c.queued[2].done(true);assert.equal(Object.keys(c.S.calendarRoleFired).length,1);c.S.me.active='other';assert.equal(c.calInviteNoteValid(c.queued[1].note,'b','main'),false);c.S.me.active='main';now=new D(2099,0,10,13,1).getTime();assert.equal(c.calInviteNoteValid(c.queued[1].note,'b','main'),false);c.calFireInvitedReminders();assert.equal(c.queued.length,3);});


test('undated personal reminders are visible, optional due times have no invented duration and edits keep the record ID',async()=>{const c=calendarVM();Object.assign(c,{actId:()=>c.S.me.active,getC:()=>null,calPersist:async()=>true,go(){},uid:()=> 'id',_calSaving:false,_calPanelOwner:'main',_calPanel:'newEvent',_calEventMenu:'',_calYearView:false,_calDayView:false});c.S.contacts=[];c.S.messages={};vm.runInContext('Object.fromEntries=undefined;',c);for(const name of ['calRepeatRule','calInviteRoles','calScheduleFingerprint'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);vm.runInContext(source.split('\n').find(x=>x.startsWith('async function calNewSave(')),c);const draft={id:'personal-todo',type:'reminder',title:'整理草稿',notes:'普通待办',location:'',url:'',date:'2026-10-10',endDate:'2026-10-10',time:'09:35',endTime:'10:20',allDay:false,calendarId:'',invitees:[],repeatKey:'daily',customRepeat:{unit:'week',interval:1},reminderHasDate:false,reminderHasTime:false};c._calEventDraft={...draft};await c.calNewSave();let e=c.S.calendar[0];assert.equal(e.date,'');assert.equal(e.time,'');assert.equal(e.endTime,'');assert.equal(e.repeat.unit,'none');assert.equal(c.calUndatedReminders().length,1);assert.match(c.calAgendaHTML('2026-10-10',{}),/未安排日期/);assert.equal(c.S.contacts.length,0);e.completed=true;c._calEventDraft={...draft,_editId:e.id,_editRevision:e.revision,reminderHasDate:true,reminderHasTime:true};c._calPanel='newEvent';await c.calNewSave();e=c.S.calendar[0];assert.equal(c.S.calendar.length,1);assert.equal(e.id,'personal-todo');assert.equal(e.time,'09:35');assert.equal(e.endTime,'');assert.equal(e.alertMinutes,0);assert.equal(e.completed,false);assert.deepEqual(Array.from(e.completedDates),['2026-10-10']);const rows=c.calExpandedEvents(e,'2026-10-10','2026-10-11');assert.equal(rows[0].completed,true);assert.equal(!!rows[1].completed,false);const before=JSON.stringify(c.S.calendar);c.calPersist=async()=>false;c._calEventDraft={...draft,_editId:e.id,_editRevision:e.revision,title:'失败的改动',reminderHasDate:true,reminderHasTime:true};await c.calNewSave();assert.equal(JSON.stringify(c.S.calendar),before);});

test('a single excluded repetition does not delete its other dates or manufacture a date in saved details',()=>{const c=calendarVM();for(const name of ['calDetailEvent','calDetailClock'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);c.actId=()=>c.S.me.active;const e={id:'event',owner:'main',type:'event',date:'2026-10-09',endDate:'2026-10-09',title:'用户自己的标题',time:'09:35',endTime:'10:20',repeat:{unit:'day',interval:1},excludedDates:['2026-10-10']};c.S.calendar=[e];assert.equal(c.calEventsByYear(2026)['2026-10-10'],undefined);assert.equal(c.calEventsByYear(2026)['2026-10-11'][0].title,'用户自己的标题');assert.equal(c.calDetailClock(e,'2026-10-11'),'09:35 – 10:20');assert.equal(c.calDetailEvent({owner:'main',id:'event',date:'2026-10-10'}),null);assert.equal(c.calDetailEvent({owner:'other',id:'event',date:'2026-10-11'}),null);assert.equal(c.calDetailClock({...e,time:'',endTime:''},e.date),'全天');});


test('day layout clips overnight events, separates collisions and leaves all-day and instant task data intact',()=>{const c=calendarVM();for(const name of ['calDayRows','calDayItems','calDayLayout'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);c.S.calendar=[{id:'overnight',date:'2026-10-09',endDate:'2026-10-10',time:'23:30',endTime:'01:00',title:'跨午夜',type:'event'},{id:'first',date:'2026-10-10',time:'09:00',endTime:'10:00',title:'第一项',type:'event'},{id:'second',date:'2026-10-10',time:'09:30',endTime:'10:30',title:'重叠项',type:'event'},{id:'third',date:'2026-10-10',time:'11:00',endTime:'12:00',title:'独立项',type:'event'},{id:'task',date:'2026-10-10',time:'07:25',endTime:'',title:'待办',type:'reminder',reminderVersion:2},{id:'all',date:'2026-10-10',allDay:true,title:'全天',type:'event'}];const before=JSON.stringify(c.S),items=c.calDayItems('2026-10-10'),night=items.find(x=>x.e.id==='overnight'),task=items.find(x=>x.e.id==='task'),layout=c.calDayLayout(items);assert.equal(night.start,0);assert.equal(night.end,60);assert.equal(task.start,445);assert.equal(task.point,true);assert.equal(task.e.endTime,'');assert.equal(layout.find(x=>x.e.id==='first').columns,2);assert.equal(layout.find(x=>x.e.id==='second').columns,2);assert.equal(layout.find(x=>x.e.id==='third').columns,1);assert.equal(items.some(x=>x.e.id==='all'),false);assert.equal(JSON.stringify(c.S),before);});

test('local calendar search reads real title, role names, place, notes and dates with account and hidden-calendar boundaries',()=>{const c=calendarVM();Object.assign(c,{actId:()=>c.S.me.active,getC:id=>id==='role'?{id,name:'北',remark:'小北'}:null});for(const name of ['calSearchText','calSearchDate','calSearchFields','calSearchSeriesDate','calSearchResults'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);c.S.calendarCollections=[{id:'visible',owner:'main',name:'创作',visible:true},{id:'hidden',owner:'main',name:'隐藏分类',visible:false},{id:'other',owner:'other',name:'别人的'}];c.S.calendar=[{id:'a',owner:'main',calendarId:'visible',date:'2026-10-09',time:'09:35',endTime:'10:20',title:'交稿',location:'工作室',notes:'带封面草稿',url:'https://example.com/project',invitees:['role'],type:'event'},{id:'hidden',owner:'main',calendarId:'hidden',date:'2026-10-09',title:'交稿秘密',type:'event'},{id:'other',owner:'other',calendarId:'other',date:'2026-10-09',title:'交稿其他账户',type:'event'},{id:'series',owner:'main',calendarId:'visible',date:'2026-10-09',title:'读书',repeat:{unit:'day',interval:1},excludedDates:['2026-10-10'],type:'event'},{id:'undated',owner:'main',calendarId:'visible',date:'',title:'待办整理',type:'reminder'}];const before=JSON.stringify(c.S);for(const q of ['交稿','小北','工作室','封面','example.com','创作 交稿'])assert.equal(c.calSearchResults(q)[0].id,'a');assert.deepEqual(Array.from(c.calSearchResults('2026年10月9日'),x=>x.id),['series','a']);assert.equal(c.calSearchResults('2026-10-10').length,0);assert.equal(c.calSearchResults('读书').length,1);assert.equal(c.calSearchResults('待办整理')[0]._searchDate,'');assert.equal(c.calSearchDate('2026-02-30'),'');assert.equal(JSON.stringify(c.S),before);});


test('repeating reminder completion rejects skipped or nonexistent occurrences from stale pages',async()=>{const c=calendarVM();Object.assign(c,{calPersist:async()=>true,closeModal(){}});vm.runInContext('let _calSaving=false;',c);vm.runInContext(source.split('\n').find(x=>x.startsWith('async function calReminderToggle(')),c);const e={id:'repeat-task',type:'reminder',owner:'main',date:'2026-10-09',repeat:{unit:'week',interval:1},excludedDates:['2026-10-16'],completedDates:[]};c.S.calendar=[e];for(const date of ['2026-10-10','2026-10-16','']){const before=JSON.stringify(e);await c.calReminderToggle(e.id,date);assert.equal(JSON.stringify(e),before);}await c.calReminderToggle(e.id,'2026-10-23');assert.deepEqual(Array.from(e.completedDates),['2026-10-23']);await c.calReminderToggle(e.id,'2026-10-23');assert.equal(e.completedDates.length,0);});


test('existing calendar color applies immediately without committing unrelated editing drafts and rolls back failed persistence',async()=>{const c=calendarVM();Object.assign(c,{calPersist:async()=>true});vm.runInContext("let _calSaving=false,_calPanelOwner='main',_calDraft={id:'colors',color:'#009aff',name:'unsaved title'};",c);for(const name of ['calColorValue','calDraftColor'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'(')),c);c.S.calendarCollections=[{id:'colors',owner:'main',name:'创作计划',color:'#009aff'}];await c.calDraftColor('#ff3b30');assert.equal(c.S.calendarCollections[0].color,'#ff3b30');assert.equal(c.S.calendarCollections[0].name,'创作计划');c.calPersist=async()=>false;await c.calDraftColor('#34c759');assert.equal(c.S.calendarCollections[0].color,'#ff3b30');});


test('explicit role invitations preserve selected-event privacy and refusal visibility never re-enables alerts',async()=>{const c=calendarVM(),role={id:'role',name:'北'};let id=0;Object.assign(c,{getC:n=>n==='role'?role:null,uid:()=>String(++id),accountMessageKey:n=>n,msgs:n=>c.S.messages[n]||(c.S.messages[n]=[]),calPersist:async()=>true,notifyIncoming(){},refreshChatMessages(){},cur:()=>({p:'home'})});c.S.messages={};c.S.roleCalendar=[{id:'private',owner:'main',cid:'role',date:'2026-10-10',time:'12:00',title:'没有邀请的私人安排'}];vm.runInContext("let _calSaving=false,_calPanelOwner='main';",c);for(const name of ['roleCalRows','roleCalConsume','calRollbackCards','calInvitationLabel','calInvitationRespond','calUserEventAlerts','calPreference'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'(')),c);await c.roleCalConsume('[邀请你参加日程|2026-10-10|18:00|一起散步]',role,'turn1');assert.equal(c.S.calendar.length,1);assert.equal(c.S.messages.role[0].eventIds.length,1);assert.equal(c.S.messages.role[0].eventIds.includes('private'),false);const e=c.S.calendar[0];await c.calInvitationRespond(e.id,'declined');assert.equal(c.calEventVisible(e),false);assert.equal(c.calUserEventAlerts(e),false);await c.calPreference('showDeclined');assert.equal(c.calEventVisible(e),true);assert.equal(c.calUserEventAlerts(e),false);await c.calInvitationRespond(e.id,'accepted');assert.equal(c.calUserEventAlerts(e),true);c.calPersist=async()=>false;await c.calInvitationRespond(e.id,'declined');assert.equal(e.invitationStatus,'accepted');const count=c.S.calendar.length;await c.roleCalConsume('[邀请你参加日程|2026-10-11|19:00|一起喝茶]',role,'turn2');assert.equal(c.S.calendar.length,count);});

test('spoken scheduling validates required facts, retries once and rolls back records and cards on failed saves',async()=>{const c=calendarVM(),role={id:'role',name:'北'};let id=0;Object.assign(c,{getC:n=>n==='role'?role:null,uid:()=>String(++id),accountMessageKey:n=>n,msgs:n=>c.S.messages[n]||(c.S.messages[n]=[]),calPersist:async()=>true,notifyIncoming(){},refreshChatMessages(){},cur:()=>({p:'home'})});c.S.messages={};vm.runInContext('const CAL_ALERT_OPTIONS=[[-1,"无"],[0,"开始时"],[15,"15分钟前"]];',c);for(const name of ['calRepeatRule','calPlayerPayload','calPlayerConsume','calRollbackCards'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'(')),c);const payload={date:'2026-10-10',time:'10:15',title:'去书店',repeat:'week',alertMinutes:15,notes:'带书稿'};assert.equal(c.calPlayerPayload({...payload,time:''},role,'turn'),null);assert.equal(c.calPlayerPayload({...payload,endDate:'2026-10-11'},role,'turn'),null);assert.equal(c.calPlayerPayload({...payload,date:'2026-02-30'},role,'turn'),null);const text='记好了。\n[为你安排日程|'+JSON.stringify(payload)+']';await c.calPlayerConsume(text,role,'turn');await c.calPlayerConsume(text,role,'turn');assert.equal(c.S.calendar.length,1);assert.equal(c.S.messages.role.length,1);assert.equal(c.S.calendar[0].time,'10:15');assert.equal(c.S.calendar[0].endTime,'');assert.equal(c.S.calendar[0].repeat.unit,'week');assert.equal(c.S.calendar[0].invitees[0],'role');c.calPersist=async()=>false;await c.calPlayerConsume('[为你安排日程|'+JSON.stringify({...payload,title:'去咖啡店'})+']',role,'turn2');assert.equal(c.S.calendar.length,1);assert.equal(c.S.messages.role.length,1);});


test('informing a role never schedules a reminder and declined participation cancels already queued work',()=>{const c=calendarVM(),role={id:'role',name:'北'};const now=new Date(2099,0,10,12).getTime();Object.assign(c,{getC:()=>role,isMain:()=>true,isBlk:()=>false,roleOnlineProactiveBlocked:()=>false,calPersist:async()=>true,scheduleFeatureReply:()=>{c.calls++;return true;},calls:0});c.S.contacts=[role];for(const name of ['calParticipation','calRoleCanRemind','calEventLocalAt','calRepeatLabel','calEventFact','calDepartureText','calInviteRoles','calInvitedEvent','featureEventNote','calInviteReminderNote','calInviteNoteValid','calFireInvitedReminders']){const line=source.split('\n').find(x=>x.startsWith('function '+name+'('));if(line)vm.runInContext(line,c);}vm.runInContext('let _calInvitedBusy={};',c);c.S.calendar=[{id:'one',owner:'main',editorVersion:1,type:'event',date:'2099-01-10',endDate:'2099-01-10',time:'12:00',endTime:'13:00',title:'只是告知',alertMinutes:0,invitees:['role'],roleParticipation:{role:{mode:'inform'}}}];c.calFireInvitedReminders(now);assert.equal(c.calls,0);c.S.calendar[0].roleParticipation.role={mode:'remind',response:'declined'};c.calFireInvitedReminders(now);assert.equal(c.calls,0);});


test('calendar care is opt-in, stage-bounded, once per occurrence and canceled after completion or revoked permission',async()=>{const c=calendarVM(),D=Date,role={id:'role',name:'北'};let now=new D(2099,0,10,11).getTime();c.Date=class extends D{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};Object.assign(c,{getC:id=>id==='role'?role:null,isMain:()=>true,isBlk:()=>false,roleOnlineProactiveBlocked:()=>false,calPersist:async()=>true,scheduleFeatureReply:(id,note,delay,done)=>{c.queue.push({note,done});return true;},queue:[]});c.S.contacts=[role];c.S.me.name='用户';for(const name of ['calEventLocalAt','calRepeatLabel','calEventFact','calInviteRoles','calInvitedEvent','featureEventNote','calCareNote','calFireCalendarCare','calInviteNoteValid','calEventOutcome','calRoleInvitedText'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'(')),c);vm.runInContext('let _calInvitedBusy={},_calSaving=false;',c);const e={id:'one',owner:'main',editorVersion:1,type:'event',date:'2099-01-10',endDate:'2099-01-10',time:'12:00',endTime:'13:00',title:'交作品',notes:'检查附件',invitees:['role'],alertMinutes:15,repeat:{unit:'day',interval:1},roleParticipation:{role:{mode:'join',response:'accepted',prepare:false,followup:false}}};c.S.calendar=[e];c.calFireCalendarCare();assert.equal(c.queue.length,0);e.roleParticipation.role.prepare=true;c.calFireCalendarCare();assert.equal(c.queue.length,1);assert.match(c.queue[0].note,/交作品.*检查附件/);assert.equal(c.calInviteNoteValid(c.queue[0].note,'role','main'),true);await c.queue[0].done(true);c.calFireCalendarCare();assert.equal(c.queue.length,1);e.roleParticipation.role.followup=true;now=new D(2099,0,10,13,30).getTime();c.calFireCalendarCare();assert.equal(c.queue.length,2);assert.match(c.queue[1].note,/尚未确认完成/);await c.calEventOutcome(e.id,'2099-01-10');assert.equal(c.calInviteNoteValid(c.queue[1].note,'role','main'),false);assert.match(c.calRoleInvitedText('role'),/已完成日期 2099-01-10/);assert.equal((e.completedDates||[]).includes('2099-01-11'),false);c.calPersist=async()=>false;await c.calEventOutcome(e.id,'2099-01-10');assert.equal(e.completedDates.includes('2099-01-10'),true);e.completedDates=[];e.invitees=[];assert.equal(c.calInviteNoteValid(c.queue[1].note,'role','main'),false);});

test('a role response is scoped to its invitation and a failed response persistence restores state',async()=>{const c=calendarVM(),role={id:'role'};Object.assign(c,{getC:id=>id==='role'?role:null,isMain:()=>true,isBlk:()=>false,calPersist:async()=>true});c.S.contacts=[role];for(const name of ['calInviteRoles','calInvitedEvent'])vm.runInContext(source.split('\n').find(x=>x.startsWith('function '+name+'(')),c);const e={id:'one',owner:'main',invitees:['role'],revision:1};c.S.calendar=[e,{id:'secret',owner:'main',invitees:[]}];await c.calRoleParticipationConsume('我愿意。\n[回应日程邀请|one|accepted]',role);assert.equal(e.roleParticipation.role.response,'accepted');await c.calRoleParticipationConsume('[回应日程邀请|secret|accepted]',role);assert.equal(c.S.calendar[1].roleParticipation,undefined);c.calPersist=async()=>false;await c.calRoleParticipationConsume('[回应日程邀请|one|declined]',role);assert.equal(e.roleParticipation.role.response,'accepted');assert.equal(e.revision,2);});


test('calendar home exit returns to the phone desktop without changing schedules or period records',()=>{const c=calendarVM();c.S.calendar=[{id:'saved',date:'2026-10-10',title:'保留'}];c.S.periods=[{id:'period',startDate:'2026-10-01'}];let exits=0;c.home=()=>exits++;vm.runInContext("let _calSaving=false,_calPanel='',_calSearchOpen=true;",c);vm.runInContext(source.split('\n').find(x=>x.startsWith('function calHome(')),c);const before=JSON.stringify(c.S);c.calHome();assert.equal(exits,1);assert.equal(JSON.stringify(c.S),before);assert.equal(vm.runInContext('_calSearchOpen',c),false);vm.runInContext('_calSaving=true;',c);c.calHome();assert.equal(exits,1);});
