import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const src=fs.readFileSync(new URL('../cohab-model-diagnostics.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function harness(){
 const route={model:'fixed-main',maxTokens:4000,aux:{model:'fixed-aux'},key:'NEVER-EXPOSE',base:'https://secret.invalid'};
 const host={id:'host',name:'主角'},guest={id:'guest',name:'来客'},home={theater:{enabled:true,guest:{contactId:'guest'}}};let calls=0,html='',account='main';const queue=[];
 const c=vm.createContext({String,Array,Map,Date,Number,Object,Math,S:{settings:{chat:route,aux:route.aux,chatRouteActive:2}},CHAT_ROUTE_NAMES:['路线一','路线二','路线三'],actId:()=>account,chatRequestRoute:i=>i==null?null:route,aiCoreOn:()=>false,wechatRequestStats:m=>({messageCount:m.length,requestChars:JSON.stringify(m).length}),cohabReplyRouteIndex:()=>1,cohabReplyAux:()=>false,roleChatRouteIndex:()=>2,cohabData:()=>home,getC:id=>id==='host'?host:guest,fmtDT:x=>String(x),esc:x=>String(x).replace(/</g,'&lt;'),openModal:s=>{html=s;},cohabSettingsPanel:()=>'<div><details><summary>共同生活设置</summary><div>设置内容</div></details><button>让TA回</button></div>'});c.window=c;
 for(const name of ['joinAIContinuation','chatResultText'])vm.runInContext(app.split('\n').find(x=>x.startsWith('function '+name+'(')||x.startsWith('async function '+name+'(')),c);
 c.chatAPI=async(messages,opt={})=>{calls++;const next=queue.shift()||{text:'正常回复',reason:'stop'};if(next.error)throw next.error;return c.chatResultText(messages,opt,{model:'upstream-model',choices:[{message:{content:next.text},finish_reason:next.reason}],usage:{completion_tokens:22}});};
 c.cohabRoleChat=(role,m,opt)=>c.chatAPI(m,{...opt,routeIndex:1});vm.runInContext(fs.readFileSync(new URL('../request-size-details.js',import.meta.url),'utf8'),c);vm.runInContext(src,c);
 return {c,queue,route,host,home,show(){c.cohabModelDiagnosticOpen('host');return html;},get calls(){return calls;},account(v){account=v;}};
}
test('entry remains inside the collapsed common-life settings; opening makes no requests',()=>{const h=harness(),s=h.c.cohabSettingsPanel('host',{});assert(s.indexOf('cohabModelDiagnosticOpen')<s.indexOf('</details>'));assert.equal((s.match(/cohabModelDiagnosticOpen/g)||[]).length,1);assert.match(h.show(),/尚无.*请求记录/);assert.equal(h.calls,0);assert.doesNotMatch(h.show(),/NEVER-EXPOSE|secret.invalid/);});
test('records separate actual host and guest requests, keeps old model and max after settings change',async()=>{const h=harness();await h.c.cohabRoleChat(h.host,[{content:'sensitive body'}],{max:600});await h.c.chatAPI([],{routeIndex:2,aux:true,max:480,cohabDiagnostic:{hostId:'host',kind:'guest',actorName:'来客'}});h.route.model='changed-model';const html=h.show();assert.match(html,/fixed-main/);assert.match(html,/changed-model/);assert.match(html,/fixed-aux/);assert.match(html,/480 tokens/);assert.match(html,/600 tokens/);assert.doesNotMatch(html,/sensitive body/);assert.equal(h.calls,2);h.account('other');assert.match(h.show(),/尚无.*请求记录/);});
test('length completion is observed without adding calls or changing returned output',async()=>{const h=harness();h.queue.push({text:'前半',reason:'length'},{text:'后半',reason:'stop'});const out=await h.c.cohabRoleChat(h.host,[],{max:240,complete:true});assert.equal(out,'前半后半');assert.equal(h.calls,2,'only the existing continuation is called');const html=h.show();assert.match(html,/length/);assert.match(html,/stop/);assert.match(html,/400 tokens/);assert.equal((html.match(/请求阶段/g)||[]).length,1);});
test('failed request preserves the same error and never retries or exposes error secrets',async()=>{const h=harness(),error=Object.assign(new Error('NEVER-EXPOSE https://secret.invalid'),{status:429});h.queue.push({error});await assert.rejects(h.c.cohabRoleChat(h.host,[],{max:600}),e=>e===error);assert.equal(h.calls,1);assert.match(h.show(),/HTTP 429/);assert.doesNotMatch(h.show(),/NEVER-EXPOSE|secret.invalid/);});
test('unrelated WeChat requests do not become common-life diagnostics',async()=>{const h=harness();assert.equal(await h.c.chatAPI([],{max:100}),'正常回复');assert.match(h.show(),/尚无.*请求记录/);assert.equal(h.calls,1);});
test('web and private load the identical diagnostic module and service worker caches it',()=>{assert.equal(fs.readFileSync(new URL('../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/cohab-model-diagnostics.js',import.meta.url),'utf8'),src);for(const path of ['../小手机.html','../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html'])assert.match(fs.readFileSync(new URL(path,import.meta.url),'utf8'),/cohab-model-diagnostics.js\?v=1202/);assert.match(fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8'),/currentCore\(cache,'cohabDiagnostics'\)/);});
