import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const Watch=createRequire(import.meta.url)('../couple-watch.js');
const runtime=readFileSync(new URL('../couple-watch-runtime.js',import.meta.url),'utf8');
function harness(kind='chat',random=0){
  let at=new Date(2026,8,6,12).getTime(),owner={},snapshot={owner,account:'main',cid:'partner',kind,key:'other',name:'Other'},events=[];
  const engine=Watch.create({now:()=>at,random:()=>random,read:()=>snapshot,save(){},react:(event,valid)=>events.push({event,valid})});
  engine.tick();
  return{engine,events,owner,get snapshot(){return snapshot;},set snapshot(v){snapshot=v;engine.tick();},advance(ms){while(ms>0){const step=Math.min(ms,250);at+=step;ms-=step;engine.tick();}},jump(ms){at+=ms;engine.tick();},setTime(value){at=value;engine.tick();}};
}
for(const [kind,min] of [['chat',10000],['app',20000]]){
  test(`${kind}: minimum threshold and one event per visit`,()=>{const h=harness(kind);h.advance(min-1);assert.equal(h.events.length,0);h.advance(1);assert.equal(h.events.length,1);h.advance(180000);assert.equal(h.events.length,1);h.jump(10000);h.advance(60000);assert.equal(h.events.length,1);});
  test(`${kind}: maximum random threshold is 60 seconds`,()=>{const h=harness(kind,1);h.advance(59999);assert.equal(h.events.length,0);h.advance(1);assert.equal(h.events.length,1);});
  test(`${kind}: short visit is private, reentry restarts timer and counts it`,()=>{const h=harness(kind);const s=h.snapshot;h.advance(min-1);h.snapshot=null;h.snapshot=s;h.advance(min-1);assert.equal(h.events.length,0);h.advance(1);assert.equal(h.events[0].event.count,2);});
}
test('switching chat target gives each target its own daily count',()=>{const h=harness();h.snapshot={...h.snapshot,key:'third'};h.advance(30000);assert.equal(h.events[0].event.count,1);h.snapshot={...h.snapshot,key:'other'};h.advance(30000);assert.equal(h.events[1].event.count,2);});
test('rerender does not reset a visit',()=>{const h=harness();h.advance(20000);h.snapshot={...h.snapshot};h.advance(10000);assert.equal(h.events.length,1);assert.equal(h.events[0].event.count,1);});
test('leaving or revoking cancels in-flight result',()=>{const h=harness();h.advance(30000);assert.equal(h.events[0].valid(),true);h.snapshot=null;assert.equal(h.events[0].valid(),false);});
test('partner activity suppresses pending and in-flight events',()=>{const h=harness('app');h.advance(19000);h.snapshot={...h.snapshot,exempt:true};h.advance(90000);assert.equal(h.events.length,0);h.snapshot={...h.snapshot,exempt:false};h.advance(20000);assert.equal(h.events.length,1);h.snapshot={...h.snapshot,exempt:true};assert.equal(h.events[0].valid(),false);});
test('changing participants restarts detection but not app open count',()=>{const h=harness('app');h.advance(19000);h.snapshot={...h.snapshot,context:'with-third'};h.advance(19000);assert.equal(h.events.length,0);h.advance(1000);assert.equal(h.events[0].event.count,1);});
test('midnight resets counts and does not reuse yesterday timer',()=>{const h=harness();h.advance(30000);h.setTime(new Date(2026,8,7,0).getTime());assert.equal(h.events[0].valid(),false);h.advance(30000);assert.equal(h.events[1].event.count,1);assert.equal(Object.keys(h.owner.watchDaily.counts).length,1);});
test('suspended event loop cannot count unseen background time',()=>{const h=harness();h.advance(1000);h.jump(90000);assert.equal(h.events.length,0);h.advance(30000);assert.equal(h.events.length,1);});
test('rebind to new object cancels old response even when cid matches',()=>{const h=harness();h.advance(30000);h.snapshot={...h.snapshot,owner:{}};assert.equal(h.events[0].valid(),false);h.advance(30000);assert.equal(h.events[1].event.count,1);});
function appHarness(){
  const cp={cid:'partner',chatWatch:true,softwareWatch:true,watchApps:{games:true,cinema:true,tale:true,dread:true}},rows=[{role:'assistant',type:'text',content:'previous',id:'old'}],calls=[],notifications=[];
  let page={p:'chat',id:'other'},resolveModel;
  const s={S:{couple:cp,me:{name:'User',locked:false},settings:{hist:12},contacts:[{id:'partner',name:'Partner',persona:'kind'},{id:'other',name:'Other'}]},CoupleWatch:Watch,document:{hidden:false},_call:null,_gs:{cid:'other'},_dg:null,_uc:null,_wg:null,_off:null,_rp:null,_hq:null,_bead:null,_replyTimers:{},isMain:()=>true,actId:()=> 'main',cur:()=>page,curAppKey:()=>({gameshub:'games',gs:'games',drawguess:'games',heartquiz:'games',beadstudio:'games',uc:'games',mgroom:'games',cinemawatch:'cinema',cinemaread:'cinema',tale:'tale',dread:'dread'})[page.p],cinemaSession:()=>({cid:'other',status:'active'}),mgrRoom:()=>({roleIds:['other']}),rpMembers:()=>[{id:'other'}],save(){},render(){},openModal(){},getC:id=>s.S.contacts.find(c=>c.id===id),replyStateKey:()=> 'main:partner',replyGenerationBusy:()=>false,featureEventQueueEntries:()=>[],roleOnlineProactiveBlocked:()=>false,cinemaRoleOccupied:()=>false,wxLoginActive:()=>false,remoteControlActive:()=>false,replyEpoch:()=>0,replyStale:()=>false,msgsForAccount:id=>{assert.equal(id,'partner','must never read observed conversation');return rows;},lastRounds:x=>x,msgToText:m=>m.content,buildSystem:()=> 'Partner persona',roleChatRouteIndex:()=>2,chatAPI:(messages,opt)=>{calls.push({messages,opt});return new Promise(r=>resolveModel=r);},roleVisibleEnvelopeText:x=>x,splitBubbles:x=>x.split('\n'),isOOCLine:()=>false,initiativeRecentlyRepeated:()=>false,uid:()=> 'new',notifyIncoming:(c,m)=>notifications.push(m)};
  s.wechatNaturalOn=()=>true;const ctx=vm.createContext(s);const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');for(const name of ['normalizeHiddenThoughtFormats','setNaturalInnerThought','stripHiddenThoughtTags','wechatInnerThoughtValue'])vm.runInContext(app.split('\n').find(line=>line.startsWith('function '+name+'(')),ctx);vm.runInContext(runtime.slice(0,runtime.indexOf("if(typeof CoupleWatch!==")),ctx);
  return{s,cp,rows,calls,notifications,ctx,set page(p){page=p;},read:()=>ctx.coupleWatchRead(),resolve:v=>resolveModel(v)};
}
test('both permissions default off, chat excludes partner, hidden and alternate accounts',()=>{const h=appHarness();delete h.cp.chatWatch;assert.equal(h.read(),null);h.cp.chatWatch=true;h.page={p:'chat',id:'partner'};assert.equal(h.read(),null);h.page={p:'chat',id:'other'};h.s.document.hidden=true;assert.equal(h.read(),null);h.s.document.hidden=false;h.s.isMain=()=>false;assert.equal(h.read(),null);});
test('software only tracks explicit selected apps',()=>{const h=appHarness();h.page={p:'gameshub'};assert.equal(h.read().name,'游戏大厅');h.cp.watchApps.games=false;assert.equal(h.read(),null);});
for(const p of ['gs','drawguess','heartquiz','beadstudio','uc','mgroom','cinemawatch','cinemaread','tale','dread']){
  test(`partner exclusion: ${p}`,()=>{const h=appHarness();h.page={p};h.s._gs=h.s._dg=h.s._hq=h.s._bead={cid:'partner'};h.s._uc={players:[{id:'p_partner'}]};h.s.mgrRoom=()=>({roleIds:['partner','other']});h.s.cinemaSession=()=>({cid:'partner',status:'active'});h.s.S.tale={active:true,companions:['partner']};h.s.S.dread={active:true,gm:'partner'};assert.equal(h.read().exempt,true);});
}
test('reaction uses bound role route, minimal facts, and actual generated speech only',async()=>{const h=appHarness();const event={...h.read(),count:2},promise=h.ctx.coupleWatchReact(event,()=>true);assert.equal(h.calls.length,1);assert.equal(h.calls[0].opt.routeIndex,2);assert.equal(h.calls[0].opt.independentRoleModel,true);assert.match(h.calls[0].messages.at(-1).content,/第 2 次/);h.resolve('你又去找Other了呀。');assert.equal(await promise,true);assert.equal(h.notifications.length,1);assert.equal(h.rows.at(-1).type,'text');});
test('revocation during model request discards reply silently',async()=>{const h=appHarness();let valid=true;const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>valid);valid=false;h.resolve('late');assert.equal(await promise,false);assert.equal(h.notifications.length,0);});
test('new partner message during model request invalidates stale reaction',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.rows.push({id:'user2',role:'user',content:'new'});h.resolve('late');assert.equal(await promise,false);assert.equal(h.notifications.length,0);});
test('invalid model output produces no fallback or retry',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.resolve('[系统提示]');assert.equal(await promise,false);assert.equal(h.calls.length,1);assert.equal(h.notifications.length,0);});
test('model mood metadata does not suppress genuine generated speech',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.resolve('[心情|在意]\n你又去找朋友啦。');assert.equal(await promise,true);assert.equal(h.notifications.length,1);assert.equal(h.notifications[0].content,'你又去找朋友啦。');});
test('due event waits for normal reply slot without retrying a model call',()=>{let at=0,ready=false,calls=0;const s={owner:{},account:'main',cid:'p',kind:'chat',key:'q'};const engine=Watch.create({read:()=>s,save(){},now:()=>at,random:()=>0,ready:()=>ready,react(){calls++;}});engine.tick();for(at=250;at<=40000;at+=250)engine.tick();assert.equal(calls,0);ready=true;engine.tick();assert.equal(calls,1);engine.tick();assert.equal(calls,1);});
test('web event is not permanently blocked by old unanswered user message',async()=>{const h=appHarness();h.rows.push({id:'old-user',role:'user',type:'text',content:'old question'});assert.equal(h.ctx.coupleWatchReady(h.read()),true);const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);assert.equal(h.calls.length,1);h.resolve('你又去找朋友了呀。');assert.equal(await promise,true);});
test('web event is independent of ordinary proactive quiet and stale feature queue',()=>{const h=appHarness();h.s.roleOnlineProactiveBlocked=()=>true;h.s.featureEventQueueEntries=()=>[{note:'old failed feature'}];assert.equal(h.ctx.coupleWatchReady(h.read()),true);});
test('four genuine model lines must not silently discard the entire event',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.resolve('你在刷抖音呀。\n看到什么了？\n有意思的话。\n也和我讲讲。');assert.equal(await promise,true);assert.equal(h.notifications.length,4);});
test('inline mood metadata does not hide generated speech',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.resolve('[心情|好奇]你又在刷抖音呀。');assert.equal(await promise,true);assert.equal(h.notifications[0].content,'你又在刷抖音呀。');});
test('canonical inner thought from the real role prompt does not discard chat supervision',async()=>{const h=appHarness();const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>true);h.resolve('[内心|想知道他刚才跟朋友聊了什么。]\n刚才找朋友聊天了呀？');assert.equal(await promise,true);assert.equal(h.notifications.length,1);assert.equal(h.notifications[0].content,'刚才找朋友聊天了呀？');});
test('accepted supervision updates thought but cancelled generation cannot overwrite it',async()=>{const h=appHarness(),c=h.s.getC('partner');c.innerThought='之前的内心';let valid=true;const promise=h.ctx.coupleWatchReact({...h.read(),count:1},()=>valid);valid=false;h.resolve('[内心|失效的内心]\n失效消息');assert.equal(await promise,false);assert.equal(c.innerThought,'之前的内心');const next=h.ctx.coupleWatchReact({...h.read(),count:2},()=>true);h.resolve('[内心|刚才有点好奇]\n刚才聊什么呢？');assert.equal(await next,true);assert.equal(c.innerThought,'刚才有点好奇');});
test('new observed event is not suppressed by ordinary proactive similarity filter',async()=>{const h=appHarness();h.s.initiativeRecentlyRepeated=()=>true;const promise=h.ctx.coupleWatchReact({...h.read(),count:2},()=>true);h.resolve('又在刷抖音呢？');assert.equal(await promise,true);});
test('visible main-thread stall does not restart a 30-second foreground visit',()=>{const h=harness();h.advance(20000);h.jump(8000);h.advance(2000);assert.equal(h.events.length,1);});
test('captured event survives returning to partner chat while model is generating',async()=>{const h=appHarness();const event={...h.read(),count:1};const promise=h.ctx.coupleWatchReact(event,()=>h.ctx.coupleWatchAuthorized(event));h.page={p:'chat',id:'partner'};assert.equal(h.ctx.coupleWatchAuthorized(event),true);h.resolve('刚才去找朋友啦？');assert.equal(await promise,true);assert.equal(h.notifications.length,1);});
test('captured event remains revoked after permission is switched off and back on',async()=>{const h=appHarness();const event={...h.read(),count:1};const promise=h.ctx.coupleWatchReact(event,()=>h.ctx.coupleWatchAuthorized(event));h.ctx.coupleWatchToggle('chatWatch');h.ctx.coupleWatchToggle('chatWatch');assert.equal(h.ctx.coupleWatchAuthorized(event),false);h.resolve('late');assert.equal(await promise,false);});
test('captured software event is cancelled when partner joins current activity',async()=>{const h=appHarness();h.page={p:'gameshub'};const event={...h.read(),count:1},promise=h.ctx.coupleWatchReact(event,()=>h.ctx.coupleWatchAuthorized(event));h.page={p:'gs'};h.s._gs={cid:'partner'};h.resolve('late');assert.equal(await promise,false);});
test('engine hands off fired snapshot validity separately from dwell page',()=>{let at=Date.now(),s={owner:{},account:'main',cid:'p',kind:'chat',key:'q'},allowed=true,check;const engine=Watch.create({now:()=>at,random:()=>0,read:()=>s,save(){},authorized:()=>allowed,react:(e,valid)=>{check=valid;}});engine.tick();for(let n=0;n<120;n++){at+=250;engine.tick();}assert.equal(check(),true);s=null;engine.tick();assert.equal(check(),true);allowed=false;assert.equal(check(),false);});
test('active calls and actual reply generation still block dispatch',()=>{const h=appHarness();h.s._call={};assert.equal(h.ctx.coupleWatchReady(h.read()||{cid:'partner',account:'main'}),false);h.s._call=null;h.s.replyGenerationBusy=()=>true;assert.equal(h.ctx.coupleWatchReady(h.read()),false);});
