import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=process.env.EIGHT_SOURCE_ROOT?new URL('file:///'+process.env.EIGHT_SOURCE_ROOT.replace(/\\/g,'/')+'/'):new URL('../',import.meta.url);
for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){
 const app=fs.readFileSync(new URL(file,root),'utf8'),label=file==='app.js'?'web':'private';
 function source(name){const start=app.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0,'missing '+name);const tail=app.slice(start),end=tail.slice(1).search(/\n(?:function |async function |const |let |\/\*)/);return end<0?tail:tail.slice(0,end+1);}
 function box(names,extra={}){const ctx=vm.createContext({console,Date,Math,JSON,Set,Array,String,Response,uid:()=> 'fixture',...extra});vm.runInContext(names.map(source).join('\n'),ctx);return ctx;}
 test(label+': control metadata is removed, ordinary speech and narration remain',()=>{const c=box(['roleInternalControlLine','rolePublicText']);assert.equal(c.rolePublicText('嗯？\n已在本轮完成，不再重复。\n吃饭吧。'),'嗯？\n吃饭吧。');assert.equal(c.rolePublicText('[保持安静]'),'');for(const t of ['宝宝，保持安静一点。','这件事已经完成了。','【他安静地坐下来。】'])assert.equal(c.rolePublicText(t),t);});
 test(label+': exclusive packet checks before mutation; unmatched target fails closed',()=>{const c=box(['gRpRecipient','gRpState','gRpTake'],{S:{me:{name:'North'}},getC:id=>({name:id}),gnm:(g,id)=>id,save:()=>{},addBill:()=>{throw Error('unexpected credit');}}),g={members:['a','b'],msgs:[]},m={senderId:'a',type:'redpacket',amount:52,note:'给North的专属红包',count:1,splits:[52],grabs:[]};assert.equal(c.gRpTake(g,m,'b'),null);assert.deepEqual(m.grabs,[]);assert.equal(m.to,'me');c.S.me.name='新名字';assert.equal(c.gRpRecipient(g,m),'me');assert.equal(c.gRpRecipient(g,{note:'给未识别对象的专属红包'}),'__ambiguous__');assert.equal(c.gRpRecipient(g,{note:'恭喜发财'}),'');});
 test(label+': strangers reject repeated arrival openings and preserve distinct personalities',()=>{const c=box(['roleInternalControlLine','dyStrangerOpeningKey','dyStrangerArrivalOpening','dyStrangerParse']),styles=['安静理性','活泼好奇','直爽'],rows=[{name:'慢半拍',text:'最近有没有一首歌会单曲循环？'},{name:'猫尾巴',text:'我刚把煎蛋翻到锅外了，你厨艺怎么样哈哈'},{name:'旧车票',text:'想找人交换书单，你愿意推荐一本吗？'}];assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]).length,3);assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[rows[0].text]),null);rows[0].text='看了North的视频直接找到你';assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]),null);rows[0].text=rows[1].text;assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]),null);});
 test(label+': friend fallback probes safely, then submits each write exactly once',async()=>{const calls=[];const c=box(['pfTransportRoute','pfRpc'],{GATE_URL:'https://direct.test',PF_RELAY_BASE:'https://relay.test',_pfTransportRoute:'',_pfTransportAt:0,_pfTransportProbe:null,pfHeaders:()=>({}),fetchT:async(url,opt)=>{calls.push({url,args:JSON.parse(opt.body)});if(url.startsWith('https://direct.test'))throw Error('blocked');return new Response(JSON.stringify(url.endsWith('search')?[]:{id:'confirmed'}));}});assert.equal((await c.pfRpc('phone_friend_send_message',{p_body:'晚饭吃什么？'})).id,'confirmed');assert.equal(calls.filter(x=>x.url.endsWith('phone_friend_send_message')).length,1);assert.deepEqual(calls.slice(0,2).map(x=>x.args),[{p_query:''},{p_query:''}]);assert(calls[2].url.startsWith('https://relay.test'));});
 test(label+': all routes down submits zero messages; response failures remain uncertain',async()=>{let writes=0;const c=box(['pfTransportRoute','pfRpc'],{GATE_URL:'https://direct.test',PF_RELAY_BASE:'https://relay.test',_pfTransportRoute:'',_pfTransportAt:0,_pfTransportProbe:null,pfHeaders:()=>({}),fetchT:async(url)=>{if(url.endsWith('phone_friend_send_message'))writes++;throw Error('offline');}});await assert.rejects(c.pfRpc('phone_friend_send_message',{}),/消息尚未提交/);assert.equal(writes,0);for(const response of [new Response('{}',{status:502}),new Response('broken json')]){c._pfTransportRoute='https://relay.test';c._pfTransportAt=Date.now();c.fetchT=async()=>response;await assert.rejects(c.pfRpc('phone_friend_send_message',{}),e=>e.pfSubmissionUnknown===true&&/尚未确认/.test(e.message));} });
 test(label+': unread badges exclude control, hidden transport, own and recalled messages',()=>{const c=box(['roleInternalControlLine','wxRoleUnread','wxGroupUnread','wxPfUnread'],{roleReadCounted:m=>m&&!m._silent&&!m._call&&m.type!=='sys',msgs:()=>[{role:'assistant',content:'你好'},{role:'user',content:'我自己'},{role:'assistant',content:'[保持安静]'},{role:'assistant',content:'已读',seenAt:1},{role:'assistant',content:'撤回',recalled:true}],pfIsHiddenTransport:m=>m.hidden,pfIsRpGrabTransport:m=>m.receipt});assert.equal(c.wxRoleUnread('a'),1);assert.equal(c.wxGroupUnread({msgs:[{senderId:'a',content:'你好'},{senderId:'me',content:'自己的'},{senderId:'a',type:'sys'},{senderId:'a',content:'[保持安静]'}]}),1);assert.equal(c.wxPfUnread([{from:'OTHER',time:2},{from:'ME',time:2},{from:'OTHER',time:2,hidden:true},{from:'OTHER',time:2,receipt:true}], 'OTHER',0,false),1);});
 test(label+': group model quotes user without attaching a quote, preserves other role full text',()=>{const long='完整原文'.repeat(100)+'末尾标记';const c=box(['gParseReply'],{S:{me:{name:'North'}},splitBubbles:t=>t.split(/\n/),normTag:t=>t,splitActions:t=>[t],parsePayCardLine:()=>null,LEAKRE:/^never-fixture$/,gName:m=>m.senderId,gmText:m=>m.content,uid:()=> 'id',gnm:(g,id)=>id==='me'?'North':id});const rows=[{senderId:'me',type:'text',content:long},{senderId:'a',type:'text',content:long}];assert(!c.gParseReply('[引用|1]\n知道了。',4,rows,{})[0].q);assert.equal(c.gParseReply('[引用|2]\n知道了。',4,rows,{})[0].q.text,long);});
}
