import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=process.env.EIGHT_SOURCE_ROOT?new URL('file:///'+process.env.EIGHT_SOURCE_ROOT.replace(/\\/g,'/')+'/'):new URL('../',import.meta.url);
for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){
 const app=fs.readFileSync(new URL(file,root),'utf8'),label=file==='app.js'?'web':'private';
 function source(name){const start=app.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0,'missing '+name);const tail=app.slice(start),end=tail.slice(1).search(/\n(?:function |async function |const |let |\/\*)/);return end<0?tail:tail.slice(0,end+1);}
 function box(names,extra={}){const ctx=vm.createContext({console,Date,Math,JSON,Set,Array,String,Response,setTimeout,clearTimeout,uid:()=> 'fixture',...extra});vm.runInContext(names.map(source).join('\n'),ctx);return ctx;}
 test(label+': control metadata is removed, ordinary speech and narration remain',()=>{const c=box(['roleInternalControlLine','rolePublicText']);assert.equal(c.rolePublicText('嗯？\n已在本轮完成，不再重复。\n吃饭吧。'),'嗯？\n吃饭吧。');assert.equal(c.rolePublicText('[保持安静]'),'');for(const t of ['宝宝，保持安静一点。','这件事已经完成了。','【他安静地坐下来。】'])assert.equal(c.rolePublicText(t),t);});
 test(label+': exclusive packet checks before mutation; unmatched target fails closed',()=>{const c=box(['gRpRecipient','gRpState','gRpTake'],{S:{me:{name:'North'}},getC:id=>({name:id}),gnm:(g,id)=>id,save:()=>{},addBill:()=>{throw Error('unexpected credit');}}),g={members:['a','b'],msgs:[]},m={senderId:'a',type:'redpacket',amount:52,note:'给North的专属红包',count:1,splits:[52],grabs:[]};assert.equal(c.gRpTake(g,m,'b'),null);assert.deepEqual(m.grabs,[]);assert.equal(m.to,'me');c.S.me.name='新名字';assert.equal(c.gRpRecipient(g,m),'me');assert.equal(c.gRpRecipient(g,{note:'给未识别对象的专属红包'}),'__ambiguous__');assert.equal(c.gRpRecipient(g,{note:'恭喜发财'}),'');});
 test(label+': strangers reject repeated arrival openings and preserve distinct personalities',()=>{const c=box(['roleInternalControlLine','dyStrangerOpeningKey','dyStrangerArrivalOpening','dyStrangerParse']),styles=['安静理性','活泼好奇','直爽'],rows=[{name:'慢半拍',text:'最近有没有一首歌会单曲循环？'},{name:'猫尾巴',text:'我刚把煎蛋翻到锅外了，你厨艺怎么样哈哈'},{name:'旧车票',text:'想找人交换书单，你愿意推荐一本吗？'}];assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]).length,3);assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[rows[0].text]),null);rows[0].text='看了North的视频直接找到你';assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]),null);rows[0].text=rows[1].text;assert.equal(c.dyStrangerParse(JSON.stringify(rows),styles,[]),null);});
 test(label+': friend fallback probes safely, then submits each write exactly once',async()=>{const calls=[];const c=box(['pfTransportRoute','pfRpc'],{GATE_URL:'https://direct.test',PF_RELAY_BASE:'https://relay.test',_pfTransportRoute:'',_pfTransportAt:0,_pfTransportProbe:null,pfHeaders:()=>({}),fetchT:async(url,opt)=>{calls.push({url,args:JSON.parse(opt.body)});if(url.startsWith('https://direct.test'))throw Error('blocked');return new Response(JSON.stringify(url.endsWith('search')?[]:{id:'confirmed'}));}});assert.equal((await c.pfRpc('phone_friend_send_message',{p_body:'晚饭吃什么？'})).id,'confirmed');assert.equal(calls.filter(x=>x.url.endsWith('phone_friend_send_message')).length,1);assert.deepEqual(calls.slice(0,2).map(x=>x.args),[{p_query:''},{p_query:''}]);assert(calls[2].url.startsWith('https://relay.test'));});
 test(label+': all routes down submits zero messages; response failures remain uncertain',async()=>{let writes=0;const c=box(['pfTransportRoute','pfRpc'],{GATE_URL:'https://direct.test',PF_RELAY_BASE:'https://relay.test',_pfTransportRoute:'',_pfTransportAt:0,_pfTransportProbe:null,pfHeaders:()=>({}),fetchT:async(url)=>{if(url.endsWith('phone_friend_send_message'))writes++;throw Error('offline');}});await assert.rejects(c.pfRpc('phone_friend_send_message',{}),/消息尚未提交/);assert.equal(writes,0);for(const response of [new Response('{}',{status:502}),new Response('broken json')]){c._pfTransportRoute='https://relay.test';c._pfTransportAt=Date.now();c.fetchT=async()=>response;await assert.rejects(c.pfRpc('phone_friend_send_message',{}),e=>e.pfSubmissionUnknown===true&&/尚未确认/.test(e.message));} });
 test(label+': unread badges exclude control, hidden transport, own and recalled messages',()=>{const c=box(['roleInternalControlLine','wxRoleUnread','wxGroupUnread','wxPfUnread'],{wxMessageSeen:m=>!!m.seenAt,wxReadKey:()=>'',roleReadCounted:m=>m&&!m._silent&&!m._call&&m.type!=='sys',msgs:()=>[{role:'assistant',content:'你好'},{role:'user',content:'我自己'},{role:'assistant',content:'[保持安静]'},{role:'assistant',content:'已读',seenAt:1},{role:'assistant',content:'撤回',recalled:true}],pfIsHiddenTransport:m=>m.hidden,pfIsRpGrabTransport:m=>m.receipt});assert.equal(c.wxRoleUnread('a'),1);assert.equal(c.wxGroupUnread({msgs:[{senderId:'a',content:'你好'},{senderId:'me',content:'自己的'},{senderId:'a',type:'sys'},{senderId:'a',content:'[保持安静]'}]}),1);assert.equal(c.wxPfUnread([{from:'OTHER',time:2},{from:'ME',time:2},{from:'OTHER',time:2,hidden:true},{from:'OTHER',time:2,receipt:true}], 'OTHER',0,false),1);});
 test(label+': group model quotes user without attaching a quote, preserves other role full text',()=>{const long='完整原文'.repeat(100)+'末尾标记';const c=box(['gParseReply'],{S:{me:{name:'North'}},splitBubbles:t=>t.split(/\n/),normTag:t=>t,splitActions:t=>[t],parsePayCardLine:()=>null,LEAKRE:/^never-fixture$/,gName:m=>m.senderId,gmText:m=>m.content,uid:()=> 'id',gnm:(g,id)=>id==='me'?'North':id});const rows=[{senderId:'me',type:'text',content:long},{senderId:'a',type:'text',content:long}];assert(!c.gParseReply('[引用|1]\n知道了。',4,rows,{})[0].q);assert.equal(c.gParseReply('[引用|2]\n知道了。',4,rows,{})[0].q.text,long);});
}

// Lost write responses must be reconciled by a per-send token, never by resending.
for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){
 const app=fs.readFileSync(new URL(file,root),'utf8'),label=file==='app.js'?'web':'private';
 function source(name){const start=app.search(new RegExp('(?:async )?function '+name+'\\('));if(start<0)return '';const tail=app.slice(start),end=tail.slice(1).search(/\n(?:function |async function |const |let |\/\*)/);return end<0?tail:tail.slice(0,end+1);}
 function fixture(group=false){let seq=0;const p={id:'ME',secret:'fixture-secret',messages:{OTHER:[]},groupMessages:{GROUP:[]},clearBefore:{},groupClearBefore:{},lastSync:0};const notices=[],bills=[],server=[],calls=[];
  const ctx=vm.createContext({console,Date,Math,JSON,Set,Map,Array,String,Response,setTimeout,clearTimeout,btoa,atob,escape,unescape,encodeURIComponent,decodeURIComponent,
   PHONE_FRIEND_BODY_MAX:60000,GATE_URL:'https://direct.test',PF_RELAY_BASE:'https://relay.test',_pfTransportRoute:'https://direct.test',_pfTransportAt:Date.now(),_pfTransportProbe:null,_pfSendBusy:{},_pfPayloadCache:new WeakMap(),
   S:{settings:{sound:false}},phoneFriendState:()=>p,pfHeaders:()=>({apikey:'fixture-key'}),uid:()=>String(++seq),pfEnsure:async()=>true,pfMsgList:(map,k)=>map[k]||[],pfEnsureMsgList:(map,k)=>map[k]||(map[k]=[]),
   pfInferFriendRead:()=>{},pfInferGroupRead:()=>{},pfHandleTransferRefund:()=>false,pfIsRoomTransport:()=>false,pfHandleGamePayload:()=>{},pfAbsorbGroupBubbleStyle:()=>{},pfIsRpGrabTransport:()=>false,pfIsHiddenTransport:()=>false,pfIsGroupQrTransport:()=>false,pfIsGroupManageTransport:()=>false,pfGroupOutgoingBody:(g,b)=>b,
   readReceiptOn:()=>false,pfPayloadIsPay:()=>false,pfReadIds:()=>[],save:()=>{},render:()=>{},toast:t=>notices.push(t),addBill:(...v)=>bills.push(v),cur:()=>({p:group?'pfgroup':'pfchat',id:'OTHER',gid:'GROUP'}),phoneFriendSync:async()=>{},
   fetchT:async(url,opt)=>{const args=JSON.parse(opt.body);calls.push({url,args});if(url.endsWith('phone_friend_sync'))return new Response(JSON.stringify({messages:group?[]:server,group_messages:group?server:[]}));if(url.endsWith('search'))return new Response('[]');const row={id:'server-'+server.length,from_id:'ME',to_id:'OTHER',group_id:'GROUP',body:args.p_body,time:Date.now()};server.push(row);throw new TypeError('response lost');}
  });
  const names=['pfPack','pfUnpack','pfMsgPayload','pfSafeBody','pfPendingMatches','pfTagOutgoing','pfSetSendState','pfRecoverSend','pfTransportRecord','pfClearLocalPending','pfStoreMessage','pfStoreGroupMessage','pfRpc','pfTransportRoute','pfReadStatus','sendPhoneFriendBody','sendPhoneFriendGroupBody'];vm.runInContext(names.map(source).join('\n'),ctx);
  return{ctx,p,notices,bills,server,calls,send:(body,opt)=>group?ctx.sendPhoneFriendGroupBody('GROUP',body,opt):ctx.sendPhoneFriendBody('OTHER',body,opt)};
 }
 for(const group of [false,true])test(label+': '+(group?'group':'direct')+' delivered message with lost response reconciles without another write',async()=>{const f=fixture(group);await f.send('same words');const list=group?f.p.groupMessages.GROUP:f.p.messages.OTHER;assert.equal(f.calls.filter(x=>x.url.includes('send_')).length,1);assert.equal(f.calls.filter(x=>x.url.endsWith('phone_friend_sync')).length,1);assert.equal(list.length,1);assert.equal(list[0].id,'server-0');assert.deepEqual(f.notices,[]);});
 test(label+': identical consecutive texts have different tokens and cannot match the wrong pending item',async()=>{const f=fixture();f.ctx.fetchT=async(url,opt)=>{const args=JSON.parse(opt.body);f.calls.push({url,args});if(url.endsWith('phone_friend_sync'))return new Response(JSON.stringify({messages:f.server}));if(url.endsWith('search'))return new Response('[]');if(!f.server.length)f.server.push({id:'first',from_id:'ME',to_id:'OTHER',body:args.p_body,time:Date.now()});throw Error('lost response');};await f.send('same');await f.send('same');const bodies=f.calls.filter(x=>x.url.includes('send_')).map(x=>x.args.p_body);assert.notEqual(bodies[0],bodies[1]);assert.equal(f.p.messages.OTHER.filter(x=>x.id==='first').length,1);const pending=f.p.messages.OTHER.find(x=>String(x.id).startsWith('local_'));assert.equal(pending.sendState,'unknown');assert.equal(f.ctx.pfReadStatus(pending),'发送结果待确认');});
 test(label+': uncertain transfer is neither refunded nor submitted twice',async()=>{const f=fixture();f.ctx.fetchT=async()=>{throw Error('offline');};await f.send(f.ctx.pfPack({type:'transfer',amount:52}),{bill:{amount:52,note:'fixture'}});assert.equal(f.bills.filter(x=>x[0]==='in').length,0);assert.equal(f.p.messages.OTHER[0].sendState,'unknown');assert.match(f.notices.at(-1),/尚未确认/);});
 test(label+': confirmed transfer followed by local save failure never claims send failure or refunds',async()=>{const f=fixture();let saves=0;f.ctx.save=()=>{if(++saves===2)throw Error('disk');};f.ctx.fetchT=async(url,opt)=>new Response(JSON.stringify({id:'confirmed',from_id:'ME',to_id:'OTHER',body:JSON.parse(opt.body).p_body,time:Date.now()}));await f.send(f.ctx.pfPack({type:'transfer',amount:52}),{bill:{amount:52,note:'fixture'}});assert.equal(f.bills.filter(x=>x[0]==='in').length,0);assert.match(f.notices.at(-1),/消息已发送/);});
 test(label+': read-only connection failure does not assert any message was unsubmitted',async()=>{const f=fixture();f.ctx._pfTransportRoute='';f.ctx.fetchT=async()=>{throw Error('offline');};await assert.rejects(f.ctx.pfRpc('phone_friend_sync',{}),e=>!/消息尚未提交/.test(e.message));});
 test(label+': slower but healthy probe is allowed and diagnostics contain only bounded metadata',async()=>{const f=fixture();f.ctx._pfTransportRoute='';f.ctx.fetchT=async(url,opt,ms)=>{if(ms<6000)throw Error('slow');return new Response('[]');};await f.ctx.pfRpc('phone_friend_search',{p_query:'private words'});const records=f.p.transportDiagnostics;assert.ok(records.length>0);const json=JSON.stringify(records);assert.doesNotMatch(json,/private words|fixture-key|fixture-secret|p_body|p_secret/);assert.ok(records.every(x=>x.duration>=0));});
 test(label+': hung response body ends as unknown rather than freezing send',async()=>{const f=fixture();f.ctx.fetchT=async()=>({ok:true,status:200,text:()=>new Promise(()=>{})});const result=await Promise.race([f.ctx.pfRpc('phone_friend_send_message',{},20).catch(e=>e),new Promise(resolve=>setTimeout(()=>resolve('hung'),100))]);assert.equal(result.pfSubmissionUnknown,true);});
 test(label+': definite rejection refunds exactly once and does not start uncertain recovery',async()=>{const f=fixture();let writes=0;f.ctx.fetchT=async()=>{writes++;return new Response(JSON.stringify({message:'not-friends'}),{status:400});};await f.send(f.ctx.pfPack({type:'redpacket',amount:52}),{bill:{amount:52,note:'fixture'}});assert.equal(writes,1);assert.equal(f.bills.filter(x=>x[0]==='in').length,1);assert.equal(f.p.messages.OTHER.length,0);});
 test(label+': old pending messages retain compatibility, new tokens match beyond the old two minute window',()=>{const f=fixture(),now=Date.now();f.p.messages.OTHER.push({id:'local_old',from:'ME',to:'OTHER',text:'legacy',time:now});f.ctx.pfStoreMessage({id:'old-confirmed',from_id:'ME',to_id:'OTHER',body:'legacy',time:now});assert.equal(f.p.messages.OTHER.length,1);const tagged=f.ctx.pfTagOutgoing(f.ctx.pfPack({type:'voice',text:'你好',dur:2}),'late');const pl=f.ctx.pfUnpack(tagged);assert.equal(pl.type,'voice');assert.equal(pl.text,'你好');f.p.messages.OTHER.push({id:'local_late',from:'ME',to:'OTHER',text:tagged,time:now-300000,sendState:'unknown'});f.ctx.pfStoreMessage({id:'late-confirmed',from_id:'ME',to_id:'OTHER',body:tagged,time:now});assert.equal(f.p.messages.OTHER.filter(x=>String(x.id).startsWith('local_')).length,0);});
 test(label+': invalid successful acknowledgement triggers read-only recovery',async()=>{const f=fixture();let writes=0;f.ctx.fetchT=async(url,opt)=>{if(url.endsWith('phone_friend_sync'))return new Response(JSON.stringify({messages:f.server}));writes++;f.server.push({id:'ack-lost',from_id:'ME',to_id:'OTHER',body:JSON.parse(opt.body).p_body,time:Date.now()});return new Response('null');};await f.send('hello');assert.equal(writes,1);assert.equal(f.p.messages.OTHER[0].id,'ack-lost');assert.deepEqual(f.notices,[]);});
 test(label+': uncertain group packet claim retains pending claim instead of permitting another grab',async()=>{const f=fixture(true);f.ctx.fetchT=async()=>{throw Error('offline');};const result=await f.send(f.ctx.pfPack({type:'rp_grab',mid:'packet'}),{silent:true});assert.equal(result.pending,true);const grabs=[{who:'ME',id:'local_claim'}];Object.assign(f.ctx,{pfRpFind:()=>({gid:'GROUP',pay:{},m:{}}),pfRpState:()=>({}),pfRpGrabStore:()=>({packet:grabs}),sendPhoneFriendGroupBody:async()=>result});vm.runInContext(source('pfRpGrab'),f.ctx);assert.equal(f.ctx.pfRpGrab('packet'),true);await new Promise(r=>setTimeout(r,0));assert.equal(grabs.length,1);assert.match(f.notices.at(-1),/领取结果尚未确认/);});
 test(label+': profile failure is labelled as an operation, never as an unconfirmed message',async()=>{const f=fixture();f.ctx.fetchT=async()=>{throw Error('offline');};await assert.rejects(f.ctx.pfRpc('phone_friend_upsert_profile',{}),e=>e.pfSubmissionUnknown&&/操作结果尚未确认/.test(e.message)&&!/发送结果/.test(e.message));});
}
