import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const old=name=>execFileSync('git',['show','4ba40416:'+name],{encoding:'utf8',maxBuffer:20*1024*1024});
const read=name=>fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');
const prefixes=['','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'];
function petRun(src,text,linked=true){const fn=src.slice(src.indexOf('function deskPetConsume('),src.indexOf('/* ---------- 设置页',src.indexOf('function deskPetConsume(')));let calls=[];const out=Function('cfg','doCmd','ROLE_CMD_MS',fn+';return deskPetConsume(arguments[3],arguments[4]);')(()=>({on:true,cid:'a'}),v=>{calls.push(v);return v==='醒来'||v==='开心';},1,text,{id:linked?'a':'b'});return {out,calls};}
test('missing pet delimiter reproduces old leak, executes once in both runtimes and preserves role binding',()=>{assert.equal(petRun(old('desk-pet.js'),'[桌宠醒来]').out,'[桌宠醒来]');for(const p of prefixes){const s=read(p+'desk-pet.js');assert.deepEqual(petRun(s,'马上醒来。\n[桌宠醒来]'),{out:'马上醒来。',calls:['醒来']});assert.deepEqual(petRun(s,'[桌宠｜醒来]\n[桌宠开心]'),{out:'',calls:['醒来']});assert.deepEqual(petRun(s,'[桌宠醒来]',false),{out:'',calls:[]});assert.deepEqual(petRun(s,'今天聊聊桌宠。'),{out:'今天聊聊桌宠。',calls:[]});}});
test('bank excludes withdrawn and declined cards while leaving valid cards and historical expenses intact',()=>{const cards=[{status:'revoked',fromName:'撤回测试',balance:0},{status:'declined',fromName:'拒绝测试',balance:0},{status:'pending',fromName:'赠卡人',balance:5200000},{status:'active',fromName:'赠卡人',balance:131400}],orders=[{account:'main',cid:'a',item:'旧卡购买的花',source:'亲属卡',time:1,cents:1000}];const run=s=>{const fn=s.slice(s.indexOf('function familyRoleBank('),s.indexOf('\nfunction ',s.indexOf('function familyRoleBank(')+1));return Function('cards','ledger','account','esc','money','status',fn+';return familyRoleBank("a");')(()=>cards,()=>({orders}),()=> 'main',String,n=>(n/100).toFixed(2),k=>k.status);};assert(run(old('role-family-card.js')).includes('撤回测试'));for(const p of prefixes){const html=run(read(p+'role-family-card.js'));assert(!html.includes('撤回测试'));assert(!html.includes('拒绝测试'));assert(html.includes('52000.00')&&html.includes('1314.00')&&html.includes('旧卡购买的花'));assert.equal(cards.length,4);}});
test('legacy generated names and control-only memories are repaired without replacing arbitrary genuine names',()=>{for(const p of prefixes){const s=read(p+'app.js'),start=s.indexOf('function repairGeneratedRoleMemories('),fn=s.slice(start,s.indexOf('\nfunction memoryList',start));const input=['[桌宠醒来]','【偷登我微信·完整记录】忆北偷偷登录过我的微信：【忆北冒充我发的】你好。','我的朋友叫忆北。',{text:'真正重要的约定',rolePerspective:true}];const result=Function('S',fn+';return repairGeneratedRoleMemories(arguments[1]);')({me:{name:'测试玩家'}},input);assert.equal(result.length,3);assert(result[0].includes('测试玩家'));assert(!result[0].includes('忆北'));assert.equal(result[1],input[2]);assert.equal(result[2],input[3]);assert.equal(input.length,4);}});
