import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function env(){const c={id:'role',innerThought:'上一条真实内心',innerThoughtAt:123},bar={style:{},setAttribute(){}},label={},s={Date,String,save(){},wechatNaturalOn:()=>true,S:{settings:{showMoodTag:true}},cur:()=>({p:'chat',id:'role'}),getC:()=>c,$:id=>id==='#chatMoodBar'?bar:label};const ctx=vm.createContext(s);for(const name of ['naturalInnerThoughtText','rememberValidInnerThought','visibleRoleThought','setNaturalInnerThought','refreshChatMood']){const line=app.split('\n').find(x=>x.startsWith('function '+name+'('));if(line)vm.runInContext(line,ctx);}return{ctx,c,bar,label,s};}
test('invalid thought content never replaces the last confirmed output',()=>{for(const invalid of ['[内心|坏格式','[转账|100]','<think>分析</think>','\u200b\u2060','undefined',{}]){const h=env();assert.equal(h.ctx.setNaturalInnerThought(h.c,invalid),false);assert.equal(h.c.innerThought,'上一条真实内心');assert.equal(h.c.innerThoughtAt,123);}});
test('empty current field after a confirmed display cannot hide the whole bar',()=>{const h=env();h.ctx.refreshChatMood('role');h.c.innerThought='';h.ctx.refreshChatMood('role');assert.equal(h.bar.style.display,'flex');assert.equal(h.label.textContent,'上一条真实内心');});
test('confirmed fallback survives save/load and opening the chat again',()=>{const h=env();h.ctx.refreshChatMood('role');const stored=JSON.parse(JSON.stringify(h.c));stored.innerThought='';const next=env();Object.assign(next.c,stored);next.ctx.refreshChatMood('role');assert.equal(next.bar.style.display,'flex');assert.equal(next.label.textContent,'上一条真实内心');assert.equal(next.c.innerThoughtAt,123);});
test('explicitly disabled setting still hides the mood bar',()=>{const h=env();h.ctx.refreshChatMood('role');h.s.S.settings.showMoodTag=false;h.ctx.refreshChatMood('role');assert.equal(h.bar.style.display,'none');h.s.S.settings.showMoodTag=true;h.c.innerThought='';h.ctx.refreshChatMood('role');assert.equal(h.bar.style.display,'flex');});
test('new valid thought replaces the fallback; never fabricate absent history',()=>{const h=env();assert.equal(h.ctx.setNaturalInnerThought(h.c,'新的真实内心'),true);h.c.innerThought='';assert.equal(h.ctx.visibleRoleThought(h.c),'新的真实内心');assert.equal(h.ctx.visibleRoleThought({id:'new'}),'');});
test('enabled bar without recoverable history keeps its frame without inventing thought',()=>{const h=env();delete h.c.innerThought;h.ctx.refreshChatMood('role');assert.equal(h.bar.style.display,'flex');assert.equal(h.label.textContent,'…');assert.equal(h.c.innerThoughtLastValid,undefined);});
