import assert from "node:assert/strict";
import fs from "node:fs";

const source = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const html = fs.readFileSync(new URL("../小手机.html", import.meta.url), "utf8");
const glassCss = fs.readFileSync(new URL("../glass-theme.css", import.meta.url), "utf8");

assert.match(source, /class="music-premium music-disc-\$\{musicDiscColor\(\)\}"/);
assert.match(source, /class="music-ambient"/);
assert.match(source, /id="m_disk" class="music-vinyl"/);
assert.doesNotMatch(source, /id="m_arm"/);
assert.match(source, /class="music-classic-together"/);
assert.match(source, /class="music-headphone-pair"/);
assert.match(source, /M62 28 C50 41 43 62 48 86/);
assert.match(source, /class="music-classic-distance"/);
assert.match(source, /class="music-headphone-action"[\s\S]*?<\/div><button class="music-classic-distance"[\s\S]*?<div class="music-bubbles">/);
assert.match(source, /function musicToggleChat\(\)/);
assert.match(source, /id="musicChatDock" class="music-chat-dock/);
assert.match(source, /mine\?'rgba\(255,255,255,\.98\)'\:'rgba\(72,73,78,\.98\)'/);
assert.match(source, /class="music-library-row/);
assert.match(source, /function musicEnsureCurrent\(\)/);
assert.match(source, /wanted=\(S\.music\.session&&S\.music\.session\.songId\)\|\|S\.music\.lastSongId/);
assert.match(source, /function musicLibraryRowHTML\(/);
assert.match(source, /function renderMusicHome\(\)/);
assert.match(source, /class="music-app\$\{bg\?' has-bg':''\}"/);
assert.match(source, /class="music-app-actions"/);
assert.match(source, /class="music-home-library"/);
assert.match(source, /class="music-mini"/);
assert.match(source, /function musicOpenPlayer\(/);
assert.match(source, /function musicExpandPlayer\(/);
assert.match(source, /function musicLyricIndex\(lines,time\)/);
assert.match(source, /function mLyricLoopStart\(\)/);
assert.match(source, /el\.style\.color=on\?'#ffd6e8':'#7d7d88'/);
assert.match(source, /mLyricTick\(true\)/);
assert.match(source, /\(\?:\[\.:,\]\(\\d\{1,3\}\)\)\?/);
assert.match(source, /function musicChatContacts\(\)[\s\S]*?filter\(c=>c&&!c\.deleted\)/);
assert.match(source, /function musicChatRows\(cid\)/);
assert.match(source, /function musicChatHistoryModal\(cid\)/);
assert.match(source, /onchange="musicChatHistoryModal\(this\.value\)"/);
assert.match(source, /已删除角色的记录不会在这里显示/);
assert.match(source, /onclick="musicOpenHome\(\)" aria-label="缩小播放器"/);
assert.match(source, /if\(_mView!==\'player\'\|\|!cur\)return renderMusicHome\(\)/);
assert.match(source, /class="music-settings"/);
assert.match(source, /class="music-settings-quick"/);
assert.match(source, /class="music-disc-picker"/);
assert.match(source, /function musicDiscColorSet\(color\)/);
assert.match(source, /function musicDiscColorInput\(color\)/);
assert.match(source, /function musicDiscColorModal\(\)/);
assert.match(source, /<b>唱片颜色<\/b><small>当前：\$\{musicDiscColorName\(discColor\)\} · 黑\/白\/蓝\/粉<\/small>/);
assert.match(source, /function musicDiscColorNormalize\(color\)/);
assert.match(source, /type="color" value="\$\{customValue\}" aria-label="自定义唱片颜色"/);
assert.match(source, /oninput="musicDiscColorInput\(this\.value\)" onchange="musicDiscColorInput\(this\.value\)"/);
assert.match(source, /唱片颜色独立保存，不跟随主屏主题/);
assert.match(source, /支持任意颜色/);
assert.match(source, /onclick="musicDiscColorModal\(\)"/);
assert.match(source, /唱片颜色独立设置，不会跟随主屏主题/);
assert.match(source, /discColor:\s*musicDiscColor|discColor\}/);
assert.match(source, /class="music-library-modal"/);
assert.match(source, /class="music-seek-fill"/);
assert.match(html, /\.music-premium\{/);
assert.match(html, /\.music-vinyl\{/);
assert.match(html, /repeating-radial-gradient\(circle at center/);
assert.match(html, /\.music-headphone-pair\{/);
assert.match(html, /\.music-chat-dock\.collapsed \.music-chatbar\{display:none\}/);
assert.match(html, /\.music-app-hero-record\{right:10px!important\}/);
assert.match(html, /--music-red:#eb4d57/);
assert.match(html, /\.music-app\{/);
assert.match(html, /\.music-mini\{/);
assert.match(html, /\.music-home-song\{/);
assert.match(html, /\.music-lyrics\{overflow-x:hidden!important;overflow-y:auto!important/);
assert.match(html, /\.music-lyrics\{[^}]*touch-action:pan-y/);
assert.match(html, /\.music-lyrics::-webkit-scrollbar\{display:none\}/);
assert.match(html, /\.music-stage\{min-height:0;flex:0 0 clamp\(190px,28vh,240px\)\}/);
assert.match(html, /\.music-meta\{margin-top:clamp\(18px,2\.4vh,24px\);padding:0 26px 3px\}/);
assert.match(html, /\.music-lyrics\{height:clamp\(92px,14vh,120px\);padding:0 22px\}/);
assert.match(html, /\.music-lyrics \.mlrc\{font-size:13px;line-height:1\.8\}/);
assert.match(html, /\.music-controls\{margin-top:auto;padding:1px 22px 16px\}/);
assert.match(html, /\.music-chat-toggle\{font-size:13px\}/);
assert.match(html, /\.music-chatbar textarea\{[^}]*font-size:16px!important/);
assert.match(html, /\.music-chatbar \.send\{[^}]*background:linear-gradient\(145deg,rgba\(255,255,255,\.99\)/);
assert.match(html, /\.music-headphone-action\{[^}]*radial-gradient\(circle at 34% 20%/);
assert.match(html, /\.music-vinyl-cover\{inset:30px\}/);
assert.match(html, /html\.north-apple-remote-safe \.music-stage\{[^}]*flex-basis:clamp\(168px,22vh,202px\)/);
assert.match(html, /html\.north-apple-remote-safe \.music-lyrics\{height:clamp\(68px,9vh,78px\)\}/);
assert.match(html, /@media\(max-height:720px\)\{\.music-meta\{margin-top:14px\}[\s\S]*?\.music-lyrics \.mlrc\{font-size:12px;line-height:1\.75\}[\s\S]*?\.music-controls\{padding-bottom:12px\}\.music-chat-toggle\{font-size:12px\}\}/);
assert.doesNotMatch(html, /\.music-lyrics \.mlrc\.on\{color:#ffd6e8!important/);
assert.match(html, /\.music-settings\{/);
assert.match(glassCss, /\.music-disc-picker\{/);
assert.match(glassCss, /\.music-premium\[class\*="music-disc-#"\] \.music-vinyl\{/);
assert.match(glassCss, /--music-disc-custom/);
assert.match(glassCss, /\.music-disc-picker\.music-disc-picker-custom\{/);
assert.match(html, /\.music-library-modal\{/);
assert.match(html, /@media\(max-height:720px\)/);
assert.match(source, /music:'<path d="M9\.2 17\.5V7\.2l9\.1-2\.1v9\.2"/);
assert.match(source, /m\.type==='musicinvite'[\s\S]*svgIc\('music',32,'#effcff',1\.45\)/);
assert.match(source, /linear-gradient\(135deg,rgba\(35,91,113,\.96\),rgba\(82,132,152,\.86\) 56%,rgba\(117,163,180,\.78\)\)/);
assert.match(source, /background:linear-gradient\(145deg,rgba\(255,255,255,\.18\),rgba\(255,255,255,\.055\)\)/);

const menuStart = source.indexOf("function musicMenu(");
const menuEnd = source.indexOf("function musicChatHistoryModal(", menuStart);
assert.ok(menuStart >= 0 && menuEnd > menuStart, "music menu source must be present");
assert.doesNotMatch(source.slice(menuStart, menuEnd), /[↩🎵🎧🖼]/u);

const homeStart = source.indexOf("function renderMusicHome(");
const homeEnd = source.indexOf("function renderMusic(", homeStart);
assert.ok(homeStart >= 0 && homeEnd > homeStart, "music home source must be present");
assert.doesNotMatch(source.slice(homeStart, homeEnd), /<em>\$\{chatCount/,
  "history totals must not masquerade as an unread red badge");

console.log("music visual tests passed");
