import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import cp from 'node:child_process';

// Executed against PostgreSQL inside a transaction ending with ROLLBACK.
export const transactionSQL=String.raw`
do $test$
declare seller text:='SP'||upper(substr(md5(gen_random_uuid()::text),1,8));
 host text:='SP'||upper(substr(md5(gen_random_uuid()::text),1,8));guest text:='SP'||upper(substr(md5(gen_random_uuid()::text),1,8));
 s uuid:=gen_random_uuid();h uuid:=gen_random_uuid();g uuid:=gen_random_uuid();shop uuid;split uuid;oid uuid;request uuid:=gen_random_uuid();result jsonb;product jsonb;catalog jsonb;lines jsonb;address jsonb;failed boolean;balance bigint;scheduled timestamptz:=now()+interval '1 day';
begin
 insert into public.phone_friend_profiles(phone_id,secret_hash,display_name,allow_search) values(seller,public.phone_friend_hash('social-test-secret'),'事务店主',false),(host,public.phone_friend_hash('social-test-secret'),'事务发起人',false),(guest,public.phone_friend_hash('social-test-secret'),'事务好友',false);
 insert into public.phone_licenses(id,status,phone_friend_id) values(s,'active',seller),(h,'active',host),(g,'active',guest);
 product:=jsonb_build_object('id','tea','name','事务奶茶','groupId','drinks','price',2000,'unit','杯','description','','image','','signature',true,'available',true,'specGroups','[]'::jsonb);
 catalog:=jsonb_build_object('name','事务拼单茶铺','category','奶茶','intro','','cover','','minimum',2000,'delivery',191,'published',true,'groups',jsonb_build_array(jsonb_build_object('id','drinks','name','饮品')),'products',jsonb_build_array(product));
 shop:=(public.north_market_save_shop(seller,'social-test-secret',0,catalog)->>'id')::uuid;
 perform public.north_market_claim(seller,'social-test-secret');perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',50,'wallet',gen_random_uuid(),'00000',40000,false);
 perform public.north_market_claim(host,'social-test-secret');perform public.north_market_claim(guest,'social-test-secret');
 lines:=jsonb_build_array(jsonb_build_object('productId','tea','quantity',1,'selections','{}'::jsonb));address:=jsonb_build_object('name','验收','address','虚拟位置','phone','');
 failed:=false;begin perform public.north_market_split_create(host,'social-test-secret',request,guest,shop,1,lines,address,false,'',2191);exception when others then failed:=true;end;
 if not failed then raise exception 'FAIL non-friend invitation';end if;
 insert into public.phone_friend_requests(from_id,to_id,status) values(host,guest,'accepted');
 split:=(public.north_market_split_create(host,'social-test-secret',request,guest,shop,1,lines,address,false,'',2191)->>'id')::uuid;
 if (public.north_market_split_create(host,'social-test-secret',request,guest,shop,1,lines,address,false,'',2191)->>'id')::uuid<>split then raise exception 'FAIL duplicate invitation';end if;
 result:=public.north_market_split_get(host,'social-test-secret',null,request);
 if jsonb_array_length(result->'splits')<>1 or result->'splits'->0->>'client_id'<>request::text then raise exception 'FAIL client recovery lookup';end if;
 failed:=false;begin perform public.north_market_order_create(host,'social-test-secret',request,shop,1,lines,address,false,'','',null,'00000',2191,null);exception when others then failed:=true;end;
 if not failed then raise exception 'FAIL ordinary checkout bypasses split nonce';end if;
 failed:=false;begin perform public.north_market_split_pay(seller,'social-test-secret',split,'00000');exception when others then failed:=true;end;if not failed then raise exception 'FAIL outsider pays';end if;
 result:=public.north_market_split_pay(host,'social-test-secret',split,'11111');if result->>'ok'<>'false' then raise exception 'FAIL bad PIN';end if;
 perform public.north_market_split_pay(guest,'social-test-secret',split,'00000');perform public.north_market_split_pay(guest,'social-test-secret',split,'00000');
 if (public.north_market_wallet(guest,'social-test-secret')->>'balance')::bigint<>48904 then raise exception 'FAIL guest half or replay';end if;
 if exists(select 1 from public.north_market_orders where client_id=request) then raise exception 'FAIL order before both paid';end if;
 result:=public.north_market_split_pay(host,'social-test-secret',split,'00000');oid:=(result->>'orderId')::uuid;perform public.north_market_split_pay(host,'social-test-secret',split,'00000');
 if oid is null or (public.north_market_wallet(host,'social-test-secret')->>'balance')::bigint<>48905 then raise exception 'FAIL host half or replay';end if;
 if (public.north_market_order(guest,'social-test-secret',oid)->>'isBuyer')::boolean then raise exception 'FAIL guest owns order';end if;
 perform public.north_market_order_status(host,'social-test-secret',oid,'cancelled');perform public.north_market_order_status(host,'social-test-secret',oid,'cancelled');
 if (public.north_market_wallet(host,'social-test-secret')->>'balance')::bigint<>50000 or (public.north_market_wallet(guest,'social-test-secret')->>'balance')::bigint<>50000 then raise exception 'FAIL paid split refunds to each source';end if;
 split:=(public.north_market_split_create(host,'social-test-secret',gen_random_uuid(),guest,shop,1,lines,address,false,'',2191)->>'id')::uuid;
 perform public.north_market_split_pay(host,'social-test-secret',split,'00000');update public.north_market_splits set expires_at=now()-interval '1 second' where id=split;
 perform public.north_market_split_get(guest,'social-test-secret',split);perform public.north_market_split_get(host,'social-test-secret',split);
 if (public.north_market_wallet(host,'social-test-secret')->>'balance')::bigint<>50000 then raise exception 'FAIL expired refund';end if;
 address:=address||jsonb_build_object('scheduledAt',scheduled);
 result:=public.north_market_order_create(host,'social-test-secret',gen_random_uuid(),shop,1,lines,address,false,'','',null,'00000',2191,null);oid:=(result->'order'->>'id')::uuid;
 if (result->'order'->>'scheduled_at')::timestamptz<>scheduled then raise exception 'FAIL reservation snapshot';end if;
 perform public.north_market_order_status(seller,'social-test-secret',oid,'accepted');failed:=false;begin perform public.north_market_order_status(seller,'social-test-secret',oid,'ready');exception when others then failed:=true;end;if not failed then raise exception 'FAIL reservation sent early';end if;
 update public.north_market_orders set scheduled_at=now()-interval '1 second' where id=oid;
 perform public.north_market_order_status(seller,'social-test-secret',oid,'ready');perform public.north_market_order_status(seller,'social-test-secret',oid,'delivered');perform public.north_market_order_status(host,'social-test-secret',oid,'completed');
 failed:=false;begin perform public.north_market_order_status(host,'social-test-secret',oid,'cancelled');exception when raise_exception then failed:=SQLERRM='market-completed-order-no-refund';end;if not failed then raise exception 'FAIL completed buyer refund';end if;
 failed:=false;begin perform public.north_market_order_status(seller,'social-test-secret',oid,'cancelled');exception when raise_exception then failed:=SQLERRM='market-completed-order-no-refund';end;if not failed then raise exception 'FAIL completed seller refund';end if;
 perform public.north_market_review_save(host,'social-test-secret',oid,0,jsonb_build_object('rating',4,'text','评价','images','[]'::jsonb,'anonymous',true));
 failed:=false;begin perform public.north_market_reply(guest,'social-test-secret',oid,'冒充店主');exception when others then failed:=true;end;if not failed then raise exception 'FAIL wrong seller reply';end if;
 perform public.north_market_reply(seller,'social-test-secret',oid,'谢谢评价');perform public.north_market_reply(seller,'social-test-secret',oid,'谢谢评价');
 failed:=false;begin perform public.north_market_reply(seller,'social-test-secret',oid,'再次回复');exception when others then failed:=true;end;if not failed then raise exception 'FAIL second reply';end if;
 perform public.north_market_review_save(host,'social-test-secret',oid,1,jsonb_build_object('rating',5,'text','修改评价','images','[]'::jsonb,'anonymous',true));
 if public.north_market_reviews(shop,null)->'reviews'->0->>'seller_reply'<>'谢谢评价' then raise exception 'FAIL reply missing from public feed';end if;
 if (public.north_market_review_inbox(host,'social-test-secret',false,null)->>'unread')::integer<>1 then raise exception 'FAIL unread reply';end if;
 perform public.north_market_reply_read(guest,'social-test-secret',jsonb_build_array(oid));if (public.north_market_review_inbox(host,'social-test-secret',false,null)->>'unread')::integer<>1 then raise exception 'FAIL outsider clears unread';end if;
 perform public.north_market_reply_read(host,'social-test-secret',jsonb_build_array(oid));if (public.north_market_review_inbox(host,'social-test-secret',false,null)->>'unread')::integer<>0 then raise exception 'FAIL read acknowledgement';end if;
 raise notice 'PASS split shares/PIN/identity/replay/pending/refund/expiry, reservation, one seller reply and read acknowledgement';
if (select quantity from public.north_market_stock where shop_id=shop and product_id='tea')<>49 then raise exception 'FAIL reservation/refund inventory';end if;
 result:=public.north_market_business(seller,'social-test-secret');if (result->>'profit')::bigint<>1200 or (result->>'income')::bigint<>2000 then raise exception 'FAIL realized margin';end if;
 perform public.north_market_claim(host,'social-test-secret');if (public.north_market_wallet(host,'social-test-secret')->>'balance')::bigint<>47809 then raise exception 'FAIL grant repeats';end if;
 request:=gen_random_uuid();perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',1,'wallet',request,'00000',800,false);perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',1,'wallet',request,'00000',800,false);
 if (public.north_market_wallet(seller,'social-test-secret')->>'balance')::bigint<>9200 then raise exception 'FAIL restock replay';end if;
 perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',50,'wallet',gen_random_uuid(),'00000',40000,true);
 if (public.north_market_wallet(seller,'social-test-secret')->>'balance')::bigint<>49200 then raise exception 'FAIL return original cost';end if;
 failed:=false;begin perform public.north_market_quote(shop,1,lines);exception when raise_exception then failed:=SQLERRM='market-stock-unavailable';end;if not failed then raise exception 'FAIL soldout purchasable';end if;
 perform public.north_market_couple(seller,'social-test-secret','shop-partner','Partner');result:=public.north_market_business_notices(seller,'social-test-secret','shop-partner',null);
 if jsonb_array_length(result->'notices')<>1 then raise exception 'FAIL soldout notice';end if;
 perform public.north_market_business_notices(seller,'social-test-secret','shop-partner',jsonb_build_array(result->'notices'->0->>'id'));
 if jsonb_array_length(public.north_market_business_notices(seller,'social-test-secret','shop-partner',null)->'notices')<>0 then raise exception 'FAIL repeated stock notice';end if;
 result:=public.north_market_couple(host,'social-test-secret','partner','Partner');balance:=(result->'couple'->>'revision')::integer;
 if public.north_market_role_search(host,'social-test-secret','partner','tea')->>'status'<>'unfunded' then raise exception 'FAIL auto funded role';end if;
 perform public.north_market_transfer(host,'social-test-secret','wallet','couple','partner',5000,gen_random_uuid());
 perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',1,'income',gen_random_uuid(),'00000',800,false);
 result:=public.north_market_role_search(host,'social-test-secret','partner',product->>'name');if jsonb_array_length(result->'offers')<>1 or result->'offers'->0->>'shopId'<>shop::text then raise exception 'FAIL role live keyword search';end if;
 request:=gen_random_uuid();result:=public.north_market_role_order(host,'social-test-secret','partner',balance::integer,request,shop,1,lines,address,true,2191);oid:=(result->'order'->>'id')::uuid;
 perform public.north_market_role_order(host,'social-test-secret','partner',balance::integer,request,shop,1,lines,address,true,2191);
 result:=public.north_market_wallet(host,'social-test-secret');if (result->>'balance')::bigint<>42809 or (result->'couple'->>'balance')::bigint<>2809 then raise exception 'FAIL role pays source/replay';end if;
 perform public.north_market_order_status(host,'social-test-secret',oid,'cancelled');if (public.north_market_wallet(host,'social-test-secret')->'couple'->>'balance')::bigint<>5000 then raise exception 'FAIL role refund';end if;
 perform public.north_market_stock_change(seller,'social-test-secret',shop,'tea',1,'wallet',gen_random_uuid(),'00000',800,true);if (public.north_market_wallet(seller,'social-test-secret')->>'income')::bigint<>2000 then raise exception 'FAIL income-funded return';end if;
 failed:=false;begin perform public.north_market_shop_create(seller,'social-test-secret','Second','Food',gen_random_uuid(),20000,'00000');exception when raise_exception then failed:=SQLERRM='market-earned-profit-required';end;if not failed then raise exception 'FAIL expansion without profit';end if;
 -- Isolated rolled-back fixture for threshold and maximum-store checks.
 update public.north_market_orders set subtotal=100000,stock_cost=1000 where id in(select id from public.north_market_orders where seller_id=s::text and status='completed' limit 1);
 update public.north_market_wallets set income=100000 where owner_id=s::text;
 request:=gen_random_uuid();result:=public.north_market_shop_create(seller,'social-test-secret','Second','Food',request,20000,'00000');perform public.north_market_shop_create(seller,'social-test-secret','Second','Food',request,20000,'00000');
 perform public.north_market_shop_create(seller,'social-test-secret','Third','Food',gen_random_uuid(),40000,'00000');
 if (public.north_market_wallet(seller,'social-test-secret')->>'income')::bigint<>40000 then raise exception 'FAIL startup replay/fees';end if;
 failed:=false;begin perform public.north_market_shop_create(seller,'social-test-secret','Fourth','Food',gen_random_uuid(),40000,'00000');exception when raise_exception then failed:=SQLERRM='market-three-shop-limit';end;if not failed then raise exception 'FAIL fourth shop';end if;
end $test$;
`;

for(const priv of [false,true]){
 const src=fs.readFileSync(new URL(priv?'../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/commerce-ui.js':'../commerce-ui.js',import.meta.url),'utf8');
 test((priv?'private':'web')+' AI checkout has no minimum while fixed and owner-defined minimum remain',()=>{
  let rendered=0;const ctx={deliveryRealEnabled:()=>false,northValidSaleItem:()=>true,northMerchantSaved:()=>({id:'own',minimum:2500,delivery:200}),northMerchantSaleShop:()=>({id:'own',minimum:2500,delivery:200}),northCents:p=>Math.round(p*100),toast(){},northPersonalView:null,northMerchantView:null,northProductEdit:null,northMyView:null,northCouponView:null,northCouponPurchase:null,northOrderView:null,northCheckoutDraft:null,northView:null,actId:()=> 'main',uid:()=> 'request',northShopName:'Fixed',northAllowed:()=>false,closeModal(){},render:()=>rendered++,S:{food:{cart:[]}}};vm.createContext(ctx);vm.runInContext(src.match(/  function northCheckout\(items,generic\)\{[^\n]+/)[0]+';this.checkout=northCheckout;',ctx);
  ctx.checkout([{price:5,shop:'AI',_northGeneric:true}],true);assert.equal(ctx.northCheckoutDraft.minimum,0);assert.equal(rendered,1);
  ctx.northCheckoutDraft=null;ctx.checkout([{price:5,_northSku:'fixed'}],false);assert.equal(ctx.northCheckoutDraft,null);
  ctx.checkout([{price:20,_northMerchant:true}],true);assert.equal(ctx.northCheckoutDraft,null);
  ctx.checkout([{price:25,_northMerchant:true}],true);assert.equal(ctx.northCheckoutDraft.minimum,2500);
 });
 test((priv?'private':'web')+' visits expire at thirty days and a failed cleanup preserves saved history',async()=>{
  const now=Date.now(),day=86400000,keep={at:now-29*day,key:'recent'},old={at:now-30*day,key:'old'},favorite={key:'favorite'},rows=[keep,old,{at:now+day},{at:'invalid'}];let allow=false;
  const ctx={Date,northSaving:false,S:{food:{north:{personal:{main:{visits:rows,favorites:[favorite]},other:{visits:[old],favorites:[]}}}}},northCommit:async mutate=>{const undo=mutate();if(!allow)undo();return allow;}};vm.createContext(ctx);vm.runInContext(src.match(/  function northRecentVisits\(rows,now\)\{[^\n]+/)[0]+'\n'+src.match(/  async function northExpireFootprints\(\)\{[^\n]+/)[0]+';this.recent=northRecentVisits;this.cleanup=northExpireFootprints;',ctx);
  assert.equal(ctx.recent(rows,now).length,1);assert.equal(await ctx.cleanup(),false);assert.equal(ctx.S.food.north.personal.main.visits,rows);
  allow=true;assert.equal(await ctx.cleanup(),true);assert.equal(ctx.S.food.north.personal.main.visits.length,1);assert.equal(ctx.S.food.north.personal.other.visits.length,0);assert.equal(ctx.S.food.north.personal.main.favorites[0],favorite);
 });
 test((priv?'private':'web')+' a completed local order cannot refund or restore a used coupon',async()=>{
  const order={id:'done',status:'completed',total:2000};let refunded=0;const ctx={window:{},deliveryRealEnabled:()=>false,northSaving:false,northFind:()=>order,northStatus:o=>o.status,northFundingRefund:()=>refunded++,S:{me:{balance:50}}};vm.createContext(ctx);vm.runInContext(src.match(/  window.northRefund=async function\(id\)\{[^\n]+/)[0],ctx);await ctx.window.northRefund('done');assert.equal(refunded,0);assert.equal(order.status,'completed');assert.equal(ctx.S.me.balance,50);
 });
 test((priv?'private':'web')+' failed cloud shop import retains the prior shop and its library entry',async()=>{
  const prior={id:'old',marketId:'old-cloud',name:'Old'},target={id:'new-cloud',name:'New',published:true,revision:1,catalog:{groups:[],products:[]}},data={merchants:{main:prior},merchantLibrary:{main:{'old-cloud':prior}}};let opened=0;
  const ctx={window:{},S:{},northMarketBusy:false,actId:()=> 'main',northMarketEnsure:async()=>true,northMarketRpc:async()=>({shop:target}),northMerchantSaved:()=>prior,northData:()=>data,uid:()=> 'new-local',saveNowAsync:async()=>false,northMerchantEditor:()=>opened++,toast(){}};vm.createContext(ctx);vm.runInContext(src.match(/  window.northMarketManageMine=async function\(preview,shopId\)\{[^\n]+/)[0],ctx);
  await ctx.window.northMarketManageMine(false,target.id);assert.equal(data.merchants.main,prior);assert.equal(data.merchantLibrary.main['old-cloud'],prior);assert.equal(data.merchantLibrary.main['new-cloud'],undefined);assert.equal(opened,0);assert.equal(ctx.northMarketBusy,false);
 });
 test((priv?'private':'web')+' reserved simulated order cannot arrive before the selected time',()=>{
  const fn=src.match(/  function northStatus\(o\)\{[^\n]+/)[0],ctx={Date};vm.createContext(ctx);vm.runInContext(fn+';this.status=northStatus;',ctx);
  assert.equal(ctx.status({createdAt:Date.now()-120000,scheduledAt:Date.now()+3600000,status:'paid'}),'paid');
  assert.equal(ctx.status({createdAt:Date.now()-120000,scheduledAt:Date.now()-1000,status:'paid'}),'delivered');
  assert.equal(ctx.status({createdAt:Date.now()-120000,scheduledAt:Date.now()+3600000,status:'cancelled'}),'cancelled');
 });
 test((priv?'private':'web')+' stale local coupon PIN cannot debit a local wallet or mint new vouchers',async()=>{
  let closed=0;const ctx={northCouponPurchase:{authorized:true},northPinEntry:{},closeModal:()=>closed++,toast(){},S:{me:{balance:200},food:{north:{vouchers:[]}}}};vm.createContext(ctx);vm.runInContext(src.match(/  async function northFinalizeCouponPurchase\(\)\{[^\n]+/)[0]+';this.finalize=northFinalizeCouponPurchase;',ctx);
  assert.equal(await ctx.finalize(),false);assert.equal(ctx.S.me.balance,200);assert.equal(ctx.S.food.north.vouchers.length,0);assert.equal(ctx.northCouponPurchase,null);assert.equal(closed,1);
 });
}

for (const priv of [false,true]) {
 const src=fs.readFileSync(priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/commerce-ui.js':'commerce-ui.js','utf8');
 test((priv?'private':'web')+' main cloud vouchers retain colorful layout and actual cloud coupon fields',()=>{
  const c={id:'cloud-coupon',face:500,minimum:3500,inflated:true,expires_at:'2026-11-01T00:00:00Z'};
  const ctx={money:n=>(+n).toFixed(2),esc:String,fmtDT:n=>new Date(+n||1791356400000).toISOString(),mtGlyph:()=>'',northNavIcon:()=>'',northMarketNavigation:()=>'<nav>nav</nav>',window:{},toast:()=>{},northCouponPacks:[{id:'light',name:'轻享包',price:590},{id:'daily',name:'日常包',price:690}]};
  vm.createContext(ctx);vm.runInContext(src.split('\n').find(l=>l.startsWith('  function northMarketCouponCard('))+src.match(/  function northMarketCouponsHTML\(v\)\{[^\n]+/)[0],ctx);
  const html=ctx.northMarketCouponsHTML({busy:false,rows:[c]});
  assert.match(html,/north-voucher-header/);assert.match(html,/north-voucher-hero/);
  assert.match(html,/¥5\.00/);assert.match(html,/35\.00/);assert.match(html,/2026-11-01/);
  assert.match(html,/northMarketCouponBuy\(/);assert.match(html,/northMarketCouponBoost\(/);
  assert.doesNotMatch(html,/northStartCouponPurchase\(/);
 });
 test((priv?'private':'web')+' errand opens the runner without triggering a store search',()=>{
  let notices=[],searches=0;const ctx={window:{},toast:s=>notices.push(s),foodQuick:()=>searches++};
  vm.createContext(ctx);const handler=src.match(/  window\.mtFoodErrand=function\(\)\{[^\n]+/);
  assert.ok(handler,'errand development handler exists');vm.runInContext(handler[0],ctx);
  ctx.NorthRunner={open:()=>notices.push('game')};ctx.window.NorthRunner=ctx.NorthRunner;ctx.window.mtFoodErrand();assert.deepEqual(notices,['game']);assert.equal(searches,0);
 });
}

for(const priv of [false,true]){
 const src=fs.readFileSync(priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/commerce-ui.js':'commerce-ui.js','utf8');
 test((priv?'private':'web')+' rules page is read only and stock/wallet icons are distinct',()=>{
  const ctx={esc:String,northPersonalHeader:s=>'<header>'+s+'</header>',mtGlyph:()=>'<svg>order</svg>'};vm.createContext(ctx);
  vm.runInContext(src.match(/  function northPlayRulesHTML\(\)\{[^\n]+/)[0],ctx);
  const html=ctx.northPlayRulesHTML();assert.match(html,/玩法规则/);assert.match(html,/首次可领取500/);assert.match(html,/已完成订单不能退款/);assert.match(html,/真人店不支持亲属卡/);assert.doesNotMatch(html,/onclick=|<input|<form/);
  vm.runInContext(src.match(/  function northMyFunctionIcon\(kind\)\{[^\n]+/)[0],ctx);
  assert.match(ctx.northMyFunctionIcon('stock'),/data-north-icon="stock"/);assert.match(ctx.northMyFunctionIcon('wallet'),/data-north-icon="wallet"/);assert.notEqual(ctx.northMyFunctionIcon('stock'),ctx.northMyFunctionIcon('wallet'));
 });
}

// New role selection regressions use real functions with controlled RPC/model boundaries.
for(const priv of [false,true]){
 const file=priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/commerce-ui.js':'commerce-ui.js';
 const src=process.env.NORTH_ROLE_TEST_OLD?cp.execFileSync('git',['show','HEAD:'+file],{encoding:'utf8',maxBuffer:8e6}):fs.readFileSync(file,'utf8');
 function roleContext(opt={}){
  const c={id:'partner',name:'角色',model:'main'},identity={id:'phone',secret:'test'},data={},events=[],messages=[{role:'user',type:'text',content:'我要温的芋泥奶茶'}],state={me:{name:'我'}},coupon={id:'coupon',minimum:2000,face:300,expires_at:'2099-01-01T00:00:00Z'};
  const tea={id:'tea',name:'芋泥奶茶',price:1800,stock:5,available:true,soldOut:false,specGroups:[{id:'heat',name:'温度',required:true,mode:'single',options:[{id:'cold',label:'冰的',price:0},{id:'warm',label:'温的',price:100}]}]},addon={id:'addon',name:'小料',price:100,stock:5,available:true,soldOut:false,specGroups:[]},cake={id:'cake',name:'草莓小熊蛋糕',price:2500,stock:3,available:true,soldOut:false,specGroups:[]},wrong={id:'wrong',name:'巧克力蛋糕',price:2500,stock:3,available:true,soldOut:false,specGroups:[]};
  const shop={id:'shop',name:'真人店',revision:2,minimum:2000,delivery:190,products:[tea,addon,cake,wrong]},catalog={shops:[shop]},intent={queries:['芋泥','奶茶'],must:['芋泥','奶茶'],quantity:1,preferences:[{group:'温度',value:'温'}]},choice={shopId:'shop',primaryId:'tea',lines:[{productId:'tea',quantity:1,selections:{heat:['warm']}},{productId:'addon',quantity:1,selections:{}}]};
  let modelCalls=0,paid=0;const notices=[];const ctx={window:{},Date,JSON,Math,Set,esc:String,deliveryRealEnabled:()=>false,crypto:{randomUUID:()=> 'request'},S:state,location:{hostname:'localhost'},NORTH_PREVIEW:false,actId:()=> 'main',phoneFriendState:()=>identity,northMarketCoupleRole:()=>c,northData:()=>data,msgs:()=>messages,uid:()=> 'message',money:n=>(n).toFixed(2),save(){},saveNowAsync:async()=>{if(opt.finalFailure&&paid)throw Error('local save failed');return true;},northMarketWalletCache:null,northRoleFoodCard:()=>({type:'food'}),toast:s=>notices.push(s),roleChatRouteIndex:()=>0,chatAPI:async(ms,settings)=>{modelCalls++;events.push('model'+modelCalls);assert.equal(settings.independentRoleModel,true);if(opt.switchAccount&&modelCalls===1)ctx.actId=()=> 'other';if(ms[0].content.includes('提取本轮'))return JSON.stringify(intent);if(ms[0].content.includes('从真实菜单筛选'))return JSON.stringify(opt.badSpec?{...choice,lines:[{productId:'tea',quantity:2,selections:{heat:['cold']}}]}:choice);if(opt.finalFailure)throw Error('model offline');return JSON.stringify({message:'给你挑好了，慢慢享用吧。'});},northMarketRpc:async(name,args)=>{events.push(name);if(name==='wallet')return {couple:{id:c.id,balance:5000,revision:1}};if(name==='role_catalog'){assert.ok(args.p_queries.includes('芋泥奶茶')||args.p_queries.includes('芋泥'));assert.ok(args.p_required.includes('芋泥奶茶')||args.p_required.includes('芋泥'));if(opt.networkFailure)throw Error('network offline');return catalog;}if(name==='coupons')return {coupons:[coupon]};if(name==='quote')return {subtotal:2000,delivery:190,total:2190};if(name==='role_checkout'){paid++;assert.equal(args.p_coupon,'coupon');assert.equal(args.p_total,1890);assert.equal(args.p_topup,true);if(opt.unknown){const e=Error('timeout');e.httpStatus=504;throw e;}return {order:{id:'order',shop_name:'真人店',subtotal:2000,delivery:190,discount:300,total:1890,note:'角色点餐：为凑起送价增加商品或份数',items:[{productId:'tea',name:'芋泥奶茶',quantity:1,labels:['温的']},{productId:'addon',name:'小料',quantity:1,labels:[]}]}};}if(name==='orders')return {orders:[]};throw Error('unexpected RPC '+name);}};
  vm.createContext(ctx);let start=src.indexOf('  function northRoleFoodReceipt('),end=src.indexOf('  function northMarketRoleFoodCard(',start);assert.ok(start>=0&&end>start);vm.runInContext(src.slice(start,end),ctx);return {ctx,c,data,events,notices,catalog,shop,choice,intent,paid:()=>paid,modelCalls:()=>modelCalls};
 }


 test((priv?'private':'web')+' role buys from the shared live shop without searching and preserves quote/payment checks',async()=>{const t=roleContext(),rpc=t.ctx.northMarketRpc;t.ctx.northShareValid=card=>card.version===1;t.ctx.msgs().unshift({type:'shopshare',role:'user',shopShare:{version:1,source:'cloud',id:'shop',name:'真人店'}});t.ctx.northMarketRpc=async(name,args,auth)=>{if(name==='role_catalog'||name==='list')throw Error('shared shop must not search');if(name==='shop'){t.events.push('direct-shop');assert.equal(args.p_id,'shop');return {shop:t.shop,products:t.shop.products};}return rpc(name,args,auth);};const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','19|真人店|温度:温的|温的|1','main',{messageId:'shared'});assert.equal(result.type,'marketfood');assert.equal(t.paid(),1);assert.ok(t.events.includes('quote'));assert.ok(t.events.includes('direct-shop'));assert.ok(!t.events.includes('role_catalog'));});
 test((priv?'private':'web')+' picture-only and explicit query-only requests cannot execute a mistaken food tag',async()=>{for(const request of ['我想吃蛋糕，给我发张照片看看','只查店铺菜单，不要下单','不要付款，只生成图片']){const t=roleContext();let models=0;t.ctx.northRoleModel=async()=>{models++;return '{}';};const output=await t.ctx.northRoleEnsureAction(t.c,'好。[点外卖|芋泥奶茶|19|真人店|温|温|1]',request,{messageId:'no-purchase',northCurrentRequest:true});assert.ok(!output.includes('[点外卖|'));assert.equal(models,0);assert.equal(t.paid(),0);}});
 test((priv?'private':'web')+' queried real shops report empty role funds or mismatched cloud couple without virtual fallback or payment',async()=>{for(const scenario of ['empty','relationship']){const t=roleContext(),rpc=t.ctx.northMarketRpc;t.ctx.northMarketRpc=async(name,args,auth)=>name==='wallet'?{couple:{id:scenario==='empty'?t.c.id:'another-role',balance:0}}:rpc(name,args,auth);const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','1|真人店|温|温|1','main',{messageId:'queried-'+scenario,northCatalogOnly:true,northCurrentRequest:true});assert.equal(result._northOrderFailure,true);assert.match(result.content,scenario==='empty'?/角色云银行卡余额不足/:/云端情侣关系/);assert.equal(t.paid(),0);}});
 test((priv?'private':'web')+' minimum completion preserves user limits, real specs and inventory',()=>{const t=roleContext(),product={id:'beef',name:'宋式番茄炖牛腩',price:3700,stock:1,available:true,soldOut:false,specGroups:[]},addon={id:'rice',name:'青瓷米饭',price:200,stock:2,available:true,soldOut:false,specGroups:[]},shop={id:'shop',minimum:4800,products:[product,addon]},choice={shopId:'shop',primaryId:'beef',lines:[{productId:'beef',quantity:1,selections:{}}]},plan={must:['宋式番茄炖牛腩'],quantity:1,preferences:[],request:'不要凑单'};assert.throws(()=>t.ctx.northRoleCompleteMinimum(JSON.stringify(choice),{shops:[shop]},plan),/限制了加购/);plan.request='番茄牛腩';assert.throws(()=>t.ctx.northRoleCompleteMinimum(JSON.stringify(choice),{shops:[shop]},plan),/无法用少量/);choice.lines[0].selections={fake:['fake']};assert.throws(()=>t.ctx.northRoleCompleteMinimum(JSON.stringify(choice),{shops:[shop]},plan),/无法用少量/,'v1658: an invented spec group is dropped instead of failing the whole order');assert.equal(t.ctx.northRoleSimplePlan('宋式番茄炖牛腩','37|店|无|热的|1','那我要吃宋式番茄炖牛腩').preferences.length,0);assert.equal(t.ctx.northRoleSimplePlan('宋式番茄炖牛腩','37|店|无|不适用|1','我要热的宋式番茄炖牛腩').preferences.length,1);});
 test((priv?'private':'web')+' multiple virtual tags form one recoverable card containing every selected product',async()=>{const t=roleContext();t.ctx.northBuiltinShops=()=>[{name:'NORTH甜品店',products:[{name:'蓝莓小蛋糕',available:true},{name:'草莓芋泥蛋糕',available:true}]}];t.ctx.northRoleFoodCard=(c,name,body)=>({id:'local-'+name,from:'ta',type:'food',name,shop:'NORTH甜品店',price:15,foodDetail:{name,shop:'NORTH甜品店',subtotal:1500,quantity:1,specs:[],temperature:'不适用',source:'catalog',imageUrl:'original-'+name}});const meta={messageId:'multi-virtual',northCurrentRequest:true};const content=await t.ctx.northRoleEnsureAction(t.c,'好。\n[点外卖|蓝莓小蛋糕|15|NORTH甜品店|无|不适用|1]\n[点外卖|草莓芋泥蛋糕|15|NORTH甜品店|无|不适用|1]','蓝莓小蛋糕和草莓芋泥蛋糕都要',meta);assert.equal((content.match(/\[点外卖/g)||[]).length,1);const card=await t.ctx.northPreferredRoleFood(t.c,'蓝莓小蛋糕','15|NORTH甜品店|无|不适用|1','main',meta);assert.equal(card.foodDetail.items.length,2);assert.equal(card.price,30);assert.equal(card.foodDetail.subtotal,3000);assert.equal(card.foodDetail.items[1].imageUrl,'original-草莓芋泥蛋糕');t.ctx.msgs=()=>[card];assert.equal(await t.ctx.northPreferredRoleFood(t.c,'蓝莓小蛋糕','15','main',meta),null);assert.equal(t.paid(),0);});
 test((priv?'private':'web')+' requested multiple foods are mandatory rather than unnecessary topups',()=>{const t=roleContext(),plan={...t.intent,items:[{name:'芋泥奶茶',must:['芋泥','奶茶'],quantity:1,preferences:[{group:'温度',value:'温'}]},{name:'小料',must:['小料'],quantity:1,preferences:[]}]};const offer=t.ctx.northRoleChoice(JSON.stringify(t.choice),t.catalog,plan);assert.equal(offer.extra,false);assert.equal(offer.requestedQuantities.tea,1);assert.equal(offer.requestedQuantities.addon,1);const missing={...t.choice,lines:[t.choice.lines[0]]};assert.throws(()=>t.ctx.northRoleChoice(JSON.stringify(missing),t.catalog,plan),/缺少.*商品|没有覆盖/);});
 test((priv?'private':'web')+' short buy after a shared restaurant continues two discussed dishes to one paid receipt without search',async()=>{const t=roleContext(),now=Date.now(),share={version:1,source:'cloud',id:'shared',name:'闲云野鹤居'},messages=[{id:'share',role:'user',type:'shopshare',shopShare:share,time:now-60000},{id:'talk',role:'assistant',type:'text',content:'刚让先生给你点牛腩和小炒肉，转头自己偷偷下单草莓布蕾丝。刚才只查店铺菜单，不要下单。',time:now-50000},{id:'buy',role:'user',type:'text',content:'给我买',time:now}],products=[{id:'beef',name:'宋式番茄炖牛腩',price:3700,stock:5,available:true,specGroups:[]},{id:'pork',name:'山房小炒肉',price:3900,stock:5,available:true,specGroups:[]}];let paid=0,repairs=0;share.products=products;t.ctx.msgs=()=>messages;t.ctx.northShareValid=()=>true;t.ctx.northRoleModel=async(c,task,payload)=>{if(task.includes('本轮用户明确请求点餐')){repairs++;assert.equal(payload.sharedShopMenu.products.length,2);assert.match(payload.userRequest,/给我买/);assert.match(payload.userRequest,/牛腩和小炒肉/);return JSON.stringify({order:true,name:'宋式番茄炖牛腩',shop:'闲云野鹤居',specs:'无',temperature:'不适用',quantity:1});}if(task.includes('提取本轮'))return JSON.stringify({queries:['牛腩','小炒肉'],must:['牛腩'],quantity:1,preferences:[],items:[{name:'宋式番茄炖牛腩',must:['牛腩'],quantity:1,preferences:[]},{name:'山房小炒肉',must:['小炒肉'],quantity:1,preferences:[]}]});if(task.includes('从真实菜单筛选'))return JSON.stringify({shopId:'shared',primaryId:'beef',lines:products.map(p=>({productId:p.id,quantity:1,selections:{}}))});return JSON.stringify({message:'给你点好了。'});};t.ctx.northMarketRpc=async(name,args)=>{if(name==='role_catalog'||name==='list')throw Error('must open shared shop directly');if(name==='wallet')return {couple:{id:t.c.id,balance:100000,revision:1}};if(name==='shop')return {shop:{id:'shared',name:'闲云野鹤居',revision:1,minimum:4800,delivery:190},products};if(name==='coupons')return {coupons:[]};if(name==='quote')return {subtotal:7600,delivery:190,total:7790};if(name==='role_checkout'){paid++;assert.equal(args.p_total,7790);assert.equal(args.p_lines.length,2);return {order:{id:'two-dishes',shop_name:'闲云野鹤居',total:7790,subtotal:7600,delivery:190,items:products.map(p=>({...p,quantity:1,labels:[],total:p.price}))}};}if(name==='orders')return {orders:[]};throw Error(name);};const request=t.ctx.northRoleOrderRequest(t.c,'给我买');assert.match(request.text,/闲云野鹤居/);const meta={messageId:'buy',northRequestKey:request.anchorId,northUserRequest:request.text,northActualUserText:request.actualText,northCurrentRequest:true};const action=await t.ctx.northRoleEnsureAction(t.c,'[应用查询|闲云野鹤居]','给我买',meta);assert.ok(action.includes('[点外卖|'));assert.equal(repairs,1);const card=await t.ctx.northPreferredRoleFood(t.c,'宋式番茄炖牛腩','1|闲云野鹤居|无|不适用|1','main',meta);assert.equal(card.type,'marketfood',JSON.stringify(card));assert.equal(card.marketFood.order.items.length,2);assert.equal(paid,1);messages.push(card);await t.ctx.northPreferredRoleFood(t.c,'宋式番茄炖牛腩','1|闲云野鹤居|无|不适用|1','main',meta);assert.equal(paid,1);});
 test((priv?'private':'web')+' beef purchase repairs without dessert keywords, while expired shared context never becomes a purchase request',async()=>{const t=roleContext();let repairs=0;t.ctx.northRoleModel=async()=>{repairs++;return JSON.stringify({order:true,name:'宋式番茄炖牛腩',shop:'闲云野鹤居',specs:'无',temperature:'不适用',quantity:1});};const action=await t.ctx.northRoleEnsureAction(t.c,'查到了店铺。','给我买牛腩',{messageId:'beef-buy',northCurrentRequest:true});assert.ok(action.includes('[点外卖|宋式番茄炖牛腩'));assert.equal(repairs,1);t.ctx.northShareValid=()=>true;t.ctx.msgs=()=>[{role:'user',type:'shopshare',time:Date.now()-1300000,shopShare:{source:'cloud',name:'旧店'}},{role:'assistant',type:'text',content:'牛腩和小炒肉',time:Date.now()-1250000},{role:'user',type:'text',id:'new',content:'给我买',time:Date.now()}];assert.equal(t.ctx.northRoleShortBuyContext(t.c,'给我买'),'');assert.equal(t.ctx.northRoleShortBuyContext(t.c,'只看菜单，不下单'),'');assert.equal(t.ctx.northRoleShortBuyContext(t.c,'分享店铺'),'');});
 test((priv?'private':'web')+' real food assent repairs a request without demanding an invented menu price',async()=>{const t=roleContext();t.ctx.northRoleModel=async()=>JSON.stringify({order:true,name:'宋式番茄炖牛腩',shop:'闲云野鹤居',specs:'无',temperature:'不适用',quantity:1});const meta={messageId:'real-intent',northCurrentRequest:true};t.ctx.pushMsg=()=>{};t.ctx.refreshChatMessages=()=>{};const content=await t.ctx.northRoleEnsureAction(t.c,'先生给你点，但先吃先生煎的蛋。','那我要吃宋式番茄炖牛腩',meta);assert.match(content,/\[点外卖\|宋式番茄炖牛腩\|1\|闲云野鹤居/);assert.equal(meta.northCatalogOnly,true);t.ctx.northMarketRpc=async()=>({couple:{id:t.c.id,balance:0}});const failed=await t.ctx.northPreferredRoleFood(t.c,'宋式番茄炖牛腩','1|闲云野鹤居|无|不适用|1','main',meta);assert.equal(failed.type,'sys','a real-menu-only request may never turn into a fabricated one-yuan virtual receipt');assert.equal(t.paid(),0);});
 test((priv?'private':'web')+' real tomato beef without temperature specs reaches minimum with least stock-backed topup',async()=>{const t=roleContext(),beef={id:'beef',name:'宋式番茄炖牛腩',price:3700,stock:2,available:true,soldOut:false,specGroups:[]},rice={id:'rice',name:'青瓷米饭',price:200,stock:2,available:true,soldOut:false,specGroups:[]},lotus={id:'lotus',name:'桂花糯米藕',price:1000,stock:2,available:true,soldOut:false,specGroups:[]};const shop={id:'beef-shop',name:'闲云野鹤居',revision:1,minimum:4800,delivery:190,products:[beef,rice,lotus]};let calls=0,paid=0,quoted;t.ctx.msgs=()=>[{role:'user',type:'text',content:'那我要吃宋式番茄炖牛腩'}];t.ctx.northRoleModel=async()=>JSON.stringify({shopId:shop.id,primaryId:'beef',lines:[{productId:'beef',quantity:1,selections:{}}]});t.ctx.northMarketRpc=async(name,args)=>{calls++;if(name==='wallet')return {couple:{id:t.c.id,balance:8000,revision:1}};if(name==='role_catalog')return {shops:[shop]};if(name==='coupons')return {coupons:[]};if(name==='quote'){quoted=args.p_lines;const subtotal=args.p_lines.reduce((sum,line)=>sum+shop.products.find(p=>p.id===line.productId).price*line.quantity,0);return {subtotal,total:subtotal+190};}if(name==='role_checkout'){paid++;assert.equal(args.p_total,5090);assert.equal(args.p_topup,true);return {order:{id:'beef-order',shop_name:shop.name,total:5090,subtotal:4900,delivery:190,discount:0,items:args.p_lines.map(line=>({...shop.products.find(p=>p.id===line.productId),quantity:line.quantity})),note:'角色点餐：为凑起送价增加商品或份数'}};}throw Error('unexpected '+name);};const card=await t.ctx.northPreferredRoleFood(t.c,'宋式番茄炖牛腩','37|闲云野鹤居|无|热的|1','main',{messageId:'beef-request',userText:'那我要吃宋式番茄炖牛腩',northCurrentRequest:true});assert.equal(card.type,'marketfood');assert.equal(paid,1);assert.equal(quoted.reduce((sum,line)=>sum+line.quantity,0),3);assert.equal(quoted.find(line=>line.productId==='beef').quantity,1);assert.equal(quoted.find(line=>line.productId==='rice').quantity,1);assert.equal(quoted.find(line=>line.productId==='lotus').quantity,1);t.ctx.msgs=()=>[card];assert.equal(await t.ctx.northPreferredRoleFood(t.c,'宋式番茄炖牛腩','37','main',{messageId:'beef-request'}),null);assert.equal(paid,1);});
 test((priv?'private':'web')+' fixed dessert intent carries original menu and explicit builtin needs no cloud wallet',async()=>{const t=roleContext(),builtin={window:{}};vm.runInNewContext(fs.readFileSync('assets/north-dessert-shop.js','utf8'),builtin);t.ctx.northBuiltinShops=()=>builtin.window.NorthBuiltinShops;t.ctx.northMerchantSaved=()=>null;let received;t.ctx.northRoleModel=async(c,task,payload)=>{received=payload.localMenus;return JSON.stringify(received?{order:true,name:'蓝莓小蛋糕',shop:'NORTH甜品店',specs:'无',temperature:'不适用',quantity:1}:{order:true,name:'蓝莓小蛋糕',body:'15|NORTH甜品店|无|不适用|1'});};const repaired=await t.ctx.northRoleEnsureAction(t.c,'乖，嘴倒是甜了。喝口水，等着。','我想吃蓝莓小蛋糕给我点',{messageId:'fixed',northCurrentRequest:true});assert.ok(received,'intent classifier must receive original local menus rather than invent prices');assert.match(repaired,/\[点外卖\|蓝莓小蛋糕\|15\|NORTH甜品店\|无\|不适用\|1\]/);t.ctx.northRoleFoodCard=()=>({id:'local-fixed',type:'food',from:'ta'});t.ctx.northMarketRpc=async()=>{throw Error('cloud is offline');};const meta={messageId:'fixed',northCurrentRequest:true};const first=await t.ctx.northPreferredRoleFood(t.c,'蓝莓小蛋糕','15|NORTH甜品店|无|不适用|1','main',meta);assert.equal(first.type,'food','explicit builtin must not depend on cloud wallet');assert.equal(t.paid(),0);t.ctx.msgs=()=>[first];assert.equal(await t.ctx.northPreferredRoleFood(t.c,'蓝莓小蛋糕','15|NORTH甜品店|无|不适用|1','main',meta),null);});
 test((priv?'private':'web')+' role keeps flavor keywords and actual specs, then pays once with cloud coupon and reports verified extras',async()=>{const t=roleContext();const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18|某店|半糖|温的|1','main',{turnId:'turn'});assert.equal(result.type,'marketfood');assert.equal(t.paid(),1);assert.equal(t.modelCalls(),1);assert.match(result.marketFood.resultText,/为凑起送价，加了小料 ×1/);assert.match(result.marketFood.resultText,/已减 ¥3.00/);assert.match(result.marketFood.resultText,/实付 ¥18.90/);assert.equal(t.events.filter(x=>x.startsWith('model')).length,1);t.ctx.msgs=()=>[result];assert.equal(await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'turn'}),null);assert.equal(t.paid(),1);});
 test((priv?'private':'web')+' role rejects wrong temperature, invented options, wrong flavor and unnecessary topups before payment',async()=>{const t=roleContext({badSpec:true});const repaired=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'turn'});/* v1658：模型选了冰的，用户要温的——改成温的再下单，而不是整单失败 */assert.equal(repaired.type,'marketfood');assert.deepEqual(Array.from(t.data.roleMarketIntents[0].offer.lines[0].selections.heat),['warm']);assert.doesNotMatch(t.notices.join(''),/Fetch|原始原因|API/);const choose=t.ctx.northRoleChoice;const cakePlan={must:['草莓','蛋糕'],quantity:1,preferences:[]};assert.throws(()=>choose(JSON.stringify({shopId:'shop',primaryId:'wrong',lines:[{productId:'wrong',quantity:1,selections:{}}]}),t.catalog,cakePlan),/口味/);assert.throws(()=>choose(JSON.stringify({shopId:'shop',primaryId:'cake',lines:[{productId:'cake',quantity:1,selections:{}},{productId:'addon',quantity:1,selections:{}}]}),t.catalog,cakePlan),/无需凑/);const invented=JSON.parse(JSON.stringify(t.choice));invented.lines[0].selections.heat=['fake'];assert.deepEqual(Array.from(choose(JSON.stringify(invented),t.catalog,t.intent).lines[0].selections.heat),['warm'],'v1658: an invented option is repaired to the real option the user asked for');});
 test((priv?'private':'web')+' role preserves paid receipt when local receipt saving fails and never converts network errors to virtual orders',async()=>{const t=roleContext({finalFailure:true});const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'turn'});assert.equal(result.type,'marketfood');assert.match(result.marketFood.resultText,/已付款/);assert.equal(t.paid(),1);const fail=roleContext({networkFailure:true});assert.match((await fail.ctx.northPreferredRoleFood(fail.c,'芋泥奶茶','18','main',{turnId:'turn'})).content,/没有下单成功/);assert.equal(fail.paid(),0);assert.equal(fail.data.roleMarketIntents[0].status,'failed');});
 test((priv?'private':'web')+' role account change and unknown payment cannot create or replay a charge',async()=>{const changed=roleContext({switchAccount:true});assert.equal(await changed.ctx.northPreferredRoleFood(changed.c,'芋泥奶茶','18','main',{turnId:'turn'}),null);assert.equal(changed.paid(),0);const unknown=roleContext({unknown:true});assert.match((await unknown.ctx.northPreferredRoleFood(unknown.c,'芋泥奶茶','18','main',{turnId:'turn'})).content,/付款结果还在核对/);assert.equal(unknown.data.roleMarketIntents[0].status,'unknown');assert.match((await unknown.ctx.northPreferredRoleFood(unknown.c,'芋泥奶茶','18','main',{turnId:'other-turn'})).content,/付款结果还在核对/);assert.equal(unknown.paid(),1);});
 test((priv?'private':'web')+' role coupon selection rejects expired, used and unmet thresholds and prefers earliest expiry at equal discount',()=>{const t=roleContext(),best=t.ctx.northRoleBestCoupon;const coupons=[{id:'expired',minimum:0,face:1000,expires_at:'2000-01-01'},{id:'used',minimum:0,face:1000,expires_at:'2099-01-01',used_order_id:'used'},{id:'threshold',minimum:3500,face:500,expires_at:'2099-01-01'},{id:'later',minimum:2000,face:300,expires_at:'2099-02-01'},{id:'first',minimum:2000,face:300,expires_at:'2099-01-01'}];assert.equal(best(coupons,2000).id,'first');assert.equal(best(coupons,1500),null);});

 test((priv?'private':'web')+' exact role product skips redundant intent generation and a failed request never speaks raw diagnostics as the role',async()=>{const t=roleContext();let calls=0;t.ctx.chatAPI=async(ms,opt)=>{calls++;assert.ok(opt.timeout>=120000);assert.doesNotMatch(ms[0].content,/提取本轮点单意图/);return JSON.stringify(calls===1?t.choice:{message:'给你挑好了。'});};t.ctx.northMarketRpc=async(fn,args)=>{if(fn==='wallet')return {couple:{id:t.c.id,balance:5000,revision:1}};if(fn==='role_catalog')return t.catalog;if(fn==='coupons')return {coupons:[]};if(fn==='quote')return {subtotal:2000,total:2190,delivery:190};if(fn==='role_checkout')return {order:{id:'paid',shop_name:'真人店',subtotal:2000,delivery:190,total:2190,discount:0,items:[{productId:'tea',name:'芋泥奶茶',quantity:1,labels:['温的']},{productId:'addon',name:'小料',quantity:1,labels:[]}],note:'凑起送'}};throw Error('unexpected '+fn);};const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18|任意|无|温的|1','main',{turnId:'exact'});assert.equal(result.type,'marketfood');assert.equal(calls,1);const e=Error('请求超时（上游原始原因：Fetch is aborted，Authorization: secret）');const failure=t.ctx.northRoleFailureReceipt({status:'failed'},e);assert.equal(failure.type,'sys');assert.equal(failure.role,'system');assert.doesNotMatch(failure.content,/Fetch|Authorization|secret|上游|API/);assert.match(failure.content,/超时|暂时/);});
 test((priv?'private':'web')+' cloud order promises are suppressed only in order action replies, leaving ordinary role conversation intact',()=>{const t=roleContext(),filter=t.ctx.northRoleFilterClaims;const text='先生给你点。\n点了，十五分钟到。\n[点外卖|芋泥奶茶|18]\n乖。';const result=filter(t.c,text);assert.doesNotMatch(result,/十五分钟到/);assert.match(result,/先生给你点/);assert.match(result,/\[点外卖/);assert.equal(filter(t.c,'我十五分钟到。'),'我十五分钟到。');assert.equal(filter({id:'other'},text),text);});

 test((priv?'private':'web')+' ordering notice persists until a real receipt is displayed and uncertain payment never auto-completes',()=>{const t=roleContext(),nodes={},ticks=[],later=[];t.ctx.document={body:{appendChild:el=>{nodes[el.id]=el;}},getElementById:id=>nodes[id]||null,createElement:()=>({style:{},setAttribute(){},remove(){delete nodes[this.id];}})};t.ctx.getC=()=>t.c;t.ctx.setInterval=f=>{ticks.push(f);return ticks.length;};t.ctx.clearInterval=()=>{};t.ctx.setTimeout=f=>{later.push(f);};t.ctx.northRoleOrderProgress(t.c,{account:'main',client:'x'},'searching');assert.match(nodes.north_role_order_progress.innerHTML,/正在点单/);assert.equal(later.length,0);ticks[0]();assert.ok(nodes.north_role_order_progress);t.ctx.northRoleOrderProgress(t.c,{account:'main',client:'x'},'paid');assert.doesNotMatch(nodes.north_role_order_progress.innerHTML,/点单完成/);assert.equal(later.length,0);t.ctx.northRoleReceiptShown(t.c,{marketOrderId:'paid'});assert.match(nodes.north_role_order_progress.innerHTML,/点单完成/);assert.equal(later.length,1);later[0]();assert.equal(nodes.north_role_order_progress,undefined);t.ctx.northRoleOrderProgress(t.c,{account:'main',client:'x'},'unknown');assert.match(nodes.north_role_order_progress.innerHTML,/结果待确认/);assert.equal(later.length,1);t.ctx.actId=()=> 'other';ticks.at(-1)();assert.equal(nodes.north_role_order_progress,undefined);});
 test((priv?'private':'web')+' an explicit food request with a false completed promise repairs one action, but ordinary arrival and refusal do not order',async()=>{const t=roleContext();let calls=0;t.ctx.northRoleModel=async()=>{calls++;return JSON.stringify({order:true,name:'草莓雪顶',body:'22||标准杯、半糖、无小料|少冰|1'});};const meta={turnId:'repair'};const result=await t.ctx.northRoleEnsureAction(t.c,'点了，十五分钟到。','给我点草莓雪顶',meta);assert.match(result,/\[点外卖\|草莓雪顶\|22\|/);assert.equal(meta.northRepairCalls,1);assert.equal(calls,1);assert.equal(await t.ctx.northRoleEnsureAction(t.c,'我十五分钟到。','我想喝奶茶',{}),'我十五分钟到。');assert.equal(calls,1);assert.doesNotMatch(await t.ctx.northRoleEnsureAction(t.c,'点了，十五分钟到。','不要给我点奶茶',{}),/点了|十五分钟到/);assert.equal(calls,1);});

 test((priv?'private':'web')+' explicit blueberry order with assent and a standalone duration executes one repair without mistaking refusal or personal arrival',async()=>{const t=roleContext();let calls=0;t.ctx.northRoleModel=async(c,task,payload)=>{calls++;return JSON.stringify(/回来|不点/.test(payload.reply)?{order:false}:{order:true,name:'蓝莓小蛋糕',body:'15||无|不适用|1'});};const result=await t.ctx.northRoleEnsureAction(t.c,'好。\n现在蓝莓小蛋糕。\n十五分钟。\n吃完这个，去睡觉。','我想吃蓝莓小蛋糕给我点',{});assert.match(result,/\[点外卖\|蓝莓小蛋糕/);assert.equal(calls,1);assert.equal(await t.ctx.northRoleEnsureAction(t.c,'我十五分钟回来。','我想吃蓝莓小蛋糕给我点',{}),'我十五分钟回来。');assert.equal(calls,2);assert.equal(await t.ctx.northRoleEnsureAction(t.c,'不点，等十五分钟再说。','我想吃蓝莓小蛋糕给我点',{}),'不点，等十五分钟再说。');assert.equal(calls,3);});

 test((priv?'private':'web')+' explicit blueberry request is reconciled regardless of delivery promise wording and refusal never purchases',async()=>{const t=roleContext();let calls=0;t.ctx.northRoleModel=async(c,task,payload)=>{calls++;return JSON.stringify(payload.reply.includes('不点')?{order:false}:{order:true,name:'蓝莓小蛋糕',body:'15||无|不适用|1'});};for(const text of ['好。\n十五分钟送到。\n这是今晚第四单。','行。\n给你安排蓝莓小蛋糕。','等着吃吧。']){const result=await t.ctx.northRoleEnsureAction(t.c,text,'我想吃蓝莓小蛋糕给我点',{});assert.match(result,/\[点外卖\|蓝莓小蛋糕/);assert.doesNotMatch(t.ctx.northRoleFilterClaims(t.c,result),/十五分钟送到/);}assert.equal(calls,3);const declined=await t.ctx.northRoleEnsureAction(t.c,'今晚不点，明天再买。','我想吃蓝莓小蛋糕给我点',{});assert.equal(declined,'今晚不点，明天再买。');assert.equal(calls,4);assert.equal(await t.ctx.northRoleEnsureAction(t.c,'等着吃吧。','我想吃蓝莓小蛋糕给我点',{northCurrentRequest:false}),'等着吃吧。');assert.equal(calls,4);assert.equal(t.paid(),0);});

 test((priv?'private':'web')+' manual retries bind to the user message, paid requests never debit again and failed prepayment can retry',async()=>{const t=roleContext(),meta={messageId:'user-one',modelReplyId:'reply-one',northCurrentRequest:true};const first=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',meta);t.ctx.msgs=()=>[first];assert.equal(await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{...meta,modelReplyId:'reply-two'}),null);assert.equal(t.paid(),1);assert.equal((await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{...meta,messageId:'user-two',modelReplyId:'reply-three'})).type,'marketfood');assert.equal(t.paid(),2);const options={networkFailure:true},failed=roleContext(options);assert.equal((await failed.ctx.northPreferredRoleFood(failed.c,'芋泥奶茶','18','main',meta)).type,'sys');assert.equal(failed.paid(),0);options.networkFailure=false;assert.equal((await failed.ctx.northPreferredRoleFood(failed.c,'芋泥奶茶','18','main',{...meta,modelReplyId:'retry'})).type,'marketfood');assert.equal(failed.paid(),1);const virtual=roleContext();virtual.ctx.northMarketRpc=async()=>({couple:{id:virtual.c.id,balance:0}});virtual.ctx.northRoleFoodCard=()=>({id:'virtual-card',type:'food',from:'ta'});const card=await virtual.ctx.northPreferredRoleFood(virtual.c,'蛋糕','15','main',meta);assert.equal(card._northRequestKey,'user-one');assert.equal((await virtual.ctx.northPreferredRoleFood(virtual.c,'蛋糕','15','main',{...meta,modelReplyId:'recover'})).id,'virtual-card');virtual.ctx.msgs=()=>[card];assert.equal(await virtual.ctx.northPreferredRoleFood(virtual.c,'蛋糕','15','main',{...meta,modelReplyId:'again'}),null);assert.equal(virtual.paid(),0);});

 test((priv?'private':'web')+' raw output still repairs an order claim before returning a verified cloud receipt',async()=>{const t=roleContext(),originalModel=t.ctx.northRoleModel;t.ctx.northRoleModel=async()=>JSON.stringify({order:true,name:'芋泥奶茶',body:'18||半糖|温的|1'});const appFile=priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js':'app.js',app=process.env.NORTH_ROLE_TEST_OLD?cp.execFileSync('git',['show','HEAD:'+appFile],{encoding:'utf8',maxBuffer:8e6}):fs.readFileSync(appFile,'utf8'),line=app.split('\n').find(l=>l.includes('content=await NorthMarketBusiness.ensureAction(c,content,_userText,_deliveryActionMeta)'));assert.ok(line);Object.assign(t.ctx,{_rawOutput:true,content:'点了，十五分钟到。',c:t.c,_userText:'我想喝芋泥奶茶给我点',_deliveryActionMeta:{turnId:'raw-order'},NorthMarketBusiness:{ensureAction:t.ctx.northRoleEnsureAction}});await vm.runInContext('(async()=>{'+line+'})()',t.ctx);assert.match(t.ctx.content,/\[点外卖\|芋泥奶茶/);t.ctx.northRoleModel=originalModel;const receipt=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18||半糖|温的|1','main',{turnId:'raw-order',northRepairCalls:1});assert.equal(receipt.type,'marketfood');assert.equal(t.paid(),1);assert.equal(receipt.marketOrderId,'order');});
 test((priv?'private':'web')+' multi-product role card shows merchant cover and leaves all product details in the order page',()=>{const t=roleContext();Object.assign(t.ctx,{mtStyles(){},northNavIcon:()=>'<svg></svg>',northMarketImage:(image,name)=>'<img src=\"'+image+'\" alt=\"'+name+'\">',northMarketStatus:()=> '已付款',northMarketArgument:x=>JSON.stringify(x).replace(/"/g,'&quot;')});const line=src.split('\n').find(l=>l.startsWith('  function northMarketRoleFoodCard('));vm.runInContext(line,t.ctx);const h=t.ctx.northMarketRoleFoodCard(t.c,{marketFood:{account:'main',resultText:'很长的原始结果说明',order:{id:'o',status:'paid',shop_name:'真人店',shop_cover:'https://fixture.invalid/shop-cover.jpg',total:1890,discount:300,note:'为凑起送',items:[{name:'芋泥奶茶',quantity:1,labels:['温的']},{name:'小料',quantity:1,labels:[]}]}}});assert.match(h,/shop-cover\.jpg/);assert.match(h,/共 2 种商品/);assert.doesNotMatch(h,/芋泥奶茶|小料|<details/);assert.doesNotMatch(h,/<details[^>]*\bopen\b/);assert.equal((h.split('<details')[0].match(/wx-north-food-open/g)||[]).length,1);assert.match(h,/已减 ¥3\.00/);assert.match(h,/18\.90/);assert.doesNotMatch(h,/很长的原始结果说明/);});

 test((priv?'private':'web')+' interrupted pre-payment selection does not silently consume the next explicit request',async()=>{const t=roleContext();t.data.roleMarketIntents=[{account:'main',role:t.c.id,turn:'old',client:'old',status:'searching',at:Date.now()-250000}];const result=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'new-explicit'});assert.equal(result.type,'marketfood');assert.equal(t.paid(),1);assert.equal(t.data.roleMarketIntents[0].status,'failed');});
 test((priv?'private':'web')+' new explicit cloud order can proceed after a previous card, while a paid missing card is recovered without another charge',async()=>{const t=roleContext();assert.equal(t.ctx.northRoleCloudEligible(t.c),true);const first=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'one'});assert.equal(t.paid(),1);const recovered=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'recovery-turn'});assert.equal(recovered.marketOrderId,first.marketOrderId);assert.equal(t.paid(),1);t.ctx.msgs=()=>[first];const next=await t.ctx.northPreferredRoleFood(t.c,'芋泥奶茶','18','main',{turnId:'new-explicit-order'});assert.equal(next.type,'marketfood');assert.equal(t.paid(),2);t.ctx.phoneFriendState=()=>({id:'',secret:''});assert.equal(t.ctx.northRoleCloudEligible(t.c),false);});
}

export const roleSelectionSQL=String.raw`
do $test$
declare seller text:='SP'||upper(substr(md5(gen_random_uuid()::text),1,8));buyer text:='SP'||upper(substr(md5(gen_random_uuid()::text),1,8));
 s uuid:=gen_random_uuid();b uuid:=gen_random_uuid();shop uuid;rev integer;req uuid:=gen_random_uuid();oid uuid;cid uuid;othercid uuid;
 product jsonb;catalog jsonb;lines jsonb;address jsonb:=jsonb_build_object('address','回滚验收地址','name','测试','phone','');result jsonb;failed boolean;before_wallet bigint;
begin
 insert into public.phone_friend_profiles(phone_id,secret_hash,display_name,allow_search) values(seller,public.phone_friend_hash('role-selection-test'),'回滚店主',false),(buyer,public.phone_friend_hash('role-selection-test'),'回滚顾客',false);
 insert into public.phone_licenses(id,status,phone_friend_id) values(s,'active',seller),(b,'active',buyer);
 product:=jsonb_build_object('id','tea','name','回滚芋泥奶茶','groupId','drinks','price',2000,'unit','杯','description','芋泥奶茶','image','','available',true,'signature',false,'specGroups',jsonb_build_array(jsonb_build_object('id','heat','name','温度','mode','single','required',true,'options',jsonb_build_array(jsonb_build_object('id','cold','label','冰的','price',0),jsonb_build_object('id','warm','label','温的','price',100)))));
 catalog:=jsonb_build_object('name','回滚角色店','category','奶茶','intro','','cover','','minimum',2000,'delivery',190,'published',true,'groups',jsonb_build_array(jsonb_build_object('id','drinks','name','饮品')),'products',jsonb_build_array(product));
 shop:=(public.north_market_save_shop(seller,'role-selection-test',0,catalog)->>'id')::uuid;
 perform public.north_market_claim(seller,'role-selection-test');perform public.north_market_claim(buyer,'role-selection-test');
 perform public.north_market_stock_change(seller,'role-selection-test',shop,'tea',5,'wallet',gen_random_uuid(),'00000',4000,false);
 result:=public.north_market_couple(buyer,'role-selection-test','partner','角色');rev:=(result->'couple'->>'revision')::integer;
 perform public.north_market_transfer(buyer,'role-selection-test','wallet','couple','partner',5000,gen_random_uuid());
 result:=public.north_market_role_catalog(buyer,'role-selection-test','partner','["芋泥","奶茶"]','["芋泥","奶茶"]');
 if not exists(select 1 from jsonb_array_elements(result->'shops') x where x->>'id'=shop::text and x->'products'->0->'specGroups'->0->'options'->1->>'label'='温的') then raise exception 'FAIL keyword catalog/specs';end if;
 failed:=false;begin perform public.north_market_role_catalog(seller,'role-selection-test','shop-partner','["芋泥"]','["芋泥"]');exception when raise_exception then failed:=SQLERRM='market-couple-only';end;if not failed then raise exception 'FAIL couple boundary';end if;
end $test$;
do $test$
declare seller text;buyer text;s text;b text;shop uuid;rev integer;req uuid:=gen_random_uuid();oid uuid;cid uuid;othercid uuid;result jsonb;failed boolean;before_wallet bigint;
 lines jsonb:='[{"productId":"tea","quantity":1,"selections":{"heat":["warm"]}}]';address jsonb:=jsonb_build_object('address','回滚验收地址','name','测试','phone','');
begin
 -- Locate only this transaction's fixture by its secret hash, never production accounts.
 select phone_id into seller from public.phone_friend_profiles where secret_hash=public.phone_friend_hash('role-selection-test') and display_name='回滚店主';
 select phone_id into buyer from public.phone_friend_profiles where secret_hash=public.phone_friend_hash('role-selection-test') and display_name='回滚顾客';
 select id::text into s from public.phone_licenses where phone_friend_id=seller;select id::text into b from public.phone_licenses where phone_friend_id=buyer;
 select id into shop from public.north_market_shops where owner_id=s;
 rev:=(public.north_market_wallet(buyer,'role-selection-test')->'couple'->>'revision')::integer;
 perform public.north_market_coupon_buy(buyer,'role-selection-test','light',gen_random_uuid(),'00000');
 select id into cid from public.north_market_coupons where owner_id=b and minimum=2000 order by expires_at,id limit 1;
 insert into public.north_market_coupons(owner_id,face,minimum) values(s,300,2000) returning id into othercid;
 before_wallet:=(public.north_market_wallet(buyer,'role-selection-test')->'couple'->>'balance')::bigint;
 failed:=false;begin perform public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,gen_random_uuid(),shop,1,lines,address,true,1990,othercid,false);exception when raise_exception then failed:=SQLERRM='market-coupon-unavailable';end;if not failed then raise exception 'FAIL foreign coupon';end if;
 failed:=false;begin perform public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,gen_random_uuid(),shop,1,lines,address,true,1,cid,false);exception when raise_exception then failed:=SQLERRM='market-price-changed';end;if not failed then raise exception 'FAIL invented total';end if;
 result:=public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,req,shop,1,lines,address,true,1990,cid,true);oid:=(result->'order'->>'id')::uuid;
 if (result->'order'->>'discount')::integer<>300 or result->'order'->'items'->0->'labels'->>0<>'温度：温的' then raise exception 'FAIL discount/spec snapshot';end if;
 perform public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,req,shop,1,lines,address,true,1990,cid,true);
 if (public.north_market_wallet(buyer,'role-selection-test')->'couple'->>'balance')::bigint<>before_wallet-1990 or (select quantity from public.north_market_stock where shop_id=shop and product_id='tea')<>4 then raise exception 'FAIL replay debited twice';end if;
 failed:=false;begin perform public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,gen_random_uuid(),shop,1,lines,address,true,1990,cid,true);exception when raise_exception then failed:=SQLERRM='market-coupon-unavailable';end;if not failed then raise exception 'FAIL used coupon reused';end if;
 perform public.north_market_order_status(buyer,'role-selection-test',oid,'cancelled');
 if (select used_order_id from public.north_market_coupons where id=cid) is not null or (public.north_market_wallet(buyer,'role-selection-test')->'couple'->>'balance')::bigint<>before_wallet then raise exception 'FAIL coupon/role refund';end if;
 update public.north_market_coupons set expires_at=now()-interval '1 second' where id=cid;
 failed:=false;begin perform public.north_market_role_checkout(buyer,'role-selection-test','partner',rev,gen_random_uuid(),shop,1,lines,address,true,1990,cid,false);exception when raise_exception then failed:=SQLERRM='market-coupon-unavailable';end;if not failed then raise exception 'FAIL expired coupon';end if;
 result:=public.north_market_role_catalog(buyer,'role-selection-test','partner','["芋泥"]','["芋泥","蛋糕"]');if exists(select 1 from jsonb_array_elements(result->'shops') x where x->>'id'=shop::text) then raise exception 'FAIL flavor AND category';end if;
 result:=public.north_market_role_catalog(buyer,'role-selection-test','partner','["芋泥"]','["芋泥"]');if result::text like '%owner_id%' or result::text like '%secret%' then raise exception 'FAIL private catalog leakage';end if;
 select (public.north_market_couple(seller,'role-selection-test','shop-partner','角色')->'couple'->>'revision')::integer into rev;
 result:=public.north_market_role_catalog(seller,'role-selection-test','shop-partner','["芋泥"]','["芋泥"]');if exists(select 1 from jsonb_array_elements(result->'shops')x where x->>'id'=shop::text) then raise exception 'FAIL own shop recommendation';end if;
 raise notice 'PASS role catalog AND keywords, actual specs, own-shop exclusion, coupon ownership/expiry/replay/refund, atomic role payment and stock';
end $test$;
`;

for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(prefix+' arrival follows recipient, not payer, with one persisted role notice',async()=>{
 const source=fs.readFileSync(prefix+'commerce-ui.js','utf8'),match=source.match(/  async function northArrivalRoute\(order,cloud\)\{[\s\S]*?\n  \}/);assert.ok(match,'recipient arrival routing must exist');
 const messages=[],banners=[],replies=[],role={id:'role-one',name:'先生'},state={},ctx={S:state,actId:()=> 'main',getC:id=>id===role.id?role:null,msgs:()=>messages,pushMsg:(_id,m)=>messages.push(m),saveNowAsync:async()=>true,scheduleReply:(...args)=>replies.push(args),northArrivalBanner:(...args)=>banners.push(args),Date,esc:s=>s};vm.createContext(ctx);vm.runInContext(match[0],ctx);
 const gift={id:'gift-one',shop_name:'甜品店',status:'completed',address:{recipientRole:'role-one'},items:[{name:'草莓蛋糕',quantity:1,labels:['微甜']}]};assert.equal(await ctx.northArrivalRoute(gift,true),true);assert.equal(banners.length,0);assert.equal(messages.length,1);assert.match(messages[0].content,/草莓蛋糕/);assert.match(messages[0].content,/已经送到你这里/);assert.equal(replies.length,1);
 await ctx.northArrivalRoute(gift,true);assert.equal(messages.length,1);assert.equal(replies.length,1);
 await ctx.northArrivalRoute({...gift,id:'self-one',payer_role:'role-one',address:{}},true);assert.equal(banners.length,1);assert.equal(banners[0][0],'self-one');
 assert.equal(await ctx.northArrivalRoute({...gift,id:'missing',address:{recipientRole:'removed'}},true),false);assert.equal(banners.length,1);
 role.blocked=true;assert.equal(await ctx.northArrivalRoute({...gift,id:'blocked'},true),false);assert.equal(messages.length,1);role.blocked=false;
 ctx.saveNowAsync=async()=>false;assert.equal(await ctx.northArrivalRoute({...gift,id:'unsaved'},true),false);assert.equal(messages.length,1);assert.equal(replies.length,1);
});

test('portable shop package preserves editable groups and specs without importing money, credentials or stock',()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const source=fs.readFileSync(prefix+'commerce-ui.js','utf8');let count=0;const ctx={window:{},Map,Set,JSON,uid:()=> 'new-'+(++count),actId:()=> 'buyer'};vm.createContext(ctx);const start=source.indexOf('  function northMerchantPackImage('),end=source.indexOf('  async function northMerchantPortableImage(',start);assert.ok(start>=0);vm.runInContext(source.slice(start,end)+source.split('\n').filter(l=>l.startsWith('  function northMerchantProductError(')||l.startsWith('  function northMerchantError(')).join('\n'),ctx);const shop={name:'甜品店',category:'甜品',tags:['甜品'],intro:'自定义',cover:'',minimum:1500,delivery:190,deliveryMinutes:30,groups:[{id:'cake',name:'蛋糕'}],products:[{id:'old',name:'蓝莓小蛋糕',groupId:'cake',price:1500,unit:'份',image:'',stock:99,signature:true,specGroups:[{id:'size',name:'分量',mode:'single',required:true,options:[{id:'one',label:'小份',price:0,default:true}]}]}],defaultSpecGroups:[],owner:'seller',balance:50000,secret:'private',marketId:' чужой'};const pack={format:'north-shop-pack',version:1,shop},current={id:'local',revision:7,marketId:'own-cloud',marketRevision:3};const d=ctx.northMerchantPackParse(pack,current);assert.equal(d.name,shop.name);assert.equal(d.marketId,'own-cloud');assert.equal(d.owner,'buyer');assert.equal(d.status,'draft');assert.equal(d.revision,7);assert.equal(d.products[0].groupId,d.groups[0].id);assert.equal(d.products[0].specGroups[0].options[0].label,'小份');assert.equal(d.products[0].stock,undefined);assert.equal(d.balance,undefined);assert.equal(d.secret,undefined);assert.notEqual(d.products[0].id,'old');assert.throws(()=>ctx.northMerchantPackParse({...pack,version:2},current));assert.throws(()=>ctx.northMerchantPackParse({...pack,shop:{...shop,cover:'javascript:alert(1)'}},current));assert.throws(()=>ctx.northMerchantPackParse({...pack,shop:{...shop,products:[{...shop.products[0],price:-1}]}},current));}});

for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(prefix+' merchant deletion waits for cloud soft-delete and preserves other accounts and history',async()=>{const src=fs.readFileSync(prefix+'commerce-ui.js','utf8'),line=src.split('\n').find(l=>l.startsWith('  window.northMerchantDelete=')),saved={id:'local',marketId:'cloud',marketRevision:1,name:'Shop',status:'open',revision:1},view={account:'main',draft:saved,stagedImages:[]},data={merchants:{main:saved},merchantLibrary:{main:{other:{id:'other'}}},orders:[{id:'history'}]},state={food:{cart:[{_northAccount:'main',_northMerchant:'local'},{_northAccount:'other',_northMerchant:'local'}]}},ctx={window:{},northMerchantActive:()=>true,northSaving:false,northMarketBusy:false,northMerchantView:view,northMerchantSaved:()=>saved,actId:()=> 'main',S:state,uiConfirm:async()=>true,toast(){},northMarketRpc:async()=>{throw Error('cloud unavailable');},northMerchantData:()=>data,northCommit:async mutation=>{mutation();return true;},northMarketHomeCache:{rows:[{id:'cloud'},{id:'other'}]},northMarketPageReset(){},closeModal(){},northBack(){}};vm.createContext(ctx);vm.runInContext(line,ctx);await ctx.window.northMerchantDelete();assert.equal(data.merchants.main,saved);assert.equal(state.food.cart.length,2);ctx.northMarketRpc=async(name,args)=>{assert.equal(name,'shop_delete');assert.equal(args.p_id,'cloud');return {deleted:true,revision:2};};await ctx.window.northMerchantDelete();assert.equal(data.merchants.main,undefined);assert.equal(data.merchantLibrary.main.cloud.status,'deleted');assert.equal(data.merchantLibrary.main.cloud.marketDeleted,true);assert.equal(data.merchantLibrary.main.other.id,'other');assert.equal(data.orders[0].id,'history');assert.equal(state.food.cart.length,1);assert.equal(state.food.cart[0]._northAccount,'other');assert.equal(ctx.northMarketHomeCache.rows.length,1);});

 test('deleted shop archive cannot be reimported by the edit-shop entry',async()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=fs.readFileSync(prefix+'commerce-ui.js','utf8'),data={merchants:{},merchantLibrary:{main:{gone:{status:'deleted',marketId:'gone'}}}},state={};let opened=0,saved=0;const ctx={window:{},S:state,northMarketBusy:false,actId:()=> 'main',northMarketEnsure:async()=>true,northMarketRpc:async()=>({shop:{id:'gone',name:'Deleted Old Shop',catalog:{groups:[],products:[]}}}),northData:()=>data,northMerchantSaved:()=>data.merchants.main||null,northMerchantEditor:()=>opened++,saveNowAsync:async()=>{saved++;return true;},toast(){},uid:()=> 'local',northMerchantDefaultSpecs:()=>[]};vm.createContext(ctx);vm.runInContext(src.match(/  window.northMarketManageMine=async function\(preview,shopId\)\{[^\n]+/)[0],ctx);await ctx.window.northMarketManageMine(false);assert.equal(data.merchants.main,undefined);assert.equal(saved,0);assert.equal(opened,1);assert.equal(data.merchantLibrary.main.gone.status,'deleted');}});

test('merchant products move exactly one displayed row without changing IDs or saved account data',()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=fs.readFileSync(prefix+'commerce-ui.js','utf8'),fn=src.split('\n').find(l=>l.startsWith('  window.northMerchantProductMove='));assert.ok(fn,'product move handler missing');const products=[{id:'a',groupId:'g',price:100},{id:'other',groupId:'h',price:900},{id:'b',groupId:'g',price:200},{id:'c',groupId:'g',price:300}],view={screen:'editor',draft:{products:JSON.parse(JSON.stringify(products))},dirty:false};let refreshed=0,active=true;const ctx={window:{},northMerchantView:view,northMerchantActive:()=>active,northSaving:false,northMarketBusy:false,northProductEdit:null,northMerchantRefresh:()=>refreshed++};vm.createContext(ctx);vm.runInContext(fn,ctx);ctx.window.northMerchantProductMove('a',-1);assert.equal(view.dirty,false);ctx.window.northMerchantProductMove('b',-1);assert.deepEqual(view.draft.products.map(p=>p.id),['a','b','other','c']);assert.equal(view.dirty,true);assert.equal(refreshed,1);assert.deepEqual(view.draft.products.find(p=>p.id==='b'),products[2]);ctx.window.northMerchantProductMove('a',1);assert.deepEqual(view.draft.products.map(p=>p.id),['b','a','other','c']);const unchanged=JSON.stringify(view.draft.products);ctx.northSaving=true;ctx.window.northMerchantProductMove('a',-1);ctx.northSaving=false;active=false;ctx.window.northMerchantProductMove('a',-1);assert.equal(JSON.stringify(view.draft.products),unchanged);assert.equal(products[0].id,'a');}});

test('App store lookup runs only as a role action and binds a shop-name followup to the unfulfilled meal request',async()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=fs.readFileSync(prefix+'commerce-ui.js','utf8');assert.ok(src.includes('function northRoleAppShopQuery('),'missing internal App shop tool');const c={id:'partner'},messages=[{id:'meal',role:'user',type:'text',content:'那我要吃宋式番茄炖牛腩和山房小炒肉',time:Date.now()-180000},{id:'ask',role:'assistant',type:'text',content:'哪家店，报名字。',time:Date.now()-170000},{id:'shop',role:'user',type:'text',content:'闲云野鹤居',time:Date.now()}],state={};let calls=[];const ctx={S:state,Date,JSON,Math,Set,actId:()=> 'main',msgs:()=>messages,northData:()=>({}),northMarketCoupleRole:()=>c,deliveryRealEnabled:()=>false,northMarketRpc:async(name,args)=>{calls.push(name);if(name==='list'){assert.equal(args.p_query,'闲云野鹤居');return {shops:[{id:'store',name:'闲云野鹤居'}]};}return {shop:{id:'store',name:'闲云野鹤居',minimum:4800,delivery:190},products:[{id:'beef',name:'宋式番茄炖牛腩',price:3700,stock:2,specGroups:[],available:true},{id:'pork',name:'山房小炒肉',price:3900,stock:2,specGroups:[],available:true}]};}};vm.createContext(ctx);vm.runInContext(src.split('\n').filter(l=>/^  (function northRoleShortBuyContext|function northRoleOrderRequest|async function northRoleAppShopQuery)/.test(l)).join('\n'),ctx);const request=ctx.northRoleOrderRequest(c,'闲云野鹤居');assert.equal(request.anchorId,'meal');assert.match(request.text,/宋式番茄炖牛腩和山房小炒肉/);assert.deepEqual(calls,[],'context binding must not automatically search');const result=await ctx.northRoleAppShopQuery(c,'闲云野鹤居');assert.equal(result.ok,true);assert.deepEqual(calls,['list','shop']);assert.equal(result.shops[0].products.length,2);assert.equal(result.shops[0].products[0].price,3700);assert.match(result.prompt,/App内/);assert.doesNotMatch(result.prompt,/苏州没有|早上不能/);}});

test('deleted local shops leave current joint-business lists without erasing historical funds or quota',()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=fs.readFileSync(prefix+'commerce-ui.js','utf8'),ctx={northData:()=>({merchantLibrary:{main:{gone:{status:'deleted'},live:{status:'open'}}}}),actId:()=> 'main'};vm.createContext(ctx);vm.runInContext(src.split('\n').find(l=>l.startsWith('  function northActiveBusinessData(')),ctx);const data={shopCount:3,nextStartupFee:null,profit:1200,income:2000,inventoryValue:500,shops:[{id:'gone'},{id:'live'}],stock:[{shop_id:'gone',quantity:2},{shop_id:'live',quantity:1}]};const result=ctx.northActiveBusinessData(data);assert.deepEqual(Array.from(result.shops,p=>p.id),['live']);assert.deepEqual(Array.from(result.stock,p=>p.shop_id),['live']);assert.equal(result.income,2000);assert.equal(result.profit,1200);assert.equal(result.shopCount,3,'frontend must not pretend the undeployed backend has released slots');assert.equal(data.shops.length,2);assert.equal(data.stock.length,2);}});

test('real coupon picker uses the owned-ticket layout and preserves merchandise-only discount',async()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=process.env.NORTH_COUPON_OLD?cp.execFileSync('git',['show','HEAD:'+prefix+'commerce-ui.js'],{encoding:'utf8',maxBuffer:8e6}):fs.readFileSync(prefix+'commerce-ui.js','utf8');let html='',closed=0;const draft={account:'main',quote:{subtotal:3000,delivery:190,total:3190}},coupons=[{id:'valid',face:300,minimum:2000,expires_at:'2026-11-08T07:16:00Z'},{id:'too-high',face:500,minimum:3500,expires_at:'2026-11-08T07:16:00Z'}],ctx={window:{},northMarketBusy:false,northMarketPayDraft:draft,actId:()=> 'main',northMarketCaptureShipping(){},northMarketRpc:async()=>({coupons}),openModal:s=>html=s,toast(){},esc:String,money:n=>n.toFixed(2),fmtDT:()=> '2026-11-08',Date,northMarketArgument:x=>JSON.stringify(x).replace(/"/g,'&quot;'),closeModal:()=>closed++,render(){}};vm.createContext(ctx);vm.runInContext(src.split('\n').filter(l=>l.startsWith('  function northMarketCouponCard(')||l.startsWith('  window.northMarketChooseCoupon=')||l.startsWith('  window.northMarketCouponSelect=')).join('\n'),ctx);await ctx.window.northMarketChooseCoupon();assert.match(html,/<article class="north-voucher /);assert.match(html,/¥3\.00/);assert.match(html,/满 ¥20\.00 可用/);assert.doesNotMatch(html,/<button class="btn p"/);assert.equal(draft.availableCoupons.length,1);ctx.window.northMarketCouponSelect('valid');assert.equal(draft.quote.discount,300);assert.equal(draft.quote.total,2890);assert.equal(draft.quote.delivery,190);assert.equal(closed,1);ctx.window.northMarketCouponSelect('');assert.equal(draft.quote.total,3190);draft.lockedRequest=true;ctx.window.northMarketCouponSelect('valid');assert.equal(draft.quote.total,3190);}});

test('previous local deletions sync to cloud once without touching open shops or other accounts',async()=>{for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const src=fs.readFileSync(prefix+'commerce-ui.js','utf8'),state={},data={merchantLibrary:{main:{gone:{status:'deleted',marketId:'cloud-old',marketRevision:4},open:{status:'open',marketId:'cloud-open',marketRevision:2}},other:{gone:{status:'deleted',marketId:'other-cloud',marketRevision:1}}}},calls=[],ctx={S:state,northData:()=>data,actId:()=> 'main',save(){},northMarketRpc:async(name,args)=>{calls.push([name,args.p_id,args.p_expected]);return {deleted:true,revision:5};}};vm.createContext(ctx);vm.runInContext(src.split('\n').filter(l=>l.startsWith('  var northDeletedSyncBusy=')||l.startsWith('  async function northSyncDeletedShops(')).join('\n'),ctx);await ctx.northSyncDeletedShops();await ctx.northSyncDeletedShops();assert.deepEqual(calls,[['shop_delete','cloud-old',4]]);assert.equal(data.merchantLibrary.main.gone.marketDeleted,true);assert.equal(data.merchantLibrary.other.gone.marketDeleted,undefined);assert.equal(data.merchantLibrary.main.open.status,'open');}});


test('fixed McDonalds preserves the supplied 20 original goods, images, prices and specs',async()=>{const {createHash}=await import('node:crypto');for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const window={NorthBuiltinShops:[{id:'north-dessert',name:'NORTH甜品店'}]},src=fs.readFileSync(new URL('../'+prefix+'assets/north-mcdonalds-shop.js',import.meta.url),'utf8');vm.runInNewContext(src,{window});const shop=window.NorthBuiltinShops.find(s=>s.id==='north-mcdonalds');assert.equal(shop.name,'麦当劳');assert.equal(shop.products.length,20);assert.equal(shop.status,'open');assert.equal(shop.rating,4.9);assert.equal(shop.minimum,990);assert.equal(shop.delivery,190);assert.equal(createHash('sha256').update(JSON.stringify(shop.products)).digest('hex'),'0b4174688970271a7db6da9a658be4f9194e6fc656343fee18f4c0e4e966a196');assert.equal(window.NorthBuiltinShops[0].name,'NORTH甜品店');vm.runInNewContext(src,{window});assert.equal(window.NorthBuiltinShops.length,2);}});


test('fixed Luckin preserves the supplied original goods, pictures, prices and specs',async()=>{const {createHash}=await import('node:crypto');for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const window={NorthBuiltinShops:[{id:'north-mcdonalds'}]};vm.runInNewContext(fs.readFileSync(new URL('../'+prefix+'assets/north-luckin-shop.js',import.meta.url),'utf8'),{window});const shop=window.NorthBuiltinShops.find(s=>s.id==='north-luckin');assert.equal(shop.name,'瑞幸咖啡');assert.equal(shop.products.length,17);assert.equal(createHash('sha256').update(JSON.stringify(shop.products)).digest('hex'),'556ec4f567d318f48bb86991c3c526185385bfa1e093426d8008c06bb527d2ee');assert.equal(shop.status,'open');assert.equal(shop.rating,4.9);assert.equal(window.NorthBuiltinShops[0].id,'north-mcdonalds');}});


test('fixed NORTH breakfast preserves every supplied product, image, price and spec',async()=>{const {createHash}=await import('node:crypto');for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const window={NorthBuiltinShops:[{id:'north-luckin'}]};vm.runInNewContext(fs.readFileSync(new URL('../'+prefix+'assets/north-breakfast-shop.js',import.meta.url),'utf8'),{window});const shop=window.NorthBuiltinShops.find(s=>s.id==='north-breakfast');assert.equal(shop.name,'NORTH早餐店');assert.equal(shop.products.length,21);assert.equal(createHash('sha256').update(JSON.stringify(shop.products)).digest('hex'),'f4060ca06aab62bdf20aa41ce7b67412c03d4c3448d7b0ee11573b663f65dd60');assert.equal(shop.status,'open');assert.equal(shop.rating,4.9);assert.equal(window.NorthBuiltinShops[0].id,'north-luckin');}});


test('fixed NORTH fruit bowl preserves every original good, image, price and spec',async()=>{const {createHash}=await import('node:crypto');for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const window={NorthBuiltinShops:[{id:'north-breakfast'}]};vm.runInNewContext(fs.readFileSync(new URL('../'+prefix+'assets/north-fruit-bowl-shop.js',import.meta.url),'utf8'),{window});const shop=window.NorthBuiltinShops.find(s=>s.id==='north-fruit-bowl');assert.equal(shop.name,'NORTH水果捞');assert.equal(shop.products.length,18);assert.equal(createHash('sha256').update(JSON.stringify(shop.products)).digest('hex'),'32aec199f8b469d7ac2abbbe4d4868f5ff79490044b4092adb8cf823e473075f');assert.equal(shop.status,'open');assert.equal(shop.rating,4.9);assert.equal(window.NorthBuiltinShops[0].id,'north-breakfast');}});


test('NORTH pharmacy installs the supplied cover and first ten products without modifying any image bytes',async()=>{const {createHash}=await import('node:crypto');const hashes=["c4697227e27fc2f52d1d3ec477bbd7f3ca147532e16b1f0b257f3c428d09806a", "b2fb3b377fc5e454739493f22a3338e741f79fb3146cf3eec3cbf521012a729a", "c5b232c509f11d9256f9c3e3c511089036e55f2d997a113928085b06af14d3af", "ca6faa5f84e6a2936e6ffadca4c4f15bc96a359a6000af3be8237fa5012d86f8", "aa3ce6ce61c172157fc0c1962cf1fdfca133aac461b0e12156a479fd8b229a1a", "9d9bc2396e706cce1c2a42f25deac73412b954544b0d4e7d4e005fe2c5f69267", "53ab022e9002d9f08cad6fcd9cdecbf51fd34ea6b47a4c3f0feb00ee2bf7329e", "e79c7a6e5fc62cfe2d60d6b8e23211d6bfe65c78af9d5322678c77660f867191", "4386ec7e369163e83114e0028ec18f6a302aeb6e54ddd1acb978900bddeea4f6", "857ba5d9f1c0f6d9746e6d7f807759c0dfc4b2cf5eea65c5ca6a17241db15168", "563255c650eb74f3c46f1770c760b13e1b877374c4b86ceb46b96a8a48a2a135"];for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){const window={NorthBuiltinShops:[{id:'north-fruit-bowl'}]},script=fs.readFileSync(new URL('../'+prefix+'assets/north-pharmacy-shop.js',import.meta.url),'utf8');vm.runInNewContext(script,{window});const shop=window.NorthBuiltinShops.find(s=>s.id==='north-pharmacy');assert.equal(shop.name,'NORTH药店');assert.equal(shop.products.length,24);assert.equal(shop.groups.length,5);assert.equal(shop.categoryKeys[0],'medicine');assert.equal(shop.minimum,0);assert.equal(shop.rating,4.9);assert.match(shop.intro,/模拟体验/);const images=[shop.cover,...shop.products.slice(0,10).map(p=>p.image)];images.forEach((img,i)=>assert.equal(createHash('sha256').update(Buffer.from(img.split(',')[1],'base64')).digest('hex'),hashes[i]));assert.ok(shop.products.every(p=>p.available&&shop.groups.some(g=>g.id===p.groupId)&&p.specGroups.length===0));assert.equal(window.NorthBuiltinShops[0].id,'north-fruit-bowl');vm.runInNewContext(script,{window});assert.equal(window.NorthBuiltinShops.length,2);}});


test('pharmacy second and third image batches append fourteen distinct products with unchanged originals',async()=>{const {createHash}=await import('node:crypto');const hashes=["c90dc106e6c562fe26453f90553562c97f36e5b3aea59df88955298bc1f1c224", "a504566377f91b13cb31888c9a62efe7b8eff68779b5b8d669054cd82a22ad31", "ff3b8586968ca37fa2b8e88ed03dfb21b36530912400ba31ba06d3b5262022f5", "4c1e6bfee47cd5165ed082eabda3549da5c05994b19eb99dafd2e2060a527640", "e4624ad60ed2988eeee2bd8aacbadad64cc19f3c893c1c6e150a8ffd3f82d3a3", "2131d6d46d19fb025bb3effb4dd9c3720ce86bbdd1f7bfaecd75dd1b6744f515", "4f569c51767b2308217b89e276cfb1115ee2dc8153acd19673849db58e1efd57", "efb8889109110e469157cb9b0091696ec599ed7a5257bc17f2892f50ba95e7aa", "d0e881af99f7adc2b1b533f3606f672e836dbbc2464533467560ea573f46f952", "8ceb70826a5278705c54a1d8e49a75c3135af96e3d3710e4975ad3b47379e759", "bdb0e2886fd8da78d1a98934f7e178f787cbbd7b38e1cc800caa6d00a6fa8ee6", "83a2ba89ddd5120d37a86a1cec4ccc1c7a651efb2d923d6122c64b60b3a67d1f", "92c426c0a40db9e3b2c96e5e805b9fc5cea740cb525a5b5ef87b27f9e90f41c4", "71963c96fac9442c0851308a046845ad83eb262fa8a26962b3fcfc197d607580"];const window={};vm.runInNewContext(fs.readFileSync(new URL('../assets/north-pharmacy-shop.js',import.meta.url),'utf8'),{window});const shop=window.NorthBuiltinShops[0];assert.equal(new Set(shop.products.map(p=>p.id)).size,24);shop.products.slice(10).forEach((p,i)=>assert.equal(createHash('sha256').update(Buffer.from(p.image.split(',')[1],'base64')).digest('hex'),hashes[i]));assert.equal(shop.products.find(p=>p.name==='布洛芬缓释胶囊').description.split(' · ')[0],'20粒装');assert.equal(shop.products.find(p=>p.name==='缓解疼痛胶囊').description.split(' · ')[0],'20粒装');});

// v1658: complex specs used to fail the whole order; they are now repaired against the real menu.
for(const priv of [false,true]){
 const src=fs.readFileSync(priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/commerce-ui.js':'commerce-ui.js','utf8');
 function chooser(){const ctx={Date,JSON,Math,Set,Object,Array,String,Number,Error};vm.createContext(ctx);const start=src.indexOf('  function northRoleFoodReceipt('),end=src.indexOf('  function northMarketRoleFoodCard(',start);vm.runInContext(src.slice(start,end),ctx);return ctx;}
 const cake={id:'cake',name:'可爱甜心蛋糕',price:6800,stock:3,available:true,soldOut:false,specGroups:[
  {id:'size',name:'尺寸',required:true,mode:'single',options:[{id:'s4',label:'4寸',price:0},{id:'s6',label:'6寸',price:3000}]},
  {id:'sweet',name:'甜度',required:true,mode:'single',options:[{id:'normal',label:'正常甜',price:0,default:true},{id:'less',label:'少甜',price:0}]},
  {id:'candle',name:'蜡烛',required:false,mode:'multi',options:[{id:'num',label:'数字蜡烛',price:200}]}]};
 const shop={id:'sweet-shop',name:'凌逾甜点',revision:1,minimum:2000,delivery:190,products:[cake]},catalog={shops:[shop]};
 test((priv?'private':'web')+' v1658 a size word in must moves to specs and option labels, missing required groups and single-select overflow are repaired',()=>{
  const t=chooser(),plan=t.northRoleMoveSpecWords({must:['可爱甜心','四寸'],quantity:1,preferences:[]});
  assert.deepEqual(Array.from(plan.must),['可爱甜心']);assert.equal(plan.preferences[0].value,'四寸');
  const offer=t.northRoleChoice(JSON.stringify({shopId:'sweet-shop',primaryId:'cake',lines:[{productId:'cake',quantity:1,selections:{'尺寸':['6寸','4寸']}}]}),catalog,plan);
  assert.deepEqual(Array.from(offer.lines[0].selections.size),['s4'],'用户说四寸就选4寸，单选只留一个');
  assert.deepEqual(Array.from(offer.lines[0].selections.sweet),['normal'],'漏掉的必选组用默认选项补上');
  assert.deepEqual(Array.from(offer.lines[0].selections.candle),[]);
 });
 test((priv?'private':'web')+' v1658 chatty JSON is still read, and a preference the product has no group for is not a failure',()=>{
  const t=chooser(),raw='好的，方案如下：\n{"shopId":"sweet-shop","primaryId":"cake","lines":[{"productId":"cake","quantity":1,"selections":{"size":"s4"}}]}\n希望你喜欢';
  const offer=t.northRoleChoice(raw,catalog,{must:['可爱甜心'],quantity:1,preferences:[{group:'温度',value:'温'}]});
  assert.deepEqual(Array.from(offer.lines[0].selections.size),['s4']);
  assert.throws(()=>t.northRoleChoice(raw,catalog,{must:['巧克力'],quantity:1,preferences:[]}),/口味或品类/,'商品本身不对仍然拒绝');
 });
}
