import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';import {webcrypto} from 'node:crypto';
const core=fs.readFileSync('supabase/functions/phone-shortcuts/core.ts','utf8'),worker=fs.readFileSync('supabase/functions/phone-shortcuts/index.ts','utf8');
function runtime({owner=true,job=null,response='回来啦。'}={}){const calls=[],tasks=[],inserted=[];let encrypted='';
 const client={rpc:async(name,args)=>{calls.push({name,args});return {data:name==='phone_role_push_status'?{ok:owner}:name==='phone_shortcut_claim'?job:name==='phone_shortcut_accept'?{ok:true,jobId:'fixture-id',duplicate:false}:true,error:null};},from:table=>{const q={insert(row){inserted.push({table,row});encrypted=row.config_cipher;return q;},select(){return q;},single:async()=>({data:{id:'fixture-rule'},error:null})};return q;}};
 const ctx=vm.createContext({URL,Date,Set,TextEncoder,TextDecoder,Uint8Array,crypto:webcrypto,btoa,atob,Response,Request,AbortSignal,console,createClient:()=>client,Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://cloud.example.com':'fixture-service-secret'},resolveDns:async()=>['1.1.1.1'],serve:()=>{}},EdgeRuntime:{waitUntil:p=>tasks.push(p)},fetch:async(url,options)=>{calls.push({url:String(url),options});return new Response(JSON.stringify({choices:[{message:{content:response}}]}),{status:200});}});
 vm.runInContext(stripTypeScriptTypes(core.replace(/export /g,'')+'\n'+worker.replace(/^import .*;\r?$/gm,'').replace(/export /g,'')),ctx);
 return {ctx,calls,tasks,inserted,encrypted:()=>encrypted,handle:body=>ctx.handle(new Request('https://cloud.example.com/functions/v1/phone-shortcuts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}))};
}
const input={action:'save',target:'fixture-target',ownerSecret:'a'.repeat(32),clientId:'fixture-client',roleId:'role1',roleName:'角色',name:'到家',mode:'user_message',preset:'我到家了',config:{system:'角色设定',route:{base:'https://model.example.com/v1',key:'PRIVATE-MODEL-KEY',model:'fixture'},history:[]}};
test('shortcut cloud management rejects a foreign owner before storing credentials',async()=>{const r=runtime({owner:false}),res=await r.handle(input);assert.equal(res.status,403);assert.equal(r.inserted.length,0);});
test('shortcut credentials are AES encrypted and trigger token is stored only as hash',async()=>{const r=runtime(),res=await r.handle(input),data=await res.json();assert.equal(res.status,200);assert.match(data.token,/^[a-f0-9]{64}$/);assert(!r.encrypted().includes('PRIVATE-MODEL-KEY'));assert.notEqual(r.inserted[0].row.token_hash,data.token);const decoded=await r.ctx.unseal(r.encrypted(),'fixture-service-secret');assert.equal(decoded.route.key,'PRIVATE-MODEL-KEY');});
test('shortcut cloud execution uses one non-streaming model request and finishes the durable job',async()=>{const job={id:'fixture-job',claim_token:'fixture-claim',mode:'role_event',input_text:'充电'},r=runtime({job});job.config_cipher=await r.ctx.seal(r.ctx.validateConfig(input.config),'fixture-service-secret');await r.ctx.work({rpc:async(name,args)=>{r.calls.push({name,args});return{data:name==='phone_shortcut_claim'?job:true,error:null};}},'https://cloud.example.com','fixture-service-secret','fixture-job');const models=r.calls.filter(x=>x.url?.includes('model.example.com'));assert.equal(models.length,1);assert.equal(JSON.parse(models[0].options.body).stream,false);assert(r.calls.some(x=>x.name==='phone_shortcut_finish'&&x.args.p_reply==='回来啦。'));});
test('empty cloud output becomes a failed job without retry or notification delivery',async()=>{const job={id:'fixture-job',claim_token:'claim',mode:'user_message',input_text:'你好'},r=runtime({job,response:''});job.config_cipher=await r.ctx.seal(r.ctx.validateConfig(input.config),'fixture-service-secret');await r.ctx.work({rpc:async(name,args)=>{r.calls.push({name,args});return{data:name==='phone_shortcut_claim'?job:true,error:null};}},'https://cloud.example.com','fixture-service-secret');assert.equal(r.calls.filter(x=>x.url?.includes('model.example.com')).length,1);assert(r.calls.some(x=>x.args?.p_error==='empty-model-reply'));assert(!r.calls.some(x=>x.url?.includes('phone-role-push')));});
