import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';
const source=fs.readFileSync('supabase/functions/phone-shortcuts/core.ts','utf8'),ctx=vm.createContext({URL,Date,Set});vm.runInContext(stripTypeScriptTypes(source.replace(/export /g,'')),ctx);
test('shortcut URL rejects local and redirect-style endpoints',()=>{for(const value of ['http://example.com','https://localhost','https://127.0.0.1','https://10.0.0.1','https://[::1]','https://user:pass@example.com','https://example.com?redirect=x'])assert.throws(()=>ctx.modelURL(value));assert.equal(ctx.modelURL('https://example.com/v1').href,'https://example.com/v1/chat/completions');});
test('shortcut roles preserve user-message versus event attribution',()=>{const config={system:'角色',history:[],syncedAt:Date.now()};assert.match(ctx.modelMessages(config,{mode:'user_message',input_text:'到家'})[1].content,/代发/);assert.match(ctx.modelMessages(config,{mode:'role_event',input_text:'充电'})[1].content,/不是用户刚发/);});
test('shortcut empty, English-only and explicit AI refusals never become role bubbles in either output mode',()=>{for(const on of [false,true]){for(const raw of ['','[内心|想你]','Hello.','我是一个AI，无法扮演这个角色。'])assert.throws(()=>ctx.visibleReply(raw,on));assert.match(ctx.visibleReply('[内心|想你]\n回来啦。',on),/回来啦/);}});
test('shortcut queue has exact-event dedup, quotas, revocation and no automatic model retry',()=>{const sql=fs.readFileSync('supabase/migrations/202609080002_phone_shortcuts.sql','utf8');for(const part of ['unique(rule_id,event_id)','for update skip locked','worker-timeout','daily_limit','r.revision<>j.revision','revoke all'])assert(sql.includes(part));const worker=fs.readFileSync('supabase/functions/phone-shortcuts/index.ts','utf8');assert(worker.includes("redirect:'error'"));assert(worker.includes("AES-GCM"));assert(!worker.includes('console.log'));assert(worker.includes("input.action||'trigger'"));});

function screenImportRuntime(prefix=''){
 const source=fs.readFileSync(prefix+'phone-shortcuts.js','utf8'),elements={},state={couple:{cid:'role-a',companion:{screenTimeSec:999}},me:{active:'main'}};
 let saved=true;const sandbox={window:{},Date,Set,Error,JSON,Number,String,Math,S:state,actId:()=>state.me.active,esc:s=>String(s).replace(/</g,'&lt;'),toast:()=>{},openModal:html=>{sandbox.modal=html;},closeModal:()=>{},render:()=>{},saveNowAsync:async()=>saved,uiConfirm:async()=>true,$:id=>elements[id],renderCouple:()=>'<div id="coupage1"><p>existing</p></div>',chatAPI:async messages=>{sandbox.sent=messages;return 'ok';},buildSystem:()=> 'original-chat-system'};
 vm.createContext(sandbox);vm.runInContext(source.slice(source.indexOf('/* Screen Time shortcut import:')),sandbox);return{sandbox,state,elements,api:sandbox.window.PhoneScreenTimeImport,setSaved:value=>{saved=value;}};
}
for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/']){
 test(prefix+'screen import keeps named duration pairs, zero and overlap separate',()=>{const{api}=screenImportRuntime(prefix),r=api.parse('抖音 | 11,040.155秒钟\nWeb | 2100\nexample.com | 2100\n未使用 | 0','2026-01-01');assert.equal(r.apps[0].seconds,11040.155);assert.equal(r.apps[3].seconds,0);assert.equal(r.apps.length,4);assert.equal(r.totalSeconds,undefined);assert.equal(api.parse('微信\n57分钟','2026-01-01').apps[0].seconds,3420);for(const raw of ['微信 | -1','微信 | 86401','微信 | 1\n微信 | 2','这里只有名称','[{"name":"微信","seconds":null}]'])assert.throws(()=>api.parse(raw,'2026-01-01'));assert.throws(()=>api.parse('微信 | 1','2026-02-30'));assert.throws(()=>api.parse('微信 | 1','2099-01-01'));});
 if(prefix) test(prefix+'screen import consent, account and role boundaries survive failed saves',async()=>{const r=screenImportRuntime(prefix),{api,state,elements,sandbox}=r,now=new Date(),date=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');api.open();elements['#sti_text']={value:'抖音 | 11040.155'};elements['#sti_day']={value:date};elements['#sti_consent']={checked:false};api.prepare();r.setSaved(false);assert.equal(await api.commit(),false);assert.equal(state.couple.shortcutScreenTime,undefined);r.setSaved(true);assert.equal(await api.commit(),true);assert.equal(api.prompt({id:'role-a'}),'');assert.equal(state.couple.companion.screenTimeSec,999);state.couple.shortcutScreenTime.roleAccess=true;assert(api.prompt({id:'role-a'}).includes('11040.155'));assert.equal(api.prompt({id:'role-b'}),'');state.me.active='other';assert.equal(api.record(),null);assert.equal(api.prompt({id:'role-a'}),'');state.me.active='main';state.couple.shortcutScreenTime.date='2026-01-01';assert.equal(api.prompt({id:'role-a'}),'');assert(sandbox.renderCouple().includes('cou_shortcut_screen_time'));api.open();state.couple.cid='role-b';api.prepare();assert.equal(await api.commit(),false);assert.equal(state.couple.shortcutScreenTime.cid,'role-a');});
}


test('screen upload parses actual iPhone seconds, skips anonymous website rows and preserves zero',()=>{
 const r=ctx.screenSnapshot('抖音 | 11,601.648秒\n | 2,747.097秒\n微信 | 0秒','2026-10-05',Date.parse('2026-10-05T11:00:00+08:00'));
 assert.equal(r.apps.length,2);assert.equal(r.apps[0].seconds,11601.648);assert.equal(r.apps[1].seconds,0);assert.equal(r.skipped,1);assert.equal(r.totalSeconds,undefined);
 for(const text of ['微信 | -1','微信 | 86401','微信 | 1\n微信 | 2',' | 1','微信 | nope'])assert.throws(()=>ctx.screenSnapshot(text,'2026-10-05',Date.parse('2026-10-05T11:00:00+08:00')));
 assert.throws(()=>ctx.screenSnapshot('微信 | 1','2026-02-30'));assert.throws(()=>ctx.screenSnapshot('微信 | 1','2099-01-01'));
});
for(const prefix of ['', 'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'])test(prefix+'direct cloud read refreshes before chat without leaking another role or stale session',async()=>{
 const r=screenImportRuntime(prefix),{state,sandbox,api}=r,auth={target:'owner-a',clientId:'phone_main',url:'https://cloud.example'},today=new Date().toLocaleDateString('en-CA');
 // toLocaleDateString is not used by production; derive its local date explicitly.
 const d=new Date(),date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
 let calls=0,resolve;
 sandbox.PhoneShortcuts={identity:()=>auth,request:async()=>{calls++;return{ok:true,enabled:true,snapshot:{date,apps:[{name:'微信',seconds:20}],skipped:1},receivedAt:new Date().toISOString()};}};
 sandbox.fmtDT=String;state.couple.screenCloudByRole={'main:role-a':{enabled:true,...auth,record:null}};
 assert.equal(await api.cloudPull(true),true);assert.equal(calls,1);await sandbox.chatAPI([{role:'system',content:sandbox.buildSystem({id:'role-a'})}],{});assert.equal(calls,2);assert(sandbox.sent[0].content.includes('20'));assert(api.cloudPrompt({id:'role-a'}).includes('20'));assert.equal(api.cloudPrompt({id:'role-b'}),'');assert.equal(state.couple.companion.screenTimeSec,999);
 sandbox.PhoneShortcuts.request=()=>new Promise(done=>resolve=done);const pending=api.cloudPull(true);state.me.active='other';resolve({ok:true,enabled:true,snapshot:{date,apps:[{name:'secret',seconds:100}]},receivedAt:new Date().toISOString()});assert.equal(await pending,false);assert.equal(api.cloudPrompt({id:'role-a'}),'');assert.equal(state.couple.screenCloudByRole['main:role-a'].record.apps[0].name,'微信');
});

test('web retires manual import without erasing stored records or exposing them to chat',()=>{const{sandbox,state,api}=screenImportRuntime();sandbox.fmtDT=String;const old={cid:'role-a',account:'main',roleAccess:true,apps:[{name:'stored-secret',seconds:42}]};state.couple.shortcutScreenTime=old;assert(!sandbox.renderCouple().includes('cou_shortcut_screen_time'));assert(sandbox.renderCouple().includes('cou_screen_cloud'));assert.equal(api.open,undefined);assert.equal(api.commit,undefined);assert.equal(sandbox.buildSystem({id:'role-a'}),'original-chat-system');assert.equal(state.couple.shortcutScreenTime,old);});


test('web couple space opens after unbinding without requesting a missing controller identity',async()=>{
 const {sandbox,state,api}=screenImportRuntime();let calls=0;
 sandbox.PhoneShortcuts={identity:()=>{calls++;throw Error('missing couple identity');},request:()=>{throw Error('must not request while unbound');}};
 for(const unbound of [null,{}, {cid:''}]){state.couple=unbound;assert.equal(api.cloudPanel(),'');assert.equal(await api.cloudPull(true),false);assert.equal(api.cloudPrompt({id:'role-a'}),'');assert.equal(sandbox.buildSystem({id:'role-a'}),'original-chat-system');assert.equal(sandbox.renderCouple(),'<div id="coupage1"><p>existing</p></div>');}
 assert.equal(calls,0);
 state.couple={cid:'role-a',companion:{}};sandbox.PhoneShortcuts.identity=()=>{calls++;return {target:'restored',clientId:'phone_main',url:'https://cloud.example'};};sandbox.fmtDT=String;assert(sandbox.renderCouple().includes('cou_screen_cloud'));assert(calls>0);
});

test('web in-flight screen pull cannot write into a newly rebound couple',async()=>{
 const {sandbox,state,api}=screenImportRuntime();const auth={target:'owner-a',clientId:'phone_main',url:'https://cloud.example'};let resolve;const old=state.couple;old.screenCloudByRole={'main:role-a':{enabled:true,...auth,record:null}};sandbox.PhoneShortcuts={identity:()=>auth,request:()=>new Promise(done=>resolve=done)};sandbox.fmtDT=String;const pending=api.cloudPull(true);state.couple=null;state.couple={cid:'role-b',companion:{}};resolve({ok:true,enabled:true,snapshot:{date:'2026-01-01',apps:[{name:'private-old-role',seconds:10}]},receivedAt:new Date().toISOString()});assert.equal(await pending,false);assert.equal(old.screenCloudByRole['main:role-a'].record,null);assert.equal(state.couple.screenCloudByRole,undefined);assert.equal(api.cloudPrompt({id:'role-a'}),'');
});
