import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync(new URL('../delivery.js',import.meta.url),'utf8');
const notices=[];
const chatMessages=[];
const roleSearches=[];
let oldSearchCalls=0;
let sequence=0;
let intermediateModelCalls=0;
const role={id:'role-1',name:'North',remark:'',avatar:'🖤'};
const ctx={
  console,URL,AbortController,JSON,Date,Math,Promise,Number,String,Array,Object,RegExp,
  COMPANION_URL:'https://delivery.example.test',COMPANION_KEY:'public-test-key',
  APP_VER:'v-test',S:{me:{name:'我'},food:{cart:[],results:[],q:''},contacts:[role]},
  _foodBusy:false,
  foodSearch(){oldSearchCalls++;},foodBuy(){},openFoodCart(){},openFoodOrders(){},
  privateNativeAppOn(){return false;},save(){},render(){},toast(){},uid(){return 'id-'+(++sequence);},
  getC(id){return id===role.id?role:null;},cur(){return{p:'home'};},
  scheduleReply(id,note){notices.push({id,note});return true;},
  msgs(id){return id===role.id?chatMessages:[];},
  chatAPI:async()=>{intermediateModelCalls++;return '{"matched":true,"offerId":"offer-1","reason":""}';},
  esc:s=>String(s),av:s=>String(s),openModal(){},closeModal(){},
  document:{hidden:false,getElementById(id){return id==='food_q'?{value:'奶茶'}:null;},addEventListener(){}},
  setInterval(){return 1;},setTimeout(){return 1;},clearTimeout(){},
  addEventListener(){},open(){},
};
ctx.window=ctx;
vm.runInNewContext(source,ctx,{filename:'delivery.js'});
const roleAction={structuredModelAction:true,allowNewTask:true,accountId:'main',sessionId:'role-1:main',turnId:'message-1',messageId:'message-1',modelReplyId:'reply-1',channel:'chat',userText:'帮我在真实奶茶店点一杯真实奶茶'};

assert.equal(ctx.deliveryRealEnabled(),false,'real delivery defaults off at runtime');
await ctx.foodSearch();
assert.equal(oldSearchCalls,1,'virtual search remains active while real delivery is off');

ctx.S.food.real.connectorUrl='https://delivery.example.test/api';
ctx.deliverySetEnabled(true);
let mode='search-fail';
ctx.fetch=async(_url,init)=>{
  const body=JSON.parse(init.body);
  if(mode==='search-fail')return {ok:false,status:503,json:async()=>({ok:false,error:'平台维护'})};
  if(body.action==='search'&&body.payload?.task?.taskId)roleSearches.push({
    taskId:body.payload.task.taskId,
    revision:body.payload.task.revision,
    merchant:body.payload.orderIntent?.merchant,
    items:body.payload.orderIntent?.items,
  });
  if(mode==='empty'&&body.action==='search')return {ok:true,status:200,json:async()=>({ok:true,data:{offers:[]}})};
  if(body.action==='search')return {ok:true,status:200,json:async()=>({ok:true,data:{offers:[{offerId:'offer-1',provider:'taobao_flash',merchantId:'m1',merchant:'真实奶茶店',name:'真实奶茶',price:18,deliveryFee:2,total:20,quoteId:'q1',addressFingerprint:'addr-1',optionsLoaded:true,optionGroups:[]}]}})};
  if(body.action==='create_order')return {ok:true,status:200,json:async()=>({ok:true,data:{orderId:'order-1',provider:'taobao_flash',merchantId:'m1',merchant:'真实奶茶店',items:[{name:'真实奶茶',quantity:1,price:18}],total:20,status:'created',addressFingerprint:'addr-1'}})};
  if(body.action==='pay_order')return {ok:true,status:200,json:async()=>({ok:true,data:{status:'pending_payment',paymentMethod:'alipay',payUrl:'https://alipay.example.test/cashier',payQrDataUrl:'data:image/png;base64,iVBORw0KGgo='}})};
  throw new Error('unexpected action '+body.action);
};
await ctx.foodSearch();
assert.equal(oldSearchCalls,1,'real search failure must never call the virtual search fallback');
assert.equal(ctx.S.food.results.length,0,'real search failure leaves the result list empty');

mode='success';
await ctx.foodSearch();
assert.equal(ctx.S.food.results.length,1);
assert.equal(ctx.S.food.results[0].merchant,'真实奶茶店');

ctx.S.food.real.approvedAddressFingerprint='addr-1';
role.deliveryWallet={balance:100,singleLimit:100,dailyLimit:200,spentDay:'',spentToday:0,ledger:[]};
mode='empty';
await ctx.deliveryHandleRoleRequest(role.id,'用户明确；门店=真实奶茶店；商品=不存在奶茶',roleAction);
const pendingTask=ctx.S.food.real.roleTasks[roleSearches[0].taskId];
assert.equal(ctx.S.food.orders.length,0,'an empty store-local result must not create an order');
assert.equal(chatMessages.length,0,'an empty result must not manufacture a role chat message or order card');
assert.equal(pendingTask.status,'awaiting_clarification');
assert.equal(pendingTask.clarification.kind,'product_name');
assert.equal(ctx.S.food.real.roleClarifications[role.id].taskId,pendingTask.taskId);
assert.equal(notices.length,1,'the real role model receives one fact prompt for the missing product');
assert.match(notices[0].note,/按你自己的完整人设、当前关系和说话习惯/);
assert.match(notices[0].note,/商品的准确名称到底叫什么/);
assert.match(notices[0].note,/句式必须由你自己生成，不要照抄固定话术/,'the visible clarification must be generated by the role, not a canned reply');

mode='success';
const clarificationAction={...roleAction,turnId:'message-2',messageId:'message-2',modelReplyId:'reply-2',userText:'叫真实奶茶'};
await ctx.deliveryHandleRoleRequest(role.id,'换品:用户明确；门店=真实奶茶店；商品=真实奶茶',clarificationAction);
assert.equal(roleSearches.length,2);
assert.equal(roleSearches[1].taskId,roleSearches[0].taskId,'the clarification answer must continue the original authorized task');
assert.equal(roleSearches[1].revision,roleSearches[0].revision+1,'a clarification answer advances the same task by exactly one revision');
assert.deepEqual(roleSearches[1].items,['真实奶茶']);
assert.equal(ctx.S.food.orders[0].status,'pending_payment','ordinary users receive an official unpaid order');
assert.equal(role.deliveryWallet.balance,100,'the retired role wallet is never debited');
assert.equal(role.deliveryWallet.spentToday,0);
assert.equal(chatMessages.length,1,'a complete unpaid order with an official QR becomes one chat card');
assert.equal(notices.length,2,'the role receives one clarification prompt and one final result prompt');
assert.match(notices[1].note,/真实外卖已经提交，平台已经生成这笔真实订单/,'the role must know that the checkout card represents a submitted real order');
assert.doesNotMatch(notices[1].note,/当前仍是“待付款”，并未付款/,'the role must not narrate the internal pending-payment label');
assert.match(notices[1].note,/平台没有返回付款结果时也不要擅自声称已经付款/,'submitted must not be misrepresented as a confirmed payment');
assert.match(notices[1].note,/禁止提到“卡片”“系统”“二维码”“付款入口”“收银台”/,'the model prompt must keep payment UI jargon out of the role reply');
assert.match(notices[1].note,/禁止说“自己去付款”/,'the role must not issue a system-like payment command');
assert.equal(intermediateModelCalls,0,'candidate and option automation must finish without a second model request');

console.log('real delivery state-machine tests passed');
