import assert from 'node:assert/strict';
import fs from 'node:fs';

const delivery=fs.readFileSync(new URL('../delivery.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const theme=fs.readFileSync(new URL('../glass-theme.css',import.meta.url),'utf8');

assert.match(delivery,/type:'deliveryorder'/,'a successful role order must create a dedicated chat card');
assert.match(delivery,/!safePayQr\(order\.payQrDataUrl\)/,'a role order card must require a real scannable payment QR');
assert.match(delivery,/var card=order&&pushRoleOrderCard\(c,order\);if\(order&&!card\)/,'an order without a real payment QR must remain a system-only state');
assert.doesNotMatch(delivery,/createOrder\([\s\S]{0,500}pushRoleOrderCard\(c,order\);await payOrder\(order\)/,'a confirm-page draft must not appear as a completed chat card before the cashier is reached');
assert.match(delivery,/imageUrl:safeOrderImage\(data\.imageUrl\|\|offer\.imageUrl/,'the real platform product image must follow the selected offer');
assert.match(delivery,/function safeOrderImage\(v\)\{[\s\S]*?data:image/,'a browser-captured real image must remain usable as an embedded card image');
assert.match(delivery,/cover=img\|\|'assets\/delivery-fallback-kangaroo\.jpg'/,'the user supplied kangaroo image must be the fallback cover when the platform image is absent');
assert.match(delivery,/esc\(img\?names:'订单封面'\)/,'a real platform image must remain preferred over the fallback cover');
assert.doesNotMatch(delivery,/providerText\(o\.provider\)\)\+' · REAL DELIVERY/,'the platform caption line must be absent from the chat card');
assert.doesNotMatch(delivery,/wx-real-delivery-detail-image|wx-real-delivery-detail-placeholder/,'the detail sheet must not repeat the large product image or placeholder');
assert.match(delivery,/etaMinutes:Number\.isFinite\(\+data\.etaMinutes\)/,'the platform ETA must follow the selected offer without fabrication');
assert.match(delivery,/etaText:safeEtaText\(data\.etaText\)/,'the exact checkout delivery window must be stored on the real order');
assert.match(delivery,/etaText:safeEtaText\(order\.etaText\)/,'the exact delivery window must be copied into the chat-card snapshot');
assert.match(delivery,/function orderEtaText\(order,withClock\)\{var exact=safeEtaText\(order&&order\.etaText\);if\(exact\)return exact;/,'the chat card must prefer the exact platform delivery window');
assert.match(delivery,/syncRoleOrderCard\(order\)[\s\S]*?refreshChatMessages\(order\.roleId\)/,'payment QR, amount, and ETA updates must rerender the visible role chat card immediately');
assert.match(delivery,/平台暂未给出预计送达时间/,'missing ETA must be disclosed instead of invented');
assert.match(delivery,/可以截图后，在支付宝“扫一扫”中从相册选择/,'the official payment QR must explain the screenshot workflow');
assert.match(delivery,/请严格按你自己的完整人设、当前关系和说话习惯/,'the short companion reply must remain persona-driven');
assert.doesNotMatch(delivery,/只按你自己的说话习惯自然说一句让对方查看卡片/,'the role must not be prompted to narrate the card UI');
assert.match(delivery,/禁止提到“卡片”“系统”“二维码”“付款入口”“收银台”/,'the role result must stay natural and must not expose payment UI instructions');
assert.match(delivery,/禁止说“自己去付款”/,'the role must not order the user around with system-like payment wording');
assert.match(delivery,/平台本次唯一可信的预计送达时间/,'the role must receive the same exact ETA window used by the card');
assert.match(delivery,/不得沿用历史聊天中的十五分钟、四十分钟或其他旧时间/,'old fallback ETA language must not override the current platform window');
assert.match(delivery,/if\(data\.imageUrl!=null\)\{var paidImage=/,'a real image returned at cashier time must update the live order and visible card');
assert.match(delivery,/if\(data\.imageUrl!=null\)\{var statusImage=/,'a later real image returned by status polling must update the card');
assert.match(delivery,/正在交给系统打开官方付款页面/,'payment launching must report an in-progress handoff rather than a false success');
assert.doesNotMatch(delivery,/已打开官方付款页面；付款后刷新订单状态/,'the UI must never claim that an external payment app opened before iOS confirms navigation');
assert.match(delivery,/订单已进入临近送达阶段，这次必须自然提醒一次/,'the role must issue one persona-driven near-arrival reminder from real platform status');
assert.match(delivery,/function armEtaReminder\(order\)/,'paid role orders with an exact platform ETA must arm a local near-arrival reminder without refreshing the delivery browser');
assert.match(delivery,/\(STATUS_RANK\[order\.status\]\|\|0\)<STATUS_RANK\.paid/,'unpaid orders must never schedule a delivery reminder');
assert.match(delivery,/order\.notifiedStatuses\.push\('eta_near'\)/,'the exact ETA reminder must be emitted at most once');
assert.match(delivery,/TERMINAL\[order\.status\]\)clearEtaReminder\(order\)/,'terminal platform states must cancel pending ETA reminders');
assert.match(delivery,/<h4>'\+esc\(names\)\+'<\/h4><p>'\+esc\(o\.merchant\|\|'外卖商家'\)\+'<\/p>/,'the bright primary line must be the product name and the lighter secondary line the real merchant');
assert.doesNotMatch(delivery,/\[真实外卖操作结果\]/,'technical operation prompts must not leak into chat bubbles');
assert.match(app,/m\.type==='deliveryorder'.*deliveryRealChatCardHTML/s,'chat rendering must use the real delivery card component');
assert.match(theme,/\.wx-real-delivery-card/,'the card must have dedicated dark-theme styling');
assert.match(theme,/\.wxlight \.wx-real-delivery-card/,'the card must have dedicated light-theme styling');
assert.ok(fs.existsSync(new URL('../assets/delivery-fallback-kangaroo.jpg',import.meta.url)),'the fallback cover must exist in the web assets');
assert.ok(fs.existsSync(new URL('../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/assets/delivery-fallback-kangaroo.jpg',import.meta.url)),'the fallback cover must also exist in the private app bundle');

console.log('real delivery chat-card tests passed');
