import assert from 'node:assert/strict';
import fs from 'node:fs';

const delivery=fs.readFileSync(new URL('../delivery.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const bundledDelivery=fs.readFileSync(new URL('../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/delivery.js',import.meta.url),'utf8');
const bundledApp=fs.readFileSync(new URL('../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js',import.meta.url),'utf8');
const browser=fs.readFileSync(new URL('../services/phone-delivery-browser/src/taobao-flash-browser.mjs',import.meta.url),'utf8');
const adapter=fs.readFileSync(new URL('../services/phone-delivery-browser/src/adapter.mjs',import.meta.url),'utf8');

assert.match(delivery,/var roleRequests=\{\}/,'role delivery must keep an in-flight lock');
assert.match(delivery,/if\(roleRequests\[task\.taskId\]\)return true/,'a repeated authorized task must not start a second browser order');
assert.match(delivery,/finally\{delete roleRequests\[task\.taskId\];\}/,'the task-scoped in-flight lock must always be released');
assert.match(delivery,/async function reconcileRecentRoleOrder/,'a restored local order must be reconciled with the live service before blocking a new request');
assert.match(delivery,/roleRequests\[task\.taskId\]=\{status:'reconciling'\}/,'the live reconciliation itself must be protected by the authorized task id');
assert.match(delivery,/await request\('order_status',\{orderId:order\.remoteId\}/,'the duplicate-order guard must verify the previous remote order');
assert.match(delivery,/电脑外卖服务重启后已无法继续上一笔订单，已解除防重复锁/,'a service restart must release an unverifiable stale local order');
assert.doesNotMatch(delivery,/20分钟内已有一笔角色真实外卖订单仍在处理/,'the client must not reject a new request solely from a stale local timestamp');
assert.match(delivery,/order\.status==='created'\|\|order\.status==='pending_payment'\?null:order/,'an unpaid checkout must not prevent the user from starting another order');
assert.match(delivery,/已有一笔已付款的真实外卖仍在接单、制作或配送/,'only a paid in-progress delivery should retain duplicate protection');
assert.match(delivery,/r\.roleAttempts\[cid\]=task/,'a completed or failed role task must be remembered');
assert.match(delivery,/Date\.now\(\)-a\.startedAt>180000/,'a stale restored attempt must terminate instead of remaining busy forever');
assert.match(delivery,/lastUserAt<=attempt\.endedAt/,'a terminal result cannot restart until the user sends a new message');
assert.match(delivery,/绝对不要再次说“等一下\/我再找找”/,'the role must not repeat the search prelude while an attempt is running or terminal');
assert.match(delivery,/order=await createOrder\([\s\S]*?await payOrder\(order\);[\s\S]*?resultReply\(c,order,''\)/,'the real order card must not appear until payment-link retrieval has completed');
assert.doesNotMatch(delivery,/pushRoleOrderCard\(c,order\);await payOrder\(order\)/,'a checkout draft must never be exposed as a completed role order');
assert.match(delivery,/function roleSystemNotice/,'technical delivery results must have a system-only status channel');
assert.match(delivery,/if\(error\)\{[\s\S]*roleSystemNotice[\s\S]*failureKind==='shop_closed'[\s\S]*scheduleReply/,'a confirmed closed-shop fact may schedule a natural role reply after failure');
assert.match(delivery,/全部打烊或休息中/,'closed saved shops must be reported as a factual availability result');
assert.match(delivery,/不要复述技术提示/,'the role must not paste internal delivery diagnostics into chat');
assert.doesNotMatch(delivery,/\[真实外卖操作结果\]/,'internal delivery-operation prompts must never be sent into role chat');
assert.match(delivery,/失败原因已经由系统在外卖控制页提示/,'the role prompt must keep failure details out of chat');
assert.match(delivery,/订单卡片只负责展示真实订单明细/,'the card must not replace the role acknowledgement');
assert.match(delivery,/不能因为已经发送订单卡片而保持沉默/,'a completed order must still receive a first-person persona reply');
assert.match(delivery,/你可以按人设追问，也可以直接自主决定/,'a vague food wish may be clarified or become the role current-turn autonomous choice');
assert.match(delivery,/这就已经是完整答案：不要再追问品牌、商品、口味、糖度、温度或规格/,'an autonomous order grant must not trigger another clarification loop');
assert.match(delivery,/function roleRequestIntent/,'the browser request must retain actual user messages separately from role search text');
assert.match(delivery,/authorizationConstraints:text\(task&&task\.authorizationConstraints\|\|/,'the service must bind the immutable original user authorization separately');
assert.match(delivery,/userConstraints:text\(\(task&&task\.userMessages\|\|\[\]\)\.join\('\\n'\),800\)/,'the service must receive the current task hard constraints');
assert.match(delivery,/task\.autonomous=intent\.autonomous/,'the task must remember whether the user delegated the choice');
assert.match(delivery,/authorizationSource:source/,'every task must persist its authorization source');
assert.match(delivery,/task\.authorizationSource==='role_current_turn'/,'a current-turn role action must explicitly carry autonomous authorization');
assert.match(delivery,/structuredModelAction/,'browser work must require the current real-model structured action marker');
assert.match(delivery,/可以在任何当前真实模型回合按本人意愿主动发起/,'the role may autonomously initiate delivery in any current genuine-model turn');
assert.match(delivery,/只有这个当前结构化动作能授权启动/,'autonomous permission must still be expressed by the current model action instead of stale chat or page restoration');
assert.match(delivery,/choice\.selected/,'unspecified options must preserve a real platform-selected default');
assert.match(delivery,/平台“'\+name\+'”没有本次明确要求/,'an unavailable explicit option must pause instead of silently choosing another specification');
assert.match(delivery,/function requestRoleClarification/,'uncertain real options must pause for a user clarification');
assert.match(delivery,/kind==='minimum_order'/,'a real minimum-order block must pause instead of leaving the role silent');
assert.match(delivery,/kind==='history_repeat'/,'a historical cart with extra items must have its own clarification state');
assert.match(delivery,/真实外卖等待历史套餐确认/,'the role must wait for explicit approval before reusing a historical superset');
assert.match(delivery,/之前买过的那个套餐、上次点过的套餐、买过的套餐/,'the role must preserve a previous-purchase package selector instead of inventing a product title');
assert.match(delivery,/只会在这家指定门店内选择唯一带“买过”标记的真实套餐/,'the role prompt must keep the bought-package selector scoped to one explicit merchant');
assert.match(delivery,/包含本次全部指定商品、但还带有额外商品/,'the role must explain the real extra-item fact without pretending the order succeeded');
assert.ok(delivery.includes("clarification.kind==='history_repeat'&&/^继续确认历史订单$/.test"),'only the dedicated explicit-approval command may unlock a historical superset');
assert.match(delivery,/confirmedHistoricalSuperset:intent\.confirmedHistoricalSuperset===true/,'explicit approval must be carried to the protected create-order request');
assert.match(delivery,/若对方拒绝、多余商品不要了/,'rejecting the extra historical items must run a fresh current-request search');
assert.match(delivery,/真实外卖等待起送补充/,'the role must ask for a distinct add-on when the minimum order is not met');
assert.match(delivery,/主商品始终只保留一份：奶茶只能补同店不重复的小料，主食只能补同店不重复的小吃/,'minimum-order clarification must preserve one main item and ask for a category-safe add-on');
assert.doesNotMatch(delivery,/同款增加到至少/,'the role must never suggest duplicating milk tea or a meal to reach the minimum order');
assert.doesNotMatch(delivery,/resumedChoice\.quantity=Math\.max/,'clarification resume must never force the main item quantity upward');
assert.match(delivery,/系统会沿用原 taskId，并保留同一门店和原主商品/,'a minimum-order answer must continue the existing authorized task and original item');
assert.match(delivery,/如果你想选热饮而当前商品没有热饮，只需自然问是否换一种/,'the role must naturally ask before switching away from an unavailable hot drink');
assert.match(delivery,/真实外卖等待规格确认/,'the next user answer must resume the paused option flow');
assert.match(delivery,/\[真实外卖\|换品:/,'a newly named product must abandon the old candidate and run one fresh search');
assert.match(delivery,/function clarificationFirstMatch/,'a same-task clarification may explicitly relax a full product name to a visible keyword');
assert.match(delivery,/firstMatch\.keyword[\s\S]*?originalIntent\.items\.slice\(1\)/,'a first-visible keyword answer must retain all later requested products');
assert.match(delivery,/只说“撒汤”[\s\S]*?商品=撒汤/,'the role must relay the actual match keyword instead of an instruction word');
assert.match(delivery,/撒汤”和“套餐”[\s\S]*?商品=撒汤套餐/,'all explicit title keywords must remain conjunctive in the clarification action');
assert.match(delivery,/详细原因已保留在外卖设置/,'long technical diagnostics must stay out of the chat overlay');
assert.match(delivery,/始终保留自己的判断和意愿/,'the role may accept or refuse the delivery request according to its persona');
assert.match(app,/_realDeliveryCommandSeen=false/,'the parser must track the command boundary');
assert.match(app,/_realDeliveryPreludeShown=false/,'the parser must limit a structured order turn to one visible opening line');
assert.match(app,/typeof deliveryRolePreludeAllowed==='function'&&deliveryRolePreludeAllowed\(line\)/,'only a safe current-model prelude may be shown before automation');
assert.match(app,/replace\(\/\(\[\^\\r\\n\]\)\(\[\\\[【\]/,'an acknowledgement and embedded action tag must be split before bubble parsing');
assert.match(delivery,/不能使用系统固定话术/,'the opening line must never be manufactured from canned system text');
assert.doesNotMatch(delivery,/setInterval\(function\(\)\{pollOrders/,'background timers must not navigate the delivery browser');
assert.doesNotMatch(delivery,/visibilitychange[^\n]*pollOrders|addEventListener\('online'[^\n]*pollOrders|setTimeout\(function\(\)\{pollOrders/,'refresh, foreground and network events must not poll the marketplace');
assert.match(browser,/function normalizeOptionPanelGroups/,'platform hint rows must be removed before a bundle is offered to the role');
assert.match(browser,/selectionCount > 1/,'multi-item bundles must retain their exact selection count');

for(const marker of ['roleRequestIntent','roleRequest','realSearch','createOrder','requestRoleClarification']){
  assert.match(bundledDelivery,new RegExp('function '+marker+'\\b'),`private delivery handoff function missing: ${marker}`);
}
assert.match(delivery,/function recoverExplicitDeliveryIdentity/,'the friend web entry must recover an isolated delivery identity mismatch');
for(const marker of ['_realDeliveryCommandSeen=false','_realDeliveryPreludeShown=false','deliveryRolePreludeAllowed(line)',"content=String(content||'').replace(/([^\\r\\n])"]){
  assert.ok(bundledApp.includes(marker),`private app delivery handoff marker missing: ${marker}`);
}
for(const fn of ['roleRequestIntent','roleRequest','realSearch','createOrder','requestRoleClarification'])assert.match(delivery,new RegExp('function '+fn+'\\b'),'the P0 authorization boundary must cover '+fn);
assert.match(delivery,/taskId:'delivery_'|var taskId='delivery_'/,'every legal start must generate a unique task id');
for(const field of ['authorizationSource','roleId','accountId','sessionId','turnId','messageId','createdAt','intentSummary','status','completedItems','clarification'])assert.match(delivery,new RegExp(field),'tasks must persist '+field);
assert.match(delivery,/TASK_TERMINAL\[task\.status\]/,'terminal tasks cannot be resumed');
assert.match(delivery,/task\.status='expired'/,'stale clarification tasks must expire instead of restoring');
assert.match(delivery,/if\(answeringClarification\)\{task\.lastAnswerTurnId=meta\.turnId;[\s\S]*?intent=\{searchQuery:task\.query/,'clarification must restore the existing intent directly');
assert.doesNotMatch(delivery.slice(delivery.indexOf('if(answeringClarification){task.lastAnswerTurnId='),delivery.indexOf('}else{intent=roleRequestIntent',delivery.indexOf('if(answeringClarification){task.lastAnswerTurnId='))),/roleRequestIntent\(/,'a clarification answer, including a changed product, must not rerun roleRequestIntent');
assert.match(delivery,/if\(clarification&&\(!continueClarification&&!changeProduct\|\|meta\.turnId===task\.turnId\|\|meta\.turnId===task\.lastAnswerTurnId\)\)return true/,'old turns and unrelated tags cannot masquerade as a clarification answer');
assert.match(app,/structuredModelAction:true,allowNewTask:_(?:deliveryCurrentUserTurn|deliveryCurrentCallTurn),accountId:/,'chat and call model parsers must attach current-turn authorization metadata');
assert.match(delivery,/if\(!meta\.allowNewTask\|\|!meta\.messageId\|\|!meta\.userText\)return true/,'background replies and stale user context must not create or resume an order');
assert.match(delivery,/storedTaskTurnKey\(x\)===turnKey\|\|x\.actionKey===actionKey/,'one user/model turn must create at most one task even if a later model reply changes the search text');
assert.match(delivery,/普通聊天中的“饿了、没吃饭、想吃东西、奶茶、果汁”等词本身永远不能启动浏览器/,'ordinary chat keywords must not directly trigger an order');
assert.match(delivery,/主动关心；门店=/,'the current real model can emit a structured autonomous action');
assert.match(adapter,/roleSearchAttempts/,'the service must make task search idempotent');
assert.match(adapter,/roleCreateAttempts/,'the service must make task order creation idempotent');
assert.match(adapter,/TERMINAL_TASKS\.has\(task\.status\)/,'the service must reject terminal task restoration');
assert.match(adapter,/authorizationConstraints/,'the service must keep the original authorization immutable across clarification turns');
assert.match(adapter,/task\.revision > known\.revision \+ 1/,'clarification revisions must be contiguous');
assert.match(adapter,/known\.userConstraints = task\.userConstraints/,'one newer clarification revision may add the current user answer to the same task');
assert.match(browser,/const marketplaceQuery = brandQuery/,'global search must use only the store name');
assert.doesNotMatch(browser,/const marketplaceQuery = \[brandQuery, requestedItemName\(query\)\]/,'product names must not be joined into global store search');
assert.match(browser,/knownRouteKey\(storeQuery\)[\s\S]*?activeStoreMatches/,'an arbitrary structured store name must not reuse an unrelated active storefront');
assert.match(browser,/ref\.explicitItemsComplete = true/,'explicit items must complete before minimum-order top-up');
assert.match(browser,/结算条件不完整：必须先完成全部指定商品并达到起送金额/,'checkout must independently require complete items and minimum price');
assert.match(browser,/quantity > 1 && !multiServingEligible/,'the service must reject duplicate milk-tea and meal main items');
assert.match(browser,/'撒汤': \/撒汤\//,'a clarified core soup keyword must be recognized from the real product title');
assert.match(browser,/Array\.from\(targetKey\)\.length === 2 \|\| requiredTitleTerms\.length > 1[\s\S]*?firstContained/,'an explicit two-character core or multi-keyword product must choose the first eligible real title');
assert.match(browser,/requiredTitleTerms\.every\(term => candidateKey\.includes\(term\)\)/,'every explicitly requested title term, including 套餐, must be present in the real product title');
assert.match(browser,/function shortFoodTitleAliasEligible[\s\S]*?奶茶[\s\S]*?咖啡/,'the two-character food shortcut must not replace trained milk-tea or coffee matching');
assert.match(browser,/shopSearchUrl\(page\.url\(\)\)[\s\S]*?!storeSearchTermMatches\(page\.url\(\), routeItemQuery\)[\s\S]*?searchInsideShop\(page, routeItemQuery\)/,'a stale in-shop keyword must be replaced by the current requested food term');
assert.match(browser,/mealOrder \? await this\.topUpWithMealSnacks/,'meal minimum-order top-up must use same-store snack candidates');
assert.match(browser,/: await this\.topUpWithSavedItems/,'milk-tea minimum-order top-up must use topping candidates');
assert.match(browser,/added one at a time and stop as soon as the minimum is met/,'top-up candidates must be added one at a time and stop at the minimum');

console.log('real delivery role handoff tests passed');
