import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){
 function runtime(){const src=fs.readFileSync(file,'utf8'),rows=[{id:'u1',role:'user',type:'text',content:'你好',_replyHandoffCompleted:{owner:'server',outboxId:'old',at:1}}];const ctx={msgsForAccount:()=>rows,msgToText:m=>m.content||'',replyPendingUserText:()=>rows.at(-1).role==='user'?'你好':'',featureEventNoteActive:n=>n==='feature',initiativeNoteActive:n=>n==='initiative',save:()=>{}};vm.createContext(ctx);vm.runInContext(src.slice(src.indexOf('const _replyHandoffClaims='),src.indexOf('const _roleBackgroundPending=')),ctx);return{ctx,rows,local:()=>ctx.replyHandoffBegin('r',null,1,'main','user',true),remote:()=>ctx.replyHandoffIncoming({id:'r'},{id:'old',triggerKind:'reply_handoff',replyToMessageId:'u1',replyToAccountId:'main'})};}
 test(file+' explicit retry reopens only the deleted completed answer, and keeps old remote blocked',async()=>{const {ctx,rows,local,remote}=runtime(),old=rows[0]._replyHandoffCompleted,l=local();assert.equal(rows[0]._replyHandoffCompleted,old);assert.equal(ctx.replyHandoffClaimIncoming(remote()),'completed');assert.equal(await ctx.replyHandoffClaimLocal(l),true);ctx.replyHandoffPush(l,rows,{role:'assistant',type:'text',content:'新回复'});assert.equal(ctx.replyHandoffMarkLocal(l),true);ctx.replyHandoffRelease(l);assert.equal(rows[0]._replyHandoffCompleted.owner,'local');assert.equal(ctx.replyHandoffClaimIncoming(remote()),'completed');});
 test(file+' failed regeneration remains retryable, including after reload',async()=>{const {ctx,rows,local}=runtime(),l=local();assert.equal(await ctx.replyHandoffClaimLocal(l),true);assert.equal(ctx.replyHandoffMarkLocal(l),false);ctx.replyHandoffRelease(l);const fresh=runtime();fresh.rows.splice(0,1,...JSON.parse(JSON.stringify(rows)));assert.equal(fresh.ctx.replyHandoffClaimIncoming(fresh.remote()),'completed');assert.equal(await fresh.ctx.replyHandoffClaimLocal(fresh.local()),true);});
 test(file+' two regeneration candidates still have only one owner',async()=>{const {ctx,rows,local}=runtime(),a=local(),b=local();assert.equal(await ctx.replyHandoffClaimLocal(a),true);const waiting=ctx.replyHandoffClaimLocal(b);ctx.replyHandoffPush(a,rows,{role:'assistant',type:'text',content:'一次'});ctx.replyHandoffMarkLocal(a);ctx.replyHandoffRelease(a);assert.equal(await waiting,false);});
 test(file+' implicit replay, feature event and continuation do not reopen completion',async()=>{const {ctx,rows}=runtime();const replay=ctx.replyHandoffBegin('r',null,1,'main','user');assert.equal(await ctx.replyHandoffClaimLocal(replay),false);assert.equal(ctx.replyHandoffBegin('r','feature',1,'main','user',true),null);rows.push({role:'assistant',type:'text',content:'还在这里'});assert.equal(ctx.replyHandoffBegin('r','请继续',1,'main','user',true),null);assert.equal(ctx.replyHandoffBegin('r',null,1,'alt','user',true),null);});
 test(file+' completed deleted reply is not dropped from the manual queue and old cloud replies stay blocked while queued',()=>{const {ctx,remote}=runtime();assert.equal(ctx.replyHandoffQueuedSource('r','main'),'');assert.equal(ctx.replyHandoffClaimIncoming(remote()),'completed');});
}
