import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'),source=read('request-size-details.js');
function env(){const c=vm.createContext({Map,Array,JSON,Number,String,esc:s=>String(s).replace(/</g,'&lt;')});c.window=c;vm.runInContext(read('app.js').split('\n').find(x=>x.startsWith('function wechatRequestStats(')),c);vm.runInContext(source,c);return c;}
test('breakdown exactly reconciles raw characters, emoji, escapes and message syntax',()=>{const c=env(),messages=[{role:'system',content:'基础\n# 角色基础人设\n温柔😀\n# 世界设定／世界书\n星空\n# 相关长期记忆\n约定\n# 微信聊天规则\n规则'},{role:'user',content:'上一句'},{role:'assistant',content:'他说"好"。\\'},{role:'user',content:'新的一句'}],before=JSON.stringify(messages),stats=c.wechatRequestStats(messages),d=stats.requestBreakdown;assert.equal(stats.requestChars,before.length);assert.equal(d.groups.reduce((n,x)=>n+x.chars,0),stats.requestChars);assert.equal(JSON.stringify(messages),before);for(const label of ['世界书章节','记忆与摘要章节','人设、身份与关系章节','历史消息·用户','历史消息·角色','末条用户或事件输入','消息格式、字段与转义'])assert(d.groups.some(x=>x.label===label),label);assert.equal(d.messages.length,4);assert.doesNotMatch(JSON.stringify(d),/温柔|星空|约定|上一句|新的一句|他说/);});
test('embedded common-life archive is classified even when it is in one system message',()=>{const c=env(),s=c.wechatRequestStats([{role:'system',content:'角色资料\n\n# 本场已结束对话记录（只供人物连续性参考）\n1. 旧聊天内容'},{role:'user',content:'新现场'}]);assert(s.requestBreakdown.groups.some(x=>x.label==='历史与跨场景承接章节'&&x.chars>10));assert.equal(s.requestBreakdown.groups.reduce((n,x)=>n+x.chars,0),s.requestChars);});
test('multimodal payload and empty messages remain exact without retaining payloads',()=>{const c=env(),messages=[{role:'user',content:[{type:'image_url',image_url:{url:'data:image/png;base64,SECRET_PAYLOAD'}}]},{role:'assistant',content:''}],d=c.wechatRequestStats(messages);assert.equal(d.requestBreakdown.groups.reduce((n,x)=>n+x.chars,0),JSON.stringify(messages).length);assert.doesNotMatch(JSON.stringify(d),/SECRET_PAYLOAD|data:image/);assert.match(c.requestSizeDetailsHtml(d),/图像或结构化内容/);});
test('empty and legacy records render honestly and no fresh model request is needed',()=>{const c=env();assert.match(c.requestSizeDetailsHtml({requestChars:72256}),/旧记录没有分项/);const d=c.wechatRequestStats([]);assert.equal(d.requestChars,2);assert.match(c.requestSizeDetailsHtml(d),/合计/);assert.doesNotMatch(source,/chatAPI\s*\(|fetch\s*\(/);});
test('recorded totals remain fixed after messages change; details have per-message rows',()=>{const c=env(),messages=[{role:'user',content:'短句'}],d=c.wechatRequestStats(messages);messages[0].content='长'.repeat(5000);assert.equal(d.requestBreakdown.total,d.requestChars);assert.match(c.requestSizeDetailsHtml(d),/逐条消息正文占用（1 条）/);assert.equal(d.requestBreakdown.messages[0].chars,2);});
test('both online diagnostic implementations and common-life records expose details',()=>{for(const p of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js'])assert.match(read(p),/requestSizeDetailsHtml\(d\)/);assert.match(read('cohab-model-diagnostics.js'),/requestSizeDetailsHtml\(row\)/);assert.equal(read('native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/request-size-details.js'),source);for(const p of ['小手机.html','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html']){const s=read(p);assert(s.indexOf('request-size-details.js?v=1215')<s.indexOf('cohab-model-diagnostics.js?v=1215'));}assert.match(read('sw.js'),/currentCore\(cache,'requestSize'\)/);});
