import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function runtime(){
 let now=new Date(2026,9,4,9).getTime(),scheduled=[];
 class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const S={me:{active:'main',name:'我',balance:10000,bills:[]},contacts:[{id:'r1',name:'甲',wallet:5000},{id:'r2',name:'乙',wallet:5000}],travel:{hotels:[],ticketOrders:[]},settings:{chat:{base:'fixture',key:'fixture'}},spy:{r1:{wallet:[]}}};
 const ctx={Date:Clock,S,document:{hidden:false,getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:f=>f(),todayStr:()=>new Clock().getFullYear()+'-'+String(new Clock().getMonth()+1).padStart(2,'0')+'-'+String(new Clock().getDate()).padStart(2,'0'),actId:()=>S.me.active,tvInit:()=>S.travel,getC:id=>S.contacts.find(c=>c.id===id),save(){},render(){},toast(){},esc:String,openModal(){},closeModal(){},uid:()=>String(Math.random()),NorthTravelHome:{home(){}},_call:null,cardMessages:[],pushMsg:(id,msg)=>ctx.cardMessages.push({id,msg}),tvHotelRoleMoney:c=>({balance:c.wallet,source:'roleWallet'}),scheduleReply:(id,note,done)=>{scheduled.push({id,note,done});return true;}};
 ctx.window=ctx;vm.createContext(ctx);for(const p of ['travel-hotel-data.js','travel-ticket-data.js','travel-guide.js'])vm.runInContext(fs.readFileSync(p,'utf8'),ctx);
 return {ctx,S,orders:ctx.NorthTravelOrders,setNow:n=>now=n,scheduled};
}
const ticket=()=>({id:'t1',accountId:'main',name:'上海迪士尼乐园',city:'上海',date:'2026-10-04',time:'07:00',endTime:'17:00',status:'booked',payer:'me',count:1,amount:399,people:[{id:'me',name:'我'}],ts:new Date(2026,9,3,10).getTime()});
test('ticket ends at exact end time, no-time tickets survive through their date, and incomplete ranges are rejected',()=>{const {orders}=runtime(),t=ticket(),at=new Date(2026,9,4,17).getTime();assert(orders.validWindow(t));assert(!orders.validWindow({...t,endTime:''}));assert(!orders.validWindow({...t,endTime:'06:00'}));assert(orders.visible(t,'ticket',at-1));assert(!orders.visible(t,'ticket',at));const all={...t,time:'',endTime:''};assert(orders.visible(all,'ticket',new Date(2026,9,4,23,59).getTime()));assert(!orders.visible(all,'ticket',new Date(2026,9,5).getTime()));});
test('hotel checkout-date and exact refund 24h override visit date; no funds move on expiry',()=>{const {orders,S}=runtime(),h={accountId:'main',hotelName:'酒店',status:'upcoming',checkIn:'2026-10-04',nights:2},at=new Date(2026,9,6).getTime();assert(orders.visible(h,'hotel',at-1));assert(!orders.visible(h,'hotel',at));for(const [kind,o] of [['hotel',h],['ticket',ticket()]]){Object.assign(o,{status:kind==='hotel'?'cancelled':'refunded',refundedAt:at});assert(orders.visible(o,kind,at+86400000-1));assert(!orders.visible(o,kind,at+86400000));}assert.equal(S.me.balance,10000);});
test('legacy cancelled reservations migrate once, without guessing an old refund time',()=>{const {orders}=runtime(),h={accountId:'main',status:'cancelled',checkIn:'2020-01-01'};assert(orders.visible(h,'hotel',1000));assert.equal(h.refundedAt,1000);assert(orders.visible(h,'hotel',86400999));assert(!orders.visible(h,'hotel',86401000));});
test('role pays own bank, sends independent card, repeated command cannot charge twice, refund goes only to original payer',()=>{const {ctx,S,orders}=runtime(),c=S.contacts[0];assert(orders.roleBook(c,'上海迪士尼乐园','2026-10-05','07:00','17:00','我们一起'));const o=S.travel.ticketOrders[0];assert.equal(o.count,2);assert.equal(o.amount,798);assert.equal(c.wallet,4202);assert.equal(S.me.balance,10000);assert.equal(ctx.cardMessages[0].msg.type,'attractionTicket');assert.match(orders.card(o),/ctg-chat-ticket/);assert(orders.roleBook(c,'上海迪士尼乐园','2026-10-05','07:00','17:00','我们一起'));assert.equal(c.wallet,4202);ctx.NorthTravelGuide.refund(o.id);ctx.NorthTravelGuide.refund(o.id);assert.equal(c.wallet,4202);assert.equal(S.me.balance,10000);assert.equal(o.status,'booked');assert.equal(o.refundedAt,undefined);});
test('normal model booking syntax is consumed and invalid commands cannot leave a false success claim',()=>{const {orders,S}=runtime(),c=S.contacts[0];let handled=false;assert.equal(orders.consume('买好了\n[订门票|上海迪士尼乐园|2026-10-05|07:00|17:00|我们一起]',c,ok=>handled=ok),'买好了\n');assert(handled);assert.equal(S.travel.ticketOrders.length,1);assert.equal(orders.consume('买好了\n[订门票|未知景点|2026-10-05|07:00|17:00|我们一起]',c), '');});
test('role rejection paths cannot manufacture orders or touch user/family funds; account isolation survives refunds',()=>{const {ctx,S,orders}=runtime(),c=S.contacts[0];c.wallet=1;for(const [name,date,start,end,guest] of [['未知景点','2026-10-05','07:00','17:00','我们一起'],['上海迪士尼乐园','2026-10-03','07:00','17:00','我们一起'],['上海迪士尼乐园','2026-10-05','17:00','07:00','我们一起'],['上海迪士尼乐园','2026-10-05','07:00','17:00','我们一起']])assert(!orders.roleBook(c,name,date,start,end,guest));assert.equal(S.travel.ticketOrders.length,0);assert.equal(S.me.balance,10000);c.wallet=5000;orders.roleBook(c,'上海迪士尼乐园','2026-10-05','07:00','17:00','给你');const o=S.travel.ticketOrders[0];S.me.active='other';assert.equal(orders.rows().length,0);ctx.NorthTravelGuide.refund(o.id);assert.equal(c.wallet,4601);});
test('phone facts distinguish solo and another role, ordinary role knowledge is scoped to recipients',()=>{const {orders,S}=runtime(),a=ticket(),b={...ticket(),id:'t2',people:[{id:'me',name:'我'},{id:'role:r2',name:'乙'}],count:2,knownRoleIds:['r2']};S.travel.ticketOrders.push(a,b);assert.match(orders.inspection(),/用户独自出游/);assert.match(orders.inspection(),/我、乙/);assert(!orders.rolePrompt(S.contacts[0]).includes('出游人员：我、乙'));assert(orders.rolePrompt(S.contacts[1]).includes('出游人员：我、乙'));S.me.active='other';assert(!orders.inspection().includes('迪士尼'));});
test('opening on ticket day queues natural role reminder once, delivery marker persists, failure retries without phantom success',()=>{const {orders,S,ctx,scheduled}=runtime(),o={...ticket(),reminderRoleId:'r1',knownRoleIds:['r1']};S.travel.ticketOrders.push(o);orders.wake();orders.wake();assert.equal(scheduled.length,1);assert.match(scheduled[0].note,/按自己的性格/);assert(!o.remindedAt);scheduled[0].done(false);orders.wake();assert.equal(scheduled.length,1);const message={type:'text',content:'今天去迪士尼，准备好了吗？'};orders.delivered(scheduled[0].note,message,'r1');assert.equal(message._ticketReminderOrderId,o.id);assert.equal(o.remindedAt,ctx.Date.now());orders.wake();assert.equal(scheduled.length,1);o.status='refunded';assert(!orders.noteValid(scheduled[0].note));});
test('expired, future, blocked and unconfigured reminders make no model request',()=>{for(const mode of ['expired','future','blocked','unconfigured']){const {orders,S,scheduled,setNow}=runtime(),o={...ticket(),reminderRoleId:'r1'};S.travel.ticketOrders.push(o);if(mode==='expired')setNow(new Date(2026,9,4,17).getTime());if(mode==='future')o.date='2026-10-05';if(mode==='blocked')S.contacts[0].blocked=true;if(mode==='unconfigured')S.settings.chat={};orders.wake();assert.equal(scheduled.length,0,mode);}});
