import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(){let serial=0,active='main',now=Date.now();class TestDate extends Date{static now(){return now;}}const messages={},reminders=[];const S={me:{name:'我',balance:10000},contacts:[{id:'r',name:'同行角色',wallet:10000},{id:'other',name:'另一角色',wallet:10000}],travel:{},spy:{r:{balance:10000,wallet:[]}}};const q={accountId:'main',artist:'王俊凯',city:'上海',date:'2099-10-05',end:'2099-10-05',time:'19:30',area:'field',price:1280,budget:0,count:2,people:[{id:'me',name:'我'},{id:'role:r',name:'同行角色'}]};const ctx=vm.createContext({Date:TestDate,S,actId:()=>active,todayStr:()=> '2026-10-04',uid:()=> 'concert-'+(++serial),tvInit:()=>S.travel,save(){},toast(){},esc:String,getC:k=>S.contacts.find(c=>c.id===k),tvHotelRoleMoney:c=>c.wallet!=null?({balance:c.wallet,source:'roleWallet'}):({balance:S.spy[c.id].balance,source:'roleBank'}),addBill:(t,n)=>S.me.balance+=t==='in'?n:-n,cur:()=>({p:'travel'}),render(){},msgs:k=>messages[k]||(messages[k]=[]),scheduleReply:(k,n,done,aid)=>reminders.push([k,n,done,aid]),setInterval(){},document:{querySelector:()=>null},NorthTravelConcert:{state:()=>({query:q}),active:()=>false}});vm.runInContext(fs.readFileSync(new URL('../travel-hotel-data.js',import.meta.url),'utf8'),ctx);vm.runInContext(fs.readFileSync(new URL('../travel-concert-booking.js',import.meta.url),'utf8'),ctx);return {api:ctx.NorthConcertBooking,S,q,messages,reminders,switchAccount:v=>active=v,setNow:v=>now=v,ctx};}
test('concert quotes honor artist, city, date/time, seating, budget and all ticket holders',()=>{const {api,q}=fixture();const a=api.shows(q);assert.equal(a.length,1);assert.equal(a[0].unitCents*q.count,256000);assert.equal(a[0].artist,'王俊凯');assert.equal(a[0].time,'19:30');q.budget=1000;assert.equal(api.shows(q).length,0);q.price=0;q.area='stand';assert.equal(api.shows(q).length,3);});
test('invalid dates, participants, tiers and account cannot debit or create orders',()=>{const {api,q,S,switchAccount}=fixture();for(const patch of [{date:'2099-02-30',end:'2099-02-30'},{count:1},{price:1},{time:'99:30'},{people:[{id:'role:missing'}]}]){const bad={...q,...patch};assert(api.validate(bad));assert.equal(api.bookQuote(bad,'invalid'),false);}switchAccount('other');assert(api.validate(q));assert.equal(S.me.balance,10000);assert.equal((S.travel.concertOrders||[]).length,0);});
test('booking and original wallet refund are idempotent with frozen participant snapshots',()=>{const {api,q,S}=fixture(),f=api.shows(q)[0];assert(api.bookQuote(q,f.id));assert.equal(S.me.balance,7440);assert(api.bookQuote(q,f.id));assert.equal(S.me.balance,7440);const o=api.rows()[0];q.people[1].name='改名';assert.equal(o.people[1].name,'同行角色');assert(api.refund(o.id));assert.equal(S.me.balance,10000);assert.equal(api.refund(o.id),false);assert.equal(S.travel.concertOrders.length,1);});
test('role books exclusive music card using its own funds and original bank source',()=>{const {api,S,messages}=fixture();assert(api.roleDirect(S.contacts[0],'王俊凯','上海','2099-10-05','19:30','内场','我们一起'));const o=api.rows()[0];assert.equal(o.payer,'ta');assert.equal(S.me.balance,10000);assert.equal(S.contacts[0].wallet,8040);assert.equal(messages.r[0].role,'assistant');assert.equal(messages.r[0].trip.concertV2,true);assert(api.summary(o).includes('同行角色'));assert(api.refund(o.id));assert.equal(S.contacts[0].wallet,10000);});
test('insufficient role funds suppress false success prose and create no ticket',()=>{const {api,S}=fixture();S.contacts[0].wallet=0;let ok;const text=api.consume('已经买好啦[订演唱会|王俊凯|上海|2099-10-05|19:30|内场|我们一起]',S.contacts[0],v=>ok=v);assert.equal(ok,false);assert.equal(text,'');assert.equal(api.rows().length,0);assert.equal(S.me.balance,10000);});
test('ticket hides exactly at performance end or 24h after refund; does not leak accounts or private solo orders',()=>{const {api,q,S,switchAccount}=fixture();assert(api.bookQuote(q,api.shows(q)[0].id));const o=api.rows()[0];assert(api.visible(o,o.endAt-1));assert.equal(api.visible(o,o.endAt),false);o.status='cancelled';o.refundedAt=1000;assert(api.visible(o,86400999));assert.equal(api.visible(o,86401000),false);switchAccount('other');assert.equal(api.current(o.id),undefined);assert.equal(api.rows().length,0);switchAccount('main');o.status='upcoming';assert(!api.rolePrompt(S.contacts[1]).includes('王俊凯'));});
test('role action parser executes valid six-field command and strips its control text',()=>{const {api,S}=fixture();let outcome;const result=api.consume('给你留好票了。[订演唱会|王俊凯|上海|2099-10-05|19:30|看台|给你]',S.contacts[0],ok=>outcome=ok);assert.equal(outcome,true);assert.equal(result,'给你留好票了。');assert.equal(S.contacts[0].wallet,9620);assert.equal(S.me.balance,10000);});
test('role bank-source refund returns to that bank without creating a role wallet',()=>{const {api,S}=fixture();delete S.contacts[0].wallet;assert(api.roleDirect(S.contacts[0],'王俊凯','上海','2099-10-05','19:30','看台','给你'));const o=api.rows()[0];assert.equal(o.fundingSource,'roleBank');assert.equal(S.spy.r.balance,9620);assert(api.refund(o.id));assert.equal(S.spy.r.balance,10000);assert.equal(S.contacts[0].wallet,undefined);assert.equal(S.me.balance,10000);});

test('solo and arbitrary companion purchases are inspectable without leaking unknown-role knowledge',()=>{
 const {api,q,S}=fixture();q.count=1;q.people=[{id:'me',name:'我'}];assert(api.bookQuote(q,api.shows(q)[0].id));assert.match(api.inspection(),/用户独自观演/);assert(!api.rolePrompt(S.contacts[0]).includes('王俊凯'));
 q.count=2;q.people.push({id:'role:other',name:'另一角色'});assert(api.bookQuote(q,api.shows(q)[0].id));assert.match(api.inspection(),/另一角色/);assert(api.rolePrompt(S.contacts[1]).includes('另一角色'));assert(!api.rolePrompt(S.contacts[0]).includes('王俊凯'));
});
test('reminders wait until exact opening, acknowledge visible delivery and persist without duplicate on reopen',()=>{
 const {api,q,reminders,setNow,S}=fixture();assert(api.bookQuote(q,api.shows(q)[0].id));const o=api.rows()[0];o._reminded=true; // migrate the old premature completion flag
 setNow(o.startAt-1);api.checkDue();assert.equal(reminders.length,0);setNow(o.startAt);api.checkDue();assert.equal(reminders.length,1);assert.equal(reminders[0][0],'r');assert.equal(reminders[0][3],'main');assert(!o.concertRemindedAt);assert(api.noteValid(reminders[0][1]));
 api.delivered(reminders[0][1],{type:'ticket'},'r');assert(!o.concertRemindedAt);api.delivered(reminders[0][1],{type:'text',content:'演唱会开场了，我们一起听。'},'r');assert.equal(o.concertRemindedAt.r,o.startAt);reminders[0][2](true);setNow(o.startAt+180000);api.checkDue();assert.equal(reminders.length,1);assert(S.travel.concertOrders[0].concertRemindedAt.r);
});
test('failed reminder retries, does not mark success, and expiry invalidates in-flight output',()=>{
 const {api,q,reminders,setNow}=fixture();assert(api.bookQuote(q,api.shows(q)[0].id));const o=api.rows()[0];setNow(o.startAt);api.checkDue();reminders[0][2](false);setNow(o.startAt+119999);api.checkDue();assert.equal(reminders.length,1);setNow(o.startAt+120000);api.checkDue();assert.equal(reminders.length,2);assert(!o.concertRemindedAt);setNow(o.endAt);assert.equal(api.noteValid(reminders[1][1]),false);api.delivered(reminders[1][1],{type:'text',content:'晚到的提醒'},'r');assert(!o.concertRemindedAt);api.checkDue();assert.equal(api.rows().length,0);assert.equal(reminders.length,2);
});
test('refund, blocked roles and account switch invalidate reminders; solo purchase never broadcasts',()=>{
 const {api,q,S,reminders,setNow,switchAccount}=fixture();assert(api.bookQuote(q,api.shows(q)[0].id));const o=api.rows()[0],note='[演唱会开场提醒|'+o.id+'|r]';setNow(o.startAt);assert(api.noteValid(note));S.contacts[0].blocked=true;assert.equal(api.noteValid(note),false);api.checkDue();assert.equal(reminders.length,0);S.contacts[0].blocked=false;switchAccount('other');assert.equal(api.noteValid(note),false);switchAccount('main');o.status='cancelled';o.refundedAt=o.startAt;assert.equal(api.noteValid(note),false);api.checkDue();assert.equal(reminders.length,0);
 const solo=fixture();solo.q.count=1;solo.q.people=[{id:'me',name:'我'}];assert(solo.api.bookQuote(solo.q,solo.api.shows(solo.q)[0].id));solo.setNow(solo.api.rows()[0].startAt);solo.api.checkDue();assert.equal(solo.reminders.length,0);
});
test('reminder cannot replace an ordinary reply already queued for that role',()=>{
 const {api,q,ctx,setNow,reminders}=fixture();assert(api.bookQuote(q,api.shows(q)[0].id));setNow(api.rows()[0].startAt);ctx.replyStateKey=(k,aid)=>aid+':'+k;ctx._replyTimers={'main:r':123};api.checkDue();assert.equal(reminders.length,0);delete ctx._replyTimers['main:r'];api.checkDue();assert.equal(reminders.length,1);
});

test("large role wallet concert booking and refund preserve exact balance",()=>{const {api,q,S}=fixture();S.contacts[0].wallet='999999999999999999999999.00';assert(api.bookQuote(q,api.shows(q)[0].id,S.contacts[0]));assert.notEqual(S.contacts[0].wallet,'999999999999999999999999.00');assert.equal(S.me.balance,10000);assert(api.refund(api.rows()[0].id));assert.equal(S.contacts[0].wallet,'999999999999999999999999.00');});
