import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(){let now=1800000000000,aid='main',serial=0;class Clock extends Date{static now(){return now;}}const S={me:{name:'我',balance:1000},contacts:[{id:'r',name:'小克',wallet:1000},{id:'b',name:'朋友',wallet:1000}],travel:{},spy:{r:{balance:1000,wallet:[]}}},messages={},reminders=[];const ctx=vm.createContext({S,Date:Clock,actId:()=>aid,tvInit:()=>S.travel,uid:()=> 'taxi-'+ ++serial,getC:k=>S.contacts.find(c=>c.id===k),esc:String,save(){},toast(){},cur:()=>({p:'travel'}),render(){},msgs:k=>messages[k]||(messages[k]=[]),addBill:(type,n)=>S.me.balance+=type==='in'?n:-n,tvHotelRoleMoney:c=>c.wallet!=null?{source:'roleWallet',balance:c.wallet}:{source:'roleBank',balance:S.spy[c.id].balance},scheduleReply:(k,n,done)=>reminders.push([k,n,done]),setInterval(){},document:{querySelector:()=>null,querySelectorAll:()=>[]},NorthTravelHome:{home(){},icon:()=>'<svg></svg>'}});vm.runInContext(fs.readFileSync(new URL('../travel-hotel-data.js',import.meta.url),'utf8'),ctx);vm.runInContext(fs.readFileSync(new URL('../travel-taxi.js',import.meta.url),'utf8'),ctx);const api=ctx.NorthTravelTaxi,q={accountId:'main',from:'上海家门口',to:'上海虹桥站',coords:null,locationAt:now,mode:'together',roleIds:['r'],helperId:'',distance:8,ts:now};api.state().query=q;return {api,q,S,messages,reminders,ctx,setNow:v=>now=v,switchAccount:v=>aid=v};}
test('four car prices increase by category and one car is not charged per companion',()=>{const {api,q,S}=fixture();const a=api.quotes(q);assert.equal(a.length,4);assert(a.find(x=>x.id==='luxury').cents>a.find(x=>x.id==='special').cents);assert.equal(a.find(x=>x.id==='express').cents,2760);assert(api.book(q,'express'));assert.equal(S.me.balance,972.4);assert.equal(api.rows()[0].people.length,2);q.roleIds.push('b');assert.equal(api.quotes(q)[0].cents,2760);});
test('invalid route, missing role, stale location and quote cannot charge',()=>{const {api,q,S,setNow}=fixture();for(const p of [{from:''},{to:q.from},{roleIds:['missing']},{mode:'give',roleIds:[]},{distance:0},{coords:{latitude:91,longitude:1}},{coords:{latitude:1,longitude:1},locationAt:0}]){assert.equal(api.book({...q,...p},'express'),false);}setNow(q.ts+600001);assert.equal(api.book(q,'express'),false);assert.equal(S.me.balance,1000);assert.equal(api.rows().length,0);});
test('duplicate booking, refund replay and original user funds are protected',()=>{const {api,q,S}=fixture();assert(api.book(q,'express'));assert(api.book(q,'express'));assert.equal(api.rows().length,1);const o=api.rows()[0];assert(api.cancel(o.id));assert.equal(S.me.balance,1000);assert.equal(api.cancel(o.id),false);assert(api.visible(o,o.closedAt+86400000-1));assert.equal(api.visible(o,o.closedAt+86400000),false);});
test('driver arrival waits for user boarding, board event is acknowledged and trip expires after completion plus24h',()=>{const {api,q,setNow,reminders}=fixture();assert(api.book(q,'express'));const o=api.rows()[0];setNow(o.arriveAt-1);api.tick();assert.equal(o.status,'waiting');assert.equal(api.board(o.id),false);setNow(o.arriveAt);api.tick();assert.equal(o.status,'arrived');assert.equal(reminders.length,1);assert(!o.reminded);const note=reminders[0][1];api.delivered(note,{type:'text',content:'车到了，上车吧。'},'r');reminders[0][2](true);api.tick();assert.equal(reminders.length,1);assert(api.board(o.id));assert.equal(o.status,'riding');assert.equal(api.noteValid(note),false);assert.equal(reminders.length,2);assert.equal(api.cancel(o.id),false);setNow(o.finishAt);api.tick();assert.equal(o.status,'completed');assert(api.visible(o,o.closedAt+86400000-1));assert.equal(api.visible(o,o.closedAt+86400000),false);});
test('role uses its own wallet or bank and receives dedicated card through command execution',()=>{const {api,q,S,messages,setNow}=fixture();let ok;assert.equal(api.consume('叫好了[叫车|上海虹桥站|专车|我们一起]',S.contacts[0],v=>ok=v),'叫好了');assert(ok);const o=api.rows()[0];assert.equal(o.payer,'ta');assert.equal(S.me.balance,1000);assert.equal(S.contacts[0].wallet,946.6);assert(messages.r.some(m=>m.role==='assistant'&&m.trip.taxiV2));assert.equal(api.cancel(o.id),false);setNow(o.arriveAt+1800000);api.tick();assert.equal(S.contacts[0].wallet,1000);q.ts=o.arriveAt+1800000;delete S.contacts[0].wallet;assert(api.roleQuery(S.contacts[0]));assert.equal(S.spy.r.balance,972.4);const bankOrder=api.rows().find(o=>o.status==='waiting');assert.equal(api.cancel(bankOrder.id),false);setNow(bankOrder.arriveAt+1800000);api.tick();assert.equal(S.spy.r.balance,1000);assert.equal(S.contacts[0].wallet,undefined);});
test('solo shared helper can arrange ride, while a third role cannot read or act on shared location',()=>{const {api,q,S}=fixture();q.mode='solo';q.roleIds=[];q.helperId='r';assert(api.rolePrompt(S.contacts[0]).includes('上海家门口'));assert(!api.rolePrompt(S.contacts[1]).includes('上海家门口'));assert.equal(api.roleQuery(S.contacts[1]),false);assert(api.roleQuery(S.contacts[0],q.to,'express','给你'));assert.match(api.summary(api.rows()[0]),/用户独自出行/);assert.match(api.inspection(),/用户独自出行/);});
test('give role ride freezes actual passenger, source account and pickup; switching mode clears user GPS',()=>{const {api,q,S}=fixture();q.mode='give';q.from='对方家门口';assert(api.book(q,'taxi'));const o=api.rows()[0];q.roleIds=[];assert.equal(o.people[0].name,'小克');assert.equal(o.from,'对方家门口');assert.match(api.summary(o),/给角色叫车/);api.state().from='我的定位';api.state().coords={latitude:1,longitude:1};api.mode('give');assert.equal(api.state().from,'');assert.equal(api.state().coords,null);assert.equal(S.me.balance,966);});
test('cancelled or wrong-account reminders cannot deliver; failure retries and queued chat is not replaced',()=>{const {api,q,setNow,reminders,ctx,switchAccount}=fixture();assert(api.book(q,'express'));const o=api.rows()[0];setNow(o.arriveAt);ctx.replyStateKey=(k,a)=>a+':'+k;ctx._replyTimers={'main:r':1};api.tick();assert.equal(reminders.length,0);delete ctx._replyTimers['main:r'];api.tick();const n=reminders[0][1];reminders[0][2](false);api.tick();assert.equal(reminders.length,1);setNow(o.arriveAt+120000);api.tick();assert.equal(reminders.length,2);switchAccount('other');assert.equal(api.noteValid(n),false);switchAccount('main');assert(api.cancel(o.id));assert.equal(api.noteValid(n),false);api.delivered(n,{type:'text',content:'晚到的提醒'},'r');assert(!o.reminded);});
test('insufficient role funds suppress success text and leave both wallets unchanged',()=>{const {api,S}=fixture();S.contacts[0].wallet=0;let ok;assert.equal(api.consume('叫好了[叫车查询]',S.contacts[0],v=>ok=v),'');assert.equal(ok,false);assert.equal(api.rows().length,0);assert.equal(S.me.balance,1000);});
test('unconfirmed boarding expires after thirty minutes with one original-source refund and no stale arrival reminder',()=>{for(const rolePaid of [false,true]){const {api,q,S,setNow,reminders}=fixture();assert(rolePaid?api.roleQuery(S.contacts[0]):api.book(q,'express'));const o=api.rows()[0];setNow(o.arriveAt+1800000-1);api.tick();assert.equal(o.status,'arrived');const note=reminders[0][1];setNow(o.arriveAt+1800000);api.tick();assert.equal(o.status,'cancelled');assert.equal(o.closedAt,o.arriveAt+1800000);assert.equal(S.me.balance,1000);assert.equal(S.contacts[0].wallet,1000);assert.equal(api.noteValid(note),false);api.tick();assert.equal(S.me.balance,1000);assert.equal(S.contacts[0].wallet,1000);assert.equal(api.board(o.id),false);setNow(o.closedAt+86400000);assert.equal(api.visible(o),false);}});

test('role passenger reports arrival then automatically boards; user trips still require explicit confirmation',()=>{const {api,q,setNow,reminders}=fixture();q.mode='give';q.from='小克家门口';assert(api.book(q,'express'));const o=api.rows()[0];setNow(o.arriveAt);api.tick();assert.match(reminders[0][1],/主动向用户报备车到了/);setNow(o.arriveAt+60000);api.tick();assert.equal(o.status,'arrived');api.delivered(reminders[0][1],{type:'text',content:'车到了，我准备上车。'},'r');reminders[0][2](true);assert.equal(o.autoBoardAt,o.arriveAt+90000);setNow(o.autoBoardAt-1);api.tick();assert.equal(o.status,'arrived');setNow(o.autoBoardAt);api.tick();assert.equal(o.status,'riding');assert.match(reminders.at(-1)[1],/主动向用户报备你已上车/);assert.equal(api.board(o.id),false);const {api:b,q:bq,setNow:clock}=fixture();assert(b.book(bq,'express'));clock(b.rows()[0].arriveAt+90000);b.tick();assert.equal(b.rows()[0].status,'arrived');});
test('destination choices use a white custom picker and cancellation is visible only in eligible orders',()=>{const {api,q}=fixture();assert(!api.render().includes('<datalist'));assert(api.render().includes('选择目的地'));assert(api.book(q,'express'));assert(!api.card(api.rows()[0]).includes('取消打车'));api.orders();assert(api.render().includes('取消打车'));});

test('manual cancellation only permits user-paid rides containing the user, and only the orders page exposes it',()=>{const {api,q,S}=fixture();assert(api.book(q,'express'));const own=api.rows()[0];assert(!api.card(own).includes('取消打车'));api.detail(own.id);assert(!api.render().includes('取消打车'));api.orders();assert(api.render().includes('取消打车'));assert(api.cancel(own.id));assert.equal(S.me.balance,1000);const {api:b,q:bq,S:bs}=fixture();bq.mode='give';assert(b.book(bq,'express'));const give=b.rows()[0],before=bs.me.balance;assert.equal(b.cancel(give.id),false);assert.equal(bs.me.balance,before);b.orders();assert(!b.render().includes('取消打车'));const {api:c,S:cs}=fixture();assert(c.roleQuery(cs.contacts[0]));const paid=c.rows()[0],balance=cs.contacts[0].wallet;assert.equal(c.cancel(paid.id),false);assert.equal(cs.contacts[0].wallet,balance);c.orders();assert(!c.render().includes('取消打车'));});

test('inspection preserves passenger snapshots and current-account status while private contextual sharing stays restricted',()=>{const {api,q,S,switchAccount}=fixture();q.mode='solo';q.roleIds=[];assert(api.book(q,'express'));const o=api.rows()[0];assert.match(api.inspection(),/用户独自出行/);assert(!api.rolePrompt(S.contacts[0]).includes('上海家门口'));assert(api.cancel(o.id));assert.match(api.inspection(),/已取消并退款/);switchAccount('other');assert.equal(api.rows().length,0);assert.equal(api.cancel(o.id),false);assert(!api.inspection().includes('上海家门口'));switchAccount('main');q.mode='together';q.roleIds=['b'];assert(api.book(q,'express'));const both=api.rows().find(x=>x.status==='waiting');S.contacts[1].name='后来改名';assert.match(api.summary(both),/我、朋友/);assert.match(api.rolePrompt(S.contacts[1]),/用户与角色同行/);assert(!api.rolePrompt(S.contacts[0]).includes('用户与角色同行'));});

test("large role wallet books and timeout refunds without touching user funds",()=>{const {api,S,setNow}=fixture();S.contacts[0].wallet='999999999999999999999999.00';assert(api.roleQuery(S.contacts[0]));const o=api.rows()[0];assert.notEqual(S.contacts[0].wallet,'999999999999999999999999.00');assert.equal(S.me.balance,1000);setNow(o.arriveAt+1800000);api.tick();assert.equal(S.contacts[0].wallet,'999999999999999999999999.00');});
