import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(){let serial=0;const S={me:{balance:5000},contacts:[{id:'r',name:'角色',wallet:5000,family:{bound:true,quota:1000,used:0,month:'2026-10'}}],travel:{trips:[]},spy:{}};let active='main';const messages={},ctx=vm.createContext({S,actId:()=>active,curMonth:()=> '2026-10',todayStr:()=> '2026-10-04',tvInit:()=>S.travel,uid:()=> 'p-'+(++serial),getC:id=>S.contacts.find(c=>c.id===id),msgs:id=>messages[id]||(messages[id]=[]),pushMsg:(id,m)=>(messages[id]||(messages[id]=[])).push(m),scheduleReply(){},save(){},toast(){},openModal(){},closeModal(){},esc:x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),addBill:(kind,n)=>S.me.balance+=kind==='out'?-n:n,tvHotelRoleMoney:c=>c.wallet!=null?{source:'roleWallet',balance:c.wallet}:{source:'roleBank',balance:S.spy[c.id]?.balance}});vm.runInContext(fs.readFileSync('travel-hotel-data.js','utf8')+fs.readFileSync('travel-payment.js','utf8'),ctx);ctx.NorthFlightBooking={rows:()=>S.travel.trips,bookQuote(q,key,c,p){const o={id:'o-'+(++serial),accountId:active,price:100,status:'upcoming'};if(!ctx.NorthTravelPayment.charge(p,10000,'模拟机票',o))return false;S.travel.trips.push(o);return true;}};const api=ctx.NorthTravelPayment;return{api,S,ctx,messages,c:S.contacts[0],switchAccount:v=>active=v,open:()=>api.open({kind:'flight',quote:{},item:'flight',name:'测试模拟机票',amount:100})};}
test('payment choice and role request do not charge until role approves; retry cannot duplicate order',()=>{const f=fixture();f.open();assert.equal(f.S.me.balance,5000);assert(f.api.pay('role','r'));assert.equal(f.c.wallet,5000);assert.equal(f.S.travel.trips.length,0);assert(f.api.accept(f.c));assert.equal(f.c.wallet,4900);assert.equal(f.S.me.balance,5000);assert(f.api.accept(f.c));assert.equal(f.c.wallet,4900);assert.equal(f.S.travel.trips.length,1);assert.equal(f.ctx.NorthHotelData.roleOrder(f.S.travel.trips[0]),false);});
test('role refusal and insufficient balance never produce a paid card or order',()=>{for(const refuse of [true,false]){const f=fixture();f.open();f.api.pay('role','r');if(!refuse)f.c.wallet=1;f.api.accept(f.c,refuse);assert.equal(f.S.travel.trips.length,0);assert.equal(f.S.me.balance,5000);assert(!f.messages.r.some(m=>m.type==='paid'));}});
test('family freeze and monthly quota reject payment without touching any wallet',()=>{for(const frozen of [true,false]){const f=fixture();f.open();if(frozen)f.S.couple={cardFrozen:true};else f.c.family.quota=99;assert.equal(f.api.pay('family','r'),false);assert.equal(f.c.family.used,0);assert.equal(f.c.wallet,5000);assert.equal(f.S.me.balance,5000);assert.equal(f.S.travel.trips.length,0);}});
test('previous-month quota resets on actual family payment; refund only restores its original month',()=>{const f=fixture();f.c.family.month='2026-09';f.c.family.used=999;f.open();assert(f.api.pay('family','r'));const o=f.S.travel.trips[0];assert.equal(f.c.family.used,100);assert.equal(f.c.family.month,'2026-10');f.c.family.month='2026-11';f.c.family.used=200;assert(f.api.refund(o));assert.equal(f.c.family.used,200);assert.equal(f.api.refund(o),false);assert.equal(f.S.me.balance,5000);});
test('role bank refund uses original bank and never switches to user wallet',()=>{const f=fixture();delete f.c.wallet;f.S.spy.r={balance:5000,wallet:[]};f.open();f.api.pay('role','r');assert(f.api.accept(f.c));const o=f.S.travel.trips[0];assert.equal(f.S.spy.r.balance,4900);f.c.wallet=999;assert(f.api.refund(o));assert.equal(f.S.spy.r.balance,5000);assert.equal(f.c.wallet,999);assert.equal(f.S.me.balance,5000);assert.equal(f.api.refund(o),false);});
test('pending role payment survives serialization; account switch cannot approve or reveal it',()=>{const f=fixture();f.open();f.api.pay('role','r');f.S.travel.paymentRequests=JSON.parse(JSON.stringify(f.S.travel.paymentRequests));const id=f.S.travel.paymentRequests[0].id;f.switchAccount('alt');assert.equal(f.api.pending('r'),null);assert.equal(f.api.accept(f.c),false);assert(!f.api.card({travelPayment:id}).includes('测试模拟机票'));assert.equal(f.c.wallet,5000);f.switchAccount('main');assert(f.api.accept(f.c));});
test('changed price and removed original funding source fail without charging or redirecting refunds',()=>{const f=fixture();f.open();f.api.pay('role','r');f.S.travel.paymentRequests[0].amount=101;assert.equal(f.api.accept(f.c),false);assert.equal(f.c.wallet,5000);assert.equal(f.S.travel.trips.length,0);const g=fixture();g.open();g.api.pay('role','r');g.api.accept(g.c);delete g.c.wallet;assert.equal(g.api.refund(g.S.travel.trips[0]),false);assert.equal(g.S.me.balance,5000);});

test('payment cards and order payer labels prefer the current remark over original role name',()=>{for(const mode of ['role','family']){const f=fixture();f.c.name='原名';f.c.remark='先生';f.open();f.api.pay(mode,'r');if(mode==='role'){assert(f.api.card(f.messages.r[0]).includes('向先生请求代付'));f.api.accept(f.c);}const m=f.messages.r.at(-1),o=f.S.travel.trips[0];assert(f.api.card(m).includes(mode==='role'?'先生代付成功':'先生的亲属卡已付款'));assert(!f.api.card(m).includes('原名'));assert.equal(f.api.label(o),mode==='role'?'先生代付':'先生的亲属卡');f.c.remark='哥哥';assert(f.api.card(m).includes('哥哥'));f.c.remark='  ';assert(f.api.card(m).includes('原名'));f.S.contacts=[];assert(f.api.card(m).includes('原付款方'));assert(!f.api.card(m).includes('我的钱包'));}});
test('dynamic payer titles escape markup and show the remark on refusal',()=>{const f=fixture();f.c.remark='<b>助理</b>&';f.open();f.api.pay('role','r');f.api.accept(f.c,true);const card=f.api.card(f.messages.r[0]);assert(card.includes('&lt;b&gt;助理&lt;/b&gt;&amp;未同意代付'));assert(!card.includes('<b>助理</b>'));});

test('both real reply handlers keep completed travel requests out of older shopping payments',()=>{for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){const source=fs.readFileSync(file,'utf8');for(const tag of ['代付成功','拒绝代付']){const f=fixture();f.open();f.api.pay('role','r');f.api.accept(f.c);const line=source.split('\n').find(x=>x.includes('mm=line.match(')&&x.includes(tag));const guard=line.slice(line.indexOf("if(typeof NorthTravelPayment"),line.indexOf('const pend=markPay'));const run=new Function('NorthTravelPayment','id','c','refreshChatMessages',"let _replyAuditPartial=false,legacy=0;for(let i=0;i<1;i++){"+guard+"legacy++}return legacy");assert.equal(run(f.api,'r',f.c,()=>{}),0,file+' '+tag);}}});
