import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('sw.js','utf8');
function fixture(){const saved=new Map(),ctx={Request,Response,Headers,Blob,URL,Promise,fetch:async()=>new Response(new Uint8Array(1024),{headers:{'content-type':'image/jpeg'}}),caches:{open:async()=>cache}};
 const cache={match:async k=>saved.get(k.url),put:async(k,r)=>saved.set(k.url,r),keys:async()=>[...saved.keys()].map(u=>new Request(u)),delete:async k=>saved.delete(k.url)};
 vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('// Travel thumbnails'),source.indexOf("self.addEventListener('fetch'")),ctx);return {ctx,cache,saved};}
test('travel thumbnail cache remains bounded after many distinct destinations',async()=>{const {ctx,cache,saved}=fixture();for(let i=0;i<70;i++)await ctx.travelImageSave(cache,new Request('https://fixture.invalid/assets/travel-home/'+i+'.jpg'),new Response(new Uint8Array(1000),{headers:{'content-type':'image/jpeg'}}));assert.equal(saved.size,24);assert(!saved.has('https://fixture.invalid/assets/travel-home/0.jpg'));assert(saved.has('https://fixture.invalid/assets/travel-home/69.jpg'));});
test('large or non-image responses never enter thumbnail cache, including unknown content length',async()=>{const {ctx,cache,saved}=fixture(),key=new Request('https://fixture.invalid/assets/travel-home/a.jpg');for(const response of [new Response(new Uint8Array(600000),{headers:{'content-type':'image/jpeg'}}),new Response('x',{headers:{'content-type':'image/jpeg','content-length':'600000'}}),new Response('<html>error</html>',{headers:{'content-type':'text/html'}}),new Response('not found',{status:404})])await ctx.travelImageSave(cache,key,response);assert.equal(saved.size,0);});
test('storage denial leaves the network image usable and does not propagate save errors',async()=>{const {ctx,cache}=fixture();ctx.caches.open=async()=>{throw Error('quota')};const result=await ctx.travelImageResponse(new Request('https://fixture.invalid/assets/travel-home/a.jpg'),{waitUntil(){throw Error('should not cache')}});assert.equal(result.status,200);assert.equal((await result.arrayBuffer()).byteLength,1024);ctx.caches.open=async()=>cache;cache.put=async()=>{throw Error('quota')};let wait;const result2=await ctx.travelImageResponse(new Request('https://fixture.invalid/assets/travel-home/b.jpg'),{waitUntil:p=>wait=p});await wait;assert.equal(result2.status,200);});
test('rapid scrolling cannot accumulate an unlimited image-cache write queue',async()=>{const {ctx,cache,saved}=fixture();let release;cache.put=async(k,r)=>{if(!release)await new Promise(resolve=>release=resolve);saved.set(k.url,r);};const waits=[];for(let i=0;i<10;i++)await ctx.travelImageResponse(new Request('https://fixture.invalid/assets/travel-home/'+i+'.jpg'),{waitUntil:p=>waits.push(p)});assert.equal(waits.length,2);release();await Promise.all(waits);assert.equal(saved.size,2);});
test('travel image cache also enforces a total five MiB budget',async()=>{const {ctx,cache,saved}=fixture();for(let i=0;i<24;i++)await ctx.travelImageSave(cache,new Request('https://fixture.invalid/assets/travel-home/'+i+'.jpg'),new Response(new Uint8Array(400000),{headers:{'content-type':'image/jpeg'}}));let total=0;for(const r of saved.values())total+=Number(r.headers.get('content-length'));assert(total<=5*1024*1024);assert(saved.size<24);});
test('travel photos are never part of shell warmup',()=>{const optional=source.slice(source.indexOf('const OPTIONAL_FILES='),source.indexOf('function sleep'));assert(!/assets\/travel-home\/[^']+\.(jpg|webp|png)/.test(optional));});
