import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(privateApp=false){let now=1800000000000,aid='main',serial=0;class Clock extends Date{static now(){return now;}}const S={me:{name:'我',balance:1000},contacts:[{id:'r',name:'小克',wallet:1000},{id:'b',name:'朋友',wallet:1000}],travel:{},spy:{r:{balance:1000,wallet:[]}}},messages={},reminders=[];const ctx=vm.createContext({S,Date:Clock,actId:()=>aid,tvInit:()=>S.travel,uid:()=> 'taxi-'+ ++serial,getC:k=>S.contacts.find(c=>c.id===k),esc:String,save(){},toast(){},cur:()=>({p:'travel'}),render(){},msgs:k=>messages[k]||(messages[k]=[]),addBill:(type,n)=>S.me.balance+=type==='in'?n:-n,tvHotelRoleMoney:c=>c.wallet!=null?{source:'roleWallet',balance:c.wallet}:{source:'roleBank',balance:S.spy[c.id].balance},scheduleReply:(k,n,done)=>reminders.push([k,n,done]),setInterval(){},document:{querySelector:()=>null,querySelectorAll:()=>[]},NorthTravelHome:{home(){},icon:()=>'<svg></svg>'}});vm.runInContext(fs.readFileSync(new URL('../travel-hotel-data.js',import.meta.url),'utf8'),ctx);vm.runInContext(fs.readFileSync(new URL(privateApp?'../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/travel-taxi.js':'../travel-taxi.js',import.meta.url),'utf8'),ctx);const api=ctx.NorthTravelTaxi,q={accountId:'main',from:'上海家门口',to:'上海虹桥站',coords:null,locationAt:now,mode:'together',roleIds:['r'],helperId:'',distance:8,ts:now};api.state().query=q;return {api,q,S,messages,reminders,ctx,setNow:v=>now=v,switchAccount:v=>aid=v};}

for(const privateApp of [false,true]){
 test(`chat pickup and destination produce original role-paid order (${privateApp})`,()=>{const {api,S,messages}=fixture(privateApp);api.state().query=null;messages.r=[{role:'user',type:'text',content:'帮我叫车，我在发现岛，要去酒吧，叫专车',time:Date.now()}]; // use fixture clock
 messages.r[0].time=1800000000000;
 let ok;const out=api.consume('车安排好了[叫车|发现岛|酒吧|专车|给你]',S.contacts[0],v=>ok=v);
 assert.equal(ok,true);assert.equal(out,'车安排好了');assert.equal(api.rows().length,1);assert.equal(api.rows()[0].from,'发现岛');assert.equal(api.rows()[0].to,'酒吧');assert.equal(api.rows()[0].type,'special');assert.equal(api.rows()[0].payer,'ta');assert.equal(S.me.balance,1000);assert.equal(S.contacts[0].wallet,946.6);assert(messages.r.some(m=>m.type==='ticket'));assert.equal(api.userRows().length,0);
 });
 test(`shorthand repair completes simulated locations or produces full tag (${privateApp})`,async()=>{const {api,S,messages}=fixture(privateApp);api.state().query=null;messages.r=[{role:'user',type:'text',content:'给我叫专车，我在发现岛，去酒吧',time:1800000000000}];let calls=0;
 const result=await api.prepare('马上[叫车查询]已经叫好了',S.contacts[0],async prompt=>{calls++;assert(prompt.includes('发现岛'));return '安排上了。[叫车|发现岛|酒吧|专车|给你]';});assert.equal(calls,1);let ok;api.consume(result,S.contacts[0],v=>ok=v);assert(ok);assert.equal(api.rows().length,1);
 const b=fixture(privateApp);b.api.state().query=null;b.messages.r=[{role:'user',type:'text',content:'给我叫车去酒吧',time:1800000000000}];const ask=await b.api.prepare('[叫车查询]叫好了',b.S.contacts[0],async()=> '你现在在哪上车？');assert(ask.includes('[叫车|'));let booked;b.api.consume(ask,b.S.contacts[0],v=>booked=v);assert(booked);assert.equal(b.api.rows().length,1);
 });
 test(`chat cannot use another role, replay stale requests or spend insufficient funds (${privateApp})`,()=>{for(const change of ['other','stale','cancel','funds']){const {api,S,messages,setNow}=fixture(privateApp);api.state().query=null;messages.r=[{role:'user',type:'text',content:'给我叫车，我在发现岛，去酒吧',time:1800000000000}];if(change==='stale')setNow(1800000600001);if(change==='cancel')messages.r.push({role:'user',type:'text',content:'不要叫车了',time:1800000000000});if(change==='funds')S.contacts[0].wallet=0;let ok;const out=api.consume('叫好了[叫车|'+(change==='invent'?'猜的位置':'发现岛')+'|酒吧|快车|给你]',change==='other'?S.contacts[1]:S.contacts[0],v=>ok=v);assert.equal(ok,false,change);assert.equal(out,'');assert.equal(api.rows().length,0);assert.equal(S.me.balance,1000);assert(messages[change==='other'?'b':'r'].some(m=>m.type==='sys'&&m.content.includes('未叫车')),change);}}
 );
 test(`valid shared query remains local and no extra model call (${privateApp})`,async()=>{const {api,S}=fixture(privateApp);let calls=0;const text=await api.prepare('好了[叫车查询]',S.contacts[0],async()=>{calls++;return '';});assert.equal(calls,0);let ok;api.consume(text,S.contacts[0],v=>ok=v);assert(ok);assert.equal(api.rows().length,1);});
}

test('a completed chat request cannot create another paid ride or steal an existing user booking',()=>{const {api,S,messages,q,setNow}=fixture();assert(api.book(q,'express'));const before=S.contacts[0].wallet;assert(api.roleQuery(S.contacts[0]));assert.equal(api.rows().length,2);assert.equal(S.contacts[0].wallet,before-27.6);const b=fixture();b.api.state().query=null;b.messages.r=[{role:'user',type:'text',content:'帮我叫车，我在发现岛，要去酒吧',time:1800000000000}];let ok;b.api.consume('[叫车|发现岛|酒吧|快车|给你]',b.S.contacts[0],v=>ok=v);assert(ok);const paid=b.S.contacts[0].wallet;b.api.consume('[叫车|发现岛|酒吧|快车|给你]',b.S.contacts[0],v=>ok=v);assert.equal(ok,false);assert.equal(b.api.rows().length,1);assert.equal(b.S.contacts[0].wallet,paid);});

for(const privateApp of [false,true])test(`role chooses simulated destination from pickup-only chat (${privateApp})`,async()=>{const {api,S,messages}=fixture(privateApp);api.state().query=null;messages.r=[{role:'user',type:'text',content:'发现岛',time:1800000000000}];let ok;api.consume('[叫车|发现岛|月光酒吧|专车|给你]',S.contacts[0],v=>ok=v);assert.equal(ok,true);assert.equal(api.rows()[0].to,'月光酒吧');assert.equal(api.rows()[0].type,'special');assert.equal(S.me.balance,1000);const b=fixture(privateApp);b.api.state().query=null;b.messages.r=[{role:'user',type:'text',content:'发现岛',time:1800000000000}];const fixed=await b.api.prepare('专车安排上[叫车查询]',b.S.contacts[0],async()=> '[叫车查询]');b.api.consume(fixed,b.S.contacts[0],v=>ok=v);assert.equal(ok,true);assert.equal(b.api.rows().length,1);assert.equal(b.api.rows()[0].from,'发现岛');});
