import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const data=fs.readFileSync(new URL('../travel-hotel-data.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../travel-hotel.js',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const core=app.slice(app.indexOf('const TV_CITIES='),app.indexOf('const TV_CITY_GROUPS'));
function fixture(city='上海',keyword=''){const state={me:{active:'main',balance:50000},contacts:[],travel:{hotels:[],hotelSearch:{city,keyword,checkIn:'2026-10-10',nights:2,stars:0,rooms:2,adults:3,children:0,roomType:'double',guestMode:'me',cid:''}}};const ctx=vm.createContext({S:state,tvInit:()=>state.travel,todayStr:()=> '2026-10-04',save(){},render(){},getC:()=>null,toast(){},document:{getElementById:()=>null},NorthTravelHome:{home(){},entry(){}}});vm.runInContext(core+data+ui,ctx);return {ctx,state,api:ctx.NorthTravelHotel,data:ctx.NorthHotelData};}
test('curated cities preserve every legacy destination and country and include aliases',()=>{const f=fixture(),old=vm.runInContext('TV_CITIES',f.ctx),all=f.data.cities();for(const c of old){assert(all.some(x=>x.name===c.n));assert.equal(f.data.resolve(c.c).cities.some(x=>x.name===c.n),true);if(c.i)assert(f.data.countries.some(x=>x[0]===(c.r||c.n)));}assert.equal(f.data.brands.length,56);assert.equal(f.data.countries.length,43);assert.equal(all.length,133);assert.equal(f.data.resolve('USA').label,'美国');assert.equal(f.data.resolve('New York').label,'纽约');});
test('known Chinese and English hotel brands match the same local records without model calls',()=>{const f=fixture('上海','希尔顿酒店');f.api.query();const first=f.state.travel.hotelSearch.hotelQuotes.items;assert(first.length>0);f.state.travel.hotelSearch.keyword='Hilton Hotel';f.api.query();assert.deepEqual(f.state.travel.hotelSearch.hotelQuotes.items.map(x=>x.id),first.map(x=>x.id));assert(first.every(x=>x.kind==='brand'));assert(first.every(x=>x.total===x.unit*4));});
test('USA plus Claude yields explicitly custom simulations in multiple US cities',()=>{const f=fixture('美国','Claude');f.state.travel.hotelSearch.preferredTags=['含早餐'];f.api.query();const s=f.state.travel.hotelSearch;assert.equal(s.category,'overseas');assert(s.hotelQuotes.items.length>0);assert(s.hotelQuotes.items.every(x=>x.kind==='custom'&&x.country==='美国'&&x.features.includes('含早餐')));assert(new Set(s.hotelQuotes.items.map(x=>x.city)).size>1);});
test('custom-name fallback never bypasses price, stars, location or facility filters',()=>{const f=fixture('美国','Claude'),s=f.state.travel.hotelSearch;Object.assign(s,{maxPrice:500,stars:4,hotelArea:'景区周边',preferredTags:['含早餐']});f.api.query();assert(s.hotelQuotes.items.length>0);assert(s.hotelQuotes.items.every(x=>x.unit<=500&&x.stars===4&&x.area==='景区周边'&&x.features.includes('含早餐')));s.maxPrice=1;f.api.query();assert.equal(s.hotelQuotes.items.length,0);});
test('results are bounded and known-brand filtering failures never become fake custom hotels',()=>{const f=fixture('中国',''),s=f.state.travel.hotelSearch;f.api.query();assert(s.hotelQuotes.items.length<=240);assert(s.hotelQuotes.items.length>20);s.keyword='汉庭';s.city='美国';f.api.query();assert(s.hotelQuotes.items.length>0);assert(s.hotelQuotes.items.every(x=>x.brand==='汉庭'));assert.doesNotMatch(data,/chatAPI|fetch\(|XMLHttpRequest/);});
test('web and private catalogues are byte identical',()=>{for(const name of ['travel-hotel-data.js','travel-hotel.js'])assert.equal(fs.readFileSync(new URL('../'+name,import.meta.url),'utf8'),fs.readFileSync(new URL('../native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'+name,import.meta.url),'utf8'));});
