import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(){let serial=0;const S={me:{balance:5000},contacts:[{id:'r',name:'角色',wallet:5000,family:{bound:true,quota:1000,used:0,month:'2026-10'}}],travel:{trips:[]},spy:{}};let active='main';const messages={},ctx=vm.createContext({S,actId:()=>active,curMonth:()=> '2026-10',todayStr:()=> '2026-10-04',tvInit:()=>S.travel,uid:()=> 'p-'+(++serial),getC:id=>S.contacts.find(c=>c.id===id),msgs:id=>messages[id]||(messages[id]=[]),pushMsg:(id,m)=>(messages[id]||(messages[id]=[])).push(m),scheduleReply(){},save(){},toast(){},openModal(){},closeModal(){},esc:String,addBill:(kind,n)=>S.me.balance+=kind==='out'?-n:n,tvHotelRoleMoney:c=>c.wallet!=null?{source:'roleWallet',balance:c.wallet}:{source:'roleBank',balance:S.spy[c.id]?.balance}});vm.runInContext(fs.readFileSync('travel-hotel-data.js','utf8')+fs.readFileSync('travel-payment.js','utf8'),ctx);ctx.NorthFlightBooking={rows:()=>S.travel.trips,bookQuote(q,key,c,p){const o={id:'o-'+(++serial),accountId:active,price:100,status:'upcoming'};if(!ctx.NorthTravelPayment.charge(p,10000,'模拟机票',o))return false;S.travel.trips.push(o);return true;}};const api=ctx.NorthTravelPayment;return{api,S,ctx,messages,c:S.contacts[0],switchAccount:v=>active=v,open:()=>api.open({kind:'flight',quote:{},item:'flight',name:'测试模拟机票',amount:100})};}
test('payment choice and role request do not charge until role approves; retry cannot duplicate order',()=>{const f=fixture();f.open();assert.equal(f.S.me.balance,5000);assert(f.api.pay('role','r'));assert.equal(f.c.wallet,5000);assert.equal(f.S.travel.trips.length,0);assert(f.api.accept(f.c));assert.equal(f.c.wallet,4900);assert.equal(f.S.me.balance,5000);assert(f.api.accept(f.c));assert.equal(f.c.wallet,4900);assert.equal(f.S.travel.trips.length,1);assert.equal(f.ctx.NorthHotelData.roleOrder(f.S.travel.trips[0]),false);});
test('role refusal and insufficient balance never produce a paid card or order',()=>{for(const refuse of [true,false]){const f=fixture();f.open();f.api.pay('role','r');if(!refuse)f.c.wallet=1;f.api.accept(f.c,refuse);assert.equal(f.S.travel.trips.length,0);assert.equal(f.S.me.balance,5000);assert(!f.messages.r.some(m=>m.type==='paid'));}});
test('family freeze and monthly quota reject payment without touching any wallet',()=>{for(const frozen of [true,false]){const f=fixture();f.open();if(frozen)f.S.couple={cardFrozen:true};else f.c.family.quota=99;assert.equal(f.api.pay('family','r'),false);assert.equal(f.c.family.used,0);assert.equal(f.c.wallet,5000);assert.equal(f.S.me.balance,5000);assert.equal(f.S.travel.trips.length,0);}});
test('previous-month quota resets on actual family payment; refund only restores its original month',()=>{const f=fixture();f.c.family.month='2026-09';f.c.family.used=999;f.open();assert(f.api.pay('family','r'));const o=f.S.travel.trips[0];assert.equal(f.c.family.used,100);assert.equal(f.c.family.month,'2026-10');f.c.family.month='2026-11';f.c.family.used=200;assert(f.api.refund(o));assert.equal(f.c.family.used,200);assert.equal(f.api.refund(o),false);assert.equal(f.S.me.balance,5000);});
test('role bank refund uses original bank and never switches to user wallet',()=>{const f=fixture();delete f.c.wallet;f.S.spy.r={balance:5000,wallet:[]};f.open();f.api.pay('role','r');assert(f.api.accept(f.c));const o=f.S.travel.trips[0];assert.equal(f.S.spy.r.balance,4900);f.c.wallet=999;assert(f.api.refund(o));assert.equal(f.S.spy.r.balance,5000);assert.equal(f.c.wallet,999);assert.equal(f.S.me.balance,5000);assert.equal(f.api.refund(o),false);});
test('pending role payment survives serialization; account switch cannot approve or reveal it',()=>{const f=fixture();f.open();f.api.pay('role','r');f.S.travel.paymentRequests=JSON.parse(JSON.stringify(f.S.travel.paymentRequests));const id=f.S.travel.paymentRequests[0].id;f.switchAccount('alt');assert.equal(f.api.pending('r'),null);assert.equal(f.api.accept(f.c),false);assert(!f.api.card({travelPayment:id}).includes('测试模拟机票'));assert.equal(f.c.wallet,5000);f.switchAccount('main');assert(f.api.accept(f.c));});
test('changed price and removed original funding source fail without charging or redirecting refunds',()=>{const f=fixture();f.open();f.api.pay('role','r');f.S.travel.paymentRequests[0].amount=101;assert.equal(f.api.accept(f.c),false);assert.equal(f.c.wallet,5000);assert.equal(f.S.travel.trips.length,0);const g=fixture();g.open();g.api.pay('role','r');g.api.accept(g.c);delete g.c.wallet;assert.equal(g.api.refund(g.S.travel.trips[0]),false);assert.equal(g.S.me.balance,5000);});
