import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const data=fs.readFileSync(new URL('../travel-hotel-data.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../travel-hotel.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(chat){const S={me:{active:'main',balance:10000},contacts:[],travel:{hotels:[],hotelSearch:{city:'上海',keyword:'希尔顿',checkIn:'2026-10-10',nights:1,rooms:1,adults:1,children:0,roomType:'double',guestMode:'me'}}};const calls=[];const ctx=vm.createContext({S,tvInit:()=>S.travel,todayStr:()=> '2026-10-04',save(){},render(){},getC:()=>null,toast(){},document:{getElementById:()=>null,querySelector:()=>null},NorthTravelHome:{home(){},entry(){}},...(chat?{chatAPI:async(m,o)=>{calls.push({m,o});return chat(m,o);}}:{})});vm.runInContext(data+ui,ctx);return {S,calls,api:ctx.NorthTravelHotel};}
const reply=JSON.stringify({explanation:'这个名字可能有拼写差异，未联网核实。试试希尔顿；报价为模拟。',suggestions:[{label:'试试希尔顿',keyword:'希尔顿'}]});
test('local matches make zero requests; misses call configured model once and reuse advice',async()=>{const f=fixture(()=>reply);f.api.query();assert.equal(f.calls.length,0);f.S.travel.hotelSearch.keyword='Hiltn';f.api.query();await tick();assert.equal(f.calls.length,1);assert.equal(f.S.travel.hotelSearch.hotelQuotes.help.status,'done');f.api.query();await tick();assert.equal(f.calls.length,1);const req=JSON.parse(f.calls[0].m[1].content);assert.deepEqual(Object.keys(req).sort(),['area','category','destination','keyword','maxPrice','preferences','stars']);assert.equal(f.calls[0].o.timeout,30000);assert.equal(f.S.me.balance,10000);assert.equal(f.S.travel.hotels.length,0);});
test('suggestions change only explicit query fields when clicked and preserve hard filters',async()=>{const f=fixture(()=>reply),s=f.S.travel.hotelSearch;s.keyword='Hiltn';s.maxPrice=1;s.stars=5;s.preferredTags=['含早餐'];f.api.query();await tick();assert.equal(s.hotelQuotes.items.length,0);assert.equal(s.keyword,'Hiltn');f.api.applySuggestion(0);await tick();assert.equal(s.keyword,'希尔顿');assert.equal(s.maxPrice,1);assert.equal(s.stars,5);assert.equal(s.preferredTags[0],'含早餐');assert.equal(s.hotelQuotes.items.length,0);});
test('in-flight identical searches deduplicate and late replies never overwrite new search',async()=>{let finish;const f=fixture(()=>new Promise(r=>finish=r)),s=f.S.travel.hotelSearch;s.keyword='Hiltn';f.api.query();const old=s.hotelQuotes;f.api.query();assert.equal(f.calls.length,1);s.keyword='全季';f.api.query();const current=s.hotelQuotes;finish(reply);await tick();assert.equal(s.hotelQuotes,current);assert.equal(current.help,undefined);assert.notEqual(old,current);assert(current.items.every(x=>x.brand==='全季'));});
test('account changes discard late replies and model errors expose retry without charging',async()=>{let finish;const f=fixture(()=>new Promise(r=>finish=r)),s=f.S.travel.hotelSearch;s.keyword='Hiltn';f.api.query();const q=s.hotelQuotes;f.S.me.active='other';finish(reply);await tick();assert.equal(q.help.status,'loading');assert.equal(f.S.me.balance,10000);const bad=fixture(()=>'{bad json');bad.S.travel.hotelSearch.keyword='Hiltn';bad.api.query();await tick();assert.equal(bad.S.travel.hotelSearch.hotelQuotes.help.status,'error');await bad.api.retryHelp();assert.equal(bad.calls.length,2);assert.equal(bad.S.me.balance,10000);});
test('isolated preview explicitly reports missing model connection rather than pretending success',async()=>{const f=fixture();f.S.travel.hotelSearch.keyword='Claude';f.api.query();await tick();assert.equal(f.S.travel.hotelSearch.hotelQuotes.help.status,'error');assert.match(f.S.travel.hotelSearch.hotelQuotes.help.text,/独立预览没有模型连接/);});
test('unknown destination triggers advice even if a simulated brand result can be created',async()=>{const f=fixture(()=>reply);f.S.travel.hotelSearch.city='Shanghaai';f.api.query();await tick();assert.equal(f.calls.length,1);assert.equal(f.S.travel.hotelSearch.city,'Shanghaai');assert.equal(f.S.travel.hotelSearch.hotelQuotes.help.status,'done');});
