import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function fixture(){const at=Date.parse("2026-10-03T22:00:00Z");class FixedDate extends Date{constructor(...args){super(...(args.length?args:[at]));}static now(){return at;}}const ctx={Date:FixedDate,S:{me:{name:'我',active:'main',balance:10000,bills:[]},contacts:[{id:'r1',name:'角色一'}],travel:{}},document:{getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},todayStr:()=> '2026-10-04',actId:()=>ctx.S.me.active,tvInit:()=>ctx.S.travel,save(){},render(){},toast(){},requestAnimationFrame:f=>f(),NorthTravelHome:{home(){}},esc:v=>String(v),openModal(){},closeModal(){},console};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('travel-hotel-data.js','utf8'),ctx);vm.runInContext(fs.readFileSync('travel-ticket-data.js','utf8'),ctx);let selected={name:'上海',country:'中国',type:'city'};ctx.NorthTravelRegions={selected:()=>selected,catalogue:()=>[...ctx.NorthHotelData.cities().map(x=>({...x,type:'city'})),...ctx.NorthHotelData.countries.map(c=>({name:c[0],country:c[0],type:'country',aliases:[c[1],c[2]]}))]};vm.runInContext(fs.readFileSync('travel-guide.js','utf8'),ctx);ctx.NorthTravelGuide.open();ctx.NorthTravelGuide.render();ctx.S.travel.guideForms.main.date='2026-10-04';return ctx;}
test('every supported country has local spots and unique ids; thumbnails are a small subset',()=>{const c=fixture(),rows=c.NorthTravelTicketData.rows();assert.equal(rows.length,104);assert.equal(new Set(rows.map(x=>x.id)).size,rows.length);for(const country of c.NorthHotelData.countries)assert(rows.some(x=>x.country===country[0]),country[0]);assert(rows.filter(x=>x.photo).length<=5);});
test('model parsing rejects invalid amounts, foreign results, scripts as prices, and oversized responses',()=>{const c=fixture(),criteria={destination:{name:'上海',country:'中国',type:'city'}},base={name:'项目',city:'上海',country:'中国',kind:'游乐园',price:99};for(const patch of [{price:-1},{price:'99'},{price:20000},{city:'巴黎',country:'法国'},{city:'北京'},{kind:'<script>'}])assert.throws(()=>c.NorthTravelGuide.parseModel(JSON.stringify({items:[{...base,...patch}]}),criteria));assert.throws(()=>c.NorthTravelGuide.parseModel('x'.repeat(18001),criteria));});
test('free simulated tickets remain free, duplicates are blocked and refunds are idempotent',()=>{const c=fixture();c.NorthTravelGuide.chooseDestination('上海博物馆');c.NorthTravelGuide.query();const id=c.S.travel.guideForms.main.quote.items[0].id;c.NorthTravelGuide.book(id);c.NorthTravelGuide.book(id);assert.equal(c.S.travel.ticketOrders.length,1);assert.equal(c.S.me.balance,10000);const order=c.S.travel.ticketOrders[0];c.NorthTravelGuide.refund(order.id);c.NorthTravelGuide.refund(order.id);assert.equal(c.S.me.balance,10000);assert.equal(order.status,'refunded');assert.equal(c.S.me.bills.length,2);});
test('late AI results are discarded after switching accounts',async()=>{const c=fixture();let finish;c.chatAPI=()=>new Promise(r=>finish=r);c.NorthTravelGuide.chooseDestination('未记录的测试岛');c.NorthTravelGuide.query();const q=c.S.travel.guideForms.main.quote;c.S.me.active='other';finish(JSON.stringify({items:[{name:'模拟项目',city:'测试岛',country:'测试国',kind:'景点',price:10}]}));await new Promise(r=>setTimeout(r,0));assert.equal(q.items.length,0);assert.equal(q.status,'idle');assert.equal(c.S.travel.ticketOrders?.length||0,0);});
test('later price and party changes cannot change the original refund amount',()=>{const c=fixture();c.NorthTravelGuide.chooseDestination('上海迪士尼乐园');c.NorthTravelGuide.query();const q=c.S.travel.guideForms.main.quote;c.NorthTravelGuide.book(q.items[0].id);const o=c.S.travel.ticketOrders[0];assert.equal(c.S.me.balance,9601);q.items[0].price=9999;c.S.travel.guideForms.main.people=['role:r1'];c.NorthTravelGuide.refund(o.id);assert.equal(c.S.me.balance,10000);assert.equal(o.amount,399);});
