import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const roots=['','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/'];
for(const base of roots){const app=fs.readFileSync(new URL('../'+base+'app.js',import.meta.url),'utf8'),take=name=>{const start=app.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert(start>=0);const next=/^(?:async )?function /m.exec(app.slice(app.indexOf('\n',start)+1));return app.slice(start,next?app.indexOf('\n',start)+1+next.index:app.length);};
 function fixture(){let seq=0;const c={id:'role',name:'同行角色',wallet:50000,blocked:true},other={id:'other',name:'另一角色',wallet:1000},S={me:{name:'我',active:'main',balance:90000},contacts:[c,other],spy:{},travel:{hotels:[],hotelSearch:{city:'上海',keyword:'全季',checkIn:'2026-10-10',nights:2,stars:4,rooms:2,adults:3,children:1,roomType:'double',guestMode:'together',cid:'role',preferredTags:['含早餐'],maxPrice:600}}},messages=[],bills=[],errors=[];const ctx=vm.createContext({S,tvInit:()=>S.travel,actId:()=>S.me.active,todayStr:()=> '2026-10-04',uid:()=> 'test-'+(++seq),msgs:()=>messages,getC:id=>S.contacts.find(c=>c.id===id),save(){},render(){},cur:()=>({p:'home'}),toast:x=>errors.push(x),closeModal(){},uiConfirm:async()=>true,northLocaleNumber:String,tvMD:String,tvP2:x=>String(x).padStart(2,'0'),addBill:(kind,amount)=>{bills.push({kind,amount});S.me.balance+=kind==='in'?amount:-amount;},esc:x=>String(x??'').replaceAll('<','&lt;').replaceAll('"','&quot;'),document:{getElementById:()=>null,querySelector:()=>null}});vm.runInContext(fs.readFileSync(new URL('../'+base+'travel-hotel-data.js',import.meta.url),'utf8')+fs.readFileSync(new URL('../'+base+'travel-hotel.js',import.meta.url),'utf8')+['tvHotelOwned','tvHotelCurrent','tvHotelSummary','tvHotelRoleMoney','tvHotelRoleMoneyApply','tvHotelRoleQueryPrompt','tvHotelConsumeBookingTags','tvHotelRoomText','tvHotelStatusText','tvHotelGuestText','tvHotelBookerText','tvHotelVisibleToRole','tvHotelCheckout','tvHotelNo','tvCharHotelBook','tvHotelCardHTML','tvHotelCancel'].map(take).join('\n'),ctx);return {ctx,c,other,S,messages,bills,errors,book:(...args)=>ctx.tvCharHotelBook(c,...args)};}
 test(base+'role booking shares catalogue, selected budget and multi-room totals; retries charge once',()=>{const f=fixture(),q=f.ctx.NorthTravelHotel.rolePlan(f.c,'上海','2026-10-10',2,4,'双人间','我们一起');assert(q.item.features.includes('含早餐'));assert(q.item.unit<=600);assert.equal(q.item.total,q.item.unit*4);const before=f.c.wallet;assert(f.book('上海','2026-10-10',2,4,'双人间','我们一起'));const h=f.S.travel.hotels[0];assert.equal(h.price,q.item.total);assert.equal(h.rooms,2);assert.equal(h.adults,3);assert.equal(h.children,1);assert.equal(h.accountId,'main');assert.equal(h.payer,'ta');assert.equal(f.c.wallet,before-h.price);assert.equal(f.S.me.balance,90000);assert(f.book('上海','2026-10-10',2,4,'双人间','我们一起'));assert.equal(f.S.travel.hotels.length,1);assert.equal(f.messages.length,1);assert.equal(f.c.wallet,before-h.price);});
 test(base+'invalid dates, capacity, unknown hotels and insufficient role funds create no paid order',()=>{for(const args of [['上海','2026-10-01',2,4,'双人间','我们一起'],['上海','2026-02-30',2,4,'双人间','我们一起'],['上海','2026-10-10',2,4,'双人间','我们一起','全季',1,3,0],['上海','2026-10-10',2,4,'双人间','我们一起','不在资料里的酒店']]){const f=fixture();assert.equal(f.book(...args),false);assert.equal(f.S.travel.hotels.length,0);assert.equal(f.c.wallet,50000);}const f=fixture();f.c.wallet=1;assert.equal(f.book('上海','2026-10-10',2,4,'双人间','我们一起'),false);assert.equal(f.c.wallet,1);assert.equal(f.S.me.balance,90000);assert.equal(f.messages.length,0);});
 test(base+'role wallet refund goes to original payer once, and serialized cards read live cancellation state',async()=>{const f=fixture();f.book('上海','2026-10-10',2,4,'双人间','我们一起');const h=f.S.travel.hotels[0],snapshot=JSON.parse(JSON.stringify(h));assert.equal(f.ctx.tvHotelVisibleToRole(h,'role'),true);assert.equal(f.ctx.tvHotelVisibleToRole(h,'other'),false);await f.ctx.tvHotelCancel(h.id,{direct:true});await f.ctx.tvHotelCancel(h.id,{direct:true});assert.equal(f.c.wallet,50000);assert.equal(f.S.me.balance,90000);assert.match(f.ctx.tvHotelSummary(snapshot),/已取消/);assert.match(f.ctx.tvHotelSummary(snapshot),/2间/);assert.match(f.ctx.tvHotelCardHTML(snapshot),/已取消/);f.S.me.active='alt';assert.equal(f.ctx.tvHotelVisibleToRole(h,'role'),false);assert.equal(f.ctx.tvHotelOwned(h),false);assert.match(f.ctx.tvHotelCardHTML(snapshot),/不可用/);});
 test(base+'role phone bank is usable without profile wallet; hotel never spends family-card funds',async()=>{const f=fixture();delete f.c.wallet;f.S.spy.role={balance:6000,wallet:[]};f.c.familyCardBalance=999999;assert(f.book('上海','2026-10-10',2,4,'双人间','我们一起'));const h=f.S.travel.hotels[0];assert.equal(h.fundingSource,'roleBank');assert.equal(f.S.spy.role.balance,6000-h.price);assert.equal(f.S.spy.role.wallet[0].amount,-h.price);await f.ctx.tvHotelCancel(h.id,{direct:true});assert.equal(f.S.spy.role.balance,6000);assert.equal(f.c.familyCardBalance,999999);assert.equal(f.S.me.balance,90000);});
 test(base+'lost role funding account never redirects refund into user wallet',async()=>{const f=fixture();f.book('上海','2026-10-10',2,4,'双人间','我们一起');const h=f.S.travel.hotels[0];f.S.contacts=[];await f.ctx.tvHotelCancel(h.id,{direct:true});assert.equal(h.status,'upcoming');assert.equal(f.S.me.balance,90000);assert.equal(f.bills.length,0);});
 test(base+'normal booking tags support explicit brands and guests; failed tags cannot retain booked claims',()=>{const f=fixture();const out=f.ctx.tvHotelConsumeBookingTags('订好了。\n[订酒店|上海|2026-10-10|2|4|双人间|我们一起|全季|2|3|1]',f.c);assert.equal(out.trim(),'订好了。');assert.equal(f.S.travel.hotels[0].rooms,2);assert.match(f.S.travel.hotels[0].hotelName,/全季/);f.c.wallet=0;assert.equal(f.ctx.tvHotelConsumeBookingTags('订好了。\n[订酒店|上海|2026-10-11|2|4|双人间|我们一起|全季|2|3|1]',f.c),'');assert.equal(f.S.travel.hotels.length,1);});
}
