import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = fs.readFileSync(path.join(root, "app.js"), "utf8");
const html = fs.readFileSync(path.join(root, "小手机.html"), "utf8");

// The already-paid call audio is cached with the video-call message and reused.
assert.match(source, /async function callReplayStoreAudio\(m,ab,dur\)/);
assert.match(source, /if\(!m\|\|!ab\|\|m\._ck!==\x27video\x27\)return/);
assert.match(source, /cacheMessage:video\?callMsg:null/);
assert.match(source, /if\(opt\.cacheMessage\)await callReplayStoreAudio\(opt\.cacheMessage,ready\.ab,ready\.buf\.duration\)/);
assert.doesNotMatch(source, /callReplayStoreAudio[\s\S]{0,200}ttsArr/);

// Original subtitle and translation stay paired instead of becoming duplicate replay clips.
assert.match(source, /_callTrans:u\.trans\|\|\x27\x27/);
assert.match(source, /_callTranslationOf:callMsg\.id/);
assert.match(source, /!m\._callTranslationOf/);

// Users select time points; unsupported/old silent records are never exported as silent videos.
assert.match(source, /function clReplayPicker\(id,cs\)/);
assert.match(source, /function callReplayPickRows\(id,cs\)/);
assert.match(source, /if\(!firstAudio\)\{toast\(\x27这些时间点没有可用声音，不能导出静音视频\x27\);return;\}/);

// Export contains both the canvas video track and an AudioContext destination track.
assert.match(source, /canvas\.captureStream\(30\)/);
assert.match(source, /createMediaStreamDestination\(\)/);
assert.match(source, /dest\.stream\.getAudioTracks\(\)\.forEach\(t=>stream\.addTrack\(t\)\)/);
assert.match(source, /new MediaRecorder\(stream,opts\)/);
assert.match(source, /navigator\.canShare\(\{files:\[file\]\}\)/);
assert.match(source, /if\(rows\.length>100\)\{toast\(\x27一次最多选择100个时间点\x27\);return;\}/);
assert.match(source, /rows\.length>50\?1800000:3500000/);
assert.match(source, /let firstAudio=null/);
assert.doesNotMatch(source, /prepared\.push\(\{row,buf/);

// Live-call rewind is removed; replay remains available from the external call log.
assert.doesNotMatch(source, /function callLiveRewind/);
assert.doesNotMatch(source, /callLiveRewind\(5\)/);
assert.doesNotMatch(source, /callrewind/);
assert.match(source, /<details[\s\S]{0,1800}event\.preventDefault\(\);event\.stopPropagation\(\);clReplayPicker\('/);

// Legacy call lines can be generated or regenerated by selected time point.
assert.match(source, /async function clReplayRevoice\(id,cs\)/);
assert.match(source, /x\.role===\x27assistant\x27&&!x\.action&&pickSpoken\(x\.text,lang\)/);
assert.doesNotMatch(source, /if\(!m\|\|m\.callAudio\)continue/);
assert.match(source, /已有声音仅在新声音成功保存后替换；失败会保留原声音/);
assert.match(source, /async function callReplayReplaceAudio\(m,ab,dur\)/);
assert.match(source, /const stored=await callReplayReplaceAudio\(m,ab,buf\.duration\)/);
assert.match(source, /if\(old\.audio\)m\.callAudio=old\.audio;else delete m\.callAudio/);
assert.match(source, /ttsArr\(spoken,c,\{cue:row\.cue,interjection:row\.interjection\}\)/);
assert.match(source, /ttsRefundAudio\(ab,\x27call-revoice-decode-failed\x27\)/);
assert.match(source, /ttsRefundAudio\(ab,\x27call-revoice-store-failed\x27\)/);
assert.match(source, /ttsRefundAudio\(ab,\x27call-revoice-exception\x27\)/);
assert.match(source, /r\.time\?hm\(r\.time\):\(\x27第\x27\+\(i\+1\)\+\x27条\x27\)/);
assert.match(source, /row&&row\.time\?hm\(row\.time\)/);
assert.match(source, /_callVoiceCue:_turnVoiceCue\|\|\x27\x27/);
assert.match(source, /function ttsRelayInterjection\(s,rawCue\)/);
assert.match(source, /voice_setting:{speed:vp.speed/);

// User-recorded voice is replayed from its original audio; typed/recognized text remains subtitle-only.
assert.match(source, /m\.role===\x27assistant\x27\?m\.callAudio:\(m\.type===\x27voice\x27\?m\.audio:\x27\x27\)/);

// The live call send button is neutral gray, while the microphone retains its explicit state color.
assert.match(html, /\.callinput button\{[^}]*background:#4a4a50/);
assert.doesNotMatch(html, /\.callinput button\{[^}]*#ff6fa5/);
assert.doesNotMatch(html, /\.callrewind/);

console.log("video call replay tests passed");
