import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const files=['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js'];
function extract(src,name){src=src.replace(/\r\n/g,'\n');const start=src.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert(start>=0,name);const rest=src.slice(start),next=rest.slice(1).search(/\n(?:async )?function /);return next<0?rest:rest.slice(0,next+1);}
function harness(src){const ctx=vm.createContext({VOICE_MAX_CHARS:300,ttsContentLang:c=>c.voice.lang,hasForeign:t=>/[a-z]/i.test(t),voiceLangName:()=> '英语',ttsRequestedCue:()=>'',ttsAutoCue:()=>'',splitBubbles:s=>String(s).split('\n'),wechatRoleDrift:s=>/AI assistant/.test(s),roleInterceptDiagnosticRemember:()=>{}});for(const n of ['roleReplyEnglishOnly','roleReplyAssertLanguage','parseVoiceTagLine','explicitVoiceReplyRequest','voiceReplyTagValid','forceRequestedVoiceReply','voiceTagNeedsLangFix','voiceReplyCanRepairCandidate','finalizeVoiceReply','chatResultText'])vm.runInContext(extract(src,n),ctx);return ctx;}
const valid='[语音|Good night.|晚安。|语气:温柔]',c={voice:{lang:'en'}};
for(const file of files){const src=fs.readFileSync(file,'utf8');
 test(file+' recognizes screenshot but does not mistake reports or negation for a request',()=>{const h=harness(src);for(const s of ['先生你发句语音','先生，你发句语音','哥哥给我来条语音','请用语音回复我'])assert(h.explicitVoiceReplyRequest(s),s);for(const s of ['先生你不要发语音','我刚才发的语音你听到了吗','他发过语音','我说先生你发过语音'])assert(!h.explicitVoiceReplyRequest(s),s);});
 test(file+' cues cannot stand in for translations; tagged candidate exception is private to voice repair',async()=>{const h=harness(src);for(const value of ['[语音|Good night.|语气:温柔]','[语音|Good night.]']){assert(h.roleReplyEnglishOnly(value));for(const raw of [false,true])await assert.rejects(h.chatResultText([],{roleReplyLanguageGuard:true,unfilteredOutput:raw},{choices:[{message:{content:value}}]}),{code:'ROLE_ENGLISH_ONLY'});assert.equal(await h.chatResultText([],{roleReplyLanguageGuard:true,roleVoiceFormatRepair:true},{choices:[{message:{content:value}}]}),value);}assert(!h.roleReplyEnglishOnly(valid));assert(!h.voiceReplyCanRepairCandidate('Good night.',{roleVoiceFormatRepair:true}));assert(h.voiceReplyCanRepairCandidate('Good night.',{roleVoiceFormatRepair:true,roleVoiceRequested:true}));});
 test(file+' repairs voice at most once and never releases failed English as text',async()=>{const h=harness(src);let calls=0;const broken='[语音|Good night.|语气:温柔]';assert.equal(await h.finalizeVoiceReply(broken,'',c,async()=>{calls++;return valid;}),valid);assert.equal(calls,1);for(const result of ['Good night.','[语音|Good night.|Warm.]','[语音|Good night.|语气:温柔]','你好。','I am an AI assistant.']){calls=0;await assert.rejects(h.finalizeVoiceReply(broken,'',c,async()=>{calls++;return result;}),{code:'VOICE_REPLY_FORMAT'});assert.equal(calls,1);}await assert.rejects(h.finalizeVoiceReply(broken,'',c,async()=>{throw new Error('network');}),{code:'VOICE_REPLY_FORMAT'});});
 test(file+' valid and ordinary replies do not pay for a repair; explicit Chinese can use the actual model words',async()=>{const h=harness(src),unexpected=async()=>{assert.fail('unexpected model request');};assert.equal(await h.finalizeVoiceReply(valid,'先生你发句语音',c,unexpected),valid);assert.equal(await h.finalizeVoiceReply('我在。','',c,unexpected),'我在。');const converted=await h.finalizeVoiceReply('我在。','先生你发句语音',{voice:{lang:'zh'}},async()=>{throw Error('network');});assert.equal(h.parseVoiceTagLine(converted).text,'我在。');});
}
test('September 5 comparison is reproducible and does not equate older code with a guaranteed fix',()=>{const old=execFileSync('git',['show','90accb87:app.js'],{encoding:'utf8',maxBuffer:30000000}),current=fs.readFileSync(files[0],'utf8');for(const name of ['parseVoiceTagLine','ttsContentLang','voiceEnglishPrompt','ttsArr'])assert.equal(extract(old,name),extract(current,name),name+' interface must stay unchanged');const ctx={};vm.createContext(ctx);vm.runInContext(extract(old,'explicitVoiceReplyRequest'),ctx);assert.equal(ctx.explicitVoiceReplyRequest('先生你发句语音'),false);assert.match(old,/vf0===0\|\|tooLong\|\|badLang/);});
