import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
for(const file of ['app.js','native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/app.js']){
 const app=fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),label=file==='app.js'?'web':'private';
 function source(name){const start=app.search(new RegExp('function '+name+'\\('));assert(start>=0);const tail=app.slice(start),end=tail.slice(1).search(/\n(?:function |async function |const |let |\/\*)/);return end<0?tail:tail.slice(0,end+1);}
 function runtime(){const storage=new Map(),saves=[],c=vm.createContext({S:{me:{active:'main',locked:false},messages:{a:[]},groups:[],moments:[]},KEY:'fixture',_heavyStamp:{messages:'old'},document:{hidden:false},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},save:n=>saves.push(n),actId:()=>c.S.me.active,isMain:()=>c.S.me.active==='main',accountMessageKey:(id,aid)=>aid==='main'?id:id+'#'+aid,roleReadCounted:m=>m&&!m._silent&&m.type!=='sys',msgs:id=>c.S.messages[c.S.me.active==='main'?id:id+'#'+c.S.me.active]||[],Date});vm.runInContext(['roleInternalControlLine','wxUnreadState','wxReadKey','wxMessageSeen','wxUnreadJournalWrite','wxUnreadRestore','wxRoleUnread','wxGroupUnread','wxMomentSeenMap','wxMomentUnread','wxMarkPageSeen'].map(source).join('\n'),c);return {c,storage,saves};}
 test(label+': hydrated legacy history becomes the baseline without editing message content',()=>{const {c}=runtime(),now=Date.now();c.S.messages.a=[{id:'old',role:'assistant',content:'旧消息',time:now-1000},{id:'future-clock',role:'assistant',content:'旧记录的未来时间',time:now+100000}];c.S.moments=[{id:'old-moment',authorId:'a',acct:'main',time:now-1000}];assert(c.wxUnreadRestore());assert.equal(c.wxRoleUnread('a'),0);assert.equal(c.wxMomentUnread(),false);assert.equal(c.S.messages.a[0].content,'旧消息');assert.equal(c.S.messages.a[0].seenAt,undefined);c.S.messages.a.push({id:'new',role:'assistant',content:'新消息',time:c.S.me._wxUnreadV2.since});assert.equal(c.wxRoleUnread('a'),1);});
 test(label+': an older archived row cannot resurrect after the core save or receipt fields are lost',()=>{const {c,storage}=runtime();c.wxUnreadRestore();const since=c.S.me._wxUnreadV2.since;c.S.messages.a=[{id:'middle',role:'assistant',content:'已存档后再阅读',time:since},{id:'tail',role:'user',content:'自己发的',time:since}];c.wxMarkPageSeen({p:'chat',id:'a'});assert(storage.get('fixture_wx_read_v2'));assert.equal(c._heavyStamp.messages,undefined);delete c.S.me._wxUnreadV2;delete c.S.messages.a[0].seenAt;c.wxUnreadRestore();assert.equal(c.wxRoleUnread('a'),0);assert(c.S.messages.a[0].seenAt);c.S.messages.a.push({id:'same-time-different-id',role:'assistant',content:'之后的新消息',time:since});assert.equal(c.wxRoleUnread('a'),1);});
 test(label+': read IDs are isolated by account and do not clear another conversation',()=>{const {c}=runtime();c.wxUnreadRestore();const time=c.S.me._wxUnreadV2.since;c.S.messages.a=[{id:'same-id',role:'assistant',content:'主身份',time}];c.S.messages['a#alt']=[{id:'same-id',role:'assistant',content:'另一身份',time}];c.wxMarkPageSeen({p:'chat',id:'a'});c.S.me.active='alt';assert.equal(c.wxRoleUnread('a'),1);c.S.me.active='main';assert.equal(c.wxRoleUnread('a'),0);});
 test(label+': locked/hidden pages never clear unread and storage quota uses immediate core fallback',()=>{const {c,saves}=runtime();c.wxUnreadRestore();c.S.messages.a=[{id:'new',role:'assistant',content:'你好',time:c.S.me._wxUnreadV2.since}];c.S.me.locked=true;c.wxMarkPageSeen({p:'chat',id:'a'});assert.equal(c.wxRoleUnread('a'),1);c.S.me.locked=false;c.document.hidden=true;c.wxMarkPageSeen({p:'chat',id:'a'});assert.equal(c.wxRoleUnread('a'),1);c.document.hidden=false;c.localStorage.setItem=()=>{throw Error('quota');};c.wxMarkPageSeen({p:'chat',id:'a'});assert.equal(c.wxRoleUnread('a'),0);assert.equal(saves.at(-1),0);});
 test(label+': already hydrated state merges only newer read marks from the same history baseline',()=>{const {c,storage}=runtime();c.wxUnreadRestore();const state=c.S.me._wxUnreadV2;state.read['r:a']={x:10};storage.set('fixture_wx_read_v2',JSON.stringify({ver:2,state:{ver:2,since:state.since,read:{'r:a':{x:20,y:30}}}}));c.wxUnreadRestore();assert.equal(state.read['r:a'].x,20);assert.equal(state.read['r:a'].y,30);storage.set('fixture_wx_read_v2',JSON.stringify({ver:2,state:{ver:2,since:state.since-1,read:{'r:a':{z:40}}}}));c.wxUnreadRestore();assert.equal(state.read['r:a'].z,undefined);});
}
