import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
type JsonObject=Record<string,unknown>;
const object=(v:unknown):JsonObject=>v&&typeof v==="object"&&!Array.isArray(v)?v as JsonObject:{};
const text=(v:unknown,n=300)=>String(v??"").trim().slice(0,n);
function cors(request:Request){const origin=request.headers.get("origin")||"";const configured=(Deno.env.get("PHONE_DELIVERY_ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim()).filter(Boolean);const allowed=!configured.length||!origin||configured.includes(origin);return{"Access-Control-Allow-Origin":allowed?(origin||"*"):"null","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"600","Vary":"Origin"};}
function reply(request:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(request),"Content-Type":"application/json; charset=utf-8"}});}
function admin(){const url=Deno.env.get("SUPABASE_URL")||"",key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!key)throw new Error("supabase-not-configured");return createClient(url,key,{auth:{persistSession:false}});}
async function auth(client:ReturnType<typeof admin>,input:JsonObject){const c=object(input.client),target=text(c.target,100),ownerSecret=text(c.ownerSecret,200);if(!/^yb_[a-z0-9]{20,96}$/.test(target)||ownerSecret.length<24)throw new Error("smart-home-client-auth-required");const r=await client.rpc("phone_delivery_authenticate",{p_target:target,p_secret:ownerSecret});if(r.error)throw r.error;if(r.data!==true)throw new Error("smart-home-client-auth-failed");return{target,ownerSecret};}
function safePlan(value:unknown){const v=object(value),allowed=new Set(["power","brightness","color","hue","saturation","warmth"]);if(!Object.keys(v).length||Object.keys(v).some(k=>!allowed.has(k)))throw new Error("unsupported-smart-home-action");if(v.power!==undefined&&!new Set(["on","off"]).has(String(v.power)))throw new Error("invalid-power");for(const key of ["brightness","hue","saturation","warmth"])if(v[key]!==undefined&&!Number.isFinite(Number(v[key])))throw new Error("invalid-number");return v;}
Deno.serve(async(request)=>{const headers=cors(request);if(request.method==="OPTIONS")return new Response(null,{status:204,headers});if(request.method!=="POST")return reply(request,{ok:false,error:"method-not-allowed"},405);try{const input=object(await request.json()),action=text(input.action,40),client=admin(),caller=await auth(client,input),payload=object(input.payload);if(action==="pairing_begin"){const r=await client.rpc("phone_smart_home_begin_pairing",{p_target:caller.target,p_owner_secret:caller.ownerSecret});if(r.error)throw r.error;return reply(request,{ok:true,data:object(r.data)});}if(action==="device_status"){const r=await client.rpc("phone_smart_home_status",{p_target:caller.target,p_owner_secret:caller.ownerSecret});if(r.error)throw r.error;return reply(request,{ok:true,data:object(r.data)});}if(action==="device_revoke"){if(payload.confirmedByUser!==true)return reply(request,{ok:false,error:"本人确认后才能解绑"},400);const r=await client.rpc("phone_smart_home_revoke",{p_target:caller.target,p_owner_secret:caller.ownerSecret});if(r.error)throw r.error;return reply(request,{ok:true,data:{revoked:r.data===true}});}if(action!=="snapshot"&&action!=="control")return reply(request,{ok:false,error:"不支持的智能家电操作"},400);const requestKey=text(object(input.client).requestKey,160);if(!/^shr_[a-z0-9-]{16,140}$/i.test(requestKey))return reply(request,{ok:false,error:"invalid-request-key"},400);const jobPayload=action==="control"?{plan:safePlan(payload.plan)}:{};const queued=await client.rpc("phone_smart_home_enqueue",{p_target:caller.target,p_owner_secret:caller.ownerSecret,p_request_key:requestKey,p_action:action,p_payload:jobPayload});if(queued.error)throw queued.error;const job=object(queued.data),state=text(job.status,30);if(state==="completed")return reply(request,{ok:true,data:object(job.result)});if(state==="failed"||state==="expired")return reply(request,{ok:false,error:text(job.error,240)||"电脑没有确认灯具状态"},409);return reply(request,{ok:false,pending:true,jobId:text(job.id,80)},202);}catch(error){return reply(request,{ok:false,error:text((error as Error)?.message||error,240)||"智能家电服务失败"},400);}});
