// Both engines, many short chat fields, distinct media, normal boot and active persistence.
// A desktop WebKit build is not the user's physical iPhone.
const {chromium,webkit}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 try{for(const engine of (process.env.NORTH_BACKUP_ENGINE?[process.env.NORTH_BACKUP_ENGINE]:['edge','webkit'])){
  const browser=await(engine==='edge'?chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}):webkit.launch({headless:true}));
  try{const context=await browser.newContext({acceptDownloads:true,viewport:{width:390,height:844},userAgent:engine==='webkit'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1':'Mozilla/5.0 (Linux; Android 12; Huawei) AppleWebKit/537.36 Chrome/134.0.0.0 Mobile Safari/537.36 EdgA/134.0.0.0'});
   const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
   const entry=origin+'/小手机.html';await page.goto(entry+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>_bootImagesPromise);
   await page.evaluate(async()=>{S.me.locked=false;S.settings.backupFixture='realistic-fields';S._backupImages=[];
    for(let i=0;i<48;i++){const key='realistic_'+i;await imgPut(key,'data:image/png;base64,'+String(i).padStart(3,'0')+'A'.repeat(65536));S._backupImages.push('idb:'+key);}
    const id=S.contacts[0].id;S.messages[id]=Array.from({length:10000},(_,i)=>({id:'fixture-'+i,role:i%2?'assistant':'user',type:'text',content:'真实结构聊天测试'.repeat(12),time:Date.now()-100000+i,meta:{seen:true,account:'main'}}));S.settings.fixtureRole=id;await prepareImportedStateForSave();await saveNowAsync();
   });
   await page.goto(entry);await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>_bootImagesPromise);await page.evaluate(()=>{const g=document.getElementById('gate');if(g)g.remove();S.me.locked=false;openSettings('data');});await page.waitForTimeout(300);await page.evaluate(()=>closeModal());
   const geometry=await page.evaluate(()=>{const e=document.getElementById('set_storage'),s=e.querySelector('svg');return{meterHeight:e.getBoundingClientRect().height,svgHeight:s.getBoundingClientRect().height};});assert(geometry.meterHeight<400,JSON.stringify(geometry));assert(geometry.svgHeight<40,JSON.stringify(geometry));
   await page.evaluate(()=>{window.parseMs=0;window.applyMs=0;const realRead=readBackupJson;readBackupJson=async(...args)=>{const at=performance.now();try{return await realRead(...args);}finally{parseMs=Math.round(performance.now()-at);}};const realApply=applyFullBackupData;applyFullBackupData=async(...args)=>{const at=performance.now();try{return await realApply(...args);}finally{applyMs=Math.round(performance.now()-at);}};window.importNotices=[];const realToast=toast;toast=text=>{importNotices.push(text);return realToast(text);};window.backupTicks=0;window.backupMaxGap=0;let last=performance.now();window.backupTimer=setInterval(()=>{backupTicks++;backupMaxGap=Math.max(backupMaxGap,performance.now()-last);last=performance.now();},16);});
   const at=Date.now();const [download]=await Promise.all([page.waitForEvent('download',{timeout:120000}),page.locator('button[onclick="exportData()"]').click()]);const exportMs=Date.now()-at;assert.equal(await download.failure(),null);const file=await download.path();const data=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(data.messages[data.settings.fixtureRole].length,10000);assert.equal(data._backupImages.length,48);assert(data._backupImages.every(x=>x.startsWith('data:image')));
   const importAt=Date.now();const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.locator('button[onclick="importData()"]').click()]);await chooser.setFiles(file);await page.waitForFunction(()=>typeof _fullBackupImportBusy!=='undefined'&&_fullBackupImportBusy);await page.waitForFunction(()=>!_fullBackupImportBusy,null,{timeout:120000});
   const metrics=await page.evaluate(()=>{clearInterval(backupTimer);return{parseMs,applyMs,ticks:backupTicks,maxGap:Math.round(backupMaxGap),count:S.messages[S.settings.fixtureRole].length,images:S._backupImages.length};});assert(await page.evaluate(()=>importNotices.some(s=>s==='完整备份已安全导入')),'must confirm successful import, not retain old fixture after a caught failure');assert.equal(metrics.count,10000);assert.equal(metrics.images,48);assert(exportMs<20000,'short-field timer regression: '+exportMs);assert(metrics.maxGap<2000,JSON.stringify(metrics));
   await page.goto(entry);await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>_bootImagesPromise);const reload=await page.evaluate(async()=>{const raw=await imgGet('__messages'),local=JSON.parse(localStorage.getItem(KEY)||'{}');return{count:S.messages&&S.messages[S.settings.fixtureRole]&&S.messages[S.settings.fixtureRole].length,role:S.settings.fixtureRole,keys:Object.keys(S.messages||{}),localMessageRef:local.messages,bootRef:!!_coreBootRef,rawBytes:raw&&raw.length,rawCount:raw&&JSON.parse(raw)[S.settings.fixtureRole]&&JSON.parse(raw)[S.settings.fixtureRole].length,openFailure:_idbOpenFailure,errors:window.__northBootError};});console.log(JSON.stringify({engine,reload}));assert.equal(reload.count,10000);assert.deepEqual(errors,[]);
   console.log(JSON.stringify({engine,exportMs,importAndReloadMs:Date.now()-importAt,bytes:fs.statSync(file).size,...geometry,...metrics,pageErrors:errors.length}));await context.close();
  }finally{await browser.close();}
 }}finally{server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
