const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp/travel-home');
const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'}[path.extname(f)]||'application/octet-stream'));res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];try{for(const priv of [false,true]){const label=priv?'private':'web',p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false})};});await p.goto(origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();renderLockScreen();S.settings.sound=false;S.settings.deskPet={on:false};S.contacts.forEach(c=>c.proactive={enabled:false});S.me.city='北京';S.me.balance=10000;gateOK=()=>true;aiCoreOn=()=>false;go('travel');NorthTravelHome.entry('flight');});assert(await p.locator('.ctf-app').isVisible());

await p.evaluate(()=>{document.querySelector('#toast')?.classList.remove('show');document.querySelector('.ctf-scroll').scrollTop=1000;});assert(await p.locator('.ctf-orders-entry').isVisible());assert(await p.locator('.ctf-orders-wrap').evaluate(e=>{const a=e.getBoundingClientRect(),b=document.querySelector('.ctf-card').getBoundingClientRect();return a.top-b.bottom>=17&&a.width===b.width;}));await p.screenshot({path:path.join(out,label+'-flight-query-spacing.png')});
await p.evaluate(()=>{const c=S.contacts[0];c.deleted=false;c.blocked=false;c.wallet=50000;S.spy=S.spy||{};S.spy[c.id]={balance:50000,wallet:[]};window.flightRole=c.id;const s=NorthTravelFlight.state();s.people=[{id:'me',name:S.me.name},{id:'role:'+c.id,name:c.remark||c.name}];s.adults=2;s.children=1;s.infants=1;s.legs[0]={from:'北京',to:'上海',date:'2099-10-05'};NorthTravelFlight.query();});
assert.equal(await p.locator('.ctf-fish svg').count(),6);await p.evaluate(()=>{const o={accountId:actId(),date:'2099-10-05',arriveAt:new Date('2099-10-05T11:00:00').getTime(),status:'upcoming'};if(!NorthFlightBooking.visible(o,new Date('2099-10-05T23:00:00').getTime())||NorthFlightBooking.visible(o,new Date('2099-10-06T00:00:00').getTime()))throw Error('flight day expiry wrong');o.arriveAt=new Date('2099-10-06T02:00:00').getTime();if(!NorthFlightBooking.visible(o,new Date('2099-10-06T01:00:00').getTime())||NorthFlightBooking.visible(o,o.arriveAt))throw Error('overnight expiry wrong');});
for(const w of [320,390,430]){await p.setViewportSize({width:w,height:844});assert(await p.evaluate(()=>document.querySelector('.ctf-list-app').scrollWidth<=document.querySelector('.ctf-list-app').clientWidth+1));}
await p.setViewportSize({width:390,height:844});
await p.evaluate(()=>{document.querySelector('.ctf-flight-scroll').scrollTop=250;});
const row=p.locator('.ctf-flight-row').nth(2),fId=await row.getAttribute('data-flight');const amount=await p.evaluate(id=>NorthFlightBooking.flights(NorthTravelFlight.state().quote).find(x=>x.id===id).totalCents/100,fId);
await p.evaluate(()=>document.addEventListener('click',()=>{window.beforeBookingScroll=document.querySelector('.ctf-flight-scroll')?.scrollTop;},{capture:true,once:true}));await row.getByRole('button',{name:'订',exact:true}).click();await p.waitForFunction(()=>!!document.querySelector('.ctf-refund'));await p.evaluate(()=>new Promise(r=>requestAnimationFrame(r)));
assert.equal(await p.evaluate(()=>S.me.balance),10000-amount);assert(Math.abs(await p.evaluate(()=>document.querySelector('.ctf-flight-scroll').scrollTop)-await p.evaluate(()=>window.beforeBookingScroll))<=1);
await p.evaluate(({id,amount})=>{const q=NorthTravelFlight.state().quote,o=NorthFlightBooking.rows()[0],c=getC(flightRole);if(o.price!==o.adultPrice*2.6||o.people.length!==2||o.children!==1||o.infants!==1)throw Error('whole-party fare or snapshot wrong');const n=S.travel.trips.length,b=S.me.balance;if(!NorthFlightBooking.bookQuote(q,id)||S.travel.trips.length!==n||S.me.balance!==b)throw Error('duplicate booking charged');if(!NorthFlightBooking.rolePrompt(c).includes(o.people[1].name))throw Error('role cannot see own companion booking');const other={id:'other',name:'other'};if(NorthFlightBooking.rolePrompt(other).includes('2099-10-05'))throw Error('unrelated role saw private booking');if(!tvTicketCardHTML(o,c).includes(o.people[1].name)||!msgToText({type:'ticket',trip:{id:o.id,flightV2:true}}).includes(o.people[1].name))throw Error('chat card/history missing companions');c.spy={granted:true};S.couple={cid:c.id,wxLoginAuth:true,remoteControlAuth:true};const fact=rolePhoneLocalRead(c.id,'travel');if(!fact.data.includes(o.people[1].name))throw Error('authorized inspection missing companions');window.resultOrder=o.id;q.adults=3;}, {id:fId,amount});
await p.locator('.ctf-refund').click();assert.equal(await p.evaluate(()=>S.me.balance),10000);await p.evaluate(()=>{if(NorthFlightBooking.refund(resultOrder)||S.me.balance!==10000)throw Error('double refund');const o=NorthFlightBooking.current(resultOrder);if(!NorthFlightBooking.visible(o,o.refundedAt+86399999)||NorthFlightBooking.visible(o,o.refundedAt+86400000))throw Error('refund 24h expiry wrong');const q=NorthTravelFlight.state().quote;q.adults=2;const c=getC(flightRole);if(!NorthFlightBooking.roleQuery(c,1))throw Error('role query booking failed');const r=NorthFlightBooking.rows().find(o=>o.payer==='ta');if(!r||c.wallet!==50000-r.price||S.me.balance!==10000||r.people.length!==2)throw Error('role own funds or party wrong');const wallet=c.wallet;c.wallet=0;if(NorthFlightBooking.roleDirect(c,'北京','巴黎','2099-10-06','经济舱','我们一起'))throw Error('insufficient role bank accepted');c.wallet=wallet;if(!NorthFlightBooking.refund(r.id)||c.wallet!==50000||S.me.balance!==10000)throw Error('role original-source refund wrong');S.me.active='other-account';if(NorthFlightBooking.current(resultOrder)||NorthFlightBooking.rows().length)throw Error('account isolation failed');S.me.active='main';});
// Normal authorized chat processes the new tag, rather than only testing a helper.
await p.evaluate(()=>{const c=getC(flightRole);S.settings.chat={base:'https://fixture.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};S.settings.replyDelay=0;chatAPI=async()=> '两个人的机票订好了。\n[订机票|北京|巴黎|2099-10-07|经济舱|我们一起]';msgs(c.id).push({id:uid(),role:'user',type:'text',content:'帮我们两个人订2099年10月7日北京去巴黎的经济舱机票',time:Date.now()});openChat(c.id);});await p.evaluate(()=>aiReply(flightRole));
await p.locator('.ctf-chat-flight').filter({hasText:'巴黎'}).last().click();assert(await p.getByText('机票订单详情',{exact:true}).isVisible());assert((await p.locator('.ctf-detail-fields').innerText()).includes('巴黎'));assert((await p.locator('.ctf-detail-fields').innerText()).includes('出行人员'));await p.evaluate(()=>document.querySelector('#toast')?.classList.remove('show'));await p.screenshot({path:path.join(out,label+'-flight-full-detail.png')});await p.getByRole('button',{name:'返回上一页',exact:true}).click();assert(await p.locator('.ctf-chat-flight').filter({hasText:'巴黎'}).last().isVisible());await p.locator('.ctf-chat-flight').filter({hasText:'巴黎'}).last().screenshot({path:path.join(out,label+'-flight-role-card.png')});
await p.evaluate(()=>{const r=NorthFlightBooking.rows().find(o=>o.to==='巴黎');if(!r||r.adults!==2||r.people.length!==2||r.payer!=='ta')throw Error('new role tag was not executed in normal chat');if(NorthFlightBooking.visible(r,NorthFlightBooking.deadline(r)))throw Error('arrival expiry wrong');getC(flightRole).wallet=0;chatAPI=async()=> '已经订好了。\n[订机票|北京|东京|2099-10-08|经济舱|给你]';msgs(flightRole).push({id:uid(),role:'user',type:'text',content:'订东京机票',time:Date.now()});});await p.evaluate(()=>aiReply(flightRole));assert.equal(await p.getByText('已经订好了。',{exact:true}).count(),0);
await p.evaluate(()=>{go('travel');NorthTravelFlight.open();const s=NorthTravelFlight.state();s.adults=2;s.children=0;s.infants=0;s.legs[0]={from:'北京',to:'上海',date:'2099-10-05'};NorthTravelFlight.query();document.querySelectorAll('.toast').forEach(e=>e.style.display='none');});await p.locator('.ctf-book').first().click();await p.evaluate(()=>{document.querySelectorAll('.toast').forEach(e=>e.style.display='none');});await p.screenshot({path:path.join(out,label+'-flight-results-booked.png')});
await p.getByRole('button',{name:'价格排序',exact:true}).click();await p.getByRole('button',{name:'下午出发',exact:true}).click();assert(await p.evaluate(()=>{const q=NorthTravelFlight.state().quote;return NorthFlightBooking.flights(q).filter(f=>document.querySelector('[data-flight=\"'+CSS.escape(f.id)+'\"]')).every(f=>+f.dep.slice(0,2)>=12);}));await p.getByRole('button',{name:'筛选⌄',exact:true}).click();assert.equal(await p.locator('.ctf-dialog').evaluate(e=>getComputedStyle(e.parentElement).backgroundColor),'rgb(255, 255, 255)');await p.locator('#ctfMaxPrice').fill('1');await p.getByRole('button',{name:'应用筛选',exact:true}).click();assert((await p.locator('.ctf-flight-empty').innerText()).includes('没有符合筛选条件的模拟航班'));assert.equal(await p.locator('.ctf-flight-row').count(),0);await p.getByRole('button',{name:'清除筛选',exact:true}).click();assert.equal(await p.locator('.ctf-flight-row').count(),6);
await p.evaluate(()=>{const c=getC(flightRole),q={account:actId(),type:'multi',cls:'economy',adults:2,children:0,infants:0,people:[{id:'me',name:S.me.name},{id:'role:'+c.id,name:c.name}],legs:[{from:'北京',to:'上海',date:'2099-10-09'},{from:'上海',to:'东京',date:'2099-10-09'}],selectedLeg:0,id:uid()};const late=NorthFlightBooking.flights(q).at(-1);const b=S.me.balance;S.me.balance=0;if(NorthFlightBooking.bookQuote(q,late.id)||S.me.balance!==0)throw Error('insufficient user balance accepted');S.me.balance=b;if(!NorthFlightBooking.bookQuote(q,late.id))throw Error('first multi leg failed');q.selectedLeg=1;const early=NorthFlightBooking.flights(q).at(0);const n=S.travel.trips.length,remaining=S.me.balance;if(NorthFlightBooking.bookQuote(q,early.id)||S.travel.trips.length!==n||S.me.balance!==remaining)throw Error('conflicting multi leg charged');c.wallet=null;S.spy[c.id].balance=50000;const direct=NorthFlightBooking.roleDirect(c,'北京','新加坡','2099-10-10','经济舱','给你');if(!direct)throw Error('role bank source booking failed');const o=NorthFlightBooking.rows().find(o=>o.to==='新加坡'),bank=S.spy[c.id].balance;c.wallet=7;if(!NorthFlightBooking.refund(o.id)||S.spy[c.id].balance!==50000||c.wallet!==7)throw Error('refund changed source after wallet added');const remind=NorthFlightBooking.rows().find(o=>o.status==='upcoming'&&o.knownRoleIds.includes(c.id));const d=remind.date,old=scheduleReply;remind.date=todayStr();let called=0;scheduleReply=()=>{called++;};NorthFlightBooking.checkDue();NorthFlightBooking.checkDue();scheduleReply=old;remind.date=d;if(called!==1)throw Error('flight reminder repeated or missing');});
assert.deepEqual(errors,[]);reports.push({runtime:label,blueFishRows:true,responsive:true,partyFare:true,scrollPreserved:true,originalRefund:true,refundIdempotent:true,roleOwnBank:true,normalChatNewTag:true,companionCardAndInspection:true,accountIsolation:true,expiry:true,sortFilter:true,pageErrors:errors});await p.close();}fs.writeFileSync(path.join(out,'flight-booking-result.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});

