const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp/travel-home');
const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'}[path.extname(f)]||'application/octet-stream'));res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];
try{for(const priv of [false,true]){const label=priv?'private':'web',p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false})};});
await p.goto(origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();localStorage.setItem('yibei_unlocked',String(SHARE_EPOCH));renderLockScreen();S.settings.sound=false;S.settings.deskPet={on:false};S.contacts.forEach(c=>c.proactive={enabled:false});window.testRole=S.contacts[0].id;const c=getC(testRole);c.blocked=false;c.deleted=false;c.wallet=50000;c.spy={granted:true,loc:false};S.couple={cid:c.id,wxLoginAuth:true,remoteControlAuth:true};S.contacts.push({id:'travel-other',name:'乙'});S.spy=S.spy||{};S.spy[c.id]={balance:50000,wallet:[]};S.me.balance=10000;S.settings.replyDelay=0;tvInit().ticketOrders=[];gateOK=()=>true;aiCoreOn=()=>false;go('travel');NorthTravelGuide.open();window.tomorrow=(()=>{const d=new Date(todayStr()+'T12:00:00');d.setDate(d.getDate()+1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');})();});
await p.getByRole('button',{name:/日期／时间/}).click();await p.locator('#ctgDate').fill(await p.evaluate(()=>tomorrow));await p.locator('#ctgTime').fill('07:00');await p.getByRole('button',{name:'确定',exact:true}).click();assert(await p.locator('#ctgEndTime').isVisible());await p.locator('#ctgEndTime').fill('06:00');await p.getByRole('button',{name:'确定',exact:true}).click();assert(await p.locator('#ctgEndTime').isVisible());await p.locator('#ctgEndTime').fill('17:00');await p.evaluate(()=>{document.querySelectorAll('.toast').forEach(e=>e.style.display='none');document.activeElement?.blur();});await p.screenshot({path:path.join(out,label+'-ticket-time-range.png'),animations:'disabled'});await p.getByRole('button',{name:'确定',exact:true}).click();assert((await p.getByRole('button',{name:/日期／时间/}).innerText()).includes('07:00—17:00'));
await p.evaluate(()=>{NorthTravelGuide.chooseDestination('上海迪士尼乐园');NorthTravelGuide.query();S.settings.chat={base:'https://fixture.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};window.normalCalls=0;chatAPI=async messages=>{normalCalls++;window.requestText=messages.map(x=>String(x.content||'')).join('\n');return '票订好了，我们明天一起去。\n[订门票|上海迪士尼乐园|'+tomorrow+'|07:00|17:00|我们一起]';};msgs(testRole).push({id:uid(),role:'user',type:'text',content:'请用你自己的银行给我们两人买明天早上七点到下午五点的上海迪士尼门票。',time:Date.now()});openChat(testRole);});
await p.evaluate(()=>aiReply(testRole));assert.equal(await p.evaluate(()=>tvInit().ticketOrders.length),1);assert.equal(await p.evaluate(()=>tvInit().ticketOrders[0].count),2);assert.equal(await p.evaluate(()=>getC(testRole).wallet),49202);assert.equal(await p.evaluate(()=>S.me.balance),10000);assert((await p.evaluate(()=>requestText)).includes('[订门票|'));assert(await p.locator('.ctg-chat-ticket').isVisible());assert((await p.locator('.ctg-chat-ticket').innerText()).includes('07:00—17:00'));await p.waitForTimeout(1200);await p.evaluate(()=>{document.querySelectorAll('.toast').forEach(e=>e.style.display='none');});await p.screenshot({path:path.join(out,label+'-role-ticket-card.png'),animations:'disabled'});await p.locator('.ctg-chat-ticket').click();assert(await p.locator('.ctg-dialog').isVisible());assert((await p.locator('.ctg-dialog').innerText()).includes('角色自己的银行'));await p.evaluate(()=>closeModal());
// Actual phone-inspection record collector and permission boundary, no replacement of either function.
await p.evaluate(async()=>{const t=tvInit(),base=t.ticketOrders[0];t.ticketOrders.push({...base,id:'solo-proof',cid:'',payer:'me',count:1,amount:399,people:[{id:'me',name:S.me.name}],knownRoleIds:[],reminderRoleId:'',name:'独自出游凭据'});t.ticketOrders.push({...base,id:'other-proof',cid:'',payer:'me',people:[{id:'me',name:S.me.name},{id:'role:travel-other',name:'乙'}],knownRoleIds:['travel-other'],reminderRoleId:'',name:'与乙同行凭据'});t.hotels.push({id:'hotel-inspection',accountId:actId(),hotelName:'酒店同行凭据',checkIn:tomorrow,nights:2,roomType:'double',guestMode:'together',cid:'travel-other',payer:'me',bookedBy:'me',price:500,status:'upcoming',ts:Date.now()});const c=getC(testRole);if(rolePhoneLocalScope('查看我买的门票')!=='travel')throw Error('ticket focus missed');const facts=spyFocusData(c.id,'旅游门票');if(!facts.data.includes('用户独自出游')||!facts.data.includes(S.me.name+'、乙')||!facts.data.includes('酒店同行凭据'))throw Error('actual phone facts lost solo/party/hotel');window.travelPhoneFacts=facts.data;c.spy.granted=false;window.noPermissionResult=await doSpyViewCore(c.id,true,{focus:'旅游门票'});c.spy.granted=true;const sys=buildSystem(c);if(sys.includes('独自出游凭据')||sys.includes('与乙同行凭据'))throw Error('unrelated order leaked into ordinary role prompt');S.me.active='other-account';if(spyFocusData(c.id,'旅游门票').data.includes('同行凭据'))throw Error('account phone facts leak');S.me.active='main';});
assert.equal(await p.evaluate(()=>noPermissionResult),false);
await p.evaluate(async()=>{let reads=0;chatAPI=async messages=>{const request=messages.map(x=>String(x.content||'')).join('\n');if(!request.includes('用户独自出游')||!request.includes('我、乙')&&!request.includes(S.me.name+'、乙'))throw Error('inspection model lost party facts');reads++;return '我看到了，你有自己去玩的票，也有和乙一起去的票。';};if(!await doSpyView(testRole,true,{focus:'旅游门票'}))throw Error('normal authorized inspection failed');if(!reads)throw Error('normal inspection did not use its model consumer');});

// Refund preserves original funding source and receipt timestamp.
await p.evaluate(()=>{const o=tvInit().ticketOrders[0];NorthTravelGuide.refund(o.id);NorthTravelGuide.refund(o.id);if(getC(testRole).wallet!==50000||S.me.balance!==10000)throw Error('role refund crossed accounts');if(!o.refundedAt)throw Error('refund time missing');});
// Advance the browser clock to tomorrow: real aiReply natural reminder delivery and reopen de-duplication.
await p.evaluate(()=>{window.realDateNow=Date.now;window.realTodayStr=todayStr;window.clockNow=new Date(tomorrow+'T09:00:00').getTime();Date.now=()=>clockNow;todayStr=()=>tomorrow;tvInit().ticketOrders[0].refundedAt=clockNow;const o=tvInit().ticketOrders.find(x=>x.id==='solo-proof');o.reminderRoleId=testRole;o.knownRoleIds=[testRole];o.reminderRetryAt=0;window.reminderCalls=0;chatAPI=async messages=>{const s=messages.map(m=>String(m.content||'')).join('\n');if(!s.includes('门票当天提醒'))throw Error('wrong reminder path');if(!s.includes('用户独自出游'))throw Error('wrong party reminder');reminderCalls++;return '今天去迪士尼呀，出门前记得把东西带好，玩得开心。';};NorthTravelOrders.wake();});
await p.waitForFunction(()=>tvInit().ticketOrders.find(x=>x.id==='solo-proof').remindedAt);assert.equal(await p.evaluate(()=>reminderCalls),1);assert(await p.getByText('今天去迪士尼呀，出门前记得把东西带好，玩得开心。',{exact:true}).isVisible());await p.screenshot({path:path.join(out,label+'-ticket-day-reminder.png')});await p.evaluate(()=>{NorthTravelOrders.wake();window.dispatchEvent(new Event('pageshow'));document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.evaluate(()=>reminderCalls),1);
await p.waitForFunction(()=>!NorthTravelOrders.busy());
// Cancel while the actual reminder model request is in flight: the late answer must stay hidden.
await p.evaluate(()=>{const base=tvInit().ticketOrders.find(x=>x.id==='solo-proof');tvInit().ticketOrders.push({...base,id:'stale-proof',name:'晚到提醒凭据',remindedAt:0,reminderRetryAt:0});window.beforeStale=msgs(testRole).length;chatAPI=()=>new Promise(resolve=>{window.staleResolve=resolve;});NorthTravelOrders.wake();});
await p.waitForFunction(()=>typeof staleResolve==='function');await p.evaluate(()=>{tvInit().ticketOrders.find(x=>x.id==='stale-proof').status='refunded';tvInit().ticketOrders.find(x=>x.id==='stale-proof').refundedAt=Date.now();staleResolve('这是一条已经失效的提醒，不应该发送。');});await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>msgs(testRole).some(m=>m.content?.includes('已经失效的提醒'))),false);await p.evaluate(()=>{tvInit().ticketOrders=tvInit().ticketOrders.filter(x=>x.id!=='stale-proof');});
// Reload the real application from its persisted archive, rather than only firing a wake event.
const saved=await p.evaluate(async()=>{await saveNowAsync();return {day:tomorrow,role:testRole};});
await p.addInitScript(({day})=>{window.clockNow=new Date(day+'T09:00:00').getTime();const NativeDate=Date;window.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[window.clockNow]));}static now(){return window.clockNow;}};},saved);
await p.goto(origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html'));await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(({day,role})=>{window.tomorrow=day;window.testRole=role;window.realDateNow=Date.now;window.realTodayStr=todayStr;S.me.locked=false;document.getElementById('gate')?.remove();renderLockScreen();gateOK=()=>true;aiCoreOn=()=>false;window.reminderCallsAfterReload=0;chatAPI=async()=>{reminderCallsAfterReload++;return '不应重复的提醒';};const o=tvInit().ticketOrders.find(x=>x.id==='solo-proof');if(!o?.remindedAt||!msgs(testRole).some(m=>m._ticketReminderOrderId==='solo-proof'))throw Error('reminder delivery did not persist');NorthTravelOrders.wake();},saved);
assert.equal(await p.evaluate(()=>reminderCallsAfterReload),0);
// Ending at 17:00 hides from list, card and inspector without deleting the financial ledger.
await p.evaluate(()=>{clockNow=new Date(tomorrow+'T17:00:00').getTime();NorthTravelOrders.wake();go('travel');NorthTravelGuide.open();NorthTravelGuide.orders();});assert.equal(await p.locator('.ctg-ticket-row').count(),1);assert((await p.locator('.ctg-ticket-row').innerText()).includes('已退款'));
await p.evaluate(()=>{clockNow=tvInit().ticketOrders[0].refundedAt+86400000;NorthTravelOrders.wake();NorthTravelGuide.orders();if(NorthTravelOrders.rows().length)throw Error('refund did not expire at 24h');if(rolePhoneLocalRead(testRole,'travel').data.includes('出游凭据'))throw Error('expired ticket still readable');if(S.me.balance!==10000||getC(testRole).wallet!==50000)throw Error('cleanup moved funds');Date.now=realDateNow;todayStr=realTodayStr;});
assert.deepEqual(errors,[]);reports.push({runtime:label,requiredStartEndRange:true,normalRoleChatBooking:true,roleOwnBankAndRefund:true,independentClickableTicketCard:true,actualPhoneInspectionPartyFacts:true,permissionDenied:true,accountIsolation:true,realAiReplyReminderWithMockModel:true,reopenReminderDedup:true,expiredOrdersHidden:true,pageErrors:errors});await p.close();}
fs.writeFileSync(path.join(out,'travel-lifecycle-result.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
