// Real web/private pages; only model HTTP responses are deterministic fixtures.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp','role-family-card');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(f)]||'application/octet-stream')+'; charset=utf-8');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}),reports=[];
try{for(const priv of [false,true]){const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[],label=priv?'private':'web';page.on('pageerror',e=>errors.push(e.message));if(priv)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const url=origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html');
const ready=async()=>{await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>{S.me.locked=false;localStorage.setItem('yibei_unlocked',String(SHARE_EPOCH));document.getElementById('gate')?.remove();renderLockScreen();window.fixtureA=S.contacts[0].id;window.fixtureB=S.contacts[1].id;});};
await page.goto(url+'?northPreview=black-home');await ready();await page.evaluate(()=>{S.me.active='main';S.me.name='North';S.me.balance=5000;S.me.bills=[];S.contacts=S.contacts.slice(0,2);S.contacts[0].name=S.contacts[0].remark='克劳德';S.contacts[1].name=S.contacts[1].remark='沈言';S.contacts.forEach(c=>{c.proactive={enabled:false};c.wallet=1680;});S.contacts[0].family={bound:true,quota:800,used:120,month:curMonth()};S.messages={};S.roleFamily=null;S.spy={};S.settings.sound=false;S.settings.deskPet={on:false};S.settings.replyDelay=0;S.settings.chat={base:'https://fake.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};S.couple={cid:fixtureA};aiCoreOn=()=>false;window.modelCalls=[];window.fixtureRaw='收到了。';fetchT=async(url,opt)=>{if(!String(url).startsWith('https://fake.invalid/'))return{ok:true,json:async()=>false,text:async()=>'false'};modelCalls.push(JSON.parse(opt.body));return{ok:true,json:async()=>({choices:[{message:{content:fixtureRaw},finish_reason:'stop'}]})};};scheduleReply=()=>true;go('wxfamily');});
await page.locator('.rf-new').click();await page.locator('#rfAmount').fill('1200');await page.locator('#rfNote').fill('给自己买点喜欢的，别总舍不得。');await page.screenshot({path:path.join(out,label+'-send.png'),animations:'disabled'});await page.getByRole('button',{name:'存入并赠送'}).click();await page.waitForFunction(()=>S.roleFamily?.cards.length===1&&cur().p==='wxfamily'&&!__roleFamily.busy()&&!document.getElementById('modal').classList.contains('show'));assert.equal(await page.evaluate(()=>S.me.balance),3800);
await page.evaluate(async()=>{window.fixtureCard=__roleFamily.cards(fixtureA)[0].id;fixtureRaw='这份心意我收下了，给自己买点喜欢的。\n[收下亲属卡|'+fixtureCard+']';openChat(fixtureA);await aiReply(fixtureA);});assert.equal(await page.evaluate(()=>__roleFamily.cards(fixtureA)[0].status),'active');assert.equal(await page.evaluate(()=>getC(fixtureA).wallet),1680);await page.evaluate(()=>{document.getElementById('msgBanner')?.classList.remove('show');document.getElementById('toast')?.classList.remove('show');});await page.screenshot({path:path.join(out,label+'-chat.png'),animations:'disabled'});
await page.evaluate(async()=>{pushMsg(fixtureA,{role:'user',type:'text',content:'给自己买一盏书桌灯吧，用我给你的亲属卡。',time:Date.now(),id:uid()});fixtureRaw='挑了盏暖光的，晚上看书正好。\n[自购|desk_lamp_1|暖光书桌灯|329.00|亲属卡|'+fixtureCard+']';await aiReply(fixtureA);});assert.equal(await page.evaluate(()=>__roleFamily.cards(fixtureA)[0].balance),87100);assert.equal(await page.evaluate(()=>getC(fixtureA).wallet),1680);assert.equal(await page.evaluate(()=>S.me.balance),3800);assert.equal(await page.evaluate(()=>__roleFamily.ledger().orders.length),1);assert((await page.evaluate(()=>modelCalls.at(-1).messages[0].content)).includes('只能走你自己的银行'));
const result=await page.evaluate(async()=>{let r=await __roleFamily.buy(fixtureA,'desk_lamp_1','暖光书桌灯','329.00','亲属卡',fixtureCard,fixtureA);if(!r.duplicate)throw Error('duplicate charged');r=await __roleFamily.buy(fixtureA,'gift','礼物','30','亲属卡',fixtureCard,'me');if(r.ok)throw Error('other recipient paid');r=await __roleFamily.buy(fixtureB,'steal','咖啡','30','亲属卡',fixtureCard,fixtureB);if(r.ok)throw Error('wrong role');r=await __roleFamily.buy(fixtureA,'huge','沙发','900','亲属卡',fixtureCard,fixtureA);if(r.ok)throw Error('overdraft');r=await __roleFamily.buy(fixtureA,'coffee','手冲咖啡豆','88.50','亲属卡',fixtureCard,fixtureA);if(!r.ok)throw Error(r.error);r=await __roleFamily.buy(fixtureA,'own_book','散文集','45','自己的银行','无',fixtureA);if(!r.ok)throw Error(r.error);return{familyBalance:__roleFamily.cards(fixtureA)[0].balance,ownBalance:getC(fixtureA).wallet,duplicateOnce:true,wrongRecipientBlocked:true,wrongRoleBlocked:true,overdraftBlocked:true};});assert.equal(result.familyBalance,78250);assert.equal(result.ownBalance,1635);
await page.evaluate(()=>{go('wxfamily');document.getElementById('msgBanner')?.classList.remove('show');document.getElementById('toast')?.classList.remove('show');});await page.screenshot({path:path.join(out,label+'-overview.png'),animations:'disabled'});await page.evaluate(()=>familyRoleManage(fixtureCard));await page.locator('#rfTopup').fill('200');await page.getByRole('button',{name:'从我的钱包充值'}).click();await page.waitForFunction(()=>__roleFamily.cards(fixtureA)[0].balance===98250&&!__roleFamily.busy());assert.equal(await page.evaluate(()=>S.me.balance),3600);await page.evaluate(()=>{closeModal();document.getElementById('toast')?.classList.remove('show');});await page.screenshot({path:path.join(out,label+'-overview.png'),animations:'disabled'});
await page.evaluate(()=>{S.couple={cid:fixtureA};S.spy[fixtureA]={balance:9999,orders:[],wallet:[],wechat:[]};getC(fixtureA).spy={granted:true};_spyUnlock[fixtureA]=true;_spyApp='bank';go('spy',{id:fixtureA});document.getElementById('msgBanner')?.classList.remove('show');document.getElementById('toast')?.classList.remove('show');});assert((await page.locator('.rf-bank').innerText()).includes('982.50'));assert((await page.locator('.rf-bank').innerText()).includes('亲属卡'));await page.screenshot({path:path.join(out,label+'-bank.png'),animations:'disabled'});await page.evaluate(()=>{_spyApp='shop';render();});assert.equal(await page.locator('.rf-order').count(),3);await page.screenshot({path:path.join(out,label+'-shopping.png'),animations:'disabled'});
await page.evaluate(async()=>{delete S.spy[fixtureA];await saveNowAsync();});await page.goto(url);await ready();assert.equal(await page.evaluate(()=>__roleFamily.cards(fixtureA)[0].balance),98250);assert.equal(await page.evaluate(()=>__roleFamily.ledger().orders.length),3);assert.equal(await page.evaluate(()=>getC(fixtureA).wallet),1635);await page.evaluate(()=>{window.fixtureCard=__roleFamily.cards(fixtureA)[0].id;scheduleReply=()=>true;go('wxfamily');familyRoleSendOpen(fixtureB);});await page.locator('#rfAmount').fill('500');await page.getByRole('button',{name:'存入并赠送'}).click();await page.waitForFunction(()=>__roleFamily.cards(fixtureB).length===1&&!__roleFamily.busy()&&!document.getElementById('modal').classList.contains('show'));await page.evaluate(async()=>{const k=__roleFamily.cards(fixtureB)[0];if(!await __roleFamily.decide(k.id,fixtureB,false))throw Error('decline failed');if(await __roleFamily.decide(k.id,fixtureB,false))throw Error('duplicate decline');});assert.equal(await page.evaluate(()=>S.me.balance),3600);
await page.evaluate(()=>familyRoleTab('received'));assert((await page.locator('.rf-received').innerText()).includes('680.00'));await page.screenshot({path:path.join(out,label+'-received.png'),animations:'disabled'});
const layouts=[];for(const width of [320,390,430])for(const white of [false,true]){await page.setViewportSize({width,height:844});await page.evaluate(white=>{S.me.uiMaterial='glass';S.me.appIconPack=white?'pink':'black';S.me.wxTheme=white?'white':'black';familyRoleTab('sent');document.getElementById('msgBanner')?.classList.remove('show');document.getElementById('toast')?.classList.remove('show');},white);const box=await page.locator('.rf-premium').first().boundingBox();assert(box&&box.width<=width&&box.x>=0);assert.equal(await page.locator('.rf-page').evaluate(e=>e.scrollWidth>e.clientWidth),false);layouts.push({width,white,overflow:false});}
assert.deepEqual(errors,[]);reports.push({runtime:label,...result,realAiReplyAccepts:true,realAiReplyPurchases:true,recharge:true,refusalReturnsOnce:true,coldReloadPersists:true,phoneResetPreservesLedger:true,receivedMonthlyCardPreserved:true,layouts,pageErrors:errors});console.log(label+' family card browser passed');await page.close();}
fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
