// Real web/private browser entries, archived history, clicks and cold reloads; network is blocked.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp','unread-persistence'),baseline=process.env.UNREAD_BASELINE==='1';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\/+/,''),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');res.end(baseline&&rel.endsWith('app.js')?cp.execFileSync('git',['show','afab374fed54b8183a97866f2f9596b11999a629:'+rel],{cwd:root,maxBuffer:16*1024*1024}):fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}),reports=[];
try{for(const privateApp of [false,true]){const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[],prefix=privateApp?'private':'web';page.on('pageerror',e=>errors.push(e.message));if(privateApp)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const url=origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html');
const ready=async()=>{await page.waitForFunction(()=>window.__northBootReady===true);await page.evaluate(()=>{S.me.locked=false;localStorage.setItem('yibei_unlocked',String(SHARE_EPOCH));document.getElementById('gate')?.remove();renderLockScreen();});};const reopen=async()=>{await page.goto(url);await ready();await page.evaluate(()=>{wxTab='chats';go('wechat');});};
await page.goto(url+'?northPreview=black-home');await ready();
await page.evaluate(async()=>{S.settings.sound=false;S.couple=null;S.contacts=S.contacts.slice(0,2);S.contacts.forEach(c=>{c.proactive={enabled:false};});S.contacts[0].name=S.contacts[0].remark='已读持久保存测试';S.contacts[1].name=S.contacts[1].remark='另一会话';S.me.active='main';S.groups=[];S.moments=[{id:'legacy-moment',authorId:S.contacts[0].id,text:'旧朋友圈',time:Date.now()-100000,acct:'main',likes:[],comments:[]}];S.me._wxMomentSeen={};delete S.me._wxUnreadV2;localStorage.removeItem(KEY+'_wx_read_v2');S.messages={};S.messages[S.contacts[0].id]=Array.from({length:160},(_,i)=>({id:'legacy-'+i,role:'assistant',type:'text',content:'这是之前已经看过的旧消息。'.repeat(40),time:Date.now()-100000+i}));const p=phoneFriendState();p.friends=[];p.groups=[];p.messages={};p.groupMessages={};await saveNowAsync();await _messageArchiveWrite;await saveNowAsync();});
await reopen();const legacy=await page.evaluate(()=>({messages:wxUnreadTotal(),moments:wxMomentUnread()}));if(!baseline){assert.equal(legacy.messages,0,'legacy archive must not create unread');assert.equal(legacy.moments,false,'legacy moments must not create unread');}
// Prepare old history as genuinely read for the separate read/save/reopen defect in the released baseline.
if(baseline)await page.evaluate(async()=>{Object.values(S.messages).forEach(a=>a.forEach(m=>m.seenAt=1));S.me._wxMomentSeen={main:{'legacy-moment':1}};delete _heavyStamp.messages;await saveNowAsync();await _messageArchiveWrite;await saveNowAsync();});
await page.evaluate(async()=>{const id=S.contacts[0].id;msgs(id).push(...Array.from({length:4},(_,i)=>({id:'new-'+i,role:'assistant',type:'text',content:'新消息 '+(i+1)+'：吃完饭一起散步吧。',time:Date.now()})));go('wechat');await saveNowAsync();await _messageArchiveWrite;await saveNowAsync();});
assert.equal(await page.evaluate(()=>wxUnreadTotal()),4);assert.equal(await page.evaluate(async()=>{let core=JSON.parse(localStorage.getItem(KEY));if(core.__coreIdb)core=JSON.parse((await imgGet(CORE_IDB_KEY)).json);return core.messages.__idb;}),'messages','must exercise an already archived chat');await page.screenshot({path:path.join(out,prefix+'-1-new-four.png'),animations:'disabled'});
await page.locator('.wx-chat-row').first().click();assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);await page.evaluate(()=>go('wechat'));assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);await page.screenshot({path:path.join(out,prefix+'-2-open-cleared.png'),animations:'disabled'});
// No forced save here: reload before the ordinary/private delayed core save can complete.
await reopen();const afterImmediateReload=await page.evaluate(()=>wxUnreadTotal());if(baseline){reports.push({runtime:prefix,legacy,afterImmediateReload,defectReproduced:legacy.messages>0&&afterImmediateReload===4});await page.close();continue;}
assert.equal(afterImmediateReload,0,'read must survive immediate cold reload');for(let i=0;i<2;i++){await page.evaluate(()=>{go('home');go('wechat');});assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);await reopen();assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);}await page.screenshot({path:path.join(out,prefix+'-3-reopened-still-clear.png'),animations:'disabled'});
// New IDs at the exact same timestamp as the previous messages must still count independently.
await page.evaluate(async()=>{const id=S.contacts[0].id,t=msgs(id).find(m=>m.id==='new-0').time;msgs(id).push({id:'same-time-new',role:'assistant',type:'text',content:'这是一条后来收到的新消息。',time:t},{id:'later-new',role:'assistant',type:'text',content:'还有一条新的消息。',time:Date.now()});render();await saveNowAsync();await _messageArchiveWrite;await saveNowAsync();});assert.equal(await page.evaluate(()=>wxUnreadTotal()),2);await reopen();assert.equal(await page.evaluate(()=>wxUnreadTotal()),2,'real unread must survive reload');await page.screenshot({path:path.join(out,prefix+'-4-only-new-two.png'),animations:'disabled'});
await page.locator('.wx-chat-row').first().click();await page.evaluate(()=>{const id=S.contacts[0].id;msgs(id).push({id:'visible-new',role:'assistant',type:'text',content:'当前窗口里的新消息。',time:Date.now()});render();});assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);await reopen();assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);
// Group history, moments and real-friend read metadata have the same immediate durability boundary.
await page.evaluate(async()=>{const a=S.contacts[0].id;S.groups=[{id:'read-group',name:'群聊已读测试',members:[a],msgs:[{id:'group-new',senderId:a,type:'text',content:'群里新消息。',time:Date.now()}]}];S.moments.push({id:'moment-new',authorId:a,text:'新的朋友圈。',time:Date.now(),acct:'main',likes:[],comments:[]});await saveNowAsync();});assert.equal(await page.evaluate(()=>wxUnreadTotal()),1);assert.equal(await page.evaluate(()=>wxMomentUnread()),true);await page.evaluate(()=>{go('group',{id:'read-group'});go('wxmoment');go('wechat');});await reopen();assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);assert.equal(await page.evaluate(()=>wxMomentUnread()),false);
await page.evaluate(async()=>{const p=phoneFriendState();p.id='SPTESTSELF';p.friends=[{phone_id:'SPTESTPEER',display_name:'测试真人'}];p.messages.SPTESTPEER=[{id:'pf-new',from:'SPTESTPEER',body:'真人新消息',time:Date.now()}];await saveNowAsync();});assert.equal(await page.evaluate(()=>wxUnreadTotal()),1);await page.evaluate(()=>pfMarkRead('SPTESTPEER'));await reopen();assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);
// Read marks from main must not consume another account's new message.
await page.evaluate(()=>{const id=S.contacts[0].id;S.me.active='read-alt';msgs(id).push({id:'new-0',role:'assistant',type:'text',content:'另一个身份的新消息。',time:Date.now()});go('wechat');});assert.equal(await page.evaluate(()=>wxUnreadTotal()),1);await page.evaluate(()=>{S.me.active='main';go('wechat');});assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);
assert.deepEqual(errors,[]);reports.push({runtime:prefix,legacy,archivedReadSurvivesImmediateReload:true,repeatedReopenClear:true,onlyNewMessagesCount:true,sameTimestampIndependent:true,unreadSurvivesReload:true,activeArrivalRead:true,groupReadPersistent:true,momentReadPersistent:true,friendReadPersistent:true,accountIsolation:true});await page.close();}}
finally{fs.writeFileSync(path.join(out,baseline?'baseline.json':'verification.json'),JSON.stringify(reports,null,2));await browser.close();server.close();}console.log(JSON.stringify(reports,null,2));})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
