// Real settings UI and caught cohab failure, reload retention and clipboard fallback.
const {chromium,webkit}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),old=process.env.NORTH_DIAG_OLD;
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8');if(old&&['app.js','小手机.html'].includes(rel))return res.end(cp.execFileSync('git',['show',old+':'+rel],{cwd:root,maxBuffer:20e6}));fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
try{for(const engine of old?['edge']:['edge','webkit']){const browser=await(engine==='edge'?chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}):webkit.launch({headless:true}));try{for(const privateApp of old?[false]:[false,true]){
 const page=await browser.newPage({viewport:{width:390,height:844}});await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 const entry=origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home';await page.goto(entry);await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>_bootImagesPromise);
 await page.evaluate(()=>{const home=document.getElementById('homeDesktop');if(home)home.dispatchEvent(new MouseEvent('click',{bubbles:true}));S.me.locked=false;openSettings('data');closeModal();});
 assert.equal(await page.getByRole('button',{name:'浏览器运行诊断 · 复制记录'}).count(),1,'old version has no browser evidence entry');
 await page.evaluate(()=>{const actual=cohabAdvance;cohabAdvance=function recurseDiagnostic(){return recurseDiagnostic();};const r=cohabRoot();r.enabled=true;r.paused=false;try{cohabActionTap(null,'enter',S.contacts[0].id);}finally{cohabAdvance=actual;}});
 const evidence=await page.evaluate(()=>JSON.parse(NorthBrowserDiagnostics.report()));assert(evidence.current.lastHome.total>0);assert(evidence.current.events.some(x=>x.kind==='error'&&x.data.category==='stack-overflow'&&x.data.where==='cohab-enter'));
 await page.evaluate(()=>{const e=new Error('PRIVATE_CHAT sk-secret https://secret.invalid/?token=secret');e.stack='Error: PRIVATE_CHAT\n    at cohabAdvance (https://site.invalid/app.js?v=1239&token=secret:6967:45)';NorthBrowserDiagnostics.error('cohab-enter',e);for(let i=0;i<100;i++)NorthBrowserDiagnostics.mark('fixture-'+i);const img=new Image();img.src='idb:PRIVATE_IMAGE';document.body.appendChild(img);});
 await page.waitForTimeout(2300);let raw=await page.evaluate(()=>NorthBrowserDiagnostics.report());assert(!/PRIVATE_CHAT|PRIVATE_IMAGE|sk-secret|token=secret|secret.invalid/.test(raw));assert(JSON.parse(raw).current.events.length<=64);
 await page.reload();await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>_bootImagesPromise);const reloaded=await page.evaluate(()=>JSON.parse(NorthBrowserDiagnostics.report()));assert(reloaded.previous.events.some(x=>x.kind==='stage'&&x.data.name==='fixture-99'));
 await page.evaluate(()=>{S.me.locked=false;openSettings('data');closeModal();Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('denied'))}});});await page.getByRole('button',{name:'浏览器运行诊断 · 复制记录'}).click();await page.getByRole('button',{name:'复制诊断',exact:true}).click();await page.getByRole('button',{name:'请长按文本复制',exact:true}).waitFor();assert((await page.getByRole('textbox',{name:'浏览器运行诊断报告'}).inputValue()).includes('previous'));
 if(process.env.NORTH_DIAG_SCREENSHOT&&engine==='edge'&&!privateApp)await page.screenshot({path:process.env.NORTH_DIAG_SCREENSHOT});await page.getByRole('button',{name:'关闭',exact:true}).last().click();assert.equal(await page.locator('#north-browser-report').count(),0);
 console.log(JSON.stringify({engine,privateApp,caughtOverflow:true,reloadRetained:true,clipboardFallback:true,bounded:true,privacy:true}));await page.close();
}}finally{await browser.close();}}}finally{server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
