const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''),file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');const baseline=process.env.DIAGNOSTICS_BASELINE==='1'&&(name.endsWith('app.js')||name.endsWith('message-beijing-time.js'));res.end(baseline?cp.execFileSync('git',['show','9defbd8b:'+name],{cwd:root,maxBuffer:20*1024*1024}):fs.readFileSync(file));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
 try{for(const privateApp of [false,true]){
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
  await page.evaluate(()=>{S.me.locked=false;S.couple=null;const c=S.contacts[0];window.testId=c.id;c.spy={granted:true};c.proactive={enabled:false};S.me.lifeNotes=[{source:'manual',text:'已有笔记保持'}];S.settings.replyDelay=0;S.settings.chat={base:'https://fake.invalid/v1',key:'FIXTURE_PRIVATE_KEY',model:'fixture',maxTokens:9000,temp:.7};aiCoreOn=()=>false;window.fixtureBody='';window.testCalls=[];window.notices=[];fetchT=async(url,opt)=>{testCalls.push(JSON.parse(opt.body));return new Response(fixtureBody,{status:200,headers:{'content-type':'application/json','x-request-id':'browser-fixture'}});};toast=s=>notices.push(String(s));openChat(c.id);});
  for(const raw of [true,false])for(const [body,format] of [['','empty-body'],['data: {"choices":[]}\n\ndata: [DONE]','sse'],['<html>bad gateway</html>','invalid-json'],['{"choices":[{"message":{"content":""}}]}','empty-content']]){
   const got=await page.evaluate(async({raw,body})=>{S.settings.modelOutputUnfiltered=raw;fixtureBody=body;testCalls.length=0;S.messages[testId]=[{id:uid(),role:'user',type:'text',content:'陪我说说话',time:Date.now()}];await aiReply(testId);const rows=NorthRequestDiagnostics.list(testId);return{calls:testCalls.length,rows:rows.slice(0,5),shown:msgs(testId).filter(m=>m.role==='assistant').length,notes:S.me.lifeNotes[0].text,busy:replyGenerationBusy(testId,actId())};},{raw,body});
   assert.equal(got.shown,0);assert(got.rows.some(r=>r.kind==='request'&&r.format===format),JSON.stringify(got));assert(got.rows.some(r=>r.kind==='turn'&&r.state==='not-visible'),JSON.stringify(got));assert(!got.busy);assert.equal(got.notes,'已有笔记保持');console.log(JSON.stringify({privateApp,raw,format,recorded:true,calls:got.calls}));
  }
  const success=await page.evaluate(async()=>{S.settings.modelOutputUnfiltered=true;fixtureBody='{"choices":[{"message":{"content":"[内心|在听]\\n哦"}}]}';S.messages[testId]=[{id:uid(),role:'user',type:'text',content:'哦',time:Date.parse('2026-09-08T12:14:24Z')}];testCalls.length=0;await aiReply(testId);return{calls:testCalls.length,shown:msgs(testId).filter(m=>m.role==='assistant').length,rows:NorthRequestDiagnostics.list(testId).slice(0,2)};});assert.equal(success.calls,1);assert.equal(success.shown,1);assert(success.rows.some(r=>r.state==='handled'));
  const layout=await page.evaluate(()=>{S.settings.beijingMessageTimes=false;openChat(testId);const widths=()=>[...document.querySelectorAll('#chatbg .bubble')].map(el=>el.getBoundingClientRect().width);const before=widths();S.settings.beijingMessageTimes=true;openChat(testId);const after=widths(),labels=[...document.querySelectorAll('.beijing-message-time')].map(el=>el.textContent);return{before,after,labels,overflow:document.documentElement.scrollWidth>innerWidth};});assert.deepEqual(layout.before,layout.after);assert(layout.labels.length>=2);assert(layout.labels.every(s=>/^\d{2}:\d{2}:\d{2}$/.test(s)));assert(!layout.overflow);console.log(JSON.stringify({privateApp,shortTimestampLayout:layout}));await page.screenshot({path:path.join(root,'.qa',`request-diag-${privateApp?'private':'web'}-time.png`)});
  await page.evaluate(()=>roleChatDiagnosticOpen(testId));await page.getByRole('button',{name:'请求故障诊断 · 复制记录'}).click();assert(await page.getByRole('heading',{name:'请求故障诊断',exact:true}).isVisible());await page.getByRole('button',{name:'复制故障诊断',exact:true}).click();const report=await page.evaluate(()=>NorthRequestDiagnostics.report(testId));assert(!report.includes('FIXTURE_PRIVATE_KEY'));assert(!report.includes('已有笔记保持'));await page.screenshot({path:path.join(root,'.qa',`request-diag-${privateApp?'private':'web'}-panel.png`)});
  const saved=await page.evaluate(()=>({id:testId,count:NorthRequestDiagnostics.list(testId).length}));await page.reload();await page.waitForFunction(()=>window.__northBootReady);assert.equal(await page.evaluate(id=>NorthRequestDiagnostics.list(id).length,saved.id),saved.count);assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
