const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp/travel-home');
const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'}[path.extname(f)]||'application/octet-stream'));res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];
try{for(const priv of [false,true]){
const label=priv?'private':'web',p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[];
p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});
await p.goto(origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();localStorage.setItem('yibei_unlocked',String(SHARE_EPOCH));renderLockScreen();S.settings.sound=false;S.settings.deskPet={on:false};S.contacts.forEach(c=>c.proactive={enabled:false});S.me.balance=100000;tvInit().hotelSearch={city:'安吉',checkIn:todayStr(),nights:1,stars:0,roomType:'double',guestMode:'me',cid:'',results:null};window.oldOrderCount=tvInit().hotels.length;window.beforeOrders=JSON.stringify(tvInit().hotels);go('travel');});
await p.locator('[data-travel-action="hotel"]').click();assert(await p.locator('.cth-query').isVisible());assert.equal(await p.getByText('拍照出片',{exact:true}).count(),0);await p.screenshot({path:path.join(out,label+'-hotel.png')});
await p.locator('.cth-date-row').click();await p.locator('#cthCheckOut').fill(await p.evaluate(()=>todayStr()));await p.getByRole('button',{name:'确定日期',exact:true}).click();assert.equal(await p.locator('#modal.show').count(),1);await p.evaluate(()=>closeModal());
await p.locator('.cth-occupancy button').first().click();await p.locator('#cthAdults').selectOption('3');await p.getByRole('button',{name:'确定入住信息',exact:true}).click();assert.equal(await p.locator('#modal.show').count(),1);await p.locator('#cthRooms').selectOption('2');await p.getByRole('button',{name:'确定入住信息',exact:true}).click();
await p.locator('.cth-query-button').click();assert(await p.locator('.cth-list-app').isVisible());assert.equal(await p.locator('.cth-hotel-row').count(),20);assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.length>20));assert((await p.locator('.cth-list-guests').innerText()).includes('2间'));assert((await p.locator('.cth-list-guests').innerText()).includes('3成人'));assert.equal(await p.evaluate(()=>S.me.balance),100000);assert.equal(await p.evaluate(()=>JSON.stringify(tvInit().hotels)===beforeOrders),true);
for(const w of [320,390,430]){await p.setViewportSize({width:w,height:844});assert.equal(await p.locator('.cth-list-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.equal(await p.locator('.cth-list-app').evaluate(e=>e.scrollWidth>e.clientWidth),false);}await p.setViewportSize({width:390,height:844});
const total=await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items[0].total);await p.locator('.cth-book').first().click();assert.equal(await p.evaluate(()=>S.me.balance),100000-total);assert(await p.locator('.cth-refund').first().isVisible());assert.equal(await p.locator('.cth-book').first().isDisabled(),true);
await p.evaluate(()=>{NorthTravelHotel.book(0);tvHotelBook(0);});assert.equal(await p.evaluate(()=>S.me.balance),100000-total);assert.equal(await p.evaluate(()=>tvInit().hotels.length),await p.evaluate(()=>oldOrderCount+1));const h=await p.evaluate(()=>tvInit().hotels.at(-1));assert.equal(h.rooms,2);assert.equal(h.adults,3);assert.equal(h.price,total);assert.equal(h.accountId,await p.evaluate(()=>actId()));
await p.screenshot({path:path.join(out,label+'-hotel-results-booked.png')});await p.locator('.cth-refund').first().click();assert.equal(await p.evaluate(()=>S.me.balance),100000);await p.evaluate(()=>Promise.all([NorthTravelHotel.refund(0),tvHotelCancel(tvInit().hotels.at(-1).id,{direct:true})]));assert.equal(await p.evaluate(()=>S.me.balance),100000);assert.equal(await p.locator('.cth-refund').count(),0);assert.equal(await p.evaluate(()=>tvInit().hotels.at(-1).status),'cancelled');
await p.locator('.cth-book').first().click();assert.equal(await p.evaluate(()=>S.me.balance),100000-total);await p.getByRole('button',{name:'返回酒店查询',exact:true}).click();await p.locator('.cth-query-button').click();assert(await p.locator('.cth-refund').first().isVisible());await p.locator('.cth-refund').first().click();assert.equal(await p.evaluate(()=>S.me.balance),100000);
await p.evaluate(()=>{window.hotelHelpRequests=0;chatAPI=async()=>{window.hotelHelpRequests++;return JSON.stringify({explanation:'这个名称未在本地资料匹配，可能是自定义名称或拼写差异，未联网核实。住宿与报价均为模拟。',suggestions:[{label:'试试希尔顿',keyword:'希尔顿'}]});};});
await p.locator('#cthResultKeyword').fill('完全不存在的酒店');await p.getByRole('button',{name:'搜索酒店',exact:true}).click();await p.waitForFunction(()=>tvInit().hotelSearch.hotelQuotes.help?.status==='done');assert(await p.locator('.cth-search-help').isVisible());assert.equal(await p.evaluate(()=>window.hotelHelpRequests),1);assert(await p.locator('.cth-hotel-row').count()>0);assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.kind==='custom')));await p.screenshot({path:path.join(out,label+'-hotel-model-help.png')});await p.locator('#cthResultKeyword').fill('市中心');await p.getByRole('button',{name:'搜索酒店',exact:true}).click();assert.equal(await p.locator('.cth-hotel-row').count(),20);assert.equal(await p.locator('.cth-hotel-area').evaluateAll(es=>es.every(e=>e.textContent.includes('市中心'))),true);
// Real click captures the position after browser click auto-scroll, before booking redraw.
await p.evaluate(()=>{document.addEventListener('click',e=>{if(e.target.closest('.cth-book,.cth-refund'))window.hotelClickTop=document.querySelector('.cth-list-scroll').scrollTop;},true);document.querySelector('.cth-list-scroll').scrollTop=650;});
await p.locator('.cth-book').nth(3).click();assert((await p.evaluate(()=>window.hotelClickTop))>200);assert.equal(await p.locator('.cth-list-scroll').evaluate(e=>e.scrollTop),await p.evaluate(()=>window.hotelClickTop));await p.locator('.cth-refund').click();assert.equal(await p.locator('.cth-list-scroll').evaluate(e=>e.scrollTop),await p.evaluate(()=>window.hotelClickTop));
await p.locator('#cthResultKeyword').fill('');await p.getByRole('button',{name:'搜索酒店',exact:true}).click();await p.getByLabel('酒店排序',{exact:true}).selectOption('priceDesc');assert.equal(await p.evaluate(()=>{const a=tvInit().hotelSearch.hotelQuotes.items;return a.every((x,i)=>!i||a[i-1].unit>=x.unit);}),true);
await p.locator('.cth-list-filters').getByRole('button',{name:'价格 / 星级',exact:false}).click();await p.locator('#cthStars').selectOption('4');await p.locator('#cthPrice').fill('500');await p.getByRole('button',{name:'确定筛选',exact:true}).click();assert.equal(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.stars===4&&x.unit<=500)),true);assert(await p.locator('.cth-hotel-row').count()>0);
await p.locator('.cth-list-tags').getByText('可携带宠物',{exact:true}).click();assert.equal(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.features.includes('可携带宠物'))),true);
await p.locator('.cth-list-filters').getByRole('button',{name:'位置',exact:false}).click();await p.locator('#cthArea').selectOption('景区周边');await p.getByRole('button',{name:'确定位置',exact:true}).click();assert.equal(await p.locator('.cth-hotel-row').count(),0);
await p.evaluate(()=>{NorthTravelHotel.change('hotelArea','');NorthTravelHotel.change('stars',0);NorthTravelHotel.change('maxPrice',0);NorthTravelHotel.change('preferredTags',[]);NorthTravelHotel.query();});await p.screenshot({path:path.join(out,label+'-hotel-results.png')});
// Country-wide custom-name scenario from the user screenshot, plus local-brand aliases.
await p.evaluate(()=>{Object.assign(tvInit().hotelSearch,{city:'美国',keyword:'Claude',stars:0,maxPrice:0,hotelArea:'',preferredTags:['含早餐'],nights:2});NorthTravelHotel.queryPage();NorthTravelHotel.query();});
assert.equal(await p.evaluate(()=>tvInit().hotelSearch.category),'overseas');assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.kind==='custom'&&x.country==='美国'&&x.features.includes('含早餐'))));assert(await p.locator('.cth-hotel-row').count()<=20);assert((await p.locator('.cth-hotel-area').first().innerText()).includes('自定义模拟住宿'));
await p.getByRole('button',{name:'下一页',exact:true}).click();assert(await p.locator('.cth-hotel-row').count()<=20);const index=20,price=await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items[20].total),balance=await p.evaluate(()=>S.me.balance);await p.locator('.cth-book').first().click();assert.equal(await p.evaluate(()=>S.me.balance),balance-price);await p.locator('.cth-refund').first().click();assert.equal(await p.evaluate(()=>S.me.balance),balance);await p.screenshot({path:path.join(out,label+'-us-claude.png')});
await p.locator('#cthResultKeyword').fill('Hilton Hotel');await p.getByRole('button',{name:'搜索酒店',exact:true}).click();assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.length>0));assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.kind==='brand')));
await p.evaluate(()=>{Object.assign(tvInit().hotelSearch,{city:'上海',keyword:'全季酒店',preferredTags:[]});NorthTravelHotel.queryPage();NorthTravelHotel.query();});assert(await p.evaluate(()=>tvInit().hotelSearch.hotelQuotes.items.every(x=>x.brand==='全季')));assert(await p.locator('.cth-hotel-row').count()>0);
// Insufficient balance cannot create an order or deduct anything.
await p.evaluate(()=>{window.orderCount=tvInit().hotels.length;S.me.balance=1;NorthTravelHotel.book(0);});assert.equal(await p.evaluate(()=>S.me.balance),1);assert.equal(await p.evaluate(()=>tvInit().hotels.length===orderCount),true);await p.evaluate(()=>{S.me.balance=100000;});
// New order page uses existing paid orders, preserves original dates and refund amount.
await p.locator('.cth-book').first().click();const paidOrder=await p.evaluate(()=>({...tvInit().hotels.at(-1)})),paidBalance=await p.evaluate(()=>S.me.balance);await p.evaluate(()=>NorthTravelHotel.orders());assert(await p.locator('.cth-orders-app').isVisible());assert((await p.locator('.cth-orders-app').innerText()).includes(paidOrder.checkIn));assert((await p.locator('.cth-orders-app').innerText()).includes(paidOrder.price.toFixed(2)));await p.screenshot({path:path.join(out,label+'-hotel-orders.png')});
await p.evaluate(()=>{const t=tvInit(),h=t.hotels.at(-1);window.testPaidId=h.id;for(let i=0;i<24;i++)t.hotels.push({...h,id:'order-scroll-fixture-'+i,no:'TEST'+i,status:'cancelled',ts:i<3?h.ts+10000+i:h.ts-1000-i});t.hotels.push({...h,id:'other-account-fixture',hotelName:'OTHER_ACCOUNT_HOTEL',accountId:'other'});NorthTravelHotel.orders();document.querySelector('.cth-list-scroll').scrollTop=700;});assert.equal(await p.getByText('OTHER_ACCOUNT_HOTEL',{exact:false}).count(),0);assert.equal(await p.locator('.cth-hotel-row').count(),20);await p.locator('.cth-book').click();assert.equal(await p.evaluate(()=>S.me.balance),paidBalance+paidOrder.price);assert.equal(await p.locator('.cth-list-scroll').evaluate(e=>e.scrollTop),await p.evaluate(()=>window.hotelClickTop));await p.evaluate(()=>NorthTravelHotel.refundOrder(3));assert.equal(await p.evaluate(()=>S.me.balance),paidBalance+paidOrder.price);await p.getByRole('button',{name:'下一页',exact:true}).click();assert(await p.locator('.cth-hotel-row').count()<=20);await p.getByRole('button',{name:'返回酒店查询',exact:true}).click();assert(await p.locator('.cth-query').isVisible());
// An ordinary shopping list redraw retains its position without changing other routes.
await p.evaluate(()=>{S.shop.results=Array.from({length:35},(_,i)=>({name:'测试商品'+i,price:30,emoji:'🛍️'}));go('shop');});await p.locator('.shop-scroll').evaluate(e=>e.scrollTop=600);await p.evaluate(()=>render());assert.equal(await p.locator('.shop-scroll').evaluate(e=>e.scrollTop),600);
// Normal chat entry with existing archives and phone-check authorization; model output is a fixture.
const roleResult=await p.evaluate(async()=>{const c=S.contacts[0];window.hotelRoleTestId=c.id;c.proactive={enabled:false};c.wallet=50000;c.blocked=false;c.spy={...(c.spy||{}),granted:true,loc:true};S.couple={cid:c.id,wxLoginAuth:true,remoteControlAuth:true};S.spy=S.spy||{};S.spy[c.id]={...(S.spy[c.id]||{}),balance:50000,wallet:[{item:'已有银行记录',amount:100,when:todayStr()}]};S.me.balance=100000;S.me.lifeNotes=[{roleId:c.id,accountId:'main',text:'已有授权后的小事记录',ts:Date.now()}];S.settings.replyDelay=0;S.settings.chat={base:'https://fixture.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};gateOK=()=>true;aiCoreOn=()=>false;window.hotelRolePrompts=[];chatAPI=async(messages)=>{hotelRolePrompts.push(messages.map(x=>String(x.content||'')).join('\n'));return '我来安排。\n[订酒店|上海|'+todayStr()+'|2|4|双人间|我们一起|全季|2|3|1]';};Object.assign(tvInit().hotelSearch,{city:'上海',keyword:'全季',checkIn:todayStr(),nights:2,stars:4,roomType:'double',rooms:2,adults:3,children:1,guestMode:'together',cid:c.id,maxPrice:600,preferredTags:['含早餐'],hotelArea:''});const count=tvInit().hotels.length;msgs(c.id).push({id:uid(),role:'user',type:'text',content:'请按刚才的条件，给我们订上海全季酒店，两间房三位成人一位儿童，住两晚。',time:Date.now()});openChat(c.id);await aiReply(c.id);const h=tvInit().hotels.at(-1);if(tvInit().hotels.length!==count+1)throw Error('normal chat did not book hotel');if(h.rooms!==2||h.adults!==3||h.children!==1||h.payer!=='ta'||h.accountId!==actId())throw Error('role order lost query details');if(c.wallet!==50000-h.price||S.me.balance!==100000)throw Error('wrong hotel payer');if(!msgs(c.id).some(m=>m.type==='hotel'&&m.hotel.id===h.id))throw Error('hotel chat card missing');window.hotelRoleOrderId=h.id;return {id:h.id,price:h.price,role:c.id};});
assert(await p.locator('.cth-chat-hotel').isVisible());assert((await p.locator('.cth-chat-hotel').innerText()).includes('3成人'));await p.waitForFunction(()=>!document.querySelector('.toast')||getComputedStyle(document.querySelector('.toast')).display==='none',{},{timeout:5000}).catch(()=>{});await p.screenshot({path:path.join(out,label+'-hotel-chat-card.png'),animations:'disabled'});await p.locator('.cth-chat-hotel').click();assert(await p.locator('.cth-dialog').isVisible());assert((await p.locator('.cth-dialog').innerText()).includes(roleResult.price.toFixed(2)));await p.evaluate(()=>closeModal());
await p.evaluate(async()=>{const c=getC(hotelRoleTestId),h=tvInit().hotels.find(h=>h.id===hotelRoleOrderId);msgs(c.id).filter(m=>m.type==='hotel').forEach(m=>m.hotel=JSON.parse(JSON.stringify(m.hotel)));c.blocked=true;await tvHotelCancel(h.id,{direct:true});c.blocked=false;if(c.wallet!==50000||S.me.balance!==100000)throw Error('role refund wrong funding account');const prompt=buildSystem(c);if(!prompt.includes(h.hotelName)||!prompt.includes('已取消')||!prompt.includes('3成人'))throw Error('role cannot query current order facts');chatAPI=async(messages)=>{const request=messages.map(x=>String(x.content||'')).join('\n');if(!request.includes('已取消'))throw Error('chat request lost cancelled order');return '这笔酒店订单已经退订了，费用退回我的银行了。';};msgs(c.id).push({id:uid(),role:'user',type:'text',content:'我们刚才那笔酒店订单现在是什么状态？',time:Date.now()});await aiReply(c.id);if(!msgs(c.id).some(m=>m.role==='assistant'&&m.content?.includes('已经退订')))throw Error('order query reply missing');S.me.active='hotel-other-account';if(tvHotelVisibleToRole(h,c.id))throw Error('role order leaked across account');S.me.active='main';render();});assert((await p.locator('.cth-chat-hotel').innerText()).includes('已取消'));
assert.deepEqual(errors,[]);reports.push({runtime:label,resultPageSeparate:true,localCatalogue:true,modelHelpWithMockedResponse:true,bookingAndRefundScrollPreserved:true,whiteBlueOrders:true,orderAccountIsolation:true,shoppingScrollPreserved:true,customNameCountrySearch:true,paginationMax20:true,queryConditionsInherited:true,keywordPriceStarsAndPreferences:true,widths:[320,390,430],oneTapBooking:true,doubleBookingPrevented:true,roomTotalCorrect:true,refundOriginalAmount:true,doubleRefundPrevented:true,bookingSurvivesReturn:true,insufficientFundsSafe:true,ordersPreserved:true,pageErrors:errors});await p.close();
}console.log(JSON.stringify(reports));fs.writeFileSync(path.join(out,'hotel-result.json'),JSON.stringify(reports,null,2));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
