const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex_tmp/travel-home');
const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg'}[path.extname(f)]||'application/octet-stream'));res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];
try{for(const priv of [false,true]){
const label=priv?'private':'web',p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[];
p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(r.request().url().includes('api.bigdatacloud.net'))return r.fulfill({json:{city:'苏州市',locality:'相城区',principalSubdivision:'江苏省',countryName:'中国',countryCode:'CN'}});return new URL(r.request().url()).origin===origin?r.continue():r.abort();});
if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});
await p.goto(origin+(priv?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();localStorage.setItem('yibei_unlocked',String(SHARE_EPOCH));renderLockScreen();S.settings.sound=false;S.settings.deskPet={on:false};S.contacts.forEach(c=>c.proactive={enabled:false});S.me.balance=100000;tvInit().hotelSearch={city:'安吉',checkIn:todayStr(),nights:1,stars:0,roomType:'double',guestMode:'me',cid:'',results:null};window.oldOrderCount=tvInit().hotels.length;window.beforeOrders=JSON.stringify(tvInit().hotels);go('travel');});
await p.locator('[data-travel-action="guide"]').click();await p.evaluate(()=>NorthTravelRegions.open());assert(await p.locator('.ctd-app').isVisible());
const counts=await p.evaluate(()=>{const list=NorthTravelRegions.catalogue();const countries=NorthHotelData.countries;for(const c of countries)if(!list.some(x=>x.name===c[0]||x.country===c[0]))throw Error('missing country '+c[0]);for(const c of NorthHotelData.cities())if(!list.some(x=>x.name===c.name))throw Error('missing city '+c.name);return {cities:NorthHotelData.cities().length,countries:countries.length};});
await p.locator('#ctdSearch').fill('美国');assert(await p.locator('[data-destination="美国"]').isVisible());assert(await p.locator('[data-region-tab="overseas"]').evaluate(e=>e.classList.contains('selected')));await p.locator('[data-destination="美国"]').click();assert.equal(await p.evaluate(()=>NorthTravelRegions.selected().name),'美国');await p.evaluate(()=>NorthTravelRegions.open());await p.getByRole('button',{name:'境内 · 港澳台',exact:true}).click();
await p.locator('#ctdSearch').fill('上海');await p.locator('[data-destination="上海"]').last().click();assert.equal(await p.evaluate(()=>NorthTravelRegions.selected().name),'上海');await p.evaluate(()=>NorthTravelRegions.open());assert(await p.locator('.ctd-history-tags').isVisible());
await p.getByRole('button',{name:'境外',exact:true}).click();await p.locator('[data-category="非洲"]').click();assert((await p.locator('.ctd-grid').innerText()).includes('开罗'));await p.locator('[data-category="南美洲"]').click();assert((await p.locator('.ctd-grid').innerText()).includes('里约热内卢'));
await p.locator('#ctdSearch').fill('Paris');await p.locator('[data-destination="巴黎"]').click();assert.equal(await p.evaluate(()=>NorthTravelRegions.selected().name),'巴黎');await p.evaluate(()=>NorthTravelRegions.open());await p.locator('#ctdSearch').fill('United States');assert((await p.locator('.ctd-grid').innerText()).includes('美国'));await p.locator('#ctdSearch').fill('');await p.locator('[data-category="推荐"]').click();await p.screenshot({path:path.join(out,label+'-regions-overseas.png')});
await p.getByRole('button',{name:'境内 · 港澳台',exact:true}).click();await p.locator('[data-category="港澳台"]').click();assert((await p.locator('.ctd-grid').innerText()).includes('香港'));assert((await p.locator('.ctd-grid').innerText()).includes('澳门'));await p.locator('[data-category="推荐"]').click();await p.locator('#ctdSearch').fill('浙江');assert((await p.locator('.ctd-grid').innerText()).includes('杭州'));await p.locator('#ctdSearch').fill('');await p.screenshot({path:path.join(out,label+'-regions-domestic-default.png')});
await p.evaluate(()=>{window.geoCalls=0;window.geoMode='deny';Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition(ok,fail,options){geoCalls++;if(options.maximumAge!==0)throw Error('stale GPS allowed');if(geoMode==='deny')fail({code:1});else ok({coords:{latitude:31.31,longitude:120.62,accuracy:25}});}}});if(window.SmallPhoneNative)SmallPhoneNative.request=async()=>({latitude:31.31,longitude:120.62,accuracy:25,timestamp:Date.now()-86400000});});
await p.locator('.ctd-refresh').click();await p.waitForFunction(()=>document.querySelector('.ctd-location').innerText.includes('未授权定位'));assert(!(await p.locator('.ctd-location').innerText()).includes('苏州'));await p.evaluate(()=>geoMode='ok');await p.locator('.ctd-refresh').click();await p.waitForFunction(()=>document.querySelector('.ctd-location').innerText.includes('苏州'));assert((await p.locator('.ctd-location').innerText()).includes('25米'));assert.equal(await p.evaluate(()=>geoCalls),2);await p.screenshot({path:path.join(out,label+'-regions-domestic.png')});await p.evaluate(()=>NorthTravelRegions.chooseCurrent());assert.equal(await p.evaluate(()=>NorthTravelRegions.selected().name),'苏州');
await p.evaluate(()=>NorthTravelRegions.open());await p.getByRole('button',{name:/清除历史/}).click();assert.equal(await p.locator('.ctd-history-tags').count(),0);
await p.locator('#ctdSearch').fill('<img onerror=alert(1)>');assert.equal(await p.locator('.ctd-card').count(),0);await p.locator('#ctdSearch').fill('北京');assert(await p.locator('[data-destination="北京"]').isVisible());await p.locator('#ctdSearch').fill('');
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert(await p.locator('.ctd-app').evaluate(e=>e.scrollWidth<=e.clientWidth));await p.locator('#ctdBody').evaluate(e=>e.scrollTop=200);assert(await p.locator('#ctdBody').evaluate(e=>e.scrollTop>0));}
await p.evaluate(()=>{window.beforeRegionAccount=actId();S.me.active='region-test-alt';});assert.equal(await p.evaluate(()=>NorthTravelRegions.selected().name),'上海');await p.evaluate(()=>S.me.active=beforeRegionAccount);
await p.evaluate(()=>{for(const c of NorthHotelData.countries){NorthTravelRegions.choose(c[0]);if(NorthTravelRegions.selected().name!==c[0])throw Error('selection failed '+c[0]);if(NorthTravelRegions.selected().name!==c[0])throw Error('render failed '+c[0]);}NorthTravelRegions.choose('日本');});await p.evaluate(()=>NorthTravelRegions.open());await p.locator('[data-category="国家／地区"]').click();assert.equal(await p.locator('.ctd-card').count(),42);
assert.deepEqual(errors,[]);reports.push({runtime:label,...counts,allCountrySelections:true,crossTabCountrySearch:true,allExistingDestinations:true,searchAliases:true,domesticOverseas:true,provinceContinentGroups:true,historyClear:true,accountIsolation:true,gpsPermissionFailure:true,gpsSuccessMocked:true,staleNativeGPSRejected:true,widths:[320,390,430],pageErrors:errors});await p.close();}
console.log(JSON.stringify(reports));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
