// Actual entrypoints and render overlays; isolate every external request and native operation.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const p=path.resolve(root,decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,''));if(!p.startsWith(root+path.sep)||!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(p)]||'application/octet-stream')+'; charset=utf-8');res.end(fs.readFileSync(p));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
try{for(const privateApp of [false,true]){const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],loaded=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>loaded.push(r.url()));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
if(privateApp)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,message:'isolated native fixture'})};});
await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
await page.evaluate(()=>{S.me.locked=false;S.me.active='main';S.couple={cid:S.contacts[0].id};go('wxsmarthome');});
if(privateApp){await page.getByRole('button').filter({hasText:'卧室小灯'}).first().waitFor();const menu=await page.locator('.private-smart-home-choices').innerText();assert(menu.includes('卧室小灯')&&menu.includes('家庭门锁')&&menu.includes('卧室空调'),menu);
for(const [label,device] of [['卧室小灯','light'],['家庭门锁','lock'],['卧室空调','air']]){await page.evaluate(()=>go('wxsmarthome'));await page.getByRole('button').filter({hasText:label}).first().click();assert.equal(await page.evaluate(()=>cur().device),device);assert((await page.locator('#app').innerText()).length>20);}
const air=await page.locator('.private-air-page').innerText();assert(air.includes('读取苹果家庭空调'));assert(loaded.some(u=>u.endsWith('private-smart-air.js?v=1223')));console.log(JSON.stringify({privateApp,light:true,lock:true,air:true,latestAirResource:true}));
}else{assert(!loaded.some(u=>/private-smart-(air|lock)/.test(u)));assert.equal(await page.evaluate(()=>typeof window.privateSmartAirChooserCard),'undefined');console.log(JSON.stringify({privateApp,noPrivateHomeRuntime:true}));}
assert.deepEqual(errors,[]);await page.close();}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
