// Actual web/private runtimes; network/model responses are fixtures only.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.EIGHT_OUT||path.join(root,'.codex_tmp','eight-chat');
const baseline=process.env.BASELINE==='1';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});const reports=[];
try{for(const privateApp of [false,true]){const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}),errors=[];page.on('pageerror',e=>errors.push(e.message));
if(privateApp)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});
await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
await page.evaluate(()=>{S.me.locked=false;S.me.active='main';S.me.name='North';S.settings.sound=false;S.contacts.forEach(c=>{c.proactive={enabled:false};});const a=S.contacts[0],b=S.contacts[1];a.name='克罗德';a.remark='克罗德';b.name='克劳德';b.remark='克劳德';S.couple={cid:b.id};S.groups=[{id:'eight_group',name:'日常聊天',members:[a.id,b.id],msgs:[]}];window.eightA=a.id;window.eightB=b.id;});
const probe=await page.evaluate(()=>{const g=S.groups[0],a=getC(eightA),b=getC(eightB),long='群里说话注意分寸。'.repeat(30)+'这是引用原文末尾';
const off=modelUnfilteredOfflineItems('嗯？\n已在本轮完成，不再重复。');
S.me.lockNotes=[];lockNotify('先生＾＾','[保持安静]',{target:{type:'chat',id:a.id}});const quietStored=S.me.lockNotes.some(n=>n.body.includes('保持安静'));S.me.lockNotes=[];
const red={id:'eight_red',senderId:a.id,type:'redpacket',amount:52,note:'给North的专属红包',count:1,splits:[52],grabs:[],time:Date.now()};g.msgs=[red];const stolen=!!gRpTake(g,red,b.id);
const recent=[{senderId:'me',type:'text',content:long},{senderId:a.id,type:'text',content:long}];const mine=gParseReply('[引用|1]\n知道了。',4,recent,g),other=gParseReply('[引用|2]\n知道了。',4,recent,g);const bar=groupQuoteBar(other[0]&&other[0].q);
const transfer={id:'eight_transfer',senderId:a.id,type:'transfer',amount:18,note:'晚饭',to:'me',time:Date.now()};g.msgs=[transfer];const card=gbubble(g,transfer);
return{offlineControlBlocked:!off.some(x=>x.text.includes('本轮完成')),quietBlocked:!quietStored,exclusiveProtected:!stolen,userQuoteOmitted:!mine.some(x=>x.q),roleQuoteFull:bar.includes('这是引用原文末尾'),transferDetail:card.includes('openGroupTransferDetail'),unreadAvailable:typeof wxUnreadTotal==='function'};});
const prefix=privateApp?'private':'web';reports.push({runtime:prefix,...probe});console.log(JSON.stringify(reports[reports.length-1]));
if(baseline){await page.close();continue;}Object.entries(probe).forEach(([k,v])=>assert(v,prefix+' '+k));
// Deterministic recipient checks, no balance mutation on opening transfer.
await page.evaluate(()=>{const g=S.groups[0];g.msgs=[{id:'eight_transfer',senderId:eightA,type:'transfer',amount:18,note:'晚饭',to:'me',time:Date.now()}];go('group',{id:g.id});window.eightBalance=S.me.balance;});
await page.locator('.wx-transfer-card').click();assert.equal(await page.evaluate(()=>cur().p),'groupTransferDetail');assert.equal(await page.evaluate(()=>S.me.balance),await page.evaluate(()=>eightBalance));await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-transfer-pending.png')});
await page.locator('.wx-transfer-actions>button').click();assert.equal(await page.evaluate(()=>S.me.balance),await page.evaluate(()=>eightBalance+18));await page.evaluate(()=>groupTransferDetailAction('eight_group','eight_transfer'));assert.equal(await page.evaluate(()=>S.me.balance),await page.evaluate(()=>eightBalance+18));await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-transfer-received.png')});
await page.evaluate(()=>{const g=S.groups[0],long='群里说话注意分寸。'.repeat(15)+'这是引用原文末尾';g.msgs=[{id:'q1',senderId:eightA,type:'text',content:long,time:Date.now()},{id:'q2',senderId:eightB,type:'text',content:'知道了。',q:{who:'克罗德',senderId:eightA,text:long},time:Date.now()+1}];go('group',{id:g.id});});
const quote=page.locator('.chat-quote-sent');assert((await quote.innerText()).includes('这是引用原文末尾'));assert.equal(await quote.evaluate(e=>e.scrollHeight<=e.clientHeight+1),true);await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-full-quote.png')});
await page.evaluate(()=>{const now=Date.now();S.groups=[];S.messages={};S.messages[eightA]=Array.from({length:4},(_,i)=>({id:'u'+i,role:'assistant',type:'text',content:i?'晚上一起吃什么？':'到家记得告诉我。',time:now+i}));S.messages[eightB]=[{id:'ub',role:'assistant',type:'text',content:'在等你。',time:now}];S.moments=[{id:'eight_moment',authorId:eightA,text:'今天做了一顿好吃的。',time:now,acct:'main',likes:[],comments:[]}];S.me._wxMomentSeen={};wxTab='chats';go('wechat');});
assert.equal(await page.evaluate(()=>wxUnreadTotal()),5);assert.equal(await page.locator('.wx-chat-row').first().locator('.wx-unread-badge').innerText(),'4');await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-unread-list.png')});
await page.locator('.wx-chat-row').first().click();assert.equal(await page.evaluate(()=>wxUnreadTotal()),1);await page.evaluate(()=>wxTab='chats');await page.evaluate(()=>go('wechat'));assert.equal(await page.locator('.tabbar .wx-unread-badge').innerText(),'1');
await page.evaluate(()=>wxTab='moments');await page.evaluate(()=>render());assert(await page.locator('.wx-discover-row.tone-moments .wx-unread-dot').count());await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-moments-dot.png')});await page.locator('.wx-discover-row.tone-moments').click();await page.evaluate(()=>back());assert.equal(await page.locator('.wx-discover-row.tone-moments .wx-unread-dot').count(),0);
// Alternate identities must not inherit the main account's unread messages.
const isolated=await page.evaluate(()=>{const old=actId();S.me.active='eight_alt';const n=wxUnreadTotal();S.me.active=old;return n;});assert.equal(isolated,0);
// Real UI rendering after protocol processing; sample conversations are fixtures.
await page.evaluate(()=>{S.me.locked=false;const o=offData(eightA);o.started=true;o.introSeen=true;o.loc='家里';o.when='今晚';o.msgs=[{id:'o1',who:'me',source:'me',text:'晚饭吃什么？',time:Date.now()-1000},...modelUnfilteredOfflineItems('嗯？\n已在本轮完成，不再重复。\n一起做个番茄鸡蛋面吧。').map(x=>({...x,time:Date.now()}))];_off={id:eightA,mode:'date',busy:false};go('off',{id:eightA});});
assert(!(await page.locator('#offbg').innerText()).includes('本轮完成'));await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-offline-clean.png')});
await page.evaluate(()=>{_off=null;S.me.locked=true;S.me.lockNotes=[];lockNotify('先生＾＾','宝宝，凌晨两点了还没睡？',{target:{type:'chat',id:eightA}});lockNotify('先生＾＾','[保持安静]',{target:{type:'chat',id:eightA}});renderLockScreen(true);});
assert(!(await page.locator('#lockScreen').innerText()).includes('保持安静'));await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-notifications-clean.png')});await page.evaluate(()=>lockOpen());await page.waitForTimeout(500);
await page.evaluate(()=>{S.groups=[{id:'eight_group',name:'日常聊天',members:[eightA,eightB],msgs:[{id:'eight_red',senderId:eightA,type:'redpacket',amount:52,note:'给North的专属红包',count:1,splits:[52],grabs:[],time:Date.now()}]}];const g=S.groups[0];if(gRpTake(g,g.msgs[0],eightB))throw Error('exclusive stolen');go('group',{id:g.id});redpOpen('group',g.id,'eight_red');});await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-exclusive-packet.png')});await page.evaluate(()=>rpOverlayClose());
await page.evaluate(()=>{const g=S.groups[0];g.msgs=[{id:'meq',senderId:'me',type:'text',content:'群里说话注意分寸，好好称呼大家。',time:Date.now()-1000},{id:'reply',senderId:eightB,type:'text',content:'知道了。',q:{who:'North',senderId:'me',text:'群里说话注意分寸。'},time:Date.now()}];go('group',{id:g.id});});assert.equal(await page.locator('.chat-quote-sent').count(),0);await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-user-reply-no-quote.png')});
await page.evaluate(async()=>{dyInit();S.dy.dms=[];S.dy.mine=[];window.eightPrompts=[];const original=chatAPI;chatAPI=async(messages)=>{eightPrompts.push(messages);return JSON.stringify([{name:'慢半拍',text:'最近有没有一首歌会单曲循环？'},{name:'猫尾巴',text:'我刚把煎蛋翻到锅外了，你厨艺怎么样哈哈'},{name:'旧车票',text:'想找人交换书单，你愿意推荐一本吗？'}]);};go('dy');_dySub='strangers';await dyGenDMs();chatAPI=original;if(S.dy.dms.length!==3||new Set(S.dy.dms.map(x=>x.persona)).size!==3)throw Error('stranger diversity');});await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-strangers.png')});
const transport=await page.evaluate(async()=>{const original=fetchT,calls=[];_pfTransportRoute='';_pfTransportAt=0;_pfTransportProbe=null;fetchT=async(url,opt)=>{calls.push({url,args:JSON.parse(opt.body)});if(url.startsWith(GATE_URL))throw Error('fixture direct blocked');return new Response(JSON.stringify(url.endsWith('phone_friend_search')?[]:{id:'fixture-confirmed'}));};try{await pfRpc('phone_friend_send_message',{p_body:'fixture message'});return calls.filter(x=>x.url.endsWith('phone_friend_send_message')).length===1&&calls[0].args.p_query===''&&calls[1].args.p_query==='';}finally{fetchT=original;_pfTransportRoute='';_pfTransportAt=0;}});assert(transport);reports[reports.length-1].friendFallbackOneWrite=true;reports[reports.length-1].strangersDistinct=true;
await page.evaluate(async()=>{const original=fetchT;window.eightFetchOriginal=original;window.eightSyncBusy=_pfSyncBusy;_pfSyncBusy=true;const p=phoneFriendState();p.id='FIXTURE_SELF';p._onlineAt=Date.now();_pfTransportRoute='';_pfTransportAt=0;fetchT=async(url,opt)=>{if(url.startsWith(GATE_URL))throw Error('fixture direct blocked');const args=JSON.parse(opt.body||'{}');return new Response(JSON.stringify(args.p_query?[{phone_id:'FIXTURE_OTHER',display_name:'测试好友（模拟网络）',avatar:'🙂'}]:[]));};go('pffriends');await phoneFriendSearch('FIXTURE_OTHER');});assert((await page.locator('#app').innerText()).includes('测试好友（模拟网络）'));await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-friend-search-simulated.png')});await page.evaluate(()=>{fetchT=eightFetchOriginal;_pfSyncBusy=eightSyncBusy;_pfTransportRoute='';});
const walletUncertain=await page.evaluate(async()=>{const originalEnsure=pfEnsure,originalFetch=fetchT;pfEnsure=async()=>true;_pfTransportRoute=PF_RELAY_BASE;_pfTransportAt=Date.now();const before=S.me.balance;try{fetchT=async()=>new Response('{}',{status:502});await sendPhoneFriendBody('FIXTURE_FRIEND','测试待确认转账',{silent:true,bill:{amount:18,note:'测试转账'}});if(S.me.balance!==before-18)return false;fetchT=async()=>new Response('{"message":"denied"}',{status:401});await sendPhoneFriendBody('FIXTURE_FRIEND','测试明确拒绝转账',{silent:true,bill:{amount:18,note:'测试转账'}});return S.me.balance===before-18;}finally{pfEnsure=originalEnsure;fetchT=originalFetch;_pfTransportRoute='';}});assert(walletUncertain);reports[reports.length-1].ambiguousWalletProtected=true;
// Private visible inheritance uses the real entry, saved role routing and rendering.
if(privateApp){const inherited=await page.evaluate(()=>{const a=getC(eightA),b=getC(eightB);S.settings.chatRouteActive=1;S.settings.chatRoutes=[{base:'https://fixture.invalid/v1',key:'fixture',model:'one',aux:{model:'one-aux'}},{base:'https://fixture.invalid/v1',key:'fixture',model:'two',aux:{model:'two-aux'}}];b.chatRouteIndex=0;roleChatRouteSet(a.id,0);const independent=roleChatRouteIndex(a)===0&&roleChatRouteIndex(b)===0;roleChatRouteSet(a.id,'default');const follow=roleChatRouteIndex(a)===1&&roleChatRouteIndex(b)===0;closeModal();S.settings.roleMomentImages=false;postRoleMoment(a,'这是只发文字的继承验收',{images:['fixture-image'],photoCards:[]});const moment=S.moments[0],noImage=moment.images.length===0&&moment.photoCards.length===0;S.settings.roleMomentImages=true;const source='I will wait here for you.',m={id:'inherited-translation',role:'assistant',type:'text',content:source,textTrans:'我会在这里等你。',textTransSource:source,_textTransState:'done',time:Date.now()};msgs(a.id).push(m);go('chat',{id:a.id});return{independent,follow,noImage,translation:document.querySelector('.role-text-trans')?.textContent.includes('我会在这里等你。')};});Object.entries(inherited).forEach(([k,v])=>assert(v,'private visible inheritance '+k));await page.screenshot({animations:'disabled',path:path.join(out,'private-inherited-translation.png')});await page.evaluate(()=>roleChatDiagnosticOpen(eightA));await page.screenshot({animations:'disabled',path:path.join(out,'private-inherited-route.png')});await page.evaluate(()=>closeModal());reports[reports.length-1].privateVisibleInheritance=inherited;}
// Persist seen state, then test new arrivals and two small/large light layouts.
await page.evaluate(async()=>{S.me.locked=false;S.groups=[];S.messages={};S.messages[eightA]=[{id:'persist-seen',role:'assistant',type:'text',content:'看完记得休息。',time:Date.now()}];go('chat',{id:eightA});go('wxmoment');if(!await saveNowAsync())throw Error('fixture save');});await page.goto(page.url().split('?')[0]);await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>{S.me.locked=false;renderLockScreen();});
assert.equal(await page.evaluate(()=>wxUnreadTotal()),0);assert.equal(await page.evaluate(()=>wxMomentUnread()),false);
const late=await page.evaluate(()=>{const id=S.contacts[0].id;go('chat',{id});msgs(id).push({id:'visible-arrival',role:'assistant',type:'text',content:'晚安。',time:Date.now()});render();return wxUnreadTotal();});assert.equal(late,0);
await page.evaluate(()=>{const id=S.contacts[0].id;go('wechat');msgs(id).push({id:'unseen-arrival',role:'assistant',type:'text',content:'明天见。',time:Date.now()});S.me.wxTheme='white';wxTab='chats';render();});assert.equal(await page.evaluate(()=>wxUnreadTotal()),1);
for(const width of [320,430]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({animations:'disabled',path:path.join(out,prefix+'-unread-light-'+width+'.png')});}reports[reports.length-1].seenPersistence=true;reports[reports.length-1].activeArrivalsRead=true;
assert.deepEqual(errors,[]);await page.close();}}
finally{fs.writeFileSync(path.join(out,baseline?'baseline.json':'verification.json'),JSON.stringify(reports,null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
