const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\/+/,''),file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');const baseline=process.env.LOCK_BASELINE==='1'&&(name.endsWith('app.js')||name.endsWith('.html'));res.end(baseline?cp.execFileSync('git',['show','HEAD:'+name],{cwd:root,maxBuffer:32*1024*1024}):fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
try{for(const privateApp of [false,true]){const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);await page.evaluate(()=>{go('home');window.lockCancels=0;document.addEventListener('pointercancel',()=>lockCancels++);});const cdp=await page.context().newCDPSession(page);
const touch=async(type,x,y)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y}]});
const show=async()=>{await page.evaluate(()=>lockShow());await page.waitForTimeout(750);};
for(let i=0;i<10;i++){await show();await touch('touchStart',195,720);for(const y of [705,680,640,600]){await touch('touchMove',195,y);await page.waitForTimeout(35);}await touch('touchEnd');assert.equal(await page.evaluate(()=>S.me.locked),false,'upward swipe must unlock; browser must not cancel the app gesture');await page.waitForTimeout(650);}
assert.equal(await page.evaluate(()=>lockCancels),0,'no browser takeover while swiping screen');
await show();await page.locator('.lockhint').tap();await page.waitForFunction(()=>S.me.locked===false);await page.waitForTimeout(650);
await show();await touch('touchStart',195,720);await touch('touchMove',195,680);assert.equal(await page.locator('#lockScreen').evaluate(e=>getComputedStyle(e).transitionDuration),'0s','drag follows finger without transition');await touch('touchCancel');assert.equal(await page.evaluate(()=>S.me.locked),true);assert.equal(await page.locator('#lockScreen').evaluate(e=>e.style.transform),'');assert.equal(await page.locator('#lockScreen').evaluate(e=>e.classList.contains('dragging')),false);
await page.waitForTimeout(650);await touch('touchStart',195,720);await touch('touchMove',195,680);await touch('touchMove',290,680);await touch('touchEnd');assert.equal(await page.evaluate(()=>S.me.locked),true);assert.equal(await page.locator('#lockScreen').evaluate(e=>e.style.transform),'','horizontal abandonment clears offset');
assert.equal(await page.locator('#lockScreen').evaluate(e=>e.classList.contains('dragging')),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({privateApp,swipes:10,browserCancels:0,cancelAndHorizontalReset:true,tap:true,pageErrors:0}));await page.close();}}
finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
