const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const f=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'}[path.extname(f)]||'application/octet-stream'));res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const privateApp of [false,true]){
 const p=await b.newPage({viewport:{width:430,height:932}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date(2026,8,7,8,0,0)});await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await p.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
 await p.evaluate(()=>{
  S.me.locked=false;const c=S.contacts[0];S.couple={cid:c.id};c.persona='偏爱温柔田园风，喜欢轻巧的小辫子';window.outfitCalls=0;window.outfitRequests=[];
  const cfg={base:'https://fixture.invalid/v1',key:'fixture-secret',model:'fixture-role',temp:.7,maxTokens:900};S.settings.chat=cfg;S.settings.aux={};chatRequestRoute=()=>cfg;aiCoreOn=()=>false;
  fetchT=async(url,opt)=>{const req=JSON.parse(opt.body);if(!req.messages[0].content.includes('正在为代表玩家的小屋少女挑选穿搭'))return{ok:true,json:async()=>({choices:[{message:{content:'我在。'},finish_reason:'stop'}]})};outfitCalls++;outfitRequests.push(req);const options=JSON.parse(req.messages[1].content),night=options.period==='evening';return{ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({setId:null,dress:night?'outfit3-dress':'outfit7-dress',shoes:night?'outfit3-shoes':'outfit7-shoes',accessory:night?'outfit3-accessory':'outfit7-accessory',hair:night?'hair3':'hair6',reason:night?'今晚选轻巧短发配睡衣':'我喜欢田园粉色和月牙小辫子'})},finish_reason:'stop'}]})};};
  const i=pixelHomeIdentity(),e=pixelHomeEntry(i),a=structuredClone(PixelHomeWardrobeInfo.approved);a.adjustments.hair6={x:3};e.state=PixelHomePolicy.snapshot({version:3,mood:82,food:58,energy:65,health:94,clean:68,wardrobe:{...a,savedOutfits:[{id:'set-demo',name:'今天的月牙小白裙',look:{...a,hair:'hair6'}}]}});e.appliedDay='';e.pajamasDay='';delete e.dailyOutfit;delete e.morningOutfit;delete e.eveningOutfit;go('gameshub');openPixelHome();
 });
 let f=p.frameLocator('#pixel-home-frame');await f.locator('#loading').waitFor({state:'detached',timeout:45000});await p.waitForFunction(()=>pixelHomeEntry(pixelHomeIdentity()).morningOutfit?.source==='role-model');await f.locator('#scene').evaluate(async()=>{for(let n=0;n<200&&RoseWardrobe.getState().dress!=='outfit7-dress';n++)await new Promise(r=>setTimeout(r,30));});
 assert.equal(await f.locator('#scene').evaluate(()=>RoseWardrobe.getState().dress),'outfit7-dress');assert.equal(await f.locator('#scene').evaluate(()=>RoseWardrobe.getState().hair),'hair6');
 const morning=await p.evaluate(()=>({calls:outfitCalls,request:outfitRequests[0],prompt:buildSystem(getC(S.couple.cid)),other:pixelHomeRoleContext({id:'other'}),w:pixelHomeEntry(pixelHomeIdentity()).state.wardrobe}));assert.equal(morning.calls,1);assert(morning.request.messages[0].content.includes('偏爱温柔田园风'));assert(morning.prompt.includes('我喜欢田园粉色和月牙小辫子'));assert.equal(morning.other,'');assert.equal(morning.w.savedOutfits[0].name,'今天的月牙小白裙');assert.equal(morning.w.adjustments.hair6.x,3);
 await p.evaluate(()=>{go('gameshub');openPixelHome();});f=p.frameLocator('#pixel-home-frame');await f.locator('#loading').waitFor({state:'detached',timeout:45000});assert.equal(await p.evaluate(()=>outfitCalls),1);await p.screenshot({path:path.join(root,'.qa/v1205',privateApp?'private-role-morning.png':'web-role-morning.png')});
 await p.clock.setFixedTime(new Date(2026,8,7,19,0,0));await p.waitForFunction(()=>pixelHomeEntry(pixelHomeIdentity()).eveningOutfit?.source==='role-model');await f.locator('#scene').evaluate(async()=>{for(let n=0;n<200&&RoseWardrobe.getState().dress!=='outfit3-dress';n++)await new Promise(r=>setTimeout(r,30));});assert.equal(await f.locator('#scene').evaluate(()=>RoseWardrobe.getState().dress),'outfit3-dress');assert.equal(await f.locator('#scene').evaluate(()=>RoseWardrobe.getState().hair),'hair3');assert.equal(await p.evaluate(()=>outfitCalls),2);assert((await p.evaluate(()=>buildSystem(getC(S.couple.cid)))).includes('今晚选轻巧短发配睡衣'));await p.screenshot({path:path.join(root,'.qa/v1205',privateApp?'private-role-pajamas.png':'web-role-pajamas.png')});
 assert.deepEqual(errors,[]);console.log('PASS '+(privateApp?'private':'web')+': persona request, whole wardrobe despite named sets, approved fits, once per slot, 19:00 pajamas with independently chosen hair, actual role context and game bridge');await p.close();
 }}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
