const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');res.end(fs.readFileSync(file));});
(async()=>{
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
try{for(const privateApp of [false,true]){
const page=await browser.newPage({viewport:{width:430,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
await page.evaluate(()=>{S.me.locked=false;const c=S.contacts[0],guest=S.contacts[1],id=c.id,r=cohabRoot();r.enabled=true;r.paused=false;r.cid=id;const d=cohabData(id);d.phase='home';d.nextAt=0;d.pendingArrival=null;d.msgs=[];window.diagHostId=id;window.modelCalls=0;const cfg=i=>({model:'model-route-'+i,base:'https://fake.invalid/v1',key:'test-secret',maxTokens:9000,temp:.7,aux:{model:'aux-route-'+i}});S.settings.chat=cfg(0);S.settings.aux=cfg(0).aux;S.settings.chatRouteActive=0;aiCoreOn=()=>false;chatRequestRoute=i=>i==null?null:cfg(i);roleChatRouteIndex=()=>2;const settings=cohabSettings(d);settings.replyApiRoute='1';settings.replyModel='main';d.theater={enabled:true,addressTo:'guest',supportBubbleLimit:2,guest:{contactId:guest.id,episodeId:'test-episode',joinedSeq:1,joinedAt:Date.now(),relationToUser:'朋友',relationToHost:'朋友'},presence:{host:true,me:true,guest:true}};fetchT=async(url,opt)=>{modelCalls++;const body=JSON.parse(opt.body),support=body.messages[0].content.includes('只输出一个JSON对象'),text=support?'\{"bubbles":[{"type":"speak","text":"我也在听，你慢慢说。"}],"leave":false}':'【他抬头看向你。】\n我在听，慢慢说。';return{ok:true,json:async()=>({model:body.model,choices:[{message:{content:text},finish_reason:'stop'}],usage:{completion_tokens:44}})};};_off={id,mode:'cohab',busy:false};go('off',{id,mode:'cohab'});});
const button=page.locator('.cohab-settings button').filter({hasText:'模型与路线诊断'});if(await button.count()!==1)console.log(await page.evaluate(()=>({errors:window.__northBootError,panel:cohabSettingsPanel(diagHostId,cohabData(diagHostId)).slice(-2800),body:document.body.innerText.slice(-500)})),errors);assert.equal(await button.count(),1);assert.equal(await button.isVisible(),false);await page.locator('.cohab-settings > summary').click();await button.click();assert.match(await page.locator('body').innerText(),/尚无本次打开小手机后的共同生活请求记录/);assert.equal(await page.evaluate(()=>modelCalls),0);await page.evaluate(()=>closeModal());await page.evaluate(()=>offReply());await page.waitForFunction(()=>modelCalls>=2&&!_off.busy,null,{timeout:30000});
await page.evaluate(()=>cohabModelDiagnosticOpen(diagHostId));const text=await page.locator('body').innerText();assert.match(text,/240 tokens/);assert.match(text,/600 tokens/);assert.match(text,/model-route-1/);assert.match(text,/model-route-2/);assert.match(text,/stop/);assert.doesNotMatch(text,/test-secret|fake.invalid/);assert.deepEqual(errors,[]);console.log(JSON.stringify({privateApp,insideSettings:true,hiddenWhenCollapsed:true,calls:await page.evaluate(()=>modelCalls),hostAndGuestRoutes:true,pageErrors:errors}));
const cohabDetail=page.locator('.request-size-details').first();assert.equal(await cohabDetail.locator(':scope > div').isVisible(),false);const beforeOpen=await page.evaluate(()=>modelCalls);await cohabDetail.locator(':scope > summary').click();assert.match(await cohabDetail.innerText(),/合计/);assert.match(await cohabDetail.innerText(),/消息格式、字段与转义/);assert.equal(await page.evaluate(()=>modelCalls),beforeOpen);await page.evaluate(()=>{closeModal();cohabRoot().enabled=false;const id=diagHostId;S.settings.replyDelay=0;S.messages[id]=[{id:'size-user',role:'user',type:'text',content:'在吗？',time:Date.now()}];fetchT=async()=>{modelCalls++;return{ok:true,json:async()=>({choices:[{message:{content:'[内心|有点想你]\n我在，慢慢说。'},finish_reason:'stop'}]})};};openChat(id);manualReply(id);});await page.waitForFunction(()=>!replyGenerationBusy(diagHostId,actId()));const totals=await page.evaluate(()=>{const d=getC(diagHostId)._chatRouteDiagnostic;roleChatDiagnosticOpen(diagHostId);return{total:d.requestChars,sum:d.requestBreakdown.groups.reduce((n,x)=>n+x.chars,0),count:d.messageCount,rows:d.requestBreakdown.messages.length,calls:modelCalls};});assert.equal(totals.total,totals.sum);assert.equal(totals.count,totals.rows);const onlineDetail=page.locator('.request-size-details').first();await onlineDetail.locator(':scope > summary').click();assert.match(await onlineDetail.innerText(),/功能与回复规则章节/);await onlineDetail.locator('details > summary').click();assert.match(await onlineDetail.innerText(),/第 1 条/);assert.equal(await page.evaluate(()=>modelCalls),totals.calls);assert.deepEqual(errors,[]);console.log(JSON.stringify({privateApp,onlineAndCohabDetails:true,...totals}));
await page.close();
}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
