// Actual web/private entrypoints and fetch transport; only upstream responses are fixtures.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');res.end(fs.readFileSync(file));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
 try{for(const privateApp of [false,true]){
  const page=await browser.newPage({viewport:{width:430,height:900}}),errors=[];let mode='recover',calls=0;
  if(privateApp)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async route=>{const url=route.request().url();if(url.startsWith('https://call-fixture.invalid/')){calls++;if(mode==='hangup'){await page.evaluate(()=>{_call=null;});return route.abort('failed');}if(mode==='auth')return route.fulfill({status:401,contentType:'application/json',body:'{"error":{"message":"invalid key"}}'});if(mode==='recover'&&calls===1)return route.abort('failed');return route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-expose-headers':'x-request-id','x-request-id':'fixture-request'},body:'{"choices":[{"message":{"content":"电话正常回复"},"finish_reason":"stop"}]}'});}return new URL(url).origin===origin?route.continue():route.abort();});
  await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
  await page.evaluate(()=>{S.me.locked=false;S.me.active='main';window.evidenceId=S.contacts[0].id;S.contacts.forEach(c=>{c.proactive={enabled:false};});S.settings.chat={base:'https://call-fixture.invalid/v1',key:'EVIDENCE_SECRET',model:'fixture-main',temp:.7,maxTokens:900};S.settings.aux={model:'fixture-aux'};aiCoreOn=()=>false;localStorage.removeItem('north-request-diagnostics-v1');});
  const recovery=await page.evaluate(async()=>{_call={session:'recover'};const out=await callChatWithRetry([{role:'user',content:'EVIDENCE_PRIVATE_BODY'}],{diagnosticRoleId:evidenceId,routeIndex:0},getC(evidenceId));NorthRequestDiagnostics.open(evidenceId);return{out,records:JSON.parse(NorthRequestDiagnostics.report(evidenceId)).records,visible:document.body.innerText};});
  assert.equal(calls,2);assert.equal(recovery.out,'电话正常回复');const failed=recovery.records.find(r=>r.state==='failed'),success=recovery.records.find(r=>r.state==='returned');assert.equal(failed.channel,'call');assert.equal(failed.failureStage,'waiting-headers');assert.match(failed.rawError,/fetch|load/i);assert.equal(failed.timedOut,false);assert.equal(failed.operationId,success.operationId);assert.equal(success.attempt,2);assert(recovery.visible.includes('电话'));assert(recovery.visible.includes('耗时'));assert(!JSON.stringify(recovery.records).includes('EVIDENCE_SECRET'));assert(!JSON.stringify(recovery.records).includes('EVIDENCE_PRIVATE_BODY'));
  for(const next of ['hangup','auth']){mode=next;calls=0;const result=await page.evaluate(async(next)=>{_call={session:next};try{await callChatWithRetry([{role:'user',content:'测试'}],{diagnosticRoleId:evidenceId,routeIndex:0},getC(evidenceId));return{unexpected:true};}catch(e){return{code:e.code,status:e.status};}},next);assert.equal(calls,1);if(next==='hangup')assert.equal(result.code,'call-session-ended');else assert.equal(result.status,401);}
  const privacy=await page.evaluate(()=>{S.me.active='another-account';return NorthRequestDiagnostics.list(evidenceId).length;});assert.equal(privacy,0);assert.deepEqual(errors,[]);console.log(JSON.stringify({privateApp,realFetch:true,recoveredWithTwoAttempts:true,hangupStopsRetry:true,unauthorizedNoRetry:true,diagnosticVisible:true,accountIsolation:true,pageErrors:0}));await page.close();
 }}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
