// Isolated real-entry regression: model HTTP is mocked; prompts, parsers and delivery are real.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');const baseline=process.env.ENGLISH_BASELINE==='1'&&file.endsWith(path.sep+'app.js');res.end(baseline?cp.execFileSync('git',['show','9defbd8b:'+path.relative(root,file).replace(/\\/g,'/')],{cwd:root,maxBuffer:20*1024*1024}):fs.readFileSync(file));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
 try{for(const privateApp of [false,true]){
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
  await page.evaluate(()=>{S.me.locked=false;S.couple=null;const c=S.contacts[0];window.testId=c.id;c.proactive={enabled:false};S.settings.replyDelay=0;S.settings.chat={base:'https://fake.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};aiCoreOn=()=>false;window.fixtureRaw='';window.testCalls=[];window.notices=[];fetchT=async(url,opt)=>{testCalls.push(JSON.parse(opt.body));return{ok:true,json:async()=>({choices:[{message:{content:fixtureRaw},finish_reason:'stop'}]})};};toast=s=>notices.push(String(s));openChat(c.id);});
  for(const on of [true,false])for(const channel of ['online','offline','cohab','call']){
   const result=await page.evaluate(async({on,channel})=>{
    S.settings.modelOutputUnfiltered=on;testCalls.length=0;notices.length=0;fixtureRaw='[内心|想听你说话]\nHello, I am here.';
    const c=getC(testId);S.messages[testId]=[{id:uid(),role:'user',type:'text',content:'陪我说说话',time:Date.now(),_call:channel==='call'}];let shown=[],failure='';
    if(channel==='online'){await aiReply(testId);shown=msgs(testId).filter(m=>m.role==='assistant');}
    if(channel==='cohab'){try{const r=await cohabReplyCore(c,cohabData(testId),'用户说：陪我说说话','陪我说说话',900,{});shown=r.items;}catch(e){failure=e.code||e.message;}}
    if(channel==='offline'){S.offline=S.offline||{};S.offline[testId]={started:true,msgs:[{id:uid(),who:'me',text:'陪我说说话',time:Date.now()}],memory:[]};_off={id:testId,mode:'date'};const previous=offRender;offRender=()=>{};try{await offAI();shown=S.offline[testId].msgs.filter(m=>m.who!=='me');}finally{_off=null;offRender=previous;}}
    if(channel==='call'){_call={id:testId,kind:'voice',session:uid(),state:'active',dir:'outgoing',replyVoice:false};_callBusy=false;try{await callAI();shown=msgs(testId).filter(m=>m.role==='assistant'&&m.type!=='sys');failure=_call&&_call.lastError||'';}finally{_call=null;}}
    return{calls:testCalls.length,shown:shown.length,failure,notices: [...notices],prompt:testCalls.map(r=>JSON.stringify(r.messages)).join('')};
   },{on,channel});
   assert(result.calls>0,JSON.stringify({privateApp,on,channel,result}));assert.equal(result.shown,0,JSON.stringify({privateApp,on,channel,result}));assert.match(result.prompt,/心情标签格式检查/);console.log(JSON.stringify({privateApp,on,channel,blocked:true,calls:result.calls}));
  }
  const kept=await page.evaluate(async()=>{S.settings.modelOutputUnfiltered=true;fixtureRaw='[内心|想听你说话]\n[语音|Good night.|晚安。]';testCalls.length=0;S.messages[testId]=[{id:uid(),role:'user',type:'text',content:'陪我说说话',time:Date.now()}];await aiReply(testId);return{rows:msgs(testId).filter(m=>m.role==='assistant').map(m=>({text:m.content,trans:m.trans})),calls:testCalls.length};});assert.equal(kept.rows.length,1);assert(kept.rows.some(r=>r.trans==='晚安。'||r.text==='晚安。'));console.log(JSON.stringify({privateApp,translationPreserved:true}));
  const pull=await page.evaluate(async()=>{const c=getC(testId),old={rpc:companionRpc,gate:gateOK,main:isMain,sync:roleServerPushSyncEnabled,notify:notifyIncoming,apply:roleServerPushApplyAction};let applied=0,notified=0,acks=[];const results=[];S.couple={cid:c.id};c.proactive={enabled:false};companionRpc=async(name,args)=>{if(name==='phone_role_push_pull')return[{id:'english-push-'+modelOutputUnfiltered(),roleId:c.id,body:'[内心|想你]\n[来电|语音]\nHello, I am here.',createdAt:new Date().toISOString()}];acks.push(name);return true;};gateOK=()=>true;isMain=()=>true;roleServerPushSyncEnabled=async()=>{};roleServerPushDeliveryBlocked=()=>false;privateCompanionAppOn=()=>true;_roleServerPushPullBusy=false;notifyIncoming=()=>{notified++;};roleServerPushApplyAction=async()=>{applied++;return true;};try{for(const on of [false,true]){S.settings.modelOutputUnfiltered=on;S.messages[testId]=[];_roleServerPushPullAt=0;await roleServerPushPull(true);results.push({on,shown:msgs(testId).filter(m=>m.role==='assistant').length,error:!!c._englishOnlyReplyError});}return{results,applied,notified,acks};}finally{companionRpc=old.rpc;gateOK=old.gate;isMain=old.main;roleServerPushSyncEnabled=old.sync;notifyIncoming=old.notify;roleServerPushApplyAction=old.apply;S.couple=null;}});assert(pull.results.every(r=>r.shown===0&&r.error),JSON.stringify(pull));assert.equal(pull.applied,0);assert.equal(pull.notified,0);console.log(JSON.stringify({privateApp,backgroundPull:pull}));
  assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
