const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];try{for(const priv of [false,true]){const ctx=await b.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[],calls=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(new URL(r.request().url()).hostname==='127.0.0.1')return r.continue();calls.push(r.request().url());return r.abort();});if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false})};});await p.goto('http://127.0.0.1:8774/'+(priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();S.settings.deskPet={on:false};S.settings.sound=false;S.contacts.forEach(c=>c.proactive={enabled:false});go('travel');window.balanceBefore=S.me.balance;});
const search=async q=>{await p.evaluate(()=>NorthTravelHome.home());await p.locator('#ctrSearch').fill(q);await p.locator('.ctr-search button').click();};
await search('上海希尔顿');assert.equal(await p.locator('.cth-app').count(),1);assert.equal(await p.locator('#cthKeyword').inputValue(),'希尔顿');assert.equal(await p.evaluate(()=>S.travel.hotelSearch.city),'上海');
await search('上海迪士尼');assert.equal(await p.locator('.ctg-app').count(),1);assert((await p.locator('.ctg-app').innerText()).includes('上海'));assert((await p.locator('.ctg-app').innerText()).includes('迪士尼'));
await search('周杰伦');assert.equal(await p.locator('.ctc-app').count(),1);assert.equal(await p.evaluate(()=>NorthTravelConcert.state().artist),'周杰伦');
await search('美国');assert.equal(await p.locator('#modalSheet').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');await p.getByRole('button',{name:'美国 · 酒店住宿 ›',exact:true}).click();assert.equal(await p.evaluate(()=>S.travel.hotelSearch.city),'美国');assert.equal(await p.evaluate(()=>S.travel.hotelSearch.category),'overseas');
await search('北京到上海');await p.getByRole('button',{name:'机票 · 北京 → 上海 ›',exact:true}).click();assert.deepEqual(await p.evaluate(()=>[NorthTravelFlight.state().legs[0].from,NorthTravelFlight.state().legs[0].to]),['北京','上海']);
await search('北京到上海');await p.getByRole('button',{name:'火车票 · 北京 → 上海 ›',exact:true}).click();assert.deepEqual(await p.evaluate(()=>[NorthTravelTrain.state().legs[0].from,NorthTravelTrain.state().legs[0].to]),['北京','上海']);
await search('迪士尼');assert(await p.locator('.ctr-search-choices button').count()>1);await p.evaluate(()=>closeModal());await search('完全未知的测试名字');assert.equal(await p.locator('.ctr-search-choices button').count(),5);await p.evaluate(()=>closeModal());
assert.equal(await p.evaluate(()=>S.me.balance===balanceBefore),true);assert.equal(await p.evaluate(()=>['hotels','ticketOrders','trips','concertOrders','taxiOrders'].every(k=>!(S.travel[k]||[]).length)),true);assert.equal(calls.some(u=>/chat\/completions|messages|phone-ai/.test(u)),false);
// Real remote approval and DOM navigation, while preventing unrelated model-led session planning.
await p.evaluate(()=>{const c=S.contacts[0];S.couple={...S.couple,cid:c.id,remoteControlAuth:true,remoteControlAutoApprove:false};window.remoteRole=c.id;remoteControlRun=async()=>{};remoteControlRequest(c.id);});assert.equal(await p.locator('.remote-allow').count(),1);await p.locator('.remote-allow').click();assert.equal(await p.evaluate(()=>remoteControlActive()),true);
await p.evaluate(()=>{window.pointerPoints=[];const original=remoteControlPointer;remoteControlPointer=(x,y)=>{pointerPoints.push([x,y]);original(x,y);};const day=new Date(Date.now()+86400000).toISOString().slice(0,10);S.travel.hotels=[{id:'remote-hotel',accountId:actId(),hotelName:'远控测试酒店',city:'上海',checkIn:day,nights:1,rooms:1,adults:1,roomType:'single',guestMode:'me',bookedBy:'me',payer:'me',price:200,status:'upcoming',_orderVisible:true,ts:Date.now()}];S.travel.taxiOrders=S.travel.taxiOrders||[];window.ordersBefore=JSON.stringify(S.travel);window.moneyBefore=S.me.balance;remoteControlNavigate({app:'travel',op:'view',targetName:'小鱼旅行全部行程订单'},{app:'travel'});});
await p.evaluate(async()=>{await remoteControlOpenApp({app:'travel',op:'view',targetName:'小鱼旅行'},getC(remoteRole));});assert((await p.locator('.app[data-k=travel]').innerText()).includes('小鱼旅行'));const desktop=await p.evaluate(()=>{const r=document.querySelector('.app[data-k=travel]').getBoundingClientRect(),l=document.querySelector('#remoteControlLayer').getBoundingClientRect();return [r.left-l.left+r.width*.55,r.top-l.top+r.height*.45];});const desktopTap=await p.evaluate(()=>pointerPoints.at(-1));assert(Math.abs(desktopTap[0]-desktop[0])<1&&Math.abs(desktopTap[1]-desktop[1])<1);await p.evaluate(()=>{pointerPoints=[];remoteControlNavigate({app:'travel',op:'view',targetName:'小鱼旅行全部行程订单'},{app:'travel'});});assert.equal(await p.locator('.ctr-app').count(),1);const expected=await p.evaluate(()=>{const r=document.querySelector('.ctr-account').getBoundingClientRect(),l=document.querySelector('#remoteControlLayer').getBoundingClientRect();return [r.left-l.left+r.width/2,r.top-l.top+r.height/2];});await p.evaluate(()=>remoteControlFocusViewedTarget({app:'travel',op:'view',targetName:'小鱼旅行全部行程订单'}));assert.equal(await p.locator('.ctr-order-row').count(),1);const pts=await p.evaluate(()=>pointerPoints);assert.equal(pts.length,2);assert(Math.abs(pts[0][0]-expected[0])<1&&Math.abs(pts[0][1]-expected[1])<1);const detailExpected=await p.evaluate(()=>{const r=document.querySelector('.ctr-order-row [data-order]').getBoundingClientRect(),l=document.querySelector('#remoteControlLayer').getBoundingClientRect();return [r.left-l.left+r.width/2,r.top-l.top+r.height/2];});assert(Math.abs(pts[1][0]-detailExpected[0])<1&&Math.abs(pts[1][1]-detailExpected[1])<1);assert.deepEqual(await p.evaluate(()=>[JSON.parse(JSON.stringify(S.travel)),S.me.balance]),await p.evaluate(()=>[JSON.parse(ordersBefore),moneyBefore]));assert.equal(await p.evaluate(()=>remoteControlAppKey('小鱼旅行订单')),'travel');assert.deepEqual(await p.evaluate(()=>['小鱼旅行','携程旅行','云程','云城'].map(n=>_appKeys(n,['travel'],()=>true)[0])),['travel','travel','travel','travel']);assert.deepEqual(errors,[]);reports.push({runtime:priv?'private':'web',hotel:true,tickets:true,concert:true,country:true,flightTrain:true,ambiguousChoice:true,noModelRequestOrBooking:true,remoteApprovedDOMTargets:true,pointerCenters:true,errors});await ctx.close();}fs.writeFileSync('.codex_tmp/travel-search-remote-result.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
