const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),reports=[];try{for(const priv of [false,true]){const p=await b.newPage({viewport:{width:430,height:844},deviceScaleFactor:2}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());if(priv)await p.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false})};});
await p.goto('http://127.0.0.1:8774/'+(priv?'native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'小手机.html')+'?northPreview=black-home');await p.waitForFunction(()=>window.__northBootReady);
await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();renderLockScreen();gateOK=()=>true;aiCoreOn=()=>false;S.settings.sound=false;S.settings.deskPet={on:false};S.settings.replyDelay=0;S.contacts.forEach(c=>c.proactive={enabled:false});S.contacts.push({id:'audit-r',name:'同行A',wallet:50000,proactive:{enabled:false}},{id:'audit-other',name:'同行B',wallet:50000,proactive:{enabled:false}});S.me.balance=10000;S.travel.concertOrders=[];S.couple={cid:'audit-r'};S.settings.chat={base:'https://fake.invalid/v1',key:'fixture',model:'fixture',maxTokens:9000,temp:.7};S.settings.chatRoutes=null;S.settings.chatRouteActive=0;window.auditCalls=0;fetchT=async()=>{auditCalls++;return {ok:true,json:async()=>({choices:[{message:{content:'[演唱会开场提醒|'+auditOrder+'|audit-r]\n演唱会开场了，我们一起去听吧。'},finish_reason:'stop'}]})};};go('travel');NorthTravelHome.entry('concert');window.auditQ={accountId:String(actId()),artist:'王俊凯',city:'上海',date:'2099-10-05',end:'2099-10-05',time:'19:30',area:'stand',price:380,budget:0,count:1,people:[{id:'me',name:S.me.name}]};
if(!NorthConcertBooking.bookQuote(auditQ,NorthConcertBooking.shows(auditQ)[0].id))throw Error('solo purchase failed');const solo=NorthConcertBooking.rows()[0];if(!rolePhoneLocalRead('audit-r','travel').data.includes('用户独自观演'))throw Error('solo inspection absent');if(NorthConcertBooking.rolePrompt(getC('audit-r')).includes('王俊凯'))throw Error('solo leaked to ordinary context');auditQ.count=2;auditQ.people.push({id:'role:audit-other',name:'同行B'});if(!NorthConcertBooking.bookQuote(auditQ,NorthConcertBooking.shows(auditQ)[0].id))throw Error('arbitrary companion purchase failed');if(!rolePhoneLocalRead('audit-r','travel').data.includes('同行B'))throw Error('other companion inspection absent');
S.travel.concertOrders=[];auditQ.people[1]={id:'role:audit-r',name:'同行A'};if(!NorthConcertBooking.bookQuote(auditQ,NorthConcertBooking.shows(auditQ)[0].id))throw Error('timed purchase failed');const o=NorthConcertBooking.rows()[0];window.auditOrder=o.id;window.auditBase=Date.now();window.auditNow=auditBase;Date.now=()=>auditNow;o.startAt=auditBase+5000;o.endAt=auditBase+15000;o.date=todayStr();o.time='19:30';NorthConcertBooking.orders();});
const widths=await p.locator('.ctc-order-row').evaluate(e=>({row:e.clientWidth,card:e.querySelector('.ctc-chat-concert').getBoundingClientRect().width,pad:parseFloat(getComputedStyle(e).paddingLeft)}));assert(Math.abs(widths.card-(widths.row-widths.pad*2))<2,JSON.stringify(widths));await p.screenshot({path:path.resolve('.codex_tmp/travel-concert/audit-'+(priv?'private':'web')+'-orders.png')});
await p.evaluate(()=>{auditNow=auditBase+4999;NorthConcertBooking.checkDue();});assert.equal(await p.evaluate(()=>auditCalls),0);await p.evaluate(()=>{auditNow=auditBase+5000;NorthConcertBooking.checkDue();});await p.waitForFunction(()=>msgs('audit-r').some(m=>m._concertReminderOrderId===auditOrder),{timeout:20000});assert.equal(await p.evaluate(()=>auditCalls),1);assert.equal(await p.evaluate(()=>msgs('audit-r').some(m=>m.type==='text'&&String(m.content||'').includes('[演唱会开场提醒'))),false);await p.evaluate(()=>{NorthConcertBooking.checkDue();NorthConcertBooking.checkDue();});assert.equal(await p.evaluate(()=>auditCalls),1);
await p.evaluate(()=>saveNowAsync());await p.goto(p.url().split('?' )[0]);await p.waitForFunction(()=>window.__northBootReady);await p.evaluate(()=>{S.me.locked=false;document.getElementById('gate')?.remove();renderLockScreen();gateOK=()=>true;aiCoreOn=()=>false;window.auditCalls=0;fetchT=async()=>{auditCalls++;throw Error('duplicate reminder after reload');};const o=S.travel.concertOrders.find(o=>o.knownRoleIds.includes('audit-r')&&o.concertRemindedAt?.['audit-r']);if(!o)throw Error('reminder receipt not persisted');window.auditOrder=o.id;window.auditBase=o.startAt-5000;window.auditNow=o.startAt+1000;Date.now=()=>auditNow;NorthConcertBooking.checkDue();go('travel');NorthTravelHome.entry('concert');NorthConcertBooking.orders();});assert.equal(await p.evaluate(()=>auditCalls),0);
await p.evaluate(()=>{auditNow=auditBase+15000;});await p.waitForFunction(()=>document.querySelectorAll('.ctc-order-row').length===0);assert.equal(await p.evaluate(()=>NorthConcertBooking.rows().length),0);assert.equal(await p.evaluate(()=>NorthConcertBooking.noteValid('[演唱会开场提醒|'+auditOrder+'|audit-r]')),false);
await p.evaluate(()=>{const prior=NorthConcertBooking.current(auditOrder);window.auditQ={accountId:String(actId()),artist:prior.artist,city:prior.city,date:'2099-10-05',end:'2099-10-05',time:'19:30',area:'stand',price:380,budget:0,count:2,people:prior.people};if(!NorthConcertBooking.bookQuote(auditQ,NorthConcertBooking.shows(auditQ)[0].id))throw Error('refund test purchase failed');window.auditRefund=NorthConcertBooking.rows()[0].id;window.beforeRefund=S.me.balance;if(!NorthConcertBooking.refund(auditRefund)||S.me.balance!==beforeRefund+760)throw Error('original refund failed');const o=NorthConcertBooking.current(auditRefund);window.refundAt=o.refundedAt;auditNow=refundAt+86400000-1;NorthConcertBooking.checkDue();});assert.equal(await p.locator('.ctc-order-row').count(),1);await p.evaluate(()=>{auditNow=refundAt+86400000;});await p.waitForFunction(()=>document.querySelectorAll('.ctc-order-row').length===0);
assert.deepEqual(errors,[]);reports.push({runtime:priv?'private':'web',fullWidth:widths,soloAndOtherCompanionInspection:true,noEarlyReminder:true,actualAiReplyDelivery:true,noDuplicateOrMarkerLeak:true,reloadReceiptPersisted:true,liveExpiry:true,originalRefundAndExact24hHide:true,errors});await p.close();}fs.writeFileSync('.codex_tmp/travel-concert/audit-result.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

