const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),server=http.createServer((q,r)=>{const f=path.resolve(root,decodeURIComponent(new URL(q.url,'http://localhost').pathname).slice(1));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){r.writeHead(404);return r.end();}r.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');r.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'});
try{for(const privateApp of [false,true]){const page=await browser.newPage({serviceWorkers:'block'}),errors=[];if(privateApp)await page.addInitScript(()=>{window.__SMALL_PHONE_PRIVATE__=true;window.SmallPhoneNative={request:async()=>({ok:false,error:'fixture-native-unavailable'})};});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+(privateApp?'/native/private-small-phone/XcodeProject/PhoneCompanionTest/PhoneWeb.bundle/index.html':'/小手机.html')+'?northPreview=black-home');await page.waitForFunction(()=>window.__northBootReady);
const result=await page.evaluate(async privateApp=>{
 S.me.locked=false;S.me.active='main';const c=S.contacts[0];S.couple={cid:c.id,grant:{},locks:{},timeLimit:{},companion:{linked:true,health:{heartRate:99},apps:[]}};c.proactive={enabled:false};
 const now=Date.now(),payload={linked:true,deviceId:'fixture-device',lastSyncAt:now,snapshot:{generatedAt:now,snapshotSequence:2,screenTime:{reportAvailable:true,generatedAt:now,totalSeconds:123,apps:[{id:'fixture-app',name:'音乐',usedSeconds:123,locked:false}]},deviceTelemetry:{batteryLevel:.42,generatedAt:now,batteryState:'unplugged'},health:{steps:300,heartRateBpm:99,generatedAt:now}}};
 if(privateApp){S._shortcutCloudEnabled=true;const job={id:'private-fixture-job',role_id:c.id,mode:'role_event',input_text:'充电',status:'completed',reply_text:'先歇一会。',received_at:new Date(now).toISOString(),completed_at:new Date(now+1000).toISOString()};fetchT=async(url,opt)=>({ok:true,json:async()=>JSON.parse(opt.body).action==='pull'?{jobs:[job]}:{ok:true}});await PhoneShortcuts.pull(true);await PhoneShortcuts.pull(true);const rows=msgs(c.id).filter(x=>x._shortcutJob===job.id);return{available:NorthPublicRuntime.available(),entry:renderSettings().includes('PhoneShortcuts.open'),history:renderCompanionPage(c,'',(_,t)=>t).includes('NorthPublicRuntime.history'),count:rows.length,reply:rows[0]?.content};}
 const st=companionState(),isolated=!st.linked&&!st.health;NorthPublicRuntime.apply(st,payload);st.roleAccess=true;st.permissions.health=true;
 const sys=buildSystem(c),html=renderCompanionPage(c,'',(_,t)=>t),calls=[];
 fetchT=async(url,opt)=>{calls.push({url,body:JSON.parse(opt.body)});return {ok:true,text:async()=>JSON.stringify([]),json:async()=>({jobs:[]})};};
 await companionRpc('phone_role_background_complete_turn',{p_role_id:c.id});const unconsented=calls.length===0;
 st.backgroundConsent[c.id]=true;await companionRpc('phone_role_push_history',{p_role_id:c.id});
 const targets=cohabPhoneTargets(c),cp=cohabPhonePrompt(c),cmd=companionLog(st,'lock','测试','pending','用户');
 companionSendCommand(st,'lock',st.apps[0],{by:'owner',actor:'用户'},cmd);await new Promise(r=>setTimeout(r,20));
 const first=NorthPublicRuntime.profile().target;S.couple.cid='other-role';const second=NorthPublicRuntime.profile().target;S.couple.cid=c.id;S.me.active='account-fixture';const accountTarget=NorthPublicRuntime.profile().target,accountEmpty=!companionState().linked;S.me.active='main';
 S._shortcutCloudEnabled=true;const auth={...PhoneShortcuts.request};
 const job={id:'fixture-shortcut-job',role_id:c.id,mode:'user_message',input_text:'到家了',status:'completed',reply_text:'回来啦，先歇一会。',received_at:new Date(now).toISOString(),completed_at:new Date(now+1000).toISOString()};
 fetchT=async(url,opt)=>({ok:true,json:async()=>JSON.parse(opt.body).action==='pull'?{jobs:[job]}:{ok:true}});
 await PhoneShortcuts.pull(true);await PhoneShortcuts.pull(true);const rows=msgs(c.id).filter(x=>x._shortcutJob===job.id);
 return {isolated,sys,html,targets,cp,unconsented,calls,separate:first!==second&&first!==accountTarget&&accountEmpty,rows:rows.map(x=>x.content),entry:renderSettings().includes('PhoneShortcuts.open')};
},privateApp);
if(privateApp){assert.equal(result.available,false);assert(result.entry&&result.history);assert.equal(result.count,1);assert.equal(result.reply,'先歇一会。');}else{assert(result.isolated&&result.unconsented&&result.separate&&result.entry);assert(result.sys.includes('300 步'));assert(!result.html.includes('Apple Watch'));assert(!result.targets.some(x=>/睡眠|心率|心电|HRV/.test(x)));assert(result.targets.includes('iPhone步数'));assert(!result.cp.includes('当前环境没有真实 iPhone'));assert(result.calls.every(x=>x.url.includes('lkhlyfpssmrjkkzhuzag')));assert(result.calls.some(x=>x.body.p_command?.externalAppId==='fixture-app'));assert.deepEqual(result.rows,['到家了','回来啦，先歇一会。']);}
assert.deepEqual(errors,[]);console.log(JSON.stringify({privateApp,publicIsolation:true,entry:true,sharedHistory:true,shortcutDedup:true,pageErrors:0}));await page.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
