import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from './worker.mjs';
const post=(fn,body={},extra={})=>new Request('https://license.smallphoneapp.com/rest/v1/rpc/'+fn,{method:'POST',headers:{Origin:'https://fenglina35-dotcom.github.io','Content-Type':'application/json',apikey:'fixture',Authorization:'Bearer fixture',...extra},body:JSON.stringify(body)});
test('friend relay keeps the original RPC, body and auth; one upstream write only',async()=>{const calls=[],body={p_from_id:'fixture',p_secret:'fixture',p_body:'群消息'};const handle=createHandler(async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({id:'confirmed'}));});const response=await handle(post('phone_friend_send_group_message',body));assert.equal(response.status,200);assert.equal(calls.length,1);assert.equal(calls[0].url,'https://lkhlyfpssmrjkkzhuzag.supabase.co/rest/v1/rpc/phone_friend_send_group_message');assert.deepEqual(JSON.parse(calls[0].init.body),body);assert.equal(calls[0].init.redirect,'manual');assert.equal(calls[0].init.headers.Authorization,'Bearer fixture');assert.equal(response.headers.get('cache-control'),'no-store');});
test('reject arbitrary RPC, query, origin, missing auth and malformed body before network',async()=>{let calls=0;const handle=createHandler(async()=>{calls++;return new Response('{}');});for(const [req,status]of[[post('admin_delete_order'),404],[post('phone_friend_search?upstream=other'),400],[post('phone_friend_search',{}, {Origin:'https://other.example'}),403],[post('phone_friend_search',{}, {Authorization:''}),401],[post('phone_friend_search',[]),400]])assert.equal((await handle(req)).status,status);assert.equal(calls,0);});
test('friend CORS preflight includes auth but sends no upstream request',async()=>{let calls=0;const handle=createHandler(async()=>{calls++;});const response=await handle(new Request('https://license.smallphoneapp.com/rest/v1/rpc/phone_friend_search',{method:'OPTIONS',headers:{Origin:'https://fenglina35-dotcom.github.io'}}));assert.equal(response.status,204);assert.match(response.headers.get('access-control-allow-headers'),/apikey/);assert.equal(calls,0);});
test('uncertain transfer/send is never retried and errors do not echo credentials',async()=>{let calls=0;const handle=createHandler(async()=>{calls++;throw Error('private-credential');});const response=await handle(post('phone_friend_send_message'));assert.equal(response.status,502);assert.equal(calls,1);assert(!String(await response.text()).includes('private-credential'));});


const rolePost=(fn,body={},extra={})=>new Request('https://license.smallphoneapp.com/companion/rest/v1/rpc/'+fn,{method:'POST',headers:{Origin:'null','Content-Type':'application/json',apikey:'fixture',Authorization:'Bearer fixture',...extra},body:JSON.stringify({p_target:'fixture-phone',p_owner_secret:'fixture-owner-secret-123456',...body})});
test('private role relay keeps the dedicated database, owner verification and one upstream call',async()=>{const calls=[],body={p_target:'fixture-phone',p_owner_secret:'fixture-owner-secret-123456',p_limit:20};const h=createHandler(async(url,init)=>{calls.push({url,init});return new Response('[{"id":"saved-role-row"}]');});const r=await h(rolePost('phone_role_push_pull',body));assert.equal(r.status,200);assert.equal(calls.length,1);assert.equal(calls[0].url,'https://qvuahlqimcfgeoetosnl.supabase.co/rest/v1/rpc/phone_role_push_pull');assert.deepEqual(JSON.parse(calls[0].init.body),body);assert.equal(calls[0].init.headers.Authorization,'Bearer fixture');assert.equal(calls[0].init.redirect,'manual');assert.equal(r.headers.get('cache-control'),'no-store');assert(!('Cookie' in calls[0].init.headers));});
test('role relay is absent in the released baseline and health is non-sensitive without an upstream request',async()=>{const {execFileSync}=await import('node:child_process');const old=execFileSync('git',['show','HEAD:services/phone-license-relay/worker.mjs'],{encoding:'utf8'});const baseline=await import('data:text/javascript;base64,'+Buffer.from(old).toString('base64'));assert.equal((await baseline.createHandler(async()=>new Response('{}'))(rolePost('phone_role_push_pull'))).status,404);let calls=0;const h=createHandler(async()=>{calls++;return new Response('{}');});const r=await h(new Request('https://license.smallphoneapp.com/companion/health'));assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true,code:'private-role-sync-relay-v1'});assert.equal(calls,0);});
test('role relay rejects control, account, arbitrary URLs, query and missing owner without network',async()=>{let calls=0;const h=createHandler(async()=>{calls++;return new Response('{}');});for(const [request,status]of[[rolePost('phone_companion_enqueue_command'),404],[rolePost('account_login'),404],[rolePost('phone_role_push_pull?target=https://other.example'),400],[rolePost('phone_role_push_pull',{p_owner_secret:''}),400],[rolePost('phone_role_push_pull',{}, {Authorization:''}),401],[rolePost('phone_role_push_pull',{}, {Origin:'https://other.example'}),403]])assert.equal((await h(request)).status,status);assert.equal(calls,0);});
test('role acknowledgment is not retried after an uncertain response and auth errors remain auth errors',async()=>{let calls=0;const h=createHandler(async()=>{calls++;throw Error('do-not-leak-owner-secret');});const r=await h(rolePost('phone_role_push_ack',{p_ids:['saved']}));assert.equal(r.status,502);assert.equal(calls,1);assert(!String(await r.text()).includes('do-not-leak'));const denied=createHandler(async()=>new Response('{"message":"owner-not-linked"}',{status:403}));assert.equal((await denied(rolePost('phone_role_push_status'))).status,403);});
test('role relay rejects redirects and non-json responses without following another destination',async()=>{for(const response of [new Response('',{status:302,headers:{Location:'https://other.example'}}),new Response('<html>interstitial</html>')]){let n=0;const r=await createHandler(async()=>{n++;return response;})(rolePost('phone_role_push_pull'));assert.equal(r.status,502);assert.equal(n,1);}});


test('role relay caps profile payloads and its timeout covers reading the upstream body',async()=>{let calls=0;const h=createHandler(async()=>{calls++;return new Response('{}');});assert.equal((await h(rolePost('phone_role_push_upsert_profile',{p_profile:{padding:'x'.repeat(1048576)}}))).status,413);assert.equal(calls,0);const slow=createHandler(async(_url,init)=>({status:200,text:()=>new Promise((_resolve,reject)=>init.signal.addEventListener('abort',()=>reject(Error('body timeout')),{once:true}))}),10);const r=await slow(rolePost('phone_role_push_pull'));assert.equal(r.status,502);assert.equal((await r.json()).message,'role-sync-timeout');});


test('role task status uses only the original owner-checked function, never global dispatch',async()=>{const calls=[],h=createHandler(async(url,init)=>{calls.push({url,init});return new Response('{"ok":true,"taskStatus":"completed"}');});const request=action=>new Request('https://license.smallphoneapp.com/companion/functions/v1/phone-role-push',{method:'POST',headers:{Origin:'null','Content-Type':'application/json',apikey:'fixture',Authorization:'Bearer fixture'},body:JSON.stringify({action,target:'fixture-phone',ownerSecret:'fixture-owner-secret-123456',roleId:'fixture-role',taskId:'fixture-task'})});assert.equal((await h(request('task_status'))).status,200);assert.equal(calls[0].url,'https://qvuahlqimcfgeoetosnl.supabase.co/functions/v1/phone-role-push');assert.equal(JSON.parse(calls[0].init.body).ownerSecret,'fixture-owner-secret-123456');assert.equal((await h(request('dispatch_due'))).status,403);assert.equal((await h(request('shortcut_deliver'))).status,403);assert.equal(calls.length,1);});
